### ISSUE TITLE
Documentation: Expand documentation for mongodbatlas_cloud_backup_schedule to include information about valid values for frequency_interval 

### ISSUE THREAD

**Issue by edmallia** [mongodb/terraform-provider-mongodbatlas#1005]
Expand the documentation Expand documentation for mongodbatlas_cloud_backup_schedule to include information about valid values for frequency_interval. The required information can be referenced [here](https://www.mongodb.com/docs/atlas/reference/api/cloud-backup/schedule/modify-one-schedule/#request-body-parameters) and [here](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Cloud-Backup-Schedule/operation/returnOneCloudBackupSchedule).

**Comment by martinstibbe** [comment]
@edmallia Will capture this effort in internal engineering ticket INTMDB-547 to correct this

**Comment by edmallia** [comment]
@martinstibbe I've done the necessary changes on my fork - https://github.com/edmallia/terraform-provider-mongodbatlas/commits/1005-EnhanceDocsFor-mongodbatlas_cloud_backup_schedule.

Have not created a PR as was not able to find a branch in the form of `release-staging-v#.#.#` as outlined in the [Contributing page](https://github.com/edmallia/terraform-provider-mongodbatlas/blob/1005-EnhanceDocsFor-mongodbatlas_cloud_backup_schedule/CONTRIBUTING.md). Could you let me know which branch I should use for the PR?

**Comment by martinstibbe** [comment]
@edmallia https://github.com/mongodb/terraform-provider-mongodbatlas/tree/v1.8.0_staging This branch is next doc release that is open for a PR will name release-staging-v#.#.# next time as we have a delay in 1.7.0 release (we ended up with two release branches for a moment)

**Comment by edmallia** [comment]
Thanks @martinstibbe! Created PR #1006

**Comment by Zuhairahmed** [comment]
Thanks again @edmallia! we are reviewing your [PR ](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1007) so closing this issue.
