### ISSUE TITLE
Warning: Deprecated attribute

### ISSUE THREAD

**Issue by KatjaLeberwurst** [mongodb/terraform-provider-mongodbatlas#1042]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.6
on linux_amd64

provider registry.terraform.io/hashicorp/aws v4.52.0
provider registry.terraform.io/mongodb/mongodbatlas v1.4.3 


```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_cloud_provider_access_setup" "setup_only" {
   project_id = var.project_id
   provider_name = "AWS"
}

resource "aws_iam_role" "test_role" {
  provider  = aws.backup
  depends_on         = [mongodbatlas_cloud_provider_access_setup.setup_only]
  name               = lower("test-role-${var.project_name}")
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
         "AWS": "${mongodbatlas_cloud_provider_access_setup.setup_only.aws.atlas_aws_account_arn}"
      },
      "Action": "sts:AssumeRole",
      "Condition": {
        "StringEquals": {
          "sts:ExternalId": "${mongodbatlas_cloud_provider_access_setup.setup_only.aws.atlas_assumed_role_external_id}"
        }
      }
    }
  ]
}
EOF

  managed_policy_arns = ["arn:aws:iam::aws:policy/AmazonS3FullAccess"]

  tags = {
    tag-key = "IAM Role Acessing s3 Bucket for MongoDB Atlas"
  }
}
```

### Steps to Reproduce

```hcl
terraform plan
```

### Expected Behavior

No warnings or deprecations are raised.

### Actual Behavior

│ Warning: Deprecated attribute
│
│   on project/backup_export_bucket_s3/main.tf line 59, in resource "aws_iam_role" "test_role":
│   59:          "AWS": "${mongodbatlas_cloud_provider_access_setup.setup_only.aws.atlas_aws_account_arn}"
│
│ The attribute "aws" is deprecated. Refer to the provider documentation for details.
│
│ (and 5 more similar warnings elsewhere)

### Additional Context

We already tested with recent versions ( Terraform v1.3.7, provider mongodbatlas v1.8.0), but warning still appears.

**Comment by VitaliAndrushkevich** [comment]
Hello @KatjaLeberwurst 
Please try to replace `mongodbatlas_cloud_provider_access_setup.setup_only.aws.atlas_aws_account_arn` to `mongodbatlas_cloud_provider_access_setup.setup_only.aws_config[0].atlas_aws_account_arn`

**Comment by martinstibbe** [comment]
@KatjaLeberwurst This appears to be an AWS provider parameter deprecation issue

**Comment by KatjaLeberwurst** [comment]
Hello @VitaliAndrushkevich 
Thank you very much! Your tip has eliminated the problem. Now I no longer get the warning.

**Comment by Zuhairahmed** [comment]
Thanks again @VitaliAndrushkevich @KatjaLeberwurst! Feel free to re-open issue if you need anything else here.
