### ISSUE TITLE
ERROR: Pager Duty API key must consist of 32 hexadecimal digits

### ISSUE THREAD

**Issue by bennyrw** [mongodb/terraform-provider-mongodbatlas#1049]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v4.48.0
+ provider registry.terraform.io/hashicorp/http v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.1
+ provider registry.terraform.io/pagerduty/pagerduty v2.6.3
```

We've also tried this against 1.8.0 and the same behaviour occurs.

### Terraform Configuration File 
```hcl
resource "mongodbatlas_alert_configuration" "dedicated_host_restarts" {
  project_id = data.mongodbatlas_project.current.id
  event_type = "OUTSIDE_METRIC_THRESHOLD"
  enabled    = true

  metric_threshold_config {
    metric_name = "RESTARTS_IN_LAST_HOUR"
    operator    = "GREATER_THAN"
    threshold = 1
    units     = "RAW"
  }

  notification {
    type_name   = "PAGER_DUTY"
    delay_min   = 0
    service_key = data.pagerduty_service_integration.events_api_v1.integration_key
  }
}
```

### Steps to Reproduce
1. `terraform apply`
2. Make a change to the alert, e.g. change threshold value
3. `terraform apply` again

### Expected Behavior
Both apply runs update the alert successfully and the changes are visible in Atlas UI

### Actual Behavior
The first (create) apply succeeds but the second (update) apply fails with error:
```
mongodbatlas_alert_configuration.dedicated_host_restarts[0]: Modifying... [id=aWQ=:NjM2MTMyNjdkOWE2MGMzNTk4MTkyNWI0-cHJvamVjdF9pZA==:NjM1OTNjOWQ4NjJlMTg0ZjdhMGU5OTBh]
╷
│ Error: error updating Alert Configuration information: PUT https://cloud.mongodb.com/api/atlas/v1.0/groups/63593c9d862e184f7a0e990a/alertConfigs/63613267d9a60c35981925b4: 400 (request "INVALID_PAGER_DUTY_SERVICE_KEY") PagerDuty service key must consist of 32 hexadecimal digits.
│ 
│   with mongodbatlas_alert_configuration.dedicated_host_restarts[0],
│   on database-results.tf line 277, in resource "mongodbatlas_alert_configuration" "dedicated_host_restarts":
│  277: resource "mongodbatlas_alert_configuration" "dedicated_host_restarts" {
│ 
╵
```

The alert is not updated - the Atlas UI shows the original threshold value.

However, the state file *is* updated, so subsequent `terraform apply` shows no changes.

We've checked the content of our state file and the API key is stored in full as we expected, with no masking (however the terraform logs do show the API key masked).

### References
This seems similar to https://github.com/mongodb/terraform-provider-mongodbatlas/issues/1001 but for Pager Duty. The fix for that was mentioned as being in 1.8.0 but we're seeing the same error for Pager Duty with 1.8.0 indicating it's still a problem there.

**Comment by martinstibbe** [comment]
@bennyrw Will try to replicate your issue using v1.8.0

**Comment by martinstibbe** [comment]
@bennyrw I see issue I will fix for service key issue this in [INTMDB-570](https://jira.mongodb.org/browse/INTMDB-570) also appears it is expecting this value to be set too
 ```
~ metric_threshold_config {
          - mode        = "AVERAGE" -> null
            # (4 unchanged attributes hidden)
        }
```

**Comment by Zuhairahmed** [comment]
@bennyrw just as an update, this fix has been included in our current sprint cycle and will be released as part of v1.8.1 out in a few weeks. will let you know when it has been released and published to Terraform Registry.

**Comment by Zuhairahmed** [comment]
@bennyrw  v1.8.1 has been published to the [Terraform Public Registry](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest)! take a spin and let us know if you need anything else.

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else here
