### ISSUE TITLE
expose 'paused' as an argument for mongodbatlas_cluster

### ISSUE THREAD

**Issue by simon-guerin** [mongodb/terraform-provider-mongodbatlas#105]
It would be great if you are able to expose **paused** as an argument for **mongodbatlas_cluster**   

We have a requirement to pause our non-prod Atlas MongoDB estate on a nightly basis so being able to use this argument for the mongodbatlas_cluster resource would really help

**Comment by themantissa** [comment]
@simon-guerin  thank you for the suggestion.  Always feel free to submit feature requests via https://feedback.mongodb.com/forums/924145-atlas as it allows other users to vote for the idea as well.  I'll add it to our list of future possible enhancements.

**Comment by simon-guerin** [comment]
Will do, thanks for your assistance!

**Comment by themantissa** [comment]
Just to note for other this feature request is now available for up voting and so I am closing this issue - https://feedback.mongodb.com/forums/924145-atlas?category_id=370723.  If you agree this is a high priority request please vote!
