### ISSUE TITLE
mongodbatlas_search_index does not recreate when cluster_name and project_id fields change.

### ISSUE THREAD

**Issue by Bhutania** [mongodb/terraform-provider-mongodbatlas#1053]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.42.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.8.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_search_index" "search-index" {
  name         = "search-index"
  project_id   = data.mongodbatlas_project.project.id
  cluster_name = data.mongodbatlas_cluster.cluster.name

  analyzer         = "lucene.standard"
  collection_name  = "some-collection"
  database         = "some-db"
  mappings_dynamic = false

  search_analyzer = "lucene.standard"

  mappings_fields = <<-EOF
LARGE JSON INPUT
}
```

### Steps to Reproduce

1. Have present `mongodbatlas_serach_index`
2. Attempt to move search index to new cluster and project by referencing different cluster name and project id.
3. Search index will not be created in new project/cluster when running terraform apply, despite changing attributes.

### Expected Behavior

Search index is destroyed on old cluster/project and recreated on new cluster/project

### Actual Behavior

Search index is not destroyed, and new search index is not built.

### Crash Output

N/A

### References

N/A

**Comment by martinstibbe** [comment]
@Bhutania I will attempt same steps to replicate issue

**Comment by martinstibbe** [comment]
@Bhutania Was able to replicate will fix in engineering ticket [INTMDB-576](https://jira.mongodb.org/browse/INTMDB-576)

**Comment by Zuhairahmed** [comment]
@Bhutania  v1.8.1 has been published to the [Terraform Public Registry](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest)! take a spin and let us know if you need anything else.

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else here
