### ISSUE TITLE
Serverless Instance wants to do an in-place update on every run

### ISSUE THREAD

**Issue by maganuk** [mongodb/terraform-provider-mongodbatlas#1070]
I have the following code:

    resource "mongodbatlas_serverless_instance" "cluster" {
      count = var.Enabled ? 1 : 0
      project_id = mongodbatlas_project.project[count.index].id
      name                                    = "mongo-cluster"
      provider_settings_backing_provider_name = "AWS"
      provider_settings_region_name           = "AP_SOUTH_1"
      provider_settings_provider_name = "SERVERLESS"
    }

after updating the module to v1.8.0, terraform wants to do an in-place update on every run:

     # module.mongo.mongodbatlas_serverless_instance.cluster[0] will be updated in-place
      ~ resource "mongodbatlas_serverless_instance" "cluster" {
          + connection_strings_private_endpoint_srv = (known after apply)
            id  = "bmFtZQ==:ZGV2LW1vbm9jbG91ZA==cHJvamVjdF9pZA==:NjNlZjY4MmQ2YjVkZjI2OTY4ODBjMTI2"
            name                                    = "mongo-cluster"
            # (10 unchanged attributes hidden)

            # (3 unchanged blocks hidden)
        }

**Comment by martinstibbe** [comment]
Without additional code to populate the rest of the configuration I can see that 
"connection_strings_private_endpoint_srv" =  null in state file , it is difficult to verify this completely
The private connection string populates on second apply if private endpoint is setup

**Comment by arciisine** [comment]
I'm running into the same issue above and my configuration is even simpler, using constants for all the inputs.

**Comment by Zuhairahmed** [comment]
@arciisine can you share your Terraform Configuration file so we can reproduce issue?

**Comment by arciisine** [comment]
@Zuhairahmed My cdktf snippet is:
`<product>` and `<productId>` are a stand in for actual product details, but redacted for privacy reasons.

```typescript
import { ServerlessInstance } from '@cdktf/provider-mongodbatlas/lib/serverless-instance';

const mongoDbConfig = {
  "projectId": "<productId>",
  "name": "<product>-staging",
  "region": "CENTRAL_US",
  "cloudProvider": "GCP",
  "instanceType": "SERVERLESS"
};

export class CommonResourcesStack extends TerraformStack {
   constructor() {
      new ServerlessInstance(this, `<product>-mongodb-${env}`, {
        name: `<product>-mongodb-${env}`,
        terminationProtectionEnabled: true,
        projectId: mongodbConfig.projectId,
        providerSettingsBackingProviderName: mongodbConfig.cloudProvider,
        providerSettingsProviderName: mongodbConfig.instanceType,
        providerSettingsRegionName: mongodbConfig.region
      });
   }
}   
```

**Comment by arciisine** [comment]
Just to follow up, the output from the terraform plan, on every run is the same as above:
```
   # mongodbatlas_serverless_instance.<product>-mongodb-staging (<product>-mongodb-staging) will be updated in-place
          ~ resource "mongodbatlas_serverless_instance" "<product>-mongodb-staging" {
              + connection_strings_private_endpoint_srv = (known after apply)
                id                                      = "<id>"
                name                                    = "<product>-mongodb-staging"
                # (10 unchanged attributes hidden)

                # (3 unchanged blocks hidden)
            }
```

**Comment by martinstibbe** [comment]
@arciisine Seems to be related to connection_strings_private_endpoint_srv value always wanting to have a value @Zuhairahmed will add to engineering ticket [INTMDB-710](https://jira.mongodb.org/browse/INTMDB-710)

**Comment by Zuhairahmed** [comment]
hi @arciisine / @maganuk  we have released fix to this issue as part of v1.10.0 release. can you test and let us know if this issue has been resolved?

**Comment by arciisine** [comment]
@Zuhairahmed Just verified that its working now.  I'm not longer seeing the mongodb changed on every terraform apply.

**Comment by Zuhairahmed** [comment]
wonderful news @arciisine! resolving issue
