### ISSUE TITLE
Unhelpful error when importing advanced cluster using mongodbatlas_cluster resource

### ISSUE THREAD

**Issue by wyardley** [mongodb/terraform-provider-mongodbatlas#1089]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```sh
Terraform v1.3.9
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/mongodb/mongodbatlas v1.8.0
```

### Steps to Reproduce
Try to import a cluster with, e.g., a multicloud cluster, or to update an existing cluster to use `cluster_type = "GEOSHARDED"`
1. `terraform init`
2. `terraform import mongodbatlas_cluster.twic_dev NNNNNNNNNNNNNNN-xyz` or `terraform apply`

### Expected Behavior
An error message linking to the docs / info on using `mongodbatlas_advanced_cluster` resource

### Actual Behavior
While the error mentions advanced clusters, it's not immediately obvious that you need a different resource type.
```
│ Error: error reading MongoDB Cluster (twic-dev): GET https://cloud.mongodb.com/api/atlas/v1.0/groups/NNNNNNNNNNNNNNN/clusters/xyz: 400 (request "MULTI_CLOUD_CLUSTER_INVALID") Multi-Cloud clusters are not supported by the v1.0 API. Please use the v1.5 API instead. Documentation for the v1.5 API is available at https://docs.atlas.mongodb.com/reference/api/clusters-advanced/.
```

### Debug Output

**Comment by Zuhairahmed** [comment]
Thanks @wyardley can you share config file so we can reproduce issue on our side? this error typically comes up when users attempt to apply [multicloud](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster) parameters to [cluster ](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster) resource which is not supported. also just FYI when migrating from `mongodbatlas_cluster` to `mongodbatlas_advanced_cluster` you will need to first terraform state rm resource-id of cluster resource and then terraform import advanced_cluster resource.

**Comment by wyardley** [comment]
@Zuhairahmed I don't know if I have all the exact examples of configs that triggered this error, but at a basic level, it should have been after updating a config like below to `SHARDED` or `GEOSHARDED`. I don't have one that I can easily reproduce on right this second.

I checked, and the below _does_ work Ok if I just flip `REPLICASET` to `GEOSHARDED`, so it may have been when I started adding additional `replication_specs` blocks.

```hcl
resource "mongodbatlas_cluster" "foo" {
  project_id   = mongodbatlas_project.foo.id
  name         = "foo"
  cluster_type = "REPLICASET"

  replication_specs {
    num_shards = 1
    zone_name  = "Zone 1"
    regions_config {
      region_name     = "US_WEST_2"
      electable_nodes = 3
      priority        = 7
      read_only_nodes = 0
    }
  }
  cloud_backup                 = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.4"

  provider_name               = "GCP"
  disk_size_gb                = 300
  provider_instance_size_name = "M30"

  advanced_configuration {
    javascript_enabled = true
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

And yes, I've been able to successfully do the state surgery necessary to get this working on an existing cluster (not without a few wrinkles, but it's working now).

**Comment by Zuhairahmed** [comment]
Thanks for all this added detail @wyardley. Glad to hear you are unblocked now, will do what we can to reduce friction in this area.  @martinstibbe any ideas here? if not we can include as part of overall improvements to cluster / advanced_cluster resources in internal ticket [INTMDB-338](https://jira.mongodb.org/browse/INTMDB-338)

**Comment by wyardley** [comment]
Might also help to make some of the notes about advanced cluster being preferred in the docs for fields like `cluster_type`

I didn’t know about the other resource until I came across that note, and it’s a little unusual to have two different resource types to manage one type of “thing”.

**Comment by Zuhairahmed** [comment]
this was done primarily to prevent breaking changes on customers that currently leverage `cluster` resource. will provide more guidance / work to reduce friction in update process to `advanced_cluster` resource as part of [INTMDB-338](https://jira.mongodb.org/browse/INTMDB-338) which is targeting v1.10.0. thanks for sharing feedback

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else.
