### ISSUE TITLE
mongodbatlas_search_index does not change name

### ISSUE THREAD

**Issue by adamMo** [mongodb/terraform-provider-mongodbatlas#1096]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v4.57.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.8.1
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_search_index" "name_email_idx" {
  name         = local.name_email_index
  project_id   = data.mongodbatlas_project.mongo_project.id
  cluster_name = data.mongodbatlas_advanced_cluster.mongo_cluster.name

  database        = var.mongo_users_db
  collection_name = "users"
# irrelevant rest
}
```

### Steps to Reproduce

1. Have present mongodbatlas_serach_index
2. Attempt to change search index name, `terraform plan` shows that it would be changed
3. Search index stays with the same name

**Comment by martinstibbe** [comment]
@adamMo Confirmed I am able to replicate your issue will resolve in engineering ticket [INTMDB-671](https://jira.mongodb.org/browse/INTMDB-671)

**Comment by Zuhairahmed** [comment]
@adamMo just FYI this has been picked up as part of current sprint cycle and will be release as part of v1.8.2 in Terraform Registry in a few weeks.

**Comment by Zuhairahmed** [comment]
Hi @adamMo we just heard back from our Engineering team: You can change the index definition of an existing Atlas Search index. You cannot rename an index; if you need to change an index's name, you must create a new index and delete the old one. See docs [here ](https://www.mongodb.com/docs/atlas/atlas-search/edit-index/#:~:text=You%20cannot%20rename%20an%20index,and%20delete%20the%20old%20one) for more details. We will also update our Terraform Docs as well on [Atlas Search Index ](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/search_index) resource accordingly to make more clear. 

Hope this helps!

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else
