### ISSUE TITLE
mongodbatlas_federated_settings_org_role_mapping INVALID_ATTRIBUTE

### ISSUE THREAD

**Issue by alexanderlumix** [mongodb/terraform-provider-mongodbatlas#1110]
Terraform v1.4.1
provider registry.terraform.io/mongodb/mongodbatlas v1.8.1

mongodbatlas_federated_settings_org_role_mapping resource will always fail to create

the problem is in the request to the atlas api

making a post request to:
`https://cloud.mongodb.com/api/atlas/v1.0/federationSettings/{federationSettingsId}/connectedOrgConfigs/{orgId}/roleMappings
`
with a valid body:
```
{
  "externalGroupName": "string",
  "roleAssignments": [
    {
      "orgId": "{orgId}",
      "role": "ORG_OWNER"
    }
  ]
}
```
will result in a response:
```
{
 "detail": "Invalid attribute role specified.",
 "error": 400,
 "errorCode": "INVALID_ATTRIBUTE",
 "parameters": [
  "role"
 ],
 "reason": "Bad Request"
}
```
this should work according to the api doc: 
`https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Federated-Authentication/operation/createRoleMapping`

but in reality what it expects the body to arrive like this:
with a valid body:
```
{
  "externalGroupName": "string",
  "roleAssignments": [
    {
      "orgId": "{orgId}",
      "roleName": "ORG_OWNER"
    }
  ]
}
```

So this either needs to be fixed on your side or on the api side, please fix this asap

**Comment by jiggyjigsj** [comment]
We just encountered this same error.  Its affecting onboarding our new clusters!

**Comment by Zuhairahmed** [comment]
@alexanderlumix @jiggyjigsj confirming there was a change to underlying Atlas Admin API resource for roleAssignments parameter which we are now working to reflect in Terraform Atlas Provider. Fix will be part out of v1.8.2 release which should be out in ~1 week. Internal ticket [INTMDB-697](https://jira.mongodb.org/browse/INTMDB-697)

**Comment by manush1985** [comment]
This is affecting me too. Would be really helpful for an early fix.

**Comment by Zuhairahmed** [comment]
@alexanderlumix @manush1985 @jiggyjigsj issue has been resolved at the Atlas Admin API layer, no changes required to Terraform Provider. Can you re-test and let us know if error has been resolved on your side?

**Comment by alexanderlumix** [comment]
@Zuhairahmed Tested it and it works thanks!
