### ISSUE TITLE
When is mongodbatlas_project_ip_whitelist security group feature going to be released?

### ISSUE THREAD

**Issue by samuelint** [mongodb/terraform-provider-mongodbatlas#114]
Hi I've seen commits about mongodbatlas_project_ip_whitelist security group feature in recent commits. 
https://github.com/terraform-providers/terraform-provider-mongodbatlas/commit/8a58845535d44fd0d72be86f790cdcdc3ed83df4

Do you plan to release a new version anytime soon? I would be very helpful in my project.

Thank you very much!

**Comment by themantissa** [comment]
@samuelint we expect arrival of a major new version within this quarter and it will include this work, as well as quite a few new resources.
