### ISSUE TITLE
Terraform destroy produces a 500 (UNEXPECTED_ERROR) on the underlying API call

### ISSUE THREAD

**Issue by KevinD-87** [mongodb/terraform-provider-mongodbatlas#1162]
Since 09-05-2023, we started seeing failures on our CI/CD pipelines that spin up a test environment and destroys it after running our tests. The issue happens during the API call to remove the project on Mongo Atlas.

### Terraform CLI and Terraform MongoDB Atlas Provider Version

Terraform version: 1.1.9
Provider version: 1.8.0
(but this doesn't seem relevant for this issue, see below)

### Steps to Reproduce

Deploy a new Mongo project via Terraform, then try to destroy it via 'terraform destroy'

### Expected Behavior

The cluster and project gets destroyed.

### Actual Behavior

The cluster gets destroyed, but the project remains.

### Debug Output 

Error: error deleting project (REDACTED): DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/REDACTED: 500 (request "UNEXPECTED_ERROR") Unexpected error.

### Additional Context

Manually calling the administration API with a valid key and secret yields the same result (https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Projects/operation/deleteProject) 
```
curl -X DELETE --digest -u "REDACTED:REDACTED" "https://cloud.mongodb.com/api/atlas/v1.0/groups/REDACTED" --ssl-no-revoke
{"detail":"Unexpected error.","error":500,"errorCode":"UNEXPECTED_ERROR","parameters":[],"reason":"Internal Server Error"}
```

**Comment by ToneVDB** [comment]
We are having the same issue, seems like this has something to do with the fact that we clicked on charts.
It creates a user, that you cant directly delete.
I followed the below steps, and that seemed to work:

1. In project dashboard click on three dot icon which is left of delete icon.
2. Click on "Visit Project Settings"
3. Scroll down to the bottom
4. You will see an option "Delete Charts" click on red Delete button
5. Come back to project dashboard and now you can delete it without any error

**Comment by KevinD-87** [comment]
> We are having the same issue, seems like this has something to do with the fact that we clicked on charts. It creates a user, that you cant directly delete. I followed the below steps, and that seemed to work:
> 
> 1. In project dashboard click on three dot icon which is left of delete icon.
> 2. Click on "Visit Project Settings"
> 3. Scroll down to the bottom
> 4. You will see an option "Delete Charts" click on red Delete button
> 5. Come back to project dashboard and now you can delete it without any error

Oh wow, that worked indeed. Thank you!

**Comment by Zuhairahmed** [comment]
Thanks @ToneVDB! Closing issue @KevinD-87 since it appears issue has been resolved. Feel free to open new issue if you need anything else.
