### ISSUE TITLE
Correct docs for importing network peering resources

### ISSUE THREAD

**Issue by johannaojeling** [mongodb/terraform-provider-mongodbatlas#1179]
### Context

There are a few typos in the documentation for the Network Container and Network Peering resources with regards to importing them into the state:

https://github.com/mongodb/terraform-provider-mongodbatlas/blob/404088d493b6f1e8418acf94639895e329987ce6/website/docs/r/network_container.html.markdown?plain=1#L104

Suggested change: ~~`Clusters`~~ --> `Network Peering Containers`

https://github.com/mongodb/terraform-provider-mongodbatlas/blob/404088d493b6f1e8418acf94639895e329987ce6/website/docs/r/network_peering.html.markdown?plain=1#L424

Suggested change: ~~`Clusters`~~ --> `Network Peering Connections`

**Comment by Zuhairahmed** [comment]
@johannaojeling nice catch! you are correct, do you want to draft quick PR for this one? if not let me know, happy to do so as well. also see [Contributing Guidelines](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md) if helpful.
