### ISSUE TITLE
`region` argument missing from `mongodbatlas_third_party_integration` for integration with PagerDuty

### ISSUE THREAD

**Issue by joao-filipe-natividade** [mongodb/terraform-provider-mongodbatlas#1180]
### Description
`region` argument missing from `mongodbatlas_third_party_integration` for integration with **PagerDuty**.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
`Terraform v1.3.4`
`registry.terraform.io/mongodb/mongodbatlas v1.8.1`

### Terraform Configuration File 
```
resource "mongodbatlas_third_party_integration" "pagerduty" {
  project_id    = <MongoDB Atlas project ID>
  type              = "PAGER_DUTY"
  service_key = <PagerDuty service key>
  region          = "EU" # This argument is missing from the MongoDB Atlas provider for integration with PagerDuty.
}

```
### Steps to Reproduce
tf apply --auto-approve (with `region` as part of `mongodbatlas_third_party_integration`)

### Expected Behavior
`region` to be accepted as a valid argument.

### Actual Behavior
`region` is considered an "invalid field" as I get the following error:

>  Error: error updating third party integration type `PAGER_DUTY` (): PUT <MongoDB endpoint>/integrations/PAGER_DUTY: 400 (request "INTEGRATION_FIELDS_INVALID") At least one integration field is invalid.
> │
> │   with mongodbatlas_third_party_integration.pagerduty["sandbox"],
> │   on alerts.tf line 12, in resource "mongodbatlas_third_party_integration" "pagerduty":
> │   12: resource "mongodbatlas_third_party_integration" "pagerduty" {
> 

### Additional Context
If no region is specified the alerts will be redirected to the default PagerDuty region (US). I want to use **EU** instead.

**Comment by martinstibbe** [comment]
@joao-filipe-natividade I applied 
```
resource 
"mongodbatlas_third_party_integration" "datadog" {
  project_id = local.atlas_project_id
  type       = "PAGER_DUTY"
  service_key    = "b6f6"
  region     = "EU"
}
```

And I did using v1.8.1 and latest I did not see that error but response does seem to ignore region passed to it...
"results": [
  {
   "serviceKey": "****************************56f6",
   "region": null,
   "type": "PAGER_DUTY"
  },

**Comment by Zuhairahmed** [comment]
@joao-filipe-natividade just as an update we raised this issue with Atlas engineering team and should have an update for you in a few weeks. thank you

**Comment by joao-filipe-natividade** [comment]
This issue might be closed, actually. I realised that when setting up a new 3rd party integration in MongoDB (via `mongodbatlas_third_party_integration`) I do not need to explicitly set what PagerDuty `region` I want MongoDB to integrate with. _Apparentely_, PagerDuty knows (based on the integration key _only_) which endpoint it should integrate with (e.g. `EU` vs `US`). 

I'd recommend though adding 2 things to the [Terraform doc](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/third_party_integration):
1. The reason why `region` is not needed (explanation as per the above) for an integration with PagerDuty
2. Leave it clear to everyone that `service_key` needs to be a **32**-char long **hexadecimal** string. Keys of this type can only be issued by PagerDuty `generic_events_api_inbound_integration` integration types. Using either `events_api_v2_inbound_integration` or leveraging the vendor (`data.pagerduty_vendor.mongodb.id`) does create an integration with a key that is not compliant with MongoDB Atlas requirements.

**Comment by Zuhairahmed** [comment]
@joao-filipe-natividade we just pushed fix this, can you re-test and let us know if issue has been fully resolved? Updated internal ticket [CLOUDP-178834](https://jira.mongodb.org/browse/CLOUDP-178834)

**Comment by joao-filipe-natividade** [comment]
Hi, @Zuhairahmed. Yes, it fixed it (although I had to destroy the resource first).
