### ISSUE TITLE
`node_count` documented as read-only for advanced cluster

### ISSUE THREAD

**Issue by BSchneppe** [mongodb/terraform-provider-mongodbatlas#1187]
The `node_count` variable for the advanced cluster is described as "Number of read-only nodes for Atlas to deploy to the region."
Is this valid or should this rather read as "Number of nodes for Atlas to deploy to the region." since it is dependent on which _specs where defined?

https://github.com/mongodb/terraform-provider-mongodbatlas/blob/1350890d4ad9f0573e59d5f3ae12f703776e735e/website/docs/d/advanced_cluster.html.markdown?plain=1#L112

**Comment by Zuhairahmed** [comment]
Yes, great catch! Suggest we update slightly to "Number of nodes of the given type for MongoDB Atlas to deploy to the region" to be more inline with Atlas Admin API docs: https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Multi-Cloud-Clusters/operation/createCluster

**Comment by Zuhairahmed** [comment]
hi @BSchneppe we have released fix as part of v1.10.0 release. thank you for raising this issue!
