### ISSUE TITLE
Problem returning some fields from mongodbatlas_advanced_cluster

### ISSUE THREAD

**Issue by Unb0rn** [mongodb/terraform-provider-mongodbatlas#1189]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

Hey! I wanted to manage my project and its configuration in one submodule and the actual cluster in anoter. When I try to add the output in project submodule it errors out with an "empty tuple" error.

```hcl                                                                                                    
terraform {
  required_version = ">=1.4.6"
  required_providers {
    mongodbatlas = {
      source = "mongodb/mongodbatlas"
      version = "~>1.9.0"
    }
    random = {
      source = "hashicorp/random"
      version = "~>3.5.1"
    }
  }
}

```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "this" {
  count	= var.project_name != null ? 1 : 0

  name				= var.project_name
  org_id			= var.org_id
  project_owner_id		= try(var.project_owner_id, null)
  with_default_alerts_settings	= coalesce(var.with_default_alerts_settings, true)

  dynamic teams {
    for_each = var.teams
    content {
      team_id    = teams.value.team_id
      role_names = teams.value.role_names
    }
  }

  dynamic api_keys {
    for_each = var.api_keys
    content {
      api_key_id = api_keys.value.api_key_id
      role_names = api_keys.value.role_names
    }
  }
}

output "project_id" {
  value		= one(mongodbatlas_project.this).id
  description	= "ID of the created Atlas project"
}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Expected Behavior
The ID of the cluster should be passed to module output

### Actual Behavior
```
│ Error: Attempt to get attribute from null value
│ 
│   on modules/project/outputs.tf line 2, in output "project_id":
│    2:   value		= one(mongodbatlas_project.this).id
│     ├────────────────
│     │ mongodbatlas_project.this is empty tuple
│ 
│ This value is null, so it does not have any attributes.
```

### Crash Output
Terraform doesn't crash

**Comment by colm-quinn** [comment]
Hi!, The example you provided only shows the child module for project - in your parent module you should be able to access the child module output and pass it to a child cluster module. See https://developer.hashicorp.com/terraform/language/values/outputs#accessing-child-module-outputs for the syntax used.

I create a small example for projects & users using your template as a base. In the root `main.tf` I created the following:
```
module "project_test" {
  source = "./modules/projects"

  project_name = var.project_name
  org_id			= var.org_id
  project_owner_id		= try(var.project_owner_id, null)
  with_default_alerts_settings	= coalesce(var.with_default_alerts_settings, true)
  api_keys = var.api_keys
  teams = var.teams
}

module "user_create" {
  source = "./modules/user"
  user-name = var.user-name
  user-role = var.user-role
  project_id = "${module.project_test.project_id}"
}
```

See https://github.com/colm-quinn/terrmform-modules-test/tree/main for a complete example

**Comment by Zuhairahmed** [comment]
hi @Unb0rn can you confirm if this helps to resolve your issue? if so feel free to close this ticket. thank you.

**Comment by Zuhairahmed** [comment]
closing ticket and feel free to open new issue if you need anything else. thank you.
