### ISSUE TITLE
Continuous Backup is not supported for (new) AWS clusters

### ISSUE THREAD

**Issue by nikhil-mongo** [mongodb/terraform-provider-mongodbatlas#121]
The new AWS clusters does not support Continuous Backup since the last release of the MongoDB Atlas. This should be updated in the Terraform documentation and the code examples for the backup parameters.

Change 1 -- 

`backup_enabled               = true` // remove this parameter and should be replaced by 
`provider_backup_enabled     = true`   // enable cloud provider snapshots

This will however force the resource block of CPS to be added with every cluster creation and that's how it should be.

Error Received:
`Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/5dd0f66379358e17e49d6c40/clusters: 400 (request "Bad Request") Continuous backup is no longer supported for new AWS clusters.`

Change 2--

Add the parameters to enable Point in Time Restore as it is supported by the MongoDB Atlas API.
`pitEnabled `

> https://docs.atlas.mongodb.com/reference/api/clusters-modify-one/

Also, can we please ensure that these changes when released for Atlas are incorporated to Terraform simultaneously as the customers using Terraform do not get the changes and the implementation fails for them. 

Thanks

**Comment by themantissa** [comment]
@nikhil-mongo https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/116 will fix the doc.  It will go with the next release. 

The point in time restore option is already in the engineering queue and we plan to have in the next release. 

We cannot launch at the same time as Atlas but try to follow closely.
