### ISSUE TITLE
app_id property doesn't work in mongodbatlas_event_trigger resource

### ISSUE THREAD

**Issue by Alexkuva** [mongodb/terraform-provider-mongodbatlas#1224]
The app_id to create an Atlas Event Trigger [in the documentation](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/event_triggers#app_id) doesn't work, even by adding it manually.
I get the app_id through realm cli [in the documentation](https://www.mongodb.com/docs/atlas/app-services/apps/metadata/) because it doesn't work using API [issue on community](https://www.mongodb.com/community/forums/t/mongodb-api-for-getting-application-ids-does-not-return-any-value/230428)

I got the following issue:
```
Error: error creating MongoDB EventTriggers (<project_id>): POST https://realm.mongodb.com/api/admin/v3.0/groups/<project_id>/apps/<app_id>/triggers: 404 (request "<app_id>") app not found
```

app_id through realm cli doesn't look well (realm-cli apps list) because it's the same that project_id every time ...

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
$ terraform --version
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/http v3.3.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.9.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "customer_project" {
  name   = var.customer_name
  org_id = data.mongodbatlas_roles_org_id.kaiten_organization.org_id

}

resource "random_pet" "cluster_name" {
}

resource "mongodbatlas_cluster" "customer_cluster" {
  project_id   = mongodbatlas_project.customer_project.id
  name         = random_pet.cluster_name.id
  cluster_type = "REPLICASET"
  replication_specs {
    num_shards = 1
    regions_config {
      region_name     = var.cluster_region
      electable_nodes = 3
      priority        = 7
      read_only_nodes = 0
    }
  }
  cloud_backup = false
  mongo_db_major_version       = "6.0"

  # Provider Settings "block"
  provider_name               = var.cluster_provider_name
  disk_size_gb                = 10
  provider_instance_size_name = "M10"
}


resource "mongodbatlas_event_trigger" "instance_trigger" {
  project_id = mongodbatlas_project.customer_project.id
  app_id = "<app_id>"
  name = "instance-event"
  type = "DATABASE"
  disabled = false
  unordered = false
  config_operation_types = ["INSERT", "UPDATE"]
  config_database = "kaiten"
  config_collection = "instance"
  config_service_id = "1"
  config_full_document = false
  config_full_document_before = false
  event_processors {
    aws_eventbridge {
      config_account_id = var.aws_account
      config_region = var.cluster_region
    }
  }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by Zuhairahmed** [comment]
@Alexkuva if you look at Atlas App Services API docs ([here](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#section/Project-and-Application-IDs)), it notes "your Application ID is the ObjectId value in the `_id` field, not the `client_app_id`." can you do a cURL command as in docs example and let us know if you still get this same error after double checking you are manually inputting correcting `app_id` input?

**Comment by Alexkuva** [comment]
Yes I'm using _id via realm cli not client_app_id.
I tried using the API, but I got an empty array (https://www.mongodb.com/community/forums/t/mongodb-api-for-getting-application-ids-does-not-return-any-value/230428)

**Comment by Zuhairahmed** [comment]
> Yes I'm using _id via realm cli not client_app_id. I tried using the API, but I got an empty array (https://www.mongodb.com/community/forums/t/mongodb-api-for-getting-application-ids-does-not-return-any-value/230428)

@laurazhukas can you take look?

**Comment by Alexkuva** [comment]
Hi, I was able to get the right "_id" through the api but I had to add an optional product query parameter (atlas product types represent special apps for Atlas Triggers). Maybe it could be interesting to add it directly on the documentation?

The exact one should be : 
```
curl --request GET --header "Authrorization: Bearer <TOKEN>" [<URL>](https://realm.mongodb.com/api/admin/v3.0/groups/<projectId>/apps?product=atlas)
```

Now that I've got the right "_id", I got the following issue:
```
error creating MongoDB EventTriggers (<productId>): POST https://realm.mongodb.com/api/admin/v3.0/groups/<productId>/apps/<appId>/triggers: 400 (request "") cannot unmarshal into an ObjectID, the length must be 24 but it is 1
```
my appId retrieved has a length of 24 so.

**Comment by Zuhairahmed** [comment]
thanks sharing, has there been any update on this @Alexkuva or are you still blocked? if so @laurazhukas maybe best to advise on this specific error coming for Atlas App Services API for Event Trigger resource.

**Comment by Alexkuva** [comment]
Hi, I've still got the same issue:
`error creating MongoDB EventTriggers (<productId>): POST https://realm.mongodb.com/api/admin/v3.0/groups/<productId>/apps/<appId>/triggers: 400 (request "") cannot unmarshal into an ObjectID, the length must be 24 but it is 1`

Even with the right ID it doesn't work

**Comment by laurazhukas** [comment]
That issue is likely arising from an error in the function_id or the service_id field in the payload. I would recommend verifying that those ids match the 24 character format. Here is a link to the documentation with an example payload - https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/triggers/operation/adminCreateTrigger.

**Comment by Zuhairahmed** [comment]
Thanks @laurazhukas! @Alexkuva are you still blocked? if not feel free to close this ticket.

**Comment by Zuhairahmed** [comment]
Closing issue, feel free to open new issue if you run into any issues. thanks again @laurazhukas for the advise here!
