### ISSUE TITLE
Add support in cluster-tier autoscaling

### ISSUE THREAD

**Issue by eladazary** [mongodb/terraform-provider-mongodbatlas#123]
It seems like you didn't add support in cluster-tier autoscaling option of a cluster.
It's already supported by API and UI. Can you please assist?

**Comment by themantissa** [comment]
Hi @eladazary, we did not as it did not exist as an option when we first developed clusters support for the Terraform provider.  However we are looking how to best enable this in a future version in a Terraform workable way.   This also has been submitted as a feature request at https://feedback.mongodb.com/forums/924145-atlas?category_id=370723 so please up vote it there if you have not already.  Thank you!

**Comment by valery-zhurbenko** [comment]
@themantissa hi,
At this moment it can be done with provisioner "local-exec" and there CURL command to atlas API to enable instances autoscaling.
And then (after enabled instance autoscaling, and autoscaling event occurs) instance type can be different from type that is in tfplan and then terraform tries to change instance type back, which can be harmful and then this became an issue - to use terraform with mongodb atlas if you need mongodb instance autoscaling.

**Comment by themantissa** [comment]
@valery-zhurbenko you are describing exactly the reason we haven't yet enabled it yet (but likely will). When one enables auto scaling in Atlas you are now doing things in an automated way, outside of Terraforms flow.  This is an anti-pattern to the Terraform philosophy.  So, basically if someone set autoscaling we have to figure out, should Terraform then not do anything if they underlying cluster changes?  Just refresh it?  It's quite a challenge and I appreciate feedback and thoughts on what would make the most sense.

**Comment by valery-zhurbenko** [comment]
@themantissa I think need to implement some "ignore_changes" for "desired", but yes check "min" and "max" in this case.

**Comment by themantissa** [comment]
@valery-zhurbenko we just enabled the attributes in version 0.6.0 with documentation suggestion to use a lifecycle block w/ ignore_changes just as you noted, 0.6.0 released just last Friday.
