### ISSUE TITLE
Cloud provider snapshot management

### ISSUE THREAD

**Issue by rrondeau** [mongodb/terraform-provider-mongodbatlas#124]
Hi,

Starting with mongodb 4.2 i have to use cloud provider snapshots but i dont see any resource to manage the scheduling or the retention policy. I am using GCP as provider.

Do you have any plans on this subject ?

**Comment by themantissa** [comment]
Hi @rrondeau,  

We are just wrapping up a version and each version has included more resources based on customer need.  If you can submit this great feedback at https://feedback.mongodb.com/forums/924145-atlas?category_id=370723 then others can up vote it as well so we can prioritize accordingly.  

Thank you!
