### ISSUE TITLE
Has `project_assignment` of `mongodbatlas_api_key` not been implemented?

### ISSUE THREAD

**Issue by shirakiya** [mongodb/terraform-provider-mongodbatlas#1249]
In Documentation for v1.10.0, in order to assign PAK to multiple projects, the documentation instructs to use `project_assignment` parameter of `mongodbatlas_api_key` as below.
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/1ea0f84b92e344eae8120d531d64c083bb57f7af/website/docs/r/project_api_key.html.markdown?plain=1#L28-L30

But I seem `project_assignment` parameter of `mongodbatlas_api_key` has not been implemented in v1.10.0.
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/1ea0f84b92e344eae8120d531d64c083bb57f7af/mongodbatlas/resource_mongodbatlas_api_key.go#L16-L56

Is it just a mistake?

If that, how to assign `mongodbatlas_api_key` (related to organizations) to multiple projects without `api_key` parameter of `mongodbatlas_project`?

### Terraform CLI and Terraform MongoDB Atlas Provider Version
v1.10.0

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
```

### References

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project_api_key

**Comment by martinstibbe** [comment]
@shirakiya This looks to be a type in the documentation in the examples folder it is using mongodbatlas_project_api_key resource which is where this parameter is implemented.

**Comment by Zuhairahmed** [comment]
thanks @shirakiya for letting us know! see example in our repo on how to create api key and assign to multiple projects here: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/examples/atlas-api-key/create-api-key-assign-to-multiple-projects/main.tf 

@martinstibbe do you want to create a quick PR to correct doc bug (on this [page](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project_api_key)) for future users? thanks again to you both.

**Comment by shirakiya** [comment]
@Zuhairahmed Thanks for your useful advice! I understand it's a doc bug and how to assign API key to multiple projects.
