### ISSUE TITLE
[Query] Unable to find the endpoint_service_id

### ISSUE THREAD

**Issue by soniadas0210** [mongodb/terraform-provider-mongodbatlas#1281]
Hello All !

### Terraform CLI and Terraform MongoDB Atlas Provider Version
```command
Terraform v1.5.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.62.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/mongodb/mongodbatlas v1.10.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_privatelink_endpoint" "privatelink_endpoint" {
  project_id    = var.project_id
  provider_name = "AZURE"
  region        = var.region
}

resource "mongodbatlas_privatelink_endpoint_service" "privatelink_endpoint_service" {
  for_each = {
    for link in var.privatelinks : link.azure_private_endpoint_ip_address => link
  }
  project_id                  = mongodbatlas_privatelink_endpoint.privatelink_endpoint.project_id
  private_link_id             = mongodbatlas_privatelink_endpoint.privatelink_endpoint.private_link_id
  endpoint_service_id         = each.value.azure_private_endpoint_id
  private_endpoint_ip_address = each.value.azure_private_endpoint_ip_address
  provider_name               = "AZURE"
}
```

### Steps to Reproduce
1. `terraform import {terraform-resource-address} {project_id}--{private_link_id}--{endpoint_service_id}--{provider_name}`

### Query
I understand, that we need to import the resource `mongodbatlas_privatelink_endpoint_service` using the ID `{project_id}--{private_link_id}--{endpoint_service_id}--{provider_name}`.
But from where I can find the `{endpoint_service_id}` ?

**Comment by colm-quinn** [comment]
Hi,
The easiest way to get the private endpoints Ids would be to use the atlas cli to list them. See https://www.mongodb.com/docs/atlas/cli/stable/command/atlas-privateEndpoints-azure-list/#std-label-atlas-privateEndpoints-azure-list for details (Azure is in your example, there are a few different private endpoint commands you can use)

**Comment by soniadas0210** [comment]
Unfortunately, when I use the endpoint service it gives me the error:

```
Error: error reading MongoDB Private Service Endpoint Connection(pls_XXXXXXXXXXXXXXXXX): GET https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXXXXXXXXXXX/privateEndpoint/AZURE/endpointService/XXXXXXXXXXXXXXXX/endpoint/pls_XXXXXXXXXXXXXXX: 404 (request "PRIVATE_ENDPOINT_SERVICE_NOT_FOUND") Private endpoint service with id XXXXXXXXXXXXXXXXXX, pls_XXXXXXXXXXXXXXX was not found.
```

**Comment by soniadas0210** [comment]
@colm-quinn Is it something else I need to consider to import ?

**Comment by soniadas0210** [comment]
> Unfortunately, when I use the endpoint service it gives me the error:
> 
> ```
> Error: error reading MongoDB Private Service Endpoint Connection(pls_XXXXXXXXXXXXXXXXX): GET https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXXXXXXXXXXX/privateEndpoint/AZURE/endpointService/XXXXXXXXXXXXXXXX/endpoint/pls_XXXXXXXXXXXXXXX: 404 (request "PRIVATE_ENDPOINT_SERVICE_NOT_FOUND") Private endpoint service with id XXXXXXXXXXXXXXXXXX, pls_XXXXXXXXXXXXXXX was not found.
> ```

Any suggestion on this issue ?

**Comment by martinstibbe** [comment]
@soniadas0210 I will replicate your config example and attempt to provide a solution

**Comment by soniadas0210** [comment]
Hello All,

Any update on this issue? We are waiting to find the solution to import the endpoint service id of the mongodb atlas.

Thanks in advance.

**Comment by Zuhairahmed** [comment]
hi @soniadas0210 believe this has been closed out via MongoDB Support. can you confirm if this is the case?

**Comment by pauldraper** [comment]
https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Private-Endpoint-Services/operation/getPrivateEndpoint

This is the ID of the endpoint you own in your cloud provider.

For AWS, it's `vpce-*`. For Azure, it's URL-encoded form of `subcriptions/...`
