### ISSUE TITLE
json: cannot unmarshal number 4841168896 into Go struct field CloudProviderSnapshot.storageSizeBytes of type int

### ISSUE THREAD

**Issue by Ivikassingh** [mongodb/terraform-provider-mongodbatlas#1333]
While creating the snapshot for M20 database, I'm getting this issue

**Comment by andreaangiolillo** [comment]
Hello @Ivikassingh 
Thank you for opening the issue. Could you provide the following information:

1. Terraform version
2. MongoDB Atlas provider version
3. Your configuration file
4. Processor architecture of the machine used to run the configuration file

This will help us to reproduce the issue.

Thank you!
