### ISSUE TITLE
Error: json: cannot unmarshal number 9501614080 into Go struct field CloudProviderSnapshot.storageSizeBytes of type int 

### ISSUE THREAD

**Issue by udaykiranete4** [mongodb/terraform-provider-mongodbatlas#1341]
Terraform version: Terraform v1.5.2 on windows_386
MongoDB Atlas provider version : 1.10.2

Your configuration file: 
`  resource "mongodbatlas_cloud_backup_snapshot" "snapshot" {
    provider          = mongodbatlas.source
    project_id        = data.mongodbatlas_project.source_project.id
    cluster_name      = var.source_cluster_name
    description       = var.snap_description
    retention_in_days = var.retention_in_days
  }`
  
  
Processor architecture of the machine used to run the configuration file: 
System Type x64-based PC
Processor	AMD Ryzen 7 5825U with Radeon Graphics, 2000 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by andreaangiolillo** [comment]
Hello 👋 ,

Thanks for opening this issue. The error is related to the fact that you are using windows_386 (32-bit architecture). As per [HashiCorp's recommendations for Provider Binary Operating Systems and Architectures](https://developer.hashicorp.com/terraform/registry/providers/os-arch), the provider should include the windows_386 binary but not necessarily prioritize fixes for it. 

To address this issue, I recommend running the same Terraform configuration on a 64-bit architecture. Meanwhile, we will discuss internally how to prioritize this fix.

Thanks

**Comment by Zuhairahmed** [comment]
hi @udaykiranete4 see latest guidance on Supported OS and Architecture types. Thank you. https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/README.md#supported-os-and-architectures
