### ISSUE TITLE
terraform-provider-mongodbatlas_v1.10.2 plugin crashes when including backup schedule

### ISSUE THREAD

**Issue by russ960** [mongodb/terraform-provider-mongodbatlas#1368]
When I include the below backup schedule in my cluster.tf on a new cluster I get a crash of the provider:
```
resource "mongodbatlas_cloud_backup_schedule" "test-1368-daily-backup" {
  project_id   = local.project_id
  cluster_name = "test-1368"

  reference_hour_of_day    = 23
  reference_minute_of_hour = 00

  // This will now add the desired policy items to the existing mongodbatlas_cloud_backup_schedule resource
  policy_item_daily {
    frequency_interval = 1
    retention_unit     = "days"
    retention_value    = 7
  }
}
```
Despite he error the cluster is created in Atlas as expected but with the default backup schedule.

If I run the cluster deployment without this code it will execute properly and deploy the cluster.   I can then add the code back in and the backup schedule will be added.  It only fails when it is a new cluster deployment.

Output error message from Terraform Cloud:

> Stack trace from the terraform-provider-mongodbatlas_v1.10.2 plugin:
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0xe0dc90]
> 
> goroutine 39 [running]:
> github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.cloudBackupScheduleCreateOrUpdate({0x14284c8, 0xc000ad7950}, 0xc0008ec480, 0xc000000001?, {0xc000534c00, 0x18}, {0xc000534b70, 0x12})
> github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go:537 +0xc70
> github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasCloudBackupScheduleCreate({0x14284c8, 0xc000ad7950}, 0x0?, {0xf8cf40?, 0xc000921d10?})
> github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go:287 +0x125
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00067d420, {0x1428500, 0xc000ac6690}, 0xd?, {0xf8cf40, 0xc000921d10})
> github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:733 +0x12e
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00067d420, {0x1428500, 0xc000ac6690}, 0xc00017d5f0, 0xc00017ae00, {0xf8cf40, 0xc000921d10})
> github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/resource.go:864 +0xa7e
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00026dc68, {0x1428500?, 0xc000ac6570?}, 0xc0001611d0)
> github.com/hashicorp/terraform-plugin-sdk/v2@v2.27.0/helper/schema/grpc_provider.go:1024 +0xe8d
> github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000528aa0, {0x1428500?, 0xc000a93bc0?}, 0xc000170150)
> github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/tf5server/server.go:821 +0x574
> github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x108dbe0?, 0xc000528aa0}, {0x1428500, 0xc000a93bc0}, 0xc0001700e0, 0x0)
> github.com/hashicorp/terraform-plugin-go@v0.16.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:422 +0x170
> google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a0000, {0x142d040, 0xc0006b41a0}, 0xc000a9b440, 0xc000671560, 0x1af1ba0, 0x0)
> google.golang.org/grpc@v1.56.0/server.go:1337 +0xdf3
> google.golang.org/grpc.(*Server).handleStream(0xc0002a0000, {0x142d040, 0xc0006b41a0}, 0xc000a9b440, 0x0)
> google.golang.org/grpc@v1.56.0/server.go:1714 +0xa36
> google.golang.org/grpc.(*Server).serveStreams.func1.1()
> google.golang.org/grpc@v1.56.0/server.go:959 +0x98
> created by google.golang.org/grpc.(*Server).serveStreams.func1
> google.golang.org/grpc@v1.56.0/server.go:957 +0x18c
> 
> Error: The terraform-provider-mongodbatlas_v1.10.2 plugin crashed!
> 
> This is always indicative of a bug within the plugin. It would be immensely
> helpful if you could report the crash with the plugin's maintainers so that it
> can be fixed. The output above should help diagnose the issue.

**Comment by andreaangiolillo** [comment]
Hi @russ960 

I was not able to reproduce the issue in 1.10.2. Could you share the config of your cluster? This is the config that I used to try to replicate the issue:

```terraform
resource "mongodbatlas_project" "atlas-project" {
  name   = "Issue-1368"
  org_id = "60ddf55c27a5a20955a707d7"
}

resource "mongodbatlas_advanced_cluster" "test" {
  project_id     = mongodbatlas_project.atlas-project.id
  name           = "example2"
  cluster_type   = "REPLICASET"
  backup_enabled = true
  replication_specs {
    region_configs {
      electable_specs {
        instance_size = "M10"
        node_count    = 3
      }
      analytics_specs {
        instance_size = "M10"
        node_count    = 1
      }
      provider_name = "AWS"
      priority      = 7
      region_name   = "US_EAST_1"
    }
  }
}

resource "mongodbatlas_cloud_backup_schedule" "us-wht-mdba-app-01-daily-backup" {
  project_id   = mongodbatlas_project.atlas-project.id
  cluster_name = mongodbatlas_advanced_cluster.test.name

  reference_hour_of_day    = 23
  reference_minute_of_hour = 00

  // This will now add the desired policy items to the existing mongodbatlas_cloud_backup_schedule resource
  policy_item_daily {
    frequency_interval = 1
    retention_unit     = "days"
    retention_value    = 7
  }
}
```

 Thanks

**Comment by russ960** [comment]
@andreaangiolillo This test cluster configuration also fails:
```
resource "mongodbatlas_cluster" "shared" {
  project_id   = local.project_id
  name         = "mongodbatlas-shared"
  cluster_type = "REPLICASET"

  replication_specs {
    num_shards = 1
    regions_config {
      region_name     = local.region_name
      electable_nodes = 3
      priority        = 7
      read_only_nodes = 0
    }
  }
  cloud_backup                   = true
  auto_scaling_disk_gb_enabled   = true
  termination_protection_enabled = true
  mongo_db_major_version         = "5.0"

  # Provider Settings "block"
  provider_name               = "GCP"
  disk_size_gb                = 85
  provider_instance_size_name = "M30"

  advanced_configuration {
   oplog_size_mb = 12288
  }
}

resource "mongodbatlas_cluster" "test-1368" {
  project_id   = local.project_id
  name         = "test-1368"
  cluster_type = "REPLICASET"

  replication_specs {
    num_shards = 1
    regions_config {
      region_name     = local.region_name
      electable_nodes = 3
      priority        = 7
      read_only_nodes = 0
    }
  }
  cloud_backup                   = true
  auto_scaling_disk_gb_enabled   = true
  termination_protection_enabled = true
  mongo_db_major_version         = "5.0"

  # Provider Settings "block"
  provider_name               = "GCP"
  disk_size_gb                = 85
  provider_instance_size_name = "M30"

  advanced_configuration {
   oplog_size_mb = 12288
  }
}

resource "mongodbatlas_cloud_backup_schedule" "test-1368-daily-backup" {
  project_id   = local.project_id
  cluster_name = "test-1368"

  reference_hour_of_day    = 23
  reference_minute_of_hour = 00

  // This will now add the desired policy items to the existing mongodbatlas_cloud_backup_schedule resource
  policy_item_daily {
    frequency_interval = 1
    retention_unit     = "days"
    retention_value    = 7
  }
}
```

**Comment by andreaangiolillo** [comment]
Hello @russ960,

I've successfully replicated the issue using your configuration. However, it's important to clarify that the problem doesn't lie with the provider itself; rather, it's related to how you've configured the `mongodbatlas_cloud_backup_schedule` resource. To address this, you'll need to make the following updates to your configuration:

```terraform
resource "mongodbatlas_cloud_backup_schedule" "test-1368-daily-backup" {
  project_id   = local.project_id
  cluster_name = mongodbatlas_cluster.test-1368.name

  reference_hour_of_day    = 23
  reference_minute_of_hour = 00

  // This will now add the desired policy items to the existing mongodbatlas_cloud_backup_schedule resource
  policy_item_daily {
    frequency_interval = 1
    retention_unit     = "days"
    retention_value    = 7
  }
}
```

Note the change with the `cluster_name` field which is required to communicate to Terraform to wait for the cluster resource to be created before creating the backup policy.

Fell free to reopen the issue if after updating your configuration you still get the issue.
Thanks
