### ISSUE TITLE
add mongodbatlas_project datasource

### ISSUE THREAD

**Issue by adrian-gierakowski** [mongodb/terraform-provider-mongodbatlas#137]
I have a terraform project which creates a `mongodbatlas_project` and another project which creates clusters in this project.  In the second one, I'd like to be able to retrieve the `id` of the `mongodbatlas_project` using `org_id` and `name`

**Comment by themantissa** [comment]
@adrian-gierakowski the missing project datasource will be added in our next version, 0.4.0.   Thank you for submitting and expect it soon.
