### ISSUE TITLE
Event Trigger resource doesn't support wildcard collection name

### ISSUE THREAD

**Issue by chrischenyc** [mongodb/terraform-provider-mongodbatlas#1374]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.4.2

mongodbatlas = {
  source  = "mongodb/mongodbatlas"
  version = "~> 1.11.0"
}
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_event_trigger" "aws_eventbridge" {
  project_id = var.project_id
  app_id = var.app_id
  name = "amazon-eventbridge"
  type = "DATABASE"
  config_operation_types = ["INSERT", "UPDATE", "DELETE"]
  config_database = var.database_name
  config_collection = "*"
  config_service_id = var.service_id
  event_processors {
    aws_eventbridge {
      config_account_id = var.aws_account_id
      config_region = "ap-southeast-2"
    }
  }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

### Expected Behavior

The created trigger should listen to data changes in all collections in the given database.

### Actual Behavior

Wildcard doesn't work.

However, in MongoDB Atlas UI, when defining a database trigger, if no collection name is selected, it's considered a wildcard.

![image](https://github.com/mongodb/terraform-provider-mongodbatlas/assets/334233/f5091432-1603-4f41-ac3c-2a4a4031611d)

**Comment by Zuhairahmed** [comment]
hi @chrischenyc this an improvement that we will have to add to our [Atlas App Services API ](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/)roadmap before we can expose into Terraform Provider. agree with your suggestion. can you add this to https://feedback.mongodb.com/forums/924145-atlas?category_id=370723 (or upvote an existing one) so we can get prioritized appropriately? closing this ticket down for now, but feel free to reach out if you need anything else in the interim.

**Comment by laurazhukas** [comment]
Hi @chrischenyc, Triggers at the deployment and database level are not yet available (a trigger is only able to watch one collection today), but we are excited to be working on them this quarter. The current behavior in the form is that the trigger cannot be saved if there is no collection specified, just checked this in the UI and an error is thrown, as expected. If you came across behavior in the UI contrary to this, please let us know. Thanks!
