### ISSUE TITLE
Auto Scale Cluster Tier Missing

### ISSUE THREAD

**Issue by hc-danieltiziani** [mongodb/terraform-provider-mongodbatlas#141]
For the production environments I'd like to set the minimum and maximum instance tiers, but it is currently not available in the cluster configuration.

This option is available when you go to page "CREATE CLUSTER" |  "Auto-scale" | "CLUSTER TIER".

**Comment by themantissa** [comment]
Hi @hc-danieltiziani  investigating and adding auto scale is on our roadmap, also feel free to up vote the feature request here: https://feedback.mongodb.com/forums/924145-atlas/suggestions/39629620-expose-auto-cluster-scaling-options-via-terraform as that feedback is used in our prioritization.  Thanks!
