### ISSUE TITLE
unable to deploy a DISK_PARTITION_UTILIZATION_DATA AlertConfiguration

### ISSUE THREAD

**Issue by mitja-hofer** [mongodb/terraform-provider-mongodbatlas#1410]
Hello!

We are using the Terraform provider version `1.3.1` which is a bit old however it seemed to work fine until yesterday. Today we are seeing failed deploys even though we have made zero changes to our Terraform MongoDB Atlas configuration. The AlertConfiguration of type DISK_PARTITION_UTILIZATION_DATA fails a no-change deploy with:
```
Error: error updating Alert Configuration information: PUT https://cloud.mongodb.com/api/xyz: 400 (request "METRIC_TYPE_UNSUPPORTED") The metric type DISK_PARTITION_UTILIZATION_DATA is not supported.
```

This seems to be an issue with MongoDB Atlas API since we are seeing the same error when deploying through Cloudformation as outlined in the issue on that repo: https://github.com/mongodb/mongodbatlas-cloudformation-resources/issues/685. 

We assume some API changes. Thank you for looking into it.

**Comment by andreaangiolillo** [comment]
Hello @mitja-hofer 
I discussed this internally and I can confirm that this is an API change. 

Thanks
