### ISSUE TITLE
Error creating users with mongodbatlas_database_user (following documentation examples)

### ISSUE THREAD

**Issue by hc-danieltiziani** [mongodb/terraform-provider-mongodbatlas#144]
I'm trying to create users based on the documentation at https://www.terraform.io/docs/providers/mongodbatlas/r/database_user.html but it's not working.

```
resource "mongodbatlas_database_user" "admin_user" {
  auth_database_name = "admin"
  project_id         = "FAKEID"
  username           = "USERNAME"
  password           = "SOME PWD"

  roles {
    role_name     = "readWrite"
    database_name = "rate-service"
  }
}
```

**Error**:

```
Error: Missing required argument

  on tf/mongodb_atlas_cluster.tf line 46, in resource "mongodbatlas_database_user" "admin_user":
  46: resource "mongodbatlas_database_user" "admin_user" {

The argument "database_name" is required, but no definition was found.


Error: Unsupported argument

  on tf/mongodb_atlas_cluster.tf line 47, in resource "mongodbatlas_database_user" "admin_user":
  47:   auth_database_name = "admin"

An argument named "auth_database_name" is not expected here.
```
Using: terraform-provider-mongodbatlas_v0.4.0_x4

**Comment by themantissa** [comment]
@hc-danieltiziani thank you for the report - @PacoDw  and @marinsalinas please take a look.

**Comment by marinsalinas** [comment]
Hello @hc-danieltiziani  could you please run the following command and share the output, it is just to be sure that you are using the latest release.

`terraform provider --version`

**Comment by themantissa** [comment]
@hc-danieltiziani wanted to check in and see if the issue has been resolved or if you are still having issues?

**Comment by themantissa** [comment]
Going to assume we are good here and close.  Please comment if any issues persist.

**Comment by hc-danieltiziani** [comment]
No issues, responded on other issue. Thanks for the attention!
