### ISSUE TITLE
Cannot use mongodbatlas_maintenance_window - Error provider does not support

### ISSUE THREAD

**Issue by hc-danieltiziani** [mongodb/terraform-provider-mongodbatlas#145]
Cannot use ```mongodbatlas_maintenance_window```

**It gives the following error:** 

```
Error: Invalid resource type  on tf/mongodb_atlas_cluster.tf line 39, in resource "mongodbatlas_maintenance_window" "cluster_maintenance_window":
  39: resource "mongodbatlas_maintenance_window" "cluster_maintenance_window" {
The provider provider.mongodbatlas does not support resource type "mongodbatlas_maintenance_window".
```

```
resource "mongodbatlas_maintenance_window" "cluster_maintenance_window" {
  project_id  = 'FAKEID'
  day_of_week = 3 # S=1, M=2, T=3, W=4, T=5, F=6, S=7
  hour_of_day = 5 # Hour of the day when you would like the maintenance window to start. This parameter uses the 24-hour clock, where midnight is 0, noon is 12 (Time zone is UTC).
}
```

Using: terraform-provider-mongodbatlas_v0.4.0_x4

**Comment by themantissa** [comment]
@hc-danieltiziani thank you for the report - @PacoDw  and @marinsalinas can you please take a look.

**Comment by PacoDw** [comment]
Hello @hc-danieltiziani, I tested it (directly using the download version, with terraform test plugin resource) and It didn't get me that error, are you sure that you are using the current plugin version? Because the above error explains that the current version doesn't have that resource, it's weird because it has it so you shouldn't have that error.

**Comment by themantissa** [comment]
@hc-danieltiziani wanted to check in and see if the issue has been resolved or if you are still having issues?

**Comment by themantissa** [comment]
Going to assume we are good here and close.  Please comment if any issues persist.

**Comment by hc-danieltiziani** [comment]
Sorry I was offline, it works just fine. It was some caching issues of the provider with terraform. I upgraded it and now it's using the last one, that works. Thanks!
