### ISSUE TITLE
Error: either Atlas Programmatic API Keys or AWS Secrets Manager attributes must be set

### ISSUE THREAD

**Issue by sachinmane1983** [mongodb/terraform-provider-mongodbatlas#1483]
Terraform plan suddenly failing with error
Error: either Atlas Programmatic API Keys or AWS Secrets Manager attributes must be set

 Error: either Atlas Programmatic API Keys or AWS Secrets Manager attributes must be set
│
│   with provider["registry.terraform.io/mongodb/mongodbatlas"],
│   on main.tf line 32, in provider "mongodbatlas":
│   32: provider "mongodbatlas" {
│
THere is no change in code or api keys.

**Comment by andreaangiolillo** [comment]
Hi @sachinmane1983, Thanks for opening the issue. 

Could you provide more details about the version of the provider you are using and the method you are using to set the programmatic API keys? 

Thanks

**Comment by sachinmane1983** [comment]
mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 1.2"
    }
    
terraform {
  required_version = ">= 1.3.0"

provider "mongodbatlas" {
  public_key  = var.mongodbatlas_public_key
  private_key = local.mongodbatlas_private_key
}
variable "mongodbatlas_public_key" {
  type    = string
  default = ""
}

variable "mongodbatlas_private_key" {
  type    = string
  default = ""
}
API keys stored in atlas access manager

**Comment by andreaangiolillo** [comment]
Hi @sachinmane1983 

Thanks for sharing this configuration file.
I tried to reproduce the issue with your config file where I used v1.12.0 of the provider but I was not able to reproduce the issue. Could you make sure that your `variables.tf` defines `mongodbatlas_private_key` and `mongodbatlas_public_key` and that those vars contain your API keys? Another approach would be to update your conf file to don't use vars

```hcl
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "1.12.0"
    }
  }
  required_version = ">= 0.13"
}

provider "mongodbatlas" {
  public_key = "ADD YOUR PUBLIC KEY HERE"
  private_key =  "ADD YOUR PRIVATE KEY HERE"
}
```

Thanks

**Comment by sachinmane1983** [comment]
but it was working till yesterday there is no change happened suddenly today its throwing this error in terraform plan

**Comment by marcosuma** [comment]
@sachinmane1983 not sure if that's intentional but I see in your script contains
```
public_key = var.mongodbatlas_public_key
private_key = local.mongodbatlas_private_key
```
in one place you are using `var.`  and in the other `local.` - please kindly advise you to follow @andreaangiolillo's suggestion and let us know if it's solved.

> but it was working till yesterday there is no change happened

it's possible the script was running in a terminal/context where you had those variables being defined and now it doesn't.

**Comment by sachinmane1983** [comment]
yes that is intentional  mention in locals
i dont want to hardcoded value in variables. its stored in vault

**Comment by sachinmane1983** [comment]
issue solved after we revert back with older version = "~> 1.11.1"
but want to know why this is not working with new version? any changes required in module?

**Comment by AgustinBettati** [comment]
Hi @sachinmane1983.
From the configuration you are providing and the error message that is being returned in 1.12.0 it would seem that either the `public_key` or `private_key` attributes have an empty string value.
With this in mind, are you defining any resources besides the provider block? Version 1.11.1 may not be returning any errors but that does not ensure that authentication to the Atlas API is successful. For additional context, https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1402 included a new validation in 1.12.0 to ensure that a valid authentication mechanism is being used.

**Comment by MaxymVlasov** [comment]
Please return provider lazy init, as it was in 1.11.1. We have a module that provides us the possibility to create Atlas only when needed, and here is the provider definition

```terraform
provider "mongodbatlas" {
  public_key  = var.mongodb_enabled ? module.mongodbatlas_config[0].public_key : null
  private_key = var.mongodb_enabled ? module.mongodbatlas_config[0].private_key : null
}
```

Basically, `mongodb_enabled = false` and we assume that it will just pass, because not every our app needs Mongo.

It works fine in `1.11.1`, and broken in `1.12.1`


<details><summary>The "full" code</summary>

```tf
variable "mongodb_enabled" {
  description = "Enable a mongodb atlas cluster"
  type        = bool
  default     = false
}

# plus other variables

module "mongodbatlas_config" {
  source = "../.modules/mongodbatlas/config"

  count = var.mongodb_enabled ? 1 : 0
}

provider "mongodbatlas" {
  public_key  = var.mongodb_enabled ? module.mongodbatlas_config[0].public_key : null
  private_key = var.mongodb_enabled ? module.mongodbatlas_config[0].private_key : null
}


module "mongodbatlas_cluster" {
  source = "../.modules/mongodbatlas/cluster"

  count           = var.mongodb_enabled ? 1 : 0
  # plus other arguments
}
```

</details>

**Comment by sachinmane1983** [comment]
> Please return provider lazy init, as it was in 1.11.1. We have a module that provides us the possibility to create Atlas only when needed, and here is the provider definition
> 
> ```terraform
> provider "mongodbatlas" {
>   public_key  = var.mongodb_enabled ? module.mongodbatlas_config[0].public_key : null
>   private_key = var.mongodb_enabled ? module.mongodbatlas_config[0].private_key : null
> }
> ```
> 
> Basically, `mongodb_enabled = false` and we assume that it will just pass, because not every our app needs Mongo.
> 
> It works fine in `1.11.1`, and broken in `1.12.1`
> 
> The "full" code
> ```terraform
> variable "mongodb_enabled" {
>   description = "Enable a mongodb atlas cluster"
>   type        = bool
>   default     = false
> }
> 
> # plus other variables
> 
> module "mongodbatlas_config" {
>   source = "../.modules/mongodbatlas/config"
> 
>   count = var.mongodb_enabled ? 1 : 0
> }
> 
> provider "mongodbatlas" {
>   public_key  = var.mongodb_enabled ? module.mongodbatlas_config[0].public_key : null
>   private_key = var.mongodb_enabled ? module.mongodbatlas_config[0].private_key : null
> }
> 
> 
> module "mongodbatlas_cluster" {
>   source = "../.modules/mongodbatlas/cluster"
> 
>   count           = var.mongodb_enabled ? 1 : 0
>   # plus other arguments
> }
> ```

thanks for providing info
so what changes required in my module to use 1.12 version and it should resolve below error
Error: either Atlas Programmatic API Keys or AWS Secrets Manager attributes must be set

**Comment by MaxymVlasov** [comment]
Changes are required in the provider, not in your code, because it is definitely a bug

**Comment by sachinmane1983** [comment]
> Changes are required in the provider, not in your code, because it is definitely a bug

so we can not use 1.12 version until this bug fix?

**Comment by andreaangiolillo** [comment]
Hello @MaxymVlasov @sachinmane1983, 

Thanks for the valid feedback. We are discussing this issue internally and will provide an update as soon as possible.

Thanks for your help and patience here.

**Comment by andreaangiolillo** [comment]
Hello,

The fix will be included in v1.12.2. I'll provide an update with a comment here as soon as v1.12.2 becomes available.

Thanks

**Comment by AgustinBettati** [comment]
Hi, 

v1.12.2 has been released with this fix. Closing this issue, feel free to reopen if you have any remaining concerns on this matter.

**Comment by hadi-alnehlawi** [comment]
Hello Team, i am using v1.12.2 but still have the exact error?

**Comment by andreaangiolillo** [comment]
Hello @hadi-alnehlawi 
Could you share your configuration file and the log to help us reproduce the issue?

Thanks
