### ISSUE TITLE
mongodbatlas_network_container faulty optional variable regions

### ISSUE THREAD

**Issue by mihaiandreiratoiu** [mongodb/terraform-provider-mongodbatlas#1490]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
terraform version 1.0.0
provider version 1.12.0

### Description
Newer v.1.12.0 mongodb atlas provider contains a bug where the regions optional variable is leading to an error on other providers
Provider flavor used here is Azure

### Error
For an existing deployment in azure we get this error.

 ```
Error: Provider produced invalid plan

Provider "registry.terraform.io/mongodb/mongodbatlas" planned an invalid
value for mongodbatlas_network_container.network_container[1].regions:
planned value cty.ListValEmpty(cty.String) for a non-computed attribute.
```
Tested with 1.11.1 and with 1.12.0
With 1.11.1 it works
With 1.12.0 it fails
### Steps to reproduce
Deploy a mongodbatlas_network_container with 1.11.1 version and re-run with 1.12.0 
### Additional Context
Haven't seen some diffs in the mongodbatlas_network_container resource go files between these versions
This error seems to happen when the state differs from the provider output, I'm guessing the null logic is treated different than before
I'm guessing this is the faulty function
func StringNullIfEmpty(v string) types.String {
	return StringPtrNullIfEmpty(&v)
}

**Comment by marcosuma** [comment]
Hi @mihaiandreiratoiu, could you provide:
- ful terraform script that can quickly help us to reproduce the issue? 
- full error log

Thanks for pointing us to the direction of `StringNullIfEmpty` - it does seem weird that method affect the error on `mongodbatlas_network_container.network_container[1].regions`

You mentioned that such script should be first executed with 1.11.0 and then re-applied with 1.12.0 in order to reproduce it?

**Comment by nuno-silva** [comment]
Hello!

I'm experiencing this issue as well.

The error happens when running a plan that upgrades resources created using version 1.11 to any of these versions:
- 1.12.0
- 1.12.1
- 1.12.2
- 1.12.3 (latest)

Using terraform 1.0.1.

```
Error: Provider produced invalid plan

Provider "registry.terraform.io/mongodb/mongodbatlas" planned an invalid
value for
module.cluster.mongodbatlas_network_container.this.regions:
planned value cty.ListValEmpty(cty.String) for a non-computed attribute.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

Current work around is to use version 1.11.

Please re-open
