### ISSUE TITLE
Importing Online Archive resources is missing parameter partition_fields in terraform state

### ISSUE THREAD

**Issue by mschirbel** [mongodb/terraform-provider-mongodbatlas#1492]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
terraform version
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.17.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.12.0
```

### Terraform Configuration File 

Since the problem is with importing an existing resource, you'd need to create one in Atlas Cloud. Here's some code snippet to be used after the import.
```hcl
resource "mongodbatlas_online_archive" "this" {
    project_id   = var.project_id
    cluster_name = var.cluster_name
    coll_name    = var.collection_name
    db_name      = var.database_name

    partition_fields {
        field_name = "endDate"
        order = 0
    }

    criteria {
        type = "DATE"
        date_field = var.criteria_date_field
        expire_after_days = var.expire_after_days
    }

    schedule {
        type = "DAILY"
        end_hour = var.end_hour
        end_minute = var.end_minute
        start_hour = var.start_hour
        start_minute = var.start_minute
    }
}
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform import "mongodbatlas_online_archive.this" "<PROJECT_ID>"-"<CLUSTER_NAME>"-"<ARCHIVE_ID>"`
2. `terraform state show "mongodbatlas_online_archive.this"`

### Expected Behavior
Import all fields that exists in the actual resource in Atlas Cloud to terraform state

### Actual Behavior

The following fields are missing:
1. `partition_fields`

And those are set to `null`:
1. `db_name`
2. `sync_creation`

### Additional Context
The provider is deleting the `partition_fields` [from the map once it's imported](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/bf8b9e2355c8abc526b200ef8995e48f8228ba35/mongodbatlas/resource_mongodbatlas_online_archive.go#L514):
```go
func fromOnlineArchiveToMapInCreate(in *matlas.OnlineArchive) map[string]interface{} {
	localSchema := fromOnlineArchiveToMap(in)
	delete(localSchema, "partition_fields")
	return localSchema
}
```

**Comment by marcosuma** [comment]
Hi @mschirbel, thank you for your report. The issue has been fixed and it will be released on the 1.12.2 version.

Thank you very much,
Marco
