### ISSUE TITLE
Cluster creation with Azure provider failed

### ISSUE THREAD

**Issue by bobhlo** [mongodb/terraform-provider-mongodbatlas#15]
Provider settings `diskIOPS` and `EncryptEBSVolume` should be excluded in the payload when creating a cluster with Azure provider. Need conditional checks for providers in a few places such as https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_cluster.go#L600-L601. See Atlas API doc - https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ which indicates the two optional settings for AWS.

**Comment by themantissa** [comment]
@bobhlo  - thank you, we are working on this fix with https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/11
