### ISSUE TITLE
mongodbatlas_project name

### ISSUE THREAD

**Issue by FernandoMiguel** [mongodb/terraform-provider-mongodbatlas#150]
data "mongodbatlas_project" no longer takes `name` as filter

**Comment by FernandoMiguel** [comment]
```hcl
  "mongodbatlas_project" = {
    "cluster_count" = 0
    "created" = "2020-02-20T14:56:15Z"
    "id" = "1234567890"
    "org_id" = "987654321"
    "project_id" = "1234567890"
    "teams" = []
  }
```

id and project_id show the same info, but project name is no longer available

**Comment by themantissa** [comment]
@FernandoMiguel  this was reported and already addressed in PR https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/142.  Expect a minor version this week.
