### ISSUE TITLE
Terraform import user with database with a - in it fail

### ISSUE THREAD

**Issue by clement94310** [mongodb/terraform-provider-mongodbatlas#1502]
When i try import my user 
 terraform import 'mongodbatlas_database_user.user["user"]' xxxxxxxxxxxx-user-data-base
 where the name of database is data-base
 it says it cant import user user-data.
 there is an error of interpretation with the third -.

**Comment by AgustinBettati** [comment]
Hi @clement94310.
When importing a mongodbatlas_database_user resource the expected import format should be: 
`{project_id}-{username}-{auth_database_name}` (https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/database_user#import)

Given that `auth_database_name` has only 2 possible values https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/database_user#auth_database_name, I am not certain how to reproduce this issue.
Could you share more details of the current terraform configuration you are using?
