### ISSUE TITLE
provide a mongodbatlas_privatelink_endpoint by region when using `data "mongodbatlas_privatelink_endpoint"` 

### ISSUE THREAD

**Issue by Alonreznik** [mongodb/terraform-provider-mongodbatlas#1525]
Hello!

I'm using the latest mongodbatlas terraform provider (1.12.1) which raises an error while trying to create another endpoint/endpoint service on the same region (`PRIVATE_ENDPOINT_SERVICE_ALREADY_EXISTS_FOR_REGION`).
In cases of multi states by multiple aws accounts or environments, the current implementation of this resource just doesn't work.

Think of the next flow:
I want to create another endpoint service from another AWS account. so i need to:
a. Check if the endpoint exists on the same region
b. if exists - create the endpoint service
c. if not exists - create the endpoint, and then create the endpoint service.

I get there's a limitation between the Mongo atlas ui, and terraform, and i should create only an endpoint_service if the endpoint is currently exists. However, using terraform with the current `data` clause of `mongodbatlas_privatelink_endpoint` it's just impossible.

However, the current `data` resource of `mongodbatlas_privatelink_endpoint` requires the `private_link_id`, which is something TF can't know in advanced in a case of the endpoint doesn't exists yet. Moreover, instead of just asking "give me the endpoint in the region" and use this private_link_id, i need to create the endpoint, save the private_link_id somewhere aside, and then get it again from this place. It's just not TFish flow and has a big blocker of reusing and creating an endpoint via the provider.

The next example will work at the first time, but won't work if we want to create another endpoint service connecting to another AWS account's vpc endpoint (which is managed in a different state by a workspace path):
```hcl
resource "mongodbatlas_privatelink_endpoint" "this" {
  project_id    = var.project_id
  provider_name = 'AWS'
  region        =  'US_EAST_2'
}

resource "mongodbatlas_privatelink_endpoint_service" "this" {
  endpoint_service_id = var.endpoint_service_id # created outside and passed here as a var.
  private_link_id     = mongodbatlas_privatelink_endpoint.this.private_link_id
  project_id          = var.project_id
  provider_name       = 'AWS'
}
```

Adding the data clause to the code above to see if there's any current endpoint in the region will ask me the `private_link_id` which i don't have at the same time the code is running:

```hcl
data "mongodbatlas_privatelink_endpoint" "get" {
  private_link_id = "<UNKNOWN AT THAT POINT>"
  project_id = "1234"
  provider_name = "AWS"
}

resource "mongodbatlas_privatelink_endpoint_service" "this" {
  endpoint_service_id = var.endpoint_service_id # created outside and passed here as a var.
  private_link_id     = data.mongodbatlas_privatelink_endpoint.get.private_link_id
  project_id          = var.project_id
  provider_name       = 'AWS'
}
```

I would assume that if the resource of mongodbatlas_privatelink_endpoint asks for `region_name`, I would available to provide the region name to the `data` clause and then ask if there's any of that already in the region...

Please help in that case.

**Comment by AgustinBettati** [comment]
Hello @Alonreznik. Thanks for raising this issue.

To further understand the limitations you are currently facing, I have the following doubt:

> I want to create another endpoint service from another AWS account. so i need to:
a. Check if the endpoint exists on the same region
b. if exists - create the endpoint service
c. if not exists - create the endpoint, and then create the endpoint service.

Are you currently creating all your `mongodbatlas_privatelink_endpoint` and `mongodbatlas_privatelink_endpoint_service` resources through terraform? Because in this case you would have visibility on which regions you have existing endpoints, and use the corresponding `mongodbatlas_privatelink_endpoint.<name>.private_link_id` value.

**Comment by Zuhairahmed** [comment]
@Alonreznik given this is a feature request can you create a ticket or upvote at: https://feedback.mongodb.com/forums/924145-atlas?category_id=370723. thank you

**Comment by Alonreznik** [comment]
@AgustinBettati thanks. Sorry for the late response. 
Yes, we want to create multiple endpoints per different VPCs. However by requesting us to know in adavnced the private_endpoint_id in the data clause doesnt make this specific data clause to be usable, in the current limitation of one-endpoint-per-region (btw, this isn't a limitation on UI...)
