### ISSUE TITLE
mongodbatlas_alert_configuration - not able to specify ROLE for type_name = "GROUP"

### ISSUE THREAD

**Issue by bauerben** [mongodb/terraform-provider-mongodbatlas#153]
Hi, 

From my understanding, when creating an alert configuration via terraform, we don't seem to be able to specify a ROLE ( ex: "Project Owner" , "Cluster Manager" ...)  when type_name = "GROUP".

From the mongodbAtlas API, for alert_configuration definition we have : 
```javascript
"notifications": [
        {
          "delayMin": 0,
          "emailEnabled": true,
          "intervalMin": 5,
          "roles": [
            "GROUP_OWNER"
          ],
          "smsEnabled": false,
          "typeName": "GROUP"
        }
```
But when using mongodbatlas_alert_configuration, it is not possible to specify role : 

```javascript
 notification {
    type_name     = "GROUP"
    interval_min  = 5
    delay_min     = 0
    sms_enabled   = false
    email_enabled = true
  }
```

In order to be useful, we should be able to specify the role when creating a GROUP alert_configuration from the terraform provider.
What do you think?

**Comment by themantissa** [comment]
@bauerben agree and it seems the [documentation](https://docs.atlas.mongodb.com/reference/api/alert-configurations/) does not currently have the role information but looking at a returned role it is obviously there.   We'll need to get this corrected and once I have an ETA I will update here.

**Comment by themantissa** [comment]
Note for others looking at the issue: without role the alert configured will go to all users in the project.   One can adjust this in the UI or via the API directly.

**Comment by themantissa** [comment]
https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/177 addresses the issue.

**Comment by mbacchi** [comment]
This does not appear fixed. I am using mongodbatlas provider version 1.01 and still see this appears as changed every time I try to apply it:

```
          ~ roles         = [
              + "GROUP_OWNER",
            ]
```

**Comment by themantissa** [comment]
@mbacchi is it not being set (the previous issue) or just is being seen as changed each time but is set?  A log section or more details would help a great deal.
