### ISSUE TITLE
Issue: There is no "team_id" argument/attribute reference in "mongodbatlas_project_invitation" resource block.

### ISSUE THREAD

**Issue by ghost** [mongodb/terraform-provider-mongodbatlas#1535]
Hello!

Thank you for opening an issue. **These GitHub issues** are only for community reporting and assistance; as such, we don't have a guaranteed SLA.

**If your issue relates to Terraform itself**, please open it in the Terraform repository https://github.com/hashicorp/terraform/issues.

**If you have an active MongoDB Atlas Support contract**, the best way for us to assist you with the Terraform MongoDB Atlas Provider is through a [support ticket](https://support.mongodb.com/).

**Please note:** In order for us to provide the best experience in supporting our customers, we kindly ask to make sure that all the following sections are correctly filled with all the required information. Our support will **prioritise** issues that contain **all the required** information that follows the **"one-click reproducible issues" principle** (see below).

**Please also note:** We try to keep the Terraform MongoDB Atlas Provider issue tracker **reserved for bug reports**. Please ensure you **check open and closed issues first** to ensure your issue hasn't already been reported (if it has been reported add a reaction, i.e. +1, to the issue).

### "One-click reproducible issues" principle

* We should be able to make no changes to your provided script and **successfully run a local execution reproducing the issue**.
  * This means that you should kindly **provide all the required instructions**. This includes but not limited to:
    * Terraform Atlas provider version used to reproduce the issue
    * Terraform version used to reproduce the issue
  * Configurations that **cannot be properly executed will be de-prioritised** in favour of the ones that succeed.
* Before opening an issue, you have to try to specifically isolate it to **Terraform MongoDB Atlas** provider by **removing as many dependencies** as possible. If the issue only happens with other dependencies, then:
  * If other terraform providers are required, please make sure you also include those. _Same "one-click reproducible issue" principle applies_.
  * If external components are required to replicate it, please make sure you also provides instructions on those parts.
* Please confirm if the platform being used is Terraform OSS, Terraform Cloud, or Terraform Enterprise deployment

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
# Copy-paste your version.tf and provider.tf (or equivalent) here
```

### Terraform Configuration File 

```hcl
# Copy-paste all your configuration (e.g. main.tf and variable.tf) info here
```

### Steps to Reproduce

Please be **as detailed as possible.**
* If the issue **involves version changes** (e.g. `run plan with version 1.k.x then re-run with version 1.k.y`), please make sure you report the detailed sequence on commands to execute.
* If the issue requires **changes from the UI**, please document them **preferably with screenshots**.

```hcl
# Write here the detailed list of required steps.
```

**Comment by marcosuma** [comment]
Closing as it doesn't contain any information (unless I missed it between the placeholder text)
