### ISSUE TITLE
Rate limit of 10 invitations per 1 minutes exceeded

### ISSUE THREAD

**Issue by mpsanten** [mongodb/terraform-provider-mongodbatlas#1589]
Using this plugin we already quickly reached the max invitations allowed by Mongo. 
Error message: "

" Error: error creating Project invitation for user xxxxxxxxxxxxxxxxxx POST https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxxxxxxxxxxx/invites: 400 (request "INVITATIONS_RATE_LIMITED_IP") Rate limit of 10 invitations per 1 minutes exceeded."

I don't see any option to throttle it or any other workaround.

**Comment by Zuhairahmed** [comment]
Thanks @mpsanten can you share more details before so we can repro this issue? 

Taking into account our ["One-click reproducible issues" principle](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md#one-click-reproducible-issues-principle) defined in our guidelines, could you help us by providing the terraform configuration and terraform commands used to reach this plugin crash?
