### ISSUE TITLE
GCP peering problem

### ISSUE THREAD

**Issue by nivg1992** [mongodb/terraform-provider-mongodbatlas#16]
I am trying to configure peering atlas to GCP account

```
resource "mongodbatlas_network_container" "network_container" {
  project_id       = "PROJECT_ID"
  atlas_cidr_block = "192.168.0.0/16"
  provider_name    = "GCP"
}

resource "mongodbatlas_network_peering" "network_peering" {
  project_id        = "PROJECT_ID"
  container_id      = mongodbatlas_network_container.network_container.id
  provider_name     = "GCP"
  gcp_project_id  = "GCP_PROJECT_ID"
  network_name    = "VPC_ID"
}

resource "google_compute_network_peering" "atlas_peer" {
  name = "atlas-peer"
  network = "VPC_ID"
  peer_network = "https://www.googleapis.com/compute/v1/projects/${mongodbatlas_network_peering.network_peering.gcp_project_id}/global/networks/${mongodbatlas_network_peering.network_peering.network_name}"
  depends_on = [mongodbatlas_network_peering.network_peering]
}
```
The resource mongodbatlas_network_peering is stuck,
The Atlas API for getting the peering, show the status WAITING_FOR_USER.

I see on the documentation of MongoDB that the status of network peering on GCP are
ADDING_PEER
WAITING_FOR_USER
AVAILABLE
FAILED
DELETING

So the mongodbatlas_network_peering resource should be finished on WAITING_FOR_USER,
be able to apply the google_compute_network_peering

terraform version: v0.12.1
Atlas provider version: 0.1.0

**Comment by PacoDw** [comment]
Hello @nivg1992, this issue was resolved with the pr #11, can you test if this issue was resolved on pr #11 and the fix-#2 branch.

Let us know if you have any comments, thanks!
