### ISSUE TITLE
In the `mongodbatlas_advanced_cluster` ressource, forbidden characters for the  values of the tags are allowed by the provider and fail on apply.

### ISSUE THREAD

**Issue by leo-ferlin-sutton** [mongodb/terraform-provider-mongodbatlas#1668]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

We are using Terraform OSS via the official docker image `hashicorp/terraform:1.5.5`.

Here is the provider block:

```hcl
terraform {
  required_version = ">= 1.5.0"
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = ">= 1.12"
    }
}
```

And here is the `terraform init` output:

```
Initializing provider plugins...
- Reusing previous version of mongodb/mongodbatlas from the dependency lock file
- Installing mongodb/mongodbatlas v1.13.1...
- Installed mongodb/mongodbatlas v1.13.1 (signed by a HashiCorp partner, key ID 2A32ED1F3AD25ABF)
```

### Terraform Configuration File 

We do not have a provider block for Atlas, instead we use environment variables:
```
  MONGODB_ATLAS_PRIVATE_KEY=**REDACTED**
  MONGODB_ATLAS_PUBLIC_KEY=**REDACTED**
```

```hcl
resource "mongodbatlas_advanced_cluster" "this" {
  project_id = local.atlas_project_id

  name           = "<PLACEHOLDER>"

  mongo_db_major_version = 6
  version_release_system = "LTS"

  cluster_type = REPLICASET

  replication_specs { ... }

  tags { 
    key   = "company.net-team"
    value = "github:company/repo"
  }
}
```

### Steps to Reproduce

1. Create a `mongodbatlas_advanced_cluster` ressource in terraform **without tags**
2. `terraform apply` and create the MongoDB Atlas Cluster
3. Add a tag like the following:

```hcl
  tags { 
    key   = "debug-key"
    value = "beep:bop"
  }
```

or

```hcl
  tags { 
    key   = "debug-key"
    value = "beep/bop"
  }
```
4. Run `terraform validate` and `terraform plan`. They should succeed.
5. Run `terraform apply`, it should fail with an `UNEXPECTED_ERROR`.

### Expected Behavior

The following `terraform validate` and  `terraform plan` commands should detect that some characters are not allowed and throw an error.

The provider should enforce the invalid characters instead of letting the API
throw an `UNEXPECTED_ERROR`.

### Actual Behavior

```
$ terraform apply

[...]

│ Error: error updating MongoDB ClusterAdvanced (gyihuda): error updating MongoDB ClusterAdvanced (gyihuda): PATCH https://cloud.mongodb.com/api/atlas/v1.5/groups/<UUID>/clusters/gyihuda: 500 (request "UNEXPECTED_ERROR") Unexpected error.
│ 
│   with module.gyihuda.mongodbatlas_advanced_cluster.this,
│   on .terraform/modules/gyihuda/main.tf line 42, in resource "mongodbatlas_advanced_cluster" "this":
│   42: resource "mongodbatlas_advanced_cluster" "this" {
│ 
╵
```

### Debug Output 

Unfortunately, we could not obtain a more detailed output.

If you cannot reproduce I think I can force the situation again on a dummy cluster.

The problem seems pretty straightforward to me, so I deemed the time investment not worth it at this point. Let me know if you require it.

(Maybe through the support case we opened: https://support.mongodb.com/case/01227806)

### Crash Output

Unfortunately, we could not obtain a more detailed output.

### Additional Context

The MongoDB Atlas Web UI confirms that some characters are not allowed:

<img width="527" alt="image" src="https://github.com/mongodb/terraform-provider-mongodbatlas/assets/98740873/79fc0c66-2986-46d8-adfd-6cf3e7acf094">

<img width="527" alt="image" src="https://github.com/mongodb/terraform-provider-mongodbatlas/assets/98740873/fd0c05d1-31e5-46d9-ac8a-a066ef4209b1">

**Comment by marcosuma** [comment]
Hi @leo-ferlin-sutton, thank you for raising your issue to us. As you might have been told already with in https://support.mongodb.com/case/01227806 this is an improvement that needs to be done at the API level, not in Terraform. Hence we are working internally to fix the API behaviour. Unfortunately I don't have an issue for you to track, but you can directly check updates in the API documentation.

Thank you again for your patience.

**Comment by Zuhairahmed** [comment]
@leo-ferlin-sutton just FYI, the Terraform Atlas Provider now errors out correctly with clear next steps. see full list of allowable characters for Atlas Resource Tags - https://www.mongodb.com/docs/atlas/tags/ 

Really appreciate you flagging this one to us! 

<img width="920" alt="image" src="https://github.com/mongodb/terraform-provider-mongodbatlas/assets/47370943/180b402f-556f-44f1-b8ed-5200995b8d8b">
