### ISSUE TITLE
Provider not working with Secret Manager

### ISSUE THREAD

**Issue by sdalens** [mongodb/terraform-provider-mongodbatlas#1683]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
provider "mongodbatlas" {
    secret_name = "<ARN>"
    region      = "eu-central-1" 
}
```

### Terraform Configuration File 
```hcl
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas",
      version = "1.13.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "5.27.0"
    }
  }
}
```

### Steps to Reproduce

Run `terraform plan` and you will have the error. 

I try also with the bloc : 
```hcl
    assume_role {
        role_arn = "arn:aws:iam::XXXXXXX:role/platform/ALZP-WL-Owner"
    }
```

But I get

│ Error: EmptyStaticCreds: static credentials are empty

I have even try with access key, secret key, session token in the code and in the environment variables... it not working. 

Should also work with AWS_PROFILE environment variables, but also not working. 

### Expected Behavior
Provider should be able to connect to AWS, get the secret value. 

### Actual Behavior
Plan failed and Provider is not able to connect to AWS. Terraform encountered an error while generating this plan.

### Debug Output 

No log are given by TRACE.  

### Crash Output
╷
│ Warning: either Atlas Programmatic API Keys or AWS Secrets Manager attributes must be set
│
│   with provider["registry.terraform.io/mongodb/mongodbatlas"],
│   on providers.tf line 9, in provider "mongodbatlas":
│    9: provider "mongodbatlas" {
│
│ (and one more similar warning elsewhere)
╵
╷
│ Warning: error in configuring the provider.
│
│   with provider["registry.terraform.io/mongodb/mongodbatlas"],
│   on providers.tf line 9, in provider "mongodbatlas":
│    9: provider "mongodbatlas" {
│
│ either Atlas Programmatic API Keys or AWS Secrets Manager attributes must be set

│ Error: error getting project(): GET ..... : 401 (request "") You are not authorized for this resource.
│
│   with mongodbatlas_privatelink_endpoint.ep,
│   on main.tf line 1, in resource "mongodbatlas_privatelink_endpoint" "ep":
│    1: resource "mongodbatlas_privatelink_endpoint" "ep" {

### Additional Context
No

### References
No

**Comment by maastha** [comment]
Hello @sdalens .

Taking into account our ["One-click reproducible issues" principle](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md#one-click-reproducible-issues-principle) defined in our guidelines, could you help us by providing the exact terraform configuration and terraform commands used to reach this state?

Also recommend you to review our documentation on authenticating with AWS Secret manager [here](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs#aws-secrets-manager) as per which all 3  `role_arn`, `secret_name`, and AWS `region` are required.

**Comment by marcosuma** [comment]
Hi @sdalens, thank you very much for raising your issue with us. In addition to what @maastha has mentioned, I wanted to suggest you to read [these instructions](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/d71180fb6d624fb4927a59a56adafac0e859a1e0/website/docs/index.html.markdown).

The solution might be there. For example, if you're trying to assume credentials through AWS assume role then you'll need something like

```
# Configure the MongoDB Atlas Provider to Authenticate with AWS Secrets Manager 
provider "mongodbatlas" {
  assume_role {
    role_arn = "arn:aws:iam::476xxx451:role/mdbsts"
  }
  secret_name           = "mongodbsecret"
  // fully qualified secret_name ARN also supported as input "arn:aws:secretsmanager:af-south-1:553552370874:secret:test789-TO06Hy" 
  region                = "us-east-2"
  
  aws_access_key_id     = "ASIXXBNEK"
  aws_secret_access_key = "ZUZgVb8XYZWEXXEDURGFHFc5Au"
  aws_session_token     = "IQoXX3+Q="
  sts_endpoint          = "https://sts.us-east-2.amazonaws.com/"
}
```

Otherwise you should pass 

```
provider "mongodbatlas" {
  public_key = var.mongodbatlas_public_key
  private_key  = var.mongodbatlas_private_key
}
```
