### ISSUE TITLE
mongodbatlas_alert_configuration failing to be created on apply due to METRIC_TYPE_UNSUPPORTED for DISK_PARTITION_ alerts 400 error

### ISSUE THREAD

**Issue by NicBelley** [mongodb/terraform-provider-mongodbatlas#1716]
We used to have alerts configured for disk metrics (DISK_PARTITION_SPACE_USED_DATA) and it seems either they are not supported anymore or they have changed names. 

According to the documentation, they are still available: 
https://www.mongodb.com/docs/mongocli/v1.16/reference/atlas/alerts-list/

This docs shows:
DISK_PARTITION_SPACE_USED_DATA
DISK_PARTITION_SPACE_USED_INDEX
DISK_PARTITION_SPACE_USED_JOURNAL
DISK_PARTITION_UTILIZATION_DATA
DISK_PARTITION_UTILIZATION_INDEX
DISK_PARTITION_UTILIZATION_JOURNAL

This is my terraform script, that worked before:
`resource "mongodbatlas_alert_configuration" "disk-space" {`
`project_id = var.project_id`
`  event_type = "OUTSIDE_METRIC_THRESHOLD"`
`  enabled    = true`
  
`  metric_threshold_config {`
`    metric_name = "DISK_PARTITION_SPACE_USED_DATA"`
`    mode        = "AVERAGE"`
`    operator    = "GREATER_THAN"`
`    threshold   = 90`
`    units       = "RAW"`
`  }`
`    `
 ` notification {`
 `   type_name   = "PAGER_DUTY"`
 `   delay_min   = 10`
 `   service_key = var.alerts.resources_usage_service_key`
 ` }`
`}`

The error in the pipeline is:

`Error: error getting Alert Configuration information: PUT https://cloud.mongodb.com/api/atlas/v1.0/groups/602428316c23fa47a1739058/alertConfigs/602428316c23fa47a173905f: 400 (request "METRIC_TYPE_UNSUPPORTED") The metric type DISK_PARTITION_UTILIZATION_DATA is not supported.
  on mongodb.tf line 580, in resource "mongodbatlas_alert_configuration" "disk-space":
 580: resource "mongodbatlas_alert_configuration" "disk-space"`

**Comment by andreaangiolillo** [comment]
Hello @NicBelley 
Thanks for opening the issue. Your terraform configuration file contains `metric_name = "DISK_PARTITION_SPACE_USED_DATA"` but then the error says `(request "METRIC_TYPE_UNSUPPORTED") The metric type DISK_PARTITION_UTILIZATION_DATA is not supported`.

Is the provided tf configuration the correct one? Could you also share the Atlas provider version and the Terraform version used to reproduce the issue? Thanks

**Comment by NicBelley** [comment]
@andreaangiolillo 

We just update our version to  terraformVersion: '0.15.5' and the provider "registry.terraform.io/mongodb/mongodbatlas" to version    "1.13.1" and now it works! 

So... I guess we can close the issue?
