### ISSUE TITLE
Docs with wrong resource type

### ISSUE THREAD

**Issue by hieuln** [mongodb/terraform-provider-mongodbatlas#175]
Based on the document here: https://www.terraform.io/docs/providers/mongodbatlas/r/private_endpoint_interface_link.html the resource is:

resource "mongodbatlas_private_endpoint_link" "test" {
}

but the correct (and working) one is:

resource "mongodbatlas_private_endpoint_interface_link" "test" {
}

**Comment by themantissa** [comment]
Fixed - doc gets updated on the terraform website when we release so expect this there with 0.4.3.  Thank you!!
