### ISSUE TITLE
Unable to add encryption at rest through terraform

### ISSUE THREAD

**Issue by prernaasharma22** [mongodb/terraform-provider-mongodbatlas#1766]
Hello!

Thank you for opening an issue. **These GitHub issues** are only for community reporting and assistance; as such, we don't have a guaranteed SLA.

**If your issue relates to Terraform itself**, please open it in the Terraform repository https://github.com/hashicorp/terraform/issues.

**If you have an active MongoDB Atlas Support contract**, the best way for us to assist you with the Terraform MongoDB Atlas Provider is through a [support ticket](https://support.mongodb.com/).

**Please note:** In order for us to provide the best experience in supporting our customers, we kindly ask to make sure that all the following sections are correctly filled with all the required information. Our support will **prioritise** issues that contain **all the required** information that follows the **"one-click reproducible issues" principle** (see below).

**Please also note:** We try to keep the Terraform MongoDB Atlas Provider issue tracker **reserved for bug reports**. Please ensure you **check open and closed issues first** to ensure your issue hasn't already been reported (if it has been reported add a reaction, i.e. +1, to the issue).

### "One-click reproducible issues" principle

* We should be able to make no changes to your provided script and **successfully run a local execution reproducing the issue**.
  * This means that you should kindly **provide all the required instructions**. This includes but not limited to:
    * Terraform Atlas provider version used to reproduce the issue
    * Terraform version used to reproduce the issue
  * Configurations that **cannot be properly executed will be de-prioritised** in favour of the ones that succeed.
* Before opening an issue, you have to try to specifically isolate it to **Terraform MongoDB Atlas** provider by **removing as many dependencies** as possible. If the issue only happens with other dependencies, then:
  * If other terraform providers are required, please make sure you also include those. _Same "one-click reproducible issue" principle applies_.
  * If external components are required to replicate it, please make sure you also provides instructions on those parts.
* Please confirm if the platform being used is Terraform OSS, Terraform Cloud, or Terraform Enterprise deployment

### Terraform CLI and Terraform MongoDB Atlas Provider Version
Terraform v1.5.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.65.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.13.1

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.65.0"
    }
    mongodbatlas = {
      source                = "mongodb/mongodbatlas"
      version               = "1.13.1"
      configuration_aliases = [mongodbatlas.mongodbtest]
    }
  }
}

resource "mongodbatlas_project" "mongodbproj" {
  provider = mongodbatlas.mongodbtest
  count                                            = var.mdb_IsEnabled == true ? 1 : 0
  name                                             = var.mdb_name
  org_id                                           = var.mdb_org_id
  #project_owner_id                                 = var.mdb_project_owner_id
  with_default_alerts_settings                     = var.mdb_with_default_alerts_settings
  is_collect_database_specifics_statistics_enabled = var.mdb_is_coldb_spec_stats_enabled
  is_data_explorer_enabled                         = var.mdb_is_data_explorer_enabled
  is_extended_storage_sizes_enabled                = var.mdb_is_extended_storage_sizes_enabled
  is_performance_advisor_enabled                   = var.mdb_is_performance_advisor_enabled
  is_realtime_performance_panel_enabled            = var.mdb_is_realtime_performance_panel_enabled
  is_schema_advisor_enabled                        = var.mdb_is_schema_advisor_enabled
  region_usage_restrictions                        = var.mdb_region_usage_restrictions

  dynamic "teams" {
    for_each = var.mdb_teams_enabled ? toset(var.mdb_teams) : []
    content {
      team_id    = teams.value["team_id"]
      role_names = teams.value["role_names"]
    }
  }

  dynamic "limits" {
    for_each = var.mdb_limits_enabled ? toset(var.mdb_limits) : []
    content {
      name  = limits.value["name"]
      value = limits.value["value"]
    }
  }
}

resource "mongodbatlas_encryption_at_rest" "encryptatrest" {
  count                 = var.mdb_IsEnabled == true ? 1 : 0
  project_id = mongodbatlas_project.mongodbproj[count.index].id

  dynamic "azure_key_vault_config" {
    for_each  = var.mdb_keyvault_enabled == true ? [1] : []
    content {
      enabled             = var.mdb_kv_enabled
      client_id           = var.mdb_kv_client_id
      azure_environment   = var.mdb_kv_azure_environment
      subscription_id     = var.mdb_kv_subscription_id
      resource_group_name = var.mdb_kv_resource_group_name
      key_vault_name      = var.mdb_kv_key_vault_name
      key_identifier      = var.mdb_kv_key_identifier
      secret              = var.mdb_kv_secret
      tenant_id           = var.mdb_kv_tenant_id
    }
  }
}
```hcl
# Copy-paste all your configuration (e.g. main.tf and variable.tf) info here
```

### Steps to Reproduce

Please be **as detailed as possible.**
* If the issue **involves version changes** (e.g. `run plan with version 1.k.x then re-run with version 1.k.y`), please make sure you report the detailed sequence on commands to execute.
* If the issue requires **changes from the UI**, please document them **preferably with screenshots**.

```hcl
# Write here the detailed list of required steps.
```

### Expected Behavior
it should enable encryption at rest in mongodb project with azure keyvault config

### Actual Behavior
Error: error creating Encryption At Rest: 65794dac36b272664fcd4343
│
│   with module.mongodbproj["mdbproj1"].mongodbatlas_encryption_at_rest.encryptatrest[0],
│   on ..\terraform-module\mongodb-project\main.tf line 38, in resource "mongodbatlas_encryption_at_rest" "encryptatrest":    
│
│ PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/65794dac36b272664fcd4343/encryptionAtRest: 401 (request "")

**Comment by marcosuma** [comment]
Hi @prernaasharma22, thank you for raising your issue to us.
I see the error you are getting is a 401 which is `Unauthorized`, which is a client-side error. Have you tried to directly use the AtlasCLI or the API?

**Comment by marcosuma** [comment]
To add more here: it might be that you are not using your credentials appropriately for what you are trying to do. 
Some high-level info that might be useful for you:
* https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs
* https://www.mongodb.com/developer/products/atlas/deploy-mongodb-atlas-terraform-aws/

**Comment by prernaasharma22** [comment]
Hi @marcosuma I have tried with same credentials (private_key and public_key) to deploy the mongodb atlas project and it's working but for 2nd resource which is encyption at rest it's not working.

Also,whatever configurtion I'm passing through terraform for azure keyvault in encryption at rest resource ,with same config I tried manually it's working.

**Comment by marcosuma** [comment]
Thanks @prernaasharma22 - in order for me to try to reproduce the issue accurately, here some questions:
* Can you please follow our [main documentation](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/953fe058f67f6a1db89ef5f100b92e88282dd460/website/docs/r/encryption_at_rest.html.markdown)? Particularly try using some of the examples (for Azure) and see if you manage to succeed. We also have [other examples](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/953fe058f67f6a1db89ef5f100b92e88282dd460/examples/test-upgrade/encryption-at-rest/azure/v101/main.tf#L19).
* Can you provide the values you are using when encountering this issue? Of course please don't share any sensitive data, but the script is full of variables and want to make sure we don't guess them.
* Is the `azurerm` provider required when running the script? it doesn't seem so based on your resources

**Comment by prernaasharma22** [comment]
Issue Resolved. Thanks for quick response.

**Comment by marcosuma** [comment]
Awesome! thank you @prernaasharma22 for using MongoDB Atlas!
