### ISSUE TITLE
mongodbatlas_database_user can not be imported when they contain dashes "-" in the name

### ISSUE THREAD

**Issue by AntjeRadkiewicz1337** [mongodb/terraform-provider-mongodbatlas#179]
Hi,

we are trying to switch to this provider. While trying out the import for the mongodbatlas_database_user we found out that we can not import database_users which contain "-" in the username. This symbol is allowed in mongoDB and all our users contain dashes. :octopus: 

In https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_database_user.go line number 249 we saw that you are splitting the last information (project_id-username-auth_database_name) block from the import into 3 parts like this:

    parts := strings.SplitN(d.Id(), "-", 3)
	if len(parts) != 3 {
		r eturn nil, errors.New("import format error: to import a database user, use the format {project_id}-{username}-{auth_database_name}")
	}

	projectID := parts[0]
	username := parts[1]
	authDatabaseName := parts[2]

it would be awesome if you could implement it so that we can put for example quotes around the username.

example: "super-cool-database-user"

    func SplitAtDash(s string) []string {
		res := []string{}
		var beg int
		var inString bool

		for i := 0; i < len(s); i++ {
		if s[i] == '-' && !inString {
			res = append(res, s[beg:i])
			beg = i+1
		} else if s[i] == '"' || s[i] == '\'' {
			if !inString {
				inString = true
			} else if i > 0 && s[i-1] != '\\' {
				inString = false
			}
		}
		}
		return append(res, s[beg:])
	}

	func main(){
		strs := []string{
			`12345678901234567890abc-"super-cool-database-user"-admin`,
			`12345678901234567890abc-'super-cool-database-user'-admin`,
			`12345678901234567890abc-super-cool-database-user-admin`,
		}
		for _, str := range strs {
		fmt.Println("input string:", str)
			res := SplitAtDash(str)
			for i := range res {
		fmt.Println(res[i])
			}
		}
	}

Thanks in advance

**Comment by themantissa** [comment]
@AntjeRadkiewicz1337 thank you for the suggestion, if memory served we improved this for project already but I'll put DB Users on the list.   Is this currently blocking you or were you able to work around for now?

**Comment by AntjeRadkiewicz1337** [comment]
Hi @themantissa ,

right now it is blocking us from the migration. In order to migrate we would either have to check out the code, adapt it and import the database users, or we wait until the enhancement is done.

**Comment by themantissa** [comment]
@AntjeRadkiewicz1337 thank you for confirming that.  I've put it in our backlog and hope we can find the time to address it soon and remove the blocker.   We will keep you updated on the ETA

**Comment by YuryYaroshevich** [comment]
@themantissa any updates on this feature? it is blocking us also

**Comment by themantissa** [comment]
@YuryYaroshevich we have it on the near-term backlog so, baring any emergency needs, we hope to addressthis w/ the next release and we have been releasing each month.
