### ISSUE TITLE
[Bug]: backup_compliance_policy resource missing required attribute

### ISSUE THREAD

**Issue by gperiard** [mongodb/terraform-provider-mongodbatlas#1800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.14.0

### Terraform Version

v1.5.4

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

The documentation for `mongodbatlas_backup_compliance_policy` mentions that the following arguments have defaults when unspecified:

- pit_enabled
- encryption_at_rest_enabled
- copy_protection_enabled

### Documentation for pit_enabled

pit_enabled - Flag that indicates whether the cluster uses Continuous Cloud Backups with a Backup Compliance Policy. **If unspecified, this value defaults to false**.

[Reference](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/website/docs/r/backup_compliance_policy.html.markdown?plain=1#L152C8-L152C8)

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_backup_compliance_policy" "backup_compliance_policy" {
  project_id                 = mongodbatlas_project.pod_project[0].id
  authorized_email           = "###"
  copy_protection_enabled    = true
  pit_enabled                = true
  # encryption_at_rest_enabled = false
...
}
```

### Steps To Reproduce

1. Do not specify a one of the mentionned value when declaring a mongodbatlas_backup_compliance_policy resource.
2. Plan/Apply

### Logs

```hcl
|
│ Error: Missing required argument
│ 
│   on backup.tf line 50, in resource "mongodbatlas_backup_compliance_policy" "backup_compliance_policy":
│   50: resource "mongodbatlas_backup_compliance_policy" "backup_compliance_policy" {
│ 
│ The argument "encryption_at_rest_enabled" is required, but no definition was found.
|
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andreaangiolillo** [comment]
Hello @gperiard 👋 , Thanks for opening the issue.

I was able to reproduce the issue. The fix will be available in the next provider release.
Thanks

**Comment by andreaangiolillo** [comment]
Hello @gperiard 👋 
The fix is available with the latest TF release. Feel free to reopen the issue if using the latest provider version does not fix the issue on your side. Thanks!
