### ISSUE TITLE
Cluster auto-scaling

### ISSUE THREAD

**Issue by pierresteiner** [mongodb/terraform-provider-mongodbatlas#182]
It would be nice to have the cluster auto-scaling exposed in Terraform: https://docs.atlas.mongodb.com/cluster-autoscaling/

**Comment by themantissa** [comment]
@pierresteiner please feel free to upvote this option at our customer feedback site: 
https://feedback.mongodb.com/forums/924145-atlas/suggestions/39629620-expose-auto-cluster-scaling-options-via-terraform
