### ISSUE TITLE
[Bug]: Changing Scope block in the databaseuser resource results in a replacement

### ISSUE THREAD

**Issue by jooh-lee** [mongodb/terraform-provider-mongodbatlas#1821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.14

### Terraform Version

1.6.x

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Adding a scope to the `database_user` causes a replacement of the database user. This is caused by [this](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/internal/service/databaseuser/resource_database_user.go#L191) code:
```
			"scopes": schema.SetNestedBlock{
				PlanModifiers: []planmodifier.Set{
					setplanmodifier.RequiresReplace(),
				},
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"name": schema.StringAttribute{
							Optional: true,
						},
						"type": schema.StringAttribute{
							Optional: true,
						},
					},
				},
			},
```
This doesnt seem right, in the atlas api there is an update call to the user and that allows me to update and not have to recreate the user. I can do the same in the atlas console and that doesnt result in a user replacement

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_database_user" "test" {
  username           = "test-acc-username"
  password           = "test-acc-password"
  project_id         = "<PROJECT-ID>"
  auth_database_name = "admin"

  roles {
    role_name     = "readWrite"
    database_name = "dbforApp"
  }

  roles {
    role_name     = "readAnyDatabase"
    database_name = "admin"
  }

  labels {
    key   = "My Key"
    value = "My Value"
  }

  scopes {
    name   = "My cluster name"
    type = "CLUSTER"
  }

  scopes {
    name   = "My second cluster name"
    type = "CLUSTER"
  }
}
```

### Steps To Reproduce

1. create a user using the database_user resource
2. add scope to the user
3. plan
4. the plan will say its replacing

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lantoli** [comment]
hi @jooh-lee , thanks for raising this issue. 

The current Atlas Go SDK doesn't support  updates to no scopes, if no scopes are sent then current ones remain.  This is why we need to take this conservative approach to make sure that databse user is udpated even if all scopes are deleted. 

In the near future the Atlas Go SDK will be updated to support empty arrays in updates and we'll be able to change this behavior as the one you expect.

thanks for understanding, let me know if you have any further question.

**Comment by jooh-lee** [comment]
is it possible to only recreate the user in that one specific instance where you update to no scopes? vs on any and all updates to the scope? seems dangerous that there is a possibility of a DB user being deleted by accident or lack of knowledge of this behaviour.

I can't speak for others, but i personally would prefer a dirty plan that i can resolve manually when all scopes are removed then my active DB user having the potential to be recreated

Also some documentation on that behaviour i think would be good.

**Comment by lantoli** [comment]
hi, you have to mark in Terraform what attribute changes require a replacement so it's no so easy to do that depending on the use case.

The user is deleted and then immediately created again with same name and same params (except updated ones). It's really almost equivalent to update the user in place.  

I think there is no really a need to know this behavior, you can assume that the db user is just updated.

**Comment by jooh-lee** [comment]
we have a policy of not storing passwords or any sensitive values in terraform states as sensitive values are stored as plaintext in the state, so what we do instead is generate a random password inject that into the user but ignore the password field. that password is then essentially thrown away as we then go and generate a new password for the user that is not synced to terraform. so the act of recreating a user is super destructive event for us

**Comment by lantoli** [comment]
I see. The SDK changes are about to be released.  I can't tell for sure but it's very likely that we could have this implemented during this month or beginning next month so db user doesn't need to be recreated when scopes change

**Comment by lantoli** [comment]
hi @jooh-lee ,  the SDK has already been updated and this PR will make the database_user change in place when scopes change: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1840

you can expect this functionality in the next release.
