### ISSUE TITLE
Serverless aws_vpc_endpoint creation fails

### ISSUE THREAD

**Issue by cloubivesa** [mongodb/terraform-provider-mongodbatlas#1826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.14.0

### Terraform Version

v1.6.6

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

We are planning to start using MongoDB Atlas Serverless instance; currently we have AWS resources and MongoDB clusters in Stockholm region. The nearest serverless instances can be created in Ireland. We faced an issue in creating a vpc endpoint when replacing the cluster with a serverless instance.

### Terraform configuration to reproduce the issue

```shell
Do the changes below:
- provider.tf:
provider "aws":
region = "eu-north-1"

- aws-vpc.tf:
resource "aws_subnet" "subnet_east_a":
availability_zone = "eu-north-1a"

resource "aws_subnet" "subnet_east_b":
availability_zone = "eu-north-1b"

- atlas-serverless-instance.tf:
resource "mongodbatlas_serverless_instance" "aws_private_connection":
provider_settings_region_name = "EU_WEST_1"
```

### Steps To Reproduce

1. Use Serverless PrivateLink example in [docs](https://github.com/mongodb/terraform-provider-mongodbatlas/tree/master/examples/mongodbatlas_privatelink_endpoint/aws/serverless-instance).
2. Do the changes in code
  
3. Run terraform apply  

### Logs

```hcl
aws_vpc_endpoint.vpce_north: Creating...
╷
│ Error: creating EC2 VPC Endpoint (com.amazonaws.vpce.eu-west-1.vpce-svc-0e7975f61ffb9d0f7): InvalidServiceName: The Vpc Endpoint Service 'com.amazonaws.vpce.eu-west-1.vpce-svc-0e7975f61ffb9d0f7' does not exist
│       status code: 400, request id: 62c401a8-5e74-4c60-bb68-ccb031e406ce
│
│   with aws_vpc_endpoint.vpce_north,
│   on aws-vpc.tf line 1, in resource "aws_vpc_endpoint" "vpce_north":
│    1: resource "aws_vpc_endpoint" "vpce_north" {
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cloubivesa** [comment]
It seems to work when AWS resources and MongoDB serverless instance are in the same region (e.g `eu-west-1`).

**Comment by lantoli** [comment]
thanks @cloubivesa . that's correct, AWS VPC are regional services so they need to be in the same region as the resources.   You can also use VPC peering to connect AWS VPCs in different regions.

let me know if you need something else, thanks.
