### ISSUE TITLE
RESOURSE or RESOURCE? Spelling change for readme.md

### ISSUE THREAD

**Issue by codesterribly** [mongodb/terraform-provider-mongodbatlas#185]
Wasn't sure if this was a typo, or on purpose, but the spelling here:

"export AZURE_RESOURSE_GROUP_NAME=<YOUR_RESOURSE_GROUP_NAME>"

would seem to be wrong. Google doesn't find any valid uses for it to be spelled that way.

**Comment by themantissa** [comment]
@codesterribly checking the test, https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_network_peering_test.go#L63 it's AZURE_RESOURSE_GROUP_NAME
So spelling incorrect in both places, I'll file a ticket to fix when we have time available but until then using an incorrect spelling will work to do the test.

**Comment by themantissa** [comment]
This spelling is corrected in both the code and README within other work. Closing. Thanks!
