### ISSUE TITLE
[Bug]: Undocumented behaviour privatelink_endpoint / circle dependency

### ISSUE THREAD

**Issue by alexkunde** [mongodb/terraform-provider-mongodbatlas#1872]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v.1.14

### Terraform Version

v.1.6.5

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Currently the mongodbatlas_privatelink_endpoint is unique per Azure Region, this is not documented in the provider and leads to the following problem.

## Part 1

Let's say you have two environment, DEV and TEST. Both reside in distinct VNETs and both should get a private endpoint to connect to one MongoDB Atlas Cloud private link endpoint. Right now I would follow the [documented steps](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/examples/mongodbatlas_privatelink_endpoint/azure/main.tf) and create one azure endpoint / mongodbatlas private link endpoint pair per environment and link them. This leads to the following error:

```bash
Error: error creating MongoDB Private Endpoints Connection: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/xxx/privateEndpoint/endpointService: 409 (request "PRIVATE_ENDPOINT_SERVICE_ALREADY_EXISTS_FOR_REGION") A private endpoint service already exists for Azure region REAL_REGION.
│ 
│   with module.mongodb-config.mongodbatlas_privatelink_endpoint.mongodb,
│   on ../../modules/mongodb-config/private_endpoint.tf line 32, in resource "mongodbatlas_privatelink_endpoint" "mongodb":
│   32: resource "mongodbatlas_privatelink_endpoint" "mongodb" {
│ 
```

The real behavior is to create one privatelink_endpoint and connect one azure private endpoint per environment with the private_link. This works, I tried, but is not documented in the provider.

## Part 2

I want to create above setup in Terraform. Now this would mean creating two privatelink_endpoint_services aka the link between the Azure Endpoint and the MongoDB PrivateLink Endpoint. These links need the [privatelink_endpoint ID](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/privatelink_endpoint#private_link_id) to connect to. The data element `mongodbatlas_privatelink_endpoint` would be my choice to query the ID. Now to the broken part. To query the mongodbatlas_privatelink_endpoint for the private_link_id you first need to provide the private_link_id to the data element. With a mongodbatlas_privatelink_endpoint being unique to region and project_id when created, the same information as to when its created should suffice to query it. 

Right now there is no way to create multiple azure private endpoints in multiple terraform stacks without hardcoding the ID that might change on recreation. This should be addressed

### Terraform configuration to reproduce the issue

```shell
# TF Stack MongoDB Atlas
resource "mongodbatlas_privatelink_endpoint" "mongodb" {
  project_id    = var.project_id
  provider_name = "AZURE"
  region        = var.atlas_region
}

# TF Stack DEV

resource "azurerm_subnet" "mongodb" {
  # not important
}

resource "azurerm_private_endpoint" "mongodb" {
  name                = "${var.env}-mongodb-pe"
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name
  subnet_id           = azurerm_subnet.mongodb.id

  private_service_connection {
    name                           = data.mongodbatlas_privatelink_endpoint.mongodb.private_link_service_name
    private_connection_resource_id = data.mongodbatlas_privatelink_endpoint.mongodb.private_link_service_resource_id
    is_manual_connection           = true
    request_message                = "Azure Private Link test"
  }

}

data "mongodbatlas_privatelink_endpoint" "mongodb" {
  project_id      = var.project_id
  provider_name   = "AZURE"
  private_link_id = var.private_link_id
}

resource "mongodbatlas_privatelink_endpoint_service" "mongodb" {
  project_id                  = data.mongodbatlas_privatelink_endpoint.mongodb.project_id
  private_link_id             = data.mongodbatlas_privatelink_endpoint.mongodb.private_link_id
  endpoint_service_id         = azurerm_private_endpoint.mongodb.id
  private_endpoint_ip_address = azurerm_private_endpoint.mongodb.private_service_connection[0].private_ip_address
  provider_name               = "AZURE"
}
```

### Steps To Reproduce

Run terraform

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexkunde** [comment]
Bump

**Comment by AgustinBettati** [comment]
Hi @alexkunde. Thank you for raising this issue.

To make sure I understand your problem statement correctly: The current limitation you are facing is that you cannot query a specific `mongodbatlas_privatelink_endpoint` resource element by having only the project id, provider name, and region name.

As a follow up question, would it be possible to reference the resource "mongodbatlas_privatelink_endpoint" and use the computed attribute `private_link_id`?

**Comment by alexkunde** [comment]
Hi @AgustinBettati exactly. With a multienv setup we are not able to connect multiple endpoints with data elements with already provided info. 

For your follow up question:
In our case multi enviroment also means multi stack. So information about the private_link_endpoint is only accessible by querying the data element or hardcoding values. In this case we do not have direct access to the resource via stack.

**Comment by Zuhairahmed** [comment]
> Right now there is no way to create multiple azure private endpoints in multiple terraform stacks without hardcoding the ID that might change on recreation. This should be addressed

Understand concern, but this is a more a feature request to existing behavior vs bug per se. Suggest in this case can you propose your issue or upvote existing item at: https://feedback.mongodb.com/forums/924145-atlas?category_id=370723. feel free to open new issue in case anything else should come up. thank you
