### ISSUE TITLE
Removing an action from a role with only one action through atlas UI causes state plan refresh to fail

### ISSUE THREAD

**Issue by jooh-lee** [mongodb/terraform-provider-mongodbatlas#190]
We have a custom role created through terraform that only had one action (find). Through the atlas console, I removed the action and replaced it with a predefined role(read). Instead of picking up this change in the state refresh, it caused the plan to fail with `insufficient items for attribute "actions"; must have at least 1`. The corresponding change was not made on the terraform side, just the atlas console.

**Comment by themantissa** [comment]
@jooh-lee  ideally changes are not made in the UI for environments managed via Terraform but we can look to improve the state refresh for this resource to handle this situation.

**Comment by themantissa** [comment]
Tracking with internal ticket: [INTMDB-431](https://jira.mongodb.org/browse/INTMDB-431).  Closing issue as have no had any more reports but put in backlog. cc @Zuhairahmed
