### ISSUE TITLE
What will happen to the password field when DB user is imported?

### ISSUE THREAD

**Issue by subeen-n** [mongodb/terraform-provider-mongodbatlas#1952]
What will happen to the password field when DB user is imported? From our understanding, password field wont be part of the statefile and when we try to apply, it will show a change in password field and if we say yes, it will update the password for the DB user.

We ran into an issue where password got updated. Could you pls share more details?

**Comment by marcosuma** [comment]
Hi @subeen-n, does [this help](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/website/docs/r/database_user.html.markdown#import)?

**Comment by Zuhairahmed** [comment]
Resolving issue but feel free to reach out if you need anything else. Also in case of any feature requests feel free to create an issue or upvote an existing one at: https://feedback.mongodb.com/forums/924145-atlas?category_id=370723
