### ISSUE TITLE
[Feature]: Add resources to create function

### ISSUE THREAD

**Issue by Alexkuva** [mongodb/terraform-provider-mongodbatlas#1954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.9.0

### Terraform Version

v1.4.6

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

To create a function_id (using by himself or in mongodbatlas_event_trigger),it must be instantiated via a POST request to https://realm.mongodb.com/api/admin/v3.0/groups/${var.project_id}/apps/${var.app_id}/functionswith the following arguments:
             -H 'Content-Type: application/json' \
             -H 'Accept: application/json' \
             -H 'Authorization: Bearer ${jsondecode(data.http.access_token.response_body).access_token}' \
             -d '${local.udf_file}' \

### Terraform configuration to reproduce the issue

```shell
No specific configuration required
```

### Steps To Reproduce

`tf apply`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgustinBettati** [comment]
Hi @Alexkuva.

As defined in our GitHub issues form, for feature request you can go to the following [feedback forum](https://feedback.mongodb.com/forums/924145-atlas?category_id=370723). Specifically for your request there is already an [existing post](https://feedback.mongodb.com/forums/924145-atlas/suggestions/45693154-add-terraform-resource-for-functions) so feel free to leave an upvote or additional comments there.
 
Closing the issue, feel free to reopen if you have any doubts or concerns.

**Comment by Alexkuva** [comment]
Sorry for that, I'll use feedback forum for future feature requests. Thank you for your answer.
