### ISSUE TITLE
[Bug]: Impossible to create a database scope (database watch against) in mongodbatlas_event_trigger

### ISSUE THREAD

**Issue by Alexkuva** [mongodb/terraform-provider-mongodbatlas#1956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.9.0

### Terraform Version

v1.4.6

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

It's impossible to create database scope (database watch against) in mongodbatlas_event_trigger resource.
In order to do it, config_collection should be empty cf. api - (config_collection="" ).

Error message received by terraform: "Error: `config_operation_types`, `config_database`,`config_collection`,`config_service_id` must be provided if type is DATABASE"

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_event_trigger" "triggered_function" {
  name       = "name_udf"
  project_id = "project_id"
  app_id     = "app_id"

  function_id = "function_id"

  type      = "DATABASE"
  disabled  = false
  unordered = true


  config_operation_types = ["INSERT", "UPDATE", "REPLACE", "DELETE"]
  config_database        = "databaseName"
  config_collection      = ""
  config_service_id      = "service_id"
  config_full_document   = false

}
```

### Steps To Reproduce

`tf apply`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Alexkuva** [comment]
In order to fix the issue, PR has been open: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/1955

**Comment by AgustinBettati** [comment]
Hello @Alexkuva, thank you for raising this issue and extending a pull request with the suggested changes 💯.

I was able to reproduce your issue and verify your solution. I will create a follow up PR with your changes and:
- Updates to our terraform documentation as it is currently stating that `config_collection` is required when type is DATABASE.
- New acceptance test which contemplates the scenario of creating a watch against database trigger.

Additionally I will double check on our [API documentation](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/triggers/operation/adminCreateTrigger) as it is also stating the collection property as required.

**Comment by AgustinBettati** [comment]
The fix has been merged and will be included in the coming provider release.
