### ISSUE TITLE
[Bug] mongodbatlas_custom_db_role created with the wrong permissions

### ISSUE THREAD

**Issue by MarcoDelGamba** [mongodb/terraform-provider-mongodbatlas#1963]
Hello!

# Providers

```hcl
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "1.15.0"
    }
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.30"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.6.0"
    }
  }
}

```

### Terraform Configuration File 
```hcl
resource "mongodbatlas_database_user" "this" {
  for_each           = var.mongo_app_users
  username           = each.key
  password           = random_password.this[each.key].result
  project_id         = mongodbatlas_project.this.id
  auth_database_name = "admin"

  roles {
    role_name     = mongodbatlas_custom_db_role.this[each.key].role_name
    database_name = "admin"
  }
  scopes {
    name = mongodbatlas_advanced_cluster.this.name
    type = "CLUSTER"
  }
  depends_on = [
    mongodbatlas_custom_db_role.this
  ]
}

locals {
  mongodb_app_actions = [
    "FIND", "INSERT", "REMOVE", "UPDATE", "LIST_INDEXES", "LIST_COLLECTIONS"
  ]
}

resource "mongodbatlas_custom_db_role" "this" {
  for_each = var.mongo_app_users

  project_id = mongodbatlas_project.this.id
  role_name  = format("%s-%s", each.key, "role")

  dynamic "actions" {
    for_each = local.mongodb_app_actions

    content {
      action = actions.value
      resources {
        collection_name = ""
        database_name   = each.value.database_name
      }
    }
  }
}
```

### Steps to Reproduce

Currently trying to set up some custom roles for some applications. Applications should not be able to create collections which are managed by flyway. Since custom roles can only be created inside the admin account the database name inside the user's role block is set to "admin". However, even if the CREATE_COLLECTION permission is not explicitly granted, the custom role is able to create a collection in the target database specified inside the role resource. The same role is not able to delete a collection though so I cannot really tell what is happening

### Expected Behavior

Given the permissions specified above, I do not expect the user to be able to create collections.

Anyone able to reproduce this?

### UPDATE 
It looks like the INSERT grant allows the user also the create collections. However, if this is removed, the user is not able to add documents to the collection

**Comment by nderra** [comment]
Hi! Got the same problem here, did you find any solution?
Thanks!

**Comment by AgustinBettati** [comment]
Hi @MarcoDelGamba. Thank you for the details provided.

I was able to reproduce the issue you are mentioning. It is in fact true that the `insert` grant enables users to also create collections as stated in [the documentation](https://www.mongodb.com/docs/upcoming/reference/privilege-actions/#mongodb-authaction-insert).

We will follow up with more investigation to see if there is away to define a custom db role that allows document inserts but not collection creations.

**Comment by MarcoDelGamba** [comment]
Hi @AgustinBettati thanks for your response

I suppose an alternative may be to use an update command joint to an upsert. I wonder if there is some kind of performance penalty by following this path

**Comment by AgustinBettati** [comment]
Hi @MarcoDelGamba @nderra, we have discussed internally with the team and advise raising a feature request in our the [following forum page](https://feedback.mongodb.com/forums/924145-atlas?category_id=370723) with this use case.
Will close this issue but feel free to leave any additional comments or doubts.
