### ISSUE TITLE
[Feature]: mongodbatlas_event_trigger does not support Database operations

### ISSUE THREAD

**Issue by MarcoDelGamba** [mongodb/terraform-provider-mongodbatlas#1967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.15.0

### Terraform Version

v1.7.3

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Reading the docs, config_operation_types only supports: INSERT, UPDATE, REPLACE, DELETE. However, I was able to create a trigger manually with the following operation types:
-Create Collection
-Rename Collection
-Modify Collection

Is this supposed to be implemented during the next sprints? 

In addition to that, when creating the trigger via terraform an app_id is requested. Here, https://github.com/mongodb/terraform-provider-mongodbatlas/issues/957, it looks like we can use the cluster_id. If this is the case maybe an example should be added to the docs

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_event_trigger" "test" {
  project_id = mongodbatlas_project.this.id
  app_id = mongodbatlas_advanced_cluster.this.id # Is this correct?
  name = "Unsupported Collections Trigger"
  type = "DATABASE"
  disabled = false
  unordered = false
  config_operation_types = ["CREATE_COLLECTION"] # Not supported
  config_database = "DATABASE NAME"
  config_service_id = "SERVICE ID"
  event_processors {
    aws_eventbridge {
      config_account_id = "AWS ACCOUNT ID"
      config_region = "AWS REGION"
    }
  }
}
```

### Steps To Reproduce

Not able to run it yet

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgustinBettati** [comment]
Hi @MarcoDelGamba. Thanks for raising these points.

Regarding database operation types that our not mentioned in our documentation, I was able to verify that the underlying API does provide support for this. We will gain more understanding on the current supported operation types and expose them in the provider.

As for the value of app_id, the existing documentation defined in terraform docs is accurate and aligned with how the [underlying API is defined](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/triggers/operation/adminCreateTrigger). I would suggest creating a [feature request](https://feedback.mongodb.com/forums/924145-atlas?category_id=370723) if there is a need to improve how the app_id is defined as this would require more significant changes.

**Comment by MarcoDelGamba** [comment]
Hi @AgustinBettati
 
I opened a request.

Thank you for you help

**Comment by Zuhairahmed** [comment]
Thanks resolving this GitHub Issue, will keep you updated via UserVoice portal for feature request. Thanks again!
