### ISSUE TITLE
[Bug]: Removing `mongodbatlas_cloud_backup_schedule` resource is resulting in error `Continuous Cloud Backup cannot be on without an hourly policy item`

### ISSUE THREAD

**Issue by kgoutham93** [mongodb/terraform-provider-mongodbatlas#2029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.1.1

### Terraform Version

0.12

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

I will list the steps as per timeline
1. Created an `mongodbatlas_cluster` resource with `cloud_backup=true` and `pit_enavled=true`
2. Added `mongodbatlas_cloud_backup_schedule` resource with `policy_item_hourly` and `pit_enabled=false`
3. When I re-apply tag from step-1 I got the following error 
   ```
   Error: error updating MongoDB Cluster (CLUSTER): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/GROUP/clusters/CLUSTER: 400 (request "ATLAS_GENERAL_ERROR") Reason: Continuous Cloud Backup cannot be on without an hourly policy item.

                on infrastructure-mongo.tf line 1, in resource "mongodbatlas_cluster" "prod":
                1: resource "mongodbatlas_cluster" "prod" {
   ```
Though applying step-3 failed, the backup policy configured in step 2 is **deleted**.

Is it because,
1. Step 1 creates a default backup policy
2. Step 2 deletes the default policy and adds my custom policy
3. Update in step 3 fails because neither the default nor the custom backup policy would be present, but `cloud_backup` is still set to true.

### Terraform configuration to reproduce the issue

```shell
resource "mongodbatlas_cluster" "prod" {
  project_id   = local.project_id
  name         = local.atlas_cluster_name
  num_shards   = 1
  cloud_backup = true
  pit_enabled  = true
  mongo_db_major_version = "6.0"
  replication_factor           = 3
  auto_scaling_disk_gb_enabled = true
  auto_scaling_compute_enabled = true
  auto_scaling_compute_scale_down_enabled = true
  provider_auto_scaling_compute_min_instance_size = "M10"
  provider_auto_scaling_compute_max_instance_size = "M60"

  //Provider Settings "block"
  provider_name               = var.mongo_atlas_provider
  disk_size_gb                = 40
  provider_disk_iops          = 120
  provider_volume_type        = "STANDARD"
  provider_instance_size_name = "M10"
  provider_region_name        = "us-east-1"
}
```

### Steps To Reproduce

1. Create mongocluster resource with cloud_backup=true and pit_enabled=true
2. Set some default `mongodbatlas_cloud_backup_schedule`
3. Revert step 2 and re-apply 1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lantoli** [comment]
thanks @kgoutham93 for opening the issue. 

can you try with the latest version of MongoDB Atlas Provider, it's currently 1.15.2 and see if you still get the error?

thanks!
