### ISSUE TITLE
Changes are not detected when changing Team's role_names attribute on mongodbatlas_project

### ISSUE THREAD

**Issue by michelzanini** [mongodb/terraform-provider-mongodbatlas#209]
Hi,

I have a project resource such as this:

```
resource "mongodbatlas_project" "project" {
  org_id  = local.organization_id
  name    = local.project_name

  teams {
    team_id    = "5e5cf01b8d40110c9995491d"
    role_names = ["GROUP_OWNER"]
  }
}
```

This creates correctly, but when I want to change the teams permission, lets say from `["GROUP_OWNER"]` to `["GROUP_DATA_ACCESS_READ_WRITE"]`, that change is not detected.

I run `terraform plan` after editing the field and it says every thing is up-to-date. Basically I can't edit the role of a team. I had to remove the team, apply it, then add it back again with a different value. But this requires code changes etc... 

Expected behaviour is to detect the change correctly and update the resource. Of course, if the role name is still the same then no change should be detected.

Can this be fixed please?
Thanks.

**Comment by themantissa** [comment]
@michelzanini can you include which provider version you have just so we can be sure to have the team investigate this w/ the same version?  (I notice you are submitting a few issues- can you please include details on Terraform version/provider version on each)

**Comment by michelzanini** [comment]
Version `0.5.1` of the provider, Terraform version `0.12.16`

**Comment by themantissa** [comment]
Confirmed bug, when a team has been added to a project changing or adding to the role_name array in the configuration was not detected as different on refresh.   Will ask the developers to look into.

**Comment by PacoDw** [comment]
Hello @michelzanini, thank you so much for your review, I fixed it you can check if the changes are ok on the fix-#209 branch. 

Let me know if you have another comment or concern

**Comment by michelzanini** [comment]
Thanks for the fix @PacoDw . I tested the branch and it worked.
I can see `terraform plan` now displays the difference and `terraform apply` is applying it correctly afterwards.

Plan outout:
```
+ teams {
          + role_names = [
              + "GROUP_DATA_ACCESS_READ_WRITE",
            ]
          + team_id    = "5e3d6b2d014b7673c90b76aa"
        }
      - teams {
          - role_names = [
              - "GROUP_OWNER",
            ] -> null
          - team_id    = "5e3d6b2d014b7673c90b76aa" -> null
        }
```

Looks good!
Thanks.

**Comment by PacoDw** [comment]
you're welcome :)
