### ISSUE TITLE
[Bug][Question][Help needed]: Not able to fetch federated online archived connection string 

### ISSUE THREAD

**Issue by kailash** [mongodb/terraform-provider-mongodbatlas#2099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.15.2

### Terraform Version

1.7.4

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Not able to to fetch the federated online archived connection string

```
resource "mongodbatlas_privatelink_endpoint_service_data_federation_online_archive" "test" {
  project_id = mongodbatlas_project.atlas-project.id
  endpoint_id = "vpce-046cf43c79424d4c9"
  provider_name = "AWS"
  comment = "Test"
  region        = "US_EAST_1"
  customer_endpoint_dns_name = "vpce-046cf43c79424d4c9-nmls2y9k.vpce-svc-0824460b72e1a420e.us-east-1.vpce.amazonaws.com"
}

data "mongodbatlas_privatelink_endpoint_service_data_federation_online_archives" "test_data_source" {
  project_id = mongodbatlas_project.atlas-project.id
}

```

USing above example I am able to set up federated privatelink endpoint in mongoatals and it is also available in UI. but 

1. not able to fetch the same connection_string in `mongodbcluster.<name>.connection_string.private_endpoints`
2. also not able to fetch the federated +online archived privatelink connection_string via `mongodbatlas_privatelink_endpoint_service_data_federation_online_archives`

### Terraform configuration to reproduce the issue

```shell
Use the example usage from docs, and fetch connection_string from terraform.
```

### Steps To Reproduce

1. create an online archive on any collection
2. create a privatelink endpoint via `mongodbatlas_privatelink_endpoint_service_data_federation_online_archives`
3. try to fetch the conenction_string for this federated privatelink [how to fetch?]

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oarbusi** [comment]
Thanks for opening this issue @kailash,
connection_string cannot be fetched directly from `mongodbatlas_privatelink_endpoint_service_data_federation_online_archives`.
In this [example](https://github.com/mongodb/terraform-provider-mongodbatlas/tree/master/examples/mongodbatlas_privatelink_endpoint/aws) you can check how the terraform configuration should look like for your cluster and private endpoints to achieve what I think you are trying to do. [Here](https://github.com/mongodb/terraform-provider-mongodbatlas/tree/master/examples/mongodbatlas_privatelink_endpoint/aws/cluster) you can find a detailed explanation on how to retrieve `connection_strings`. You can also check the [mongodbatlas_cluster](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/cluster) documentation for more information on `connection_strings` attribute. 
Please let us know if this helps!

**Comment by kailash** [comment]
Hi @oarbusi , 
Thanks for the reply, I referred all links provided above before creating the post.
 
I have 2 privatelink endpoint service defined one through `mongodbatlas_privatelink_endpoint_service` and another through `mongodbatlas_privatelink_endpoint_service_data_federation_online_archive` both have differnet VPCe but same VPC.
Also I can view both of them in atlas UI one under dedicate VPCe and another under federated + online archive VPCe.
But my `mongodb_cluster` returns only dedicated VPCe details under conenction_string.

Is there something I am missing?

**Comment by oarbusi** [comment]
@kailash to help you further please share your Terraform configuration files (`mongodbatlas_cluster`, `mongodbatlas_privatelink_endpoint_service` and `mongodbatlas_privatelink_endpoint_service_data_federation_online_archive `) so that we can easily reproduce the issue.
