### ISSUE TITLE
[Bug]: Documentation fix request

### ISSUE THREAD

**Issue by rbapst-tamedia** [mongodb/terraform-provider-mongodbatlas#2110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

latest (1.15.3)

### Terraform Version

v1.6.6

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Documentation about the ["mongo_db_major_version" parameter of the "mongodbatlas_cluster" resource](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#mongo_db_major_version)
and ["mongo_db_major_version" parameter of the "mongodbatlas_advanced_cluster"](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster#mongo_db_major_version)
looks to be outdated:

> [mongo_db_major_version](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#mongo_db_major_version) - (Optional) Version of the cluster to deploy. Atlas supports the following MongoDB versions for M10+ clusters: 4.2, 4.4, 5.0, or 6.0. If omitted, Atlas deploys a cluster that runs MongoDB 5.0. If provider_instance_size_name: M0, M2 or M5, Atlas deploys MongoDB 5.0. Atlas always deploys the cluster with the latest stable release of the specified version. See [Release Notes](https://www.mongodb.com/docs/upcoming/release-notes/) for latest Current Stable Release.

Could you mention version 7.0 and remove ref to 4.2 ?

### Terraform configuration to reproduce the issue

```shell
Read https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#mongo_db_major_version
and
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster#mongo_db_major_version
```

### Steps To Reproduce

Read [cluster doc](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#mongo_db_major_version)
and
[advanced_cluster doc](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster#mongo_db_major_version)

### Logs

```hcl
-none-
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rbapst-tamedia** [comment]
BTW, the "Code of Conduct" link is not working when we create an issue. Probably to fix here (remove the "../../" but not tested) https://github.com/mongodb/terraform-provider-mongodbatlas/blob/9c0f778b499b21eb01b0613efa4d92c58dad8b69/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L97

**Comment by oarbusi** [comment]
Thanks for opening this issue @rbapst-tamedia 
We will address this in a followup pull request and the updated documentation will be available in the next release

**Comment by oarbusi** [comment]
This has been fixed as part of [this PR](https://github.com/mongodb/terraform-provider-mongodbatlas/pull/2112).
