### ISSUE TITLE
Incorrect description for atlas_cidr_block in mongodbatlas_network_peering documentation

### ISSUE THREAD

**Issue by lmego** [mongodb/terraform-provider-mongodbatlas#215]
The description for the atlas_cidr_block parameter in the **mongodbatlas_network_peering** documentation incorrectly states that it is an **"(Optional | AZURE Required) Unique identifier for an Azure AD directory."** in both Argument Reference and Attributes Reference sections

See https://www.terraform.io/docs/providers/aws/r/vpc_peering_connection.html

**Comment by themantissa** [comment]
Waiting on internal confirmation before correcting that atlasCidrBlock is not needed in the peering container connection.   Update soon.

**Comment by themantissa** [comment]
Fixed in https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/217, will go to docs w/ next version.  Thanks!
