### ISSUE TITLE
Issues with resource and API design for Cloud Provider Snapshot Backup Policy

### ISSUE THREAD

**Issue by michelzanini** [mongodb/terraform-provider-mongodbatlas#222]
Hi,

I am sorry but the description of this issue will be long.

I am having some difficulties configuring Cloud Provider Snapshot Backup Policy from Terraform.
The issues are more regarding how the Terraform resource has been designed rather than bugs.

When a cluster is first created, this is the default backup policy it gets:

![Screen Shot 2020-05-08 at 09 35 24](https://user-images.githubusercontent.com/4479787/81406752-8da31180-9110-11ea-9d74-403dbbbc864f.png)

What I really want to enable are `daily` and `weekly` backups. I do not need `hourly` and `monthly`. By using the UI here I could use the `DELETE` button to remove the `hourly` and `monthly` lines. But, I want to do it with automation, not manually.

With the release of Terraform provider `0.5.0` a new resource for backup policy was created and I immediately tried to use it.
This was my first attempt:

```
resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "backup_policy" {
  policies {
    id = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.id

    policy_item {
      id                 = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.policy_item.0.id
      frequency_interval = 1
      frequency_type     = "daily"
      retention_value    = 3
      retention_unit     = "days"
    }
    policy_item {
      id                 = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.policy_item.1.id
      frequency_interval = 1
      frequency_type     = "weekly"
      retention_value    = 1
      retention_unit     = "weeks"
    }
  }
}
```

I am trying here to define only `daily` and `weekly` backups. The references to `mongodbatlas_cluster.my_cluster` you see here are to follow what the documentation indicates. Let's assume I have declared `mongodbatlas_cluster.my_cluster` somewhere else.

The problem here is that the first item on Atlas is a `hourly` backup (when a cluster is first created) and my first `policy_item` defined in the resource is a `daily` backup. This will cause a error `400 (request "Bad Request") The frequency type of a policy item must not be changed`. This happens because a `hourly` backup cannot be updated to a `daily` via API - the frequency type can't be changed via update.

**That means it is not possible on the current design to skip `hourly` backups**. You could skip the last one, `monthly`, or the last 2, last 3, etc... as the indexes won't change when removing elements from the end of the list. 

I could specify indexes `1` and `2` instead of `0` and `1` in the code there, just after creating a new cluster, that would work. `daily` and `weekly` backups would be set and `hourly` and `monthly` would be removed. However, the next time I run `apply` it will fail, as the index `2` no longer exists. **That would mean I have to change my code in accordance to what the state is on the backup policy. Because I manage many clusters from the same code, keep changing the code is inviable to me.**

> Design issue number 1: referencing the IDs for policy items via their positions in the list is not viable as this limits variations on the number of total policies you might want. It binds the current state of Atlas with the code in a way you need to know the state before writing the code.

---

A simple solution I tried was to not declare the IDs such as:
```
resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "backup_policy" {
  policies {
    id = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.id

    policy_item {
      frequency_interval = 1
      frequency_type     = "daily"
      retention_value    = 3
      retention_unit     = "days"
    }
    policy_item {
      frequency_interval = 1
      frequency_type     = "weekly"
      retention_value    = 1
      retention_unit     = "weeks"
    }
  }
}
```

This fails because `id` is a required field. Error message: `The argument "id" is required, but no definition was found`. 
If the `id` was marked as not required, the API does accept us to send records without ID. The API then removes all previous defined policy items and creates only the ones we need. This is the API call I am making to `/groups/{id}/clusters/{name}/backup/schedule`:

```
{
    "clusterId": "5e5f9c6663c5ca0a034af49e",
    "clusterName": "my_cluster",
    "policies": [
        {
            "id": "5e628737533d877250441cbc",
            "policyItems": [
                {
                    "frequencyInterval": 1,
                    "frequencyType": "daily",
                    "retentionUnit": "days",
                    "retentionValue": 3
                },
                {
                    "frequencyInterval": 1,
                    "frequencyType": "weekly",
                    "retentionUnit": "weeks",
                    "retentionValue": 1
                }
            ]
        }
    ],
    "referenceHourOfDay": 0,
    "referenceMinuteOfHour": 0,
    "restoreWindowDays": 3
}
```

**That works more or less like I would expect. It does not matter what was there before. The state that I want now is always what I get saved in the end.** However, the saved lines are always changing their `id`'s after each API call.
That would be a problem for Terraform as this means that every `terraform plan` there would be changes reported.

Eventually what we need is to specify a fixed ID ourselves, something like this:

```
{
    (...)
            "policyItems": [
                {
                    "id": "daily-policy-id",
                    "frequencyInterval": 1,
                    "frequencyType": "daily",
                    "retentionUnit": "days",
                    "retentionValue": 3
                },
                {
                    "id": "weekly-policy-id",
                    "frequencyInterval": 1,
                    "frequencyType": "weekly",
                    "retentionUnit": "weeks",
                    "retentionValue": 1
                }
            ]
        }
    (...)
}
```

But this is not allowed via API. It returns a 400 Bad Request error. **If this was possible by the API then we would be able to define a fixed String id to each policy item instead of referencing list item positions and that would work fine**. It would always delete anything previously saved and save the items declared in it's place. Because the ID is fixed, next `plan`'s would work fine. If a change is done and the ID is kept the same, it would become a simple update.

> Design issue number 2: the API does not allow a custom String ID to be specified which makes it hard for to deal with CRUD operations. To be able to do subsequent updates to a policy item the API user first needs to create the policy item and then keep the ID as a reference for future calls. This forces Terraform to use references to a list of IDs etc...

---

Third issue I have regards to be able to dynamically define the number of policy items I want.
So for example, lets have a look at this Terraform snippet:

```
resource "mongodbatlas_project" "project" {
  (...)
  dynamic "teams" {
    for_each = { (...) }

    content {
      team_id    = teams.value["team_id"]
      role_names = teams.value["role_names"]
    }
  }
}
```

Above I can dynamically define how many `teams` items I want for my project. It allows me to provide a configuration list, and Terraform will create as many `teams` as the number of `for_each` iterations.

I wanted to be able to do as following:
```
resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "backup_policy" {
  policies {
    id = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.id

    dynamic "policy_item" {
      for_each = { (...) }

      content {
        id                 = policy_item.value["id"]
        frequency_interval = policy_item.value["frequency_interval"]
        frequency_type     = policy_item.value["frequency_type"]
        retention_value    = policy_item.value["retention_value"]
        retention_unit     = policy_item.value["retention_unit"]
      }
    }
  }
}
```

This would allow me to define any number of policies dynamically via a variable that is used on the `for_each`. However, I tried this and keep getting errors such as `Blocks of type "policy_item" are not expected here`.

I believe is either a Terraform limitation that you can't have a nested `dynamic` (as we are inside `policies` here already) or `policy_item` has not been made for `dynamic` ? I don't have much Terraform experience to know how this works...

However, I think there's a design issue here. The container `policies` that needs an ID should not be something that we should need to declare here. I see the API requires this. I have tried via API to create two `policies` to test, and the API never lets us. So it seems there's always one policy, never zero or more than one. In that case why even have it as a list? Maybe this can be changed either on the API or on Terraform resource... so we don't need it. Or maybe in both. 

But ideally this is what I would like to have:

```
resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "backup_policy" {
  policy_items {
    id                 = "daily-policy-id"
    frequency_interval = 1
    frequency_type     = "daily"
    retention_value    = 3
    retention_unit     = "days"
  }
  policy_items {
    id                 = "weekly-policy-id"
    frequency_interval = 1
    frequency_type     = "weekly"
    retention_value    = 1
    retention_unit     = "weeks"
  }
}
```

Where `policy_items` supports `dynamic`.

> Design issue number 3: There should be no need for a wrapper `policies` which always has the size of one. This limits us not be able to have dynamic policy items.

---

Resuming. 

A simple change to the API to allow a custom ID string would fix both design limitations 1 and 2. Terraform provider would only need to update it's documentation to suggest using strings instead of referencing list item positions. I don't think any other change on Terraform provider would be needed.

The limitation 3 is less important, but also good to be looked at. However, I feel the important are the other first two.

Of course maybe you have other suggestions to go around this limitations... I would be happy to hear them.

---

So this is it, thanks if you got to read all the way to here 👍 .
Thanks.

**Comment by themantissa** [comment]
Hi @michelzanini - wanted to ack that I will give this a good read as soon as I'm able but w/ the length and examples will take some time.   However know we certainly had to think through many challenges in getting this API resources supportable within Terraform so appreciate all the detail on your experience.

**Comment by themantissa** [comment]
Hi @michelzanini, I gave this a good read and I think I'll also need @marinsalinas or @PacoDw to comment on some of the Terraform specific limitations than can lead some very confusing list references (see https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/219 for our last similar example) but I'll comment on what I can.  

So when one turns on cloud provider snapshots it automatically gives a default policy, which you saw in the UI.  So the situation was that a state exists in Atlas that was not reflected in Terraform. For users perfectly happy w/ the default or that wanted to just change a variable we had to get that state into Terraform, which is what we did. When a cluster has CPS true we get the policy and then it can be modified like in the UI.   But as you note the underlying API does not have references to parts of the policy, no id, nor does it have a delete (https://docs.atlas.mongodb.com/reference/api/snapshot-schedule/ as GET and PATCH) so now the question is, how do we start with a state and then change it - all in a way that works with Terraform and the existing API?  A change in the underlying API would likely be best but that will take more time, especially so as not to impact those already using the resource.  But in the mean time we'll add a project to the backlog to see  if we can figure out a way to do a "delete" like one can in the UI - @PacoDw  I know you've thought a lot about this one so something to ponder.

**Comment by peter-dolkens** [comment]
> so now the question is, how do we start with a state and then change it - all in a way that works with Terraform and the existing API?

This is where you made a mistake.

The Terraform design philosophy is NOT to start with a state.

If I don't create a backup policy, that's fine - leave me with the default.

If I *do* create a backup policy, I expect my policy to replace whatever is there - thus eliminating the requirement to preserve any existing state.

It has frustrated me many times in the past (cloudflare refusing to update existing DNS records for example) - but at the end of the day, it is the right approach, because it eliminates problems like you're having here.

**Comment by themantissa** [comment]
This decision was made with a team and we are now reviewing it and may make a breaking change with a major version based on feedback.   Thank you.

**Comment by peter-dolkens** [comment]
Just to expand on the workarounds that @michelzanini attempted - I also tried generating a mongo-style ID, instead of using arbitrary strings.

```
resource "random_string" "backup_policy_id" {
  count                    = length(local.mongodb_atlas_backup_list)

  length = 24
  upper = false
  lower = false
  number = true
  special = true
  override_special = "abcdef"
}

resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "test" {
  count                    = length(local.mongodb_atlas_backup_list)

  project_id               = mongodbatlas_cluster.cluster[count.index].project_id
  cluster_name             = mongodbatlas_cluster.cluster[count.index].name

  reference_hour_of_day    = 3
  reference_minute_of_hour = 45
  restore_window_days      = 4

  policies {
    id                     = local.mongodb_atlas_backup_list[count.index].snapshot_backup_policy.0.policies.0.id

    policy_item {
      id                   = random_string.backup_policy_id[count.index].result
      frequency_interval = 1
      frequency_type     = "weekly"
      retention_unit     = "weeks"
      retention_value    = 520
    }
  }
}
```

**Comment by andreykaipov** [comment]
Was trying to incorporate this resource into a module today. From reading the docs, I was a bit confused/surprised at the way the resource works, so I'm glad I'm not the only one.

Thinking of workarounds, I was actually able to get the `dynamic` expression working with `policy_item`s, but you still end running against the first design issue described by @michelzanini in the OP.

Here I'm iterating over the variable `user_provided_policies` that's a list of objects with keys similar to the `policy_item`'s:

```terraform
resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "cluster" {
  ...
  policies {
    id = mongodbatlas_cluster.request.snapshot_backup_policy.0.policies.0.id

    dynamic "policy_item" {
      for_each = [
        for ix, item in var.user_provided_policies : {
          id        = mongodbatlas_cluster.request.snapshot_backup_policy.0.policies.0.policy_item[ix].id
          interval  = item.interval
          type      = item.type
          unit      = item.unit
          retention = item.retention
        }
      ]
      content {
        id                 = policy_item.value.id
        frequency_interval = policy_item.value.interval
        frequency_type     = policy_item.value.type
        retention_unit     = policy_item.value.unit
        retention_value    = policy_item.value.retention
      }
    }
  }
}
```

Here I'm assigning the IDs of the existing policy items to our provided ones so that Atlas can accept the request. Unfortunately, if the provided policy items aren't in the exact order of `<hourly, daily, weekly, monthly>`, then you'll get a 400 because frequency types can't be changed. If you omit one, same deal. And I'm afraid even if that did work, it would break again if we tried to add a policy back in, because the list has now been scaled down.

**Comment by andreykaipov** [comment]
I don't think any API work really has to be done. Looking at the existing provider code, it only does PATCHes for policy items, even though the API request when you save changes on that page is a POST.

For example, issuing this request creates a daily and weekly backup policy items. The order doesn't matter here. We can omit or add new policy items. Note IDs don't really matter either, apart from the parent policy holding the items.

```
POST https://cloud.mongodb.com/nds/backup/<org_id>/<cluster_id>/backupPolicy
{
  "referenceTimeInMins": 83,
  "restoreWindowDays": 7,
  "updateSnapshots": false,
  "policies": [
    {
      "id": "6002033dd6e2d320777b0080",
      "policyItems": [
        {
          "id": "000000000000000000000001",
          "frequencyType": "DAILY",
          "frequencyInterval": 1,
          "retentionUnit": "DAYS",
          "retention": 7
        },
        {
          "id": "000000000000000000000002",
          "frequencyType": "WEEKLY",
          "frequencyInterval": 1,
          "retentionUnit": "DAYS",
          "retention": 30
        }
      ]
    }
  ]
}
```

This works fine.

Now of course trying something funky like updating the frequency type of one of these policy items will report an error, e.g., if we change policy `..002` from `WEEKLY` to `MONTHLY` and issue the same request:
```
        {
          "id": "00000000000000000000002",
          "frequencyType": "MONTHLY",
          "frequencyInterval": 1,
          "retentionUnit": "DAYS",
          "retention": 30
        }
```

We'd get a 400:

```
{"errorCode":"BACKUP_POLICY_INVALID","message":"Backup policy is invalid: Cannot change frequency unit once a policy item is created","version":"1","status":"ERROR"}❯
```

That's fine, we can just give our a policy a new ID, say `..003`. Interestingly, since the policy item IDs don't matter, we could technically generate them from hashing the contents of the policy item or whatever (as long as it's a hexademical string).

It's interesting because this endpoint looks exactly the same as the PATCH one. The only difference seems like that IDs don't really matter for the POST.

I don't know what the next steps could be. Too funky for me.

**Comment by petewilcock** [comment]
The requirement for an [API Access List for DELETE](https://docs.atlas.mongodb.com/reference/api/cloud-backup/backup/backups/) commands on the cloud backup makes it impossible to remove one of the initial policies on creation (or latterly). 

For my fellow suffering Googlers, it throws error:

```
403 (request "RESOURCE_REQUIRES_ACCESS_LIST") This resource requires access through an access list of ip ranges
```

If we are running Terraform from a CI without a static IP (e.g. CircleCI) there is no way to whitelist the IP address of the caller in the API key access list. Consequently this resource is pretty useless and we've had to remove it - instead asking users to manage the backup policy manually in the UI. 

I don't understand how an API key that can create and delete entire clusters needs _additional_ access list whitelisting to then modify the backup policy of said clusters.

**Comment by themantissa** [comment]
@petewilcock a valid point, thank you for adding it.  One can open up the access list completely with the following two entries as a work-around for situation like yours where the IP just cannot be known - **however I must add the warning that this opens up the API access list to use from anywhere - eliminating the security check of known location and introduces a security risk if used** - with that add 0.0.0.0/1 and 128.0.0.0/1 until we find a way to better balance security with services from massive/unpredictable IP ranges.   Also we are reworking cloud provider snapshot backup policy for our next version so except a great deal of improvement with the resource as well.

**Comment by mbrancato** [comment]
To tack onto the 403 error, I too am getting this error:
```
Error: error updating a Cloud Provider Snapshot Backup Policy: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxxxxxxxxxxxxxxxx/clusters/xxxxxxxxxx/backup/schedule: 403 (request "RESOURCE_REQUIRES_ACCESS_LIST") This resource requires access through an access list of ip ranges.
```

But I am not coming from a CI egress IP, I'm trying locally from a temporary IP that is in the project's network access list. I believe this is the API returning this error, not the TF provider.

I enabled "Allow access from anywhere" in the UI, and still received the same error.

**Comment by themantissa** [comment]
@mbrancato the project network access list is different than the API key access list, the former is for the data plane and the later for the control plane.  This will walk you through where to look in the UI: https://docs.atlas.mongodb.com/configure-api-access/

**Comment by mbrancato** [comment]
Hi @themantissa - that's very confusing.

According to the docs linked:
```
For Atlas users with a non-empty API access list, all API access must originate from an IP address on an API access list.
```

Ours is empty / turned off for the API access.

**Comment by themantissa** [comment]
@mbrancato  I'm aware and am working to try to better express in our docs and reality with how it works.  This issue is it works fine as noted until you use a resource/endpoint that by itself requires an API access list.  I believe backup is one of those resources, hence the error.

**Comment by mbrancato** [comment]
Ahh, your comment here makes more sense now: https://github.com/mongodb/terraform-provider-mongodbatlas/issues/222#issuecomment-857257787

**Comment by themantissa** [comment]
Version 1.0.0 is out with a complete rework of the cloud backup schedule policy.  Details can be found in the [upgrade guide](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/guides/1.0.0-upgrade-guide) and [docs](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cloud_backup_schedule).   Hope this solves some the of issues but feedback is welcome both here or send to me directly - melissa.plunkett@mongodb.com

**Comment by elopsod** [comment]
hi @themantissa 
provider version 1.0.1 has same problem 
```
? Error: error creating a Cloud Backup Schedule: error deleting MongoDB Cloud Backup Schedule (cluster): DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/1111111111/clusters/cluster/backup/schedule: 403 (request "RESOURCE_REQUIRES_ACCESS_LIST") This resource requires access through an access list of ip ranges.
| 
|   with module.atlas_mongodb_cluster.mongodbatlas_cloud_backup_schedule.test[0],
|   on ../../../terraform-module-mongodbatlas/backup.tf line 5, in resource "mongodbatlas_cloud_backup_schedule" "test":
|    5: resource "mongodbatlas_cloud_backup_schedule" "test" {

```

**Comment by themantissa** [comment]
@elops-od the error here is not the same problem.  The error is "403 (request "RESOURCE_REQUIRES_ACCESS_LIST") This resource requires access through an access list of ip ranges."  That means the Atlas API Key you are using needs an accesslist entry for where you are running Terraform from.

**Comment by elopsod** [comment]
hi @themantissa 
I don't understand how an API key that can create and delete entire clusters needs additional access list whitelisting to then modify the backup policy of said clusters.
doesn't it seem strange to you?

**Comment by themantissa** [comment]
@elops-od Appreciate the feedback.  I've passed this on to the team who owns it.

**Comment by daroga0002** [comment]
exactly same issue which tottally breaking this provider in real case use cases

**Comment by themantissa** [comment]
@daquinoaldo  please see an earlier comment when we closed this issue: "Version 1.0.0 is out with a complete rework of the cloud backup schedule policy. Details can be found in the upgrade guide and docs. Hope this solves some the of issues but feedback is welcome both here or send to me directly - melissa.plunkett@mongodb.com"  If you find the rework is not solving the issue please feel free to reach out.

**Comment by YusDyr** [comment]
The problem still exists in v1.3.1:
```
Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding latest version of mongodb/mongodbatlas...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/random v3.3.1...
- Installed hashicorp/random v3.3.1 (signed by HashiCorp)
- Installing mongodb/mongodbatlas v1.3.1...
- Installed mongodb/mongodbatlas v1.3.1 (signed by a HashiCorp partner, key ID 2A32ED1F3AD25ABF)
...
Terraform will perform the following actions:
  # mongodbatlas_cloud_backup_schedule.schedule will be created
  + resource "mongodbatlas_cloud_backup_schedule" "schedule" {
      + cluster_id               = (known after apply)
      + cluster_name             = "dmsc-theforce-sandbox"
      + id                       = (known after apply)
      + id_policy                = (known after apply)
      + next_snapshot            = (known after apply)
      + project_id               = "xxx"
      + reference_hour_of_day    = 8
      + reference_minute_of_hour = 45
      + restore_window_days      = 5
      + update_snapshots         = (known after apply)
    }
...
Error: error creating a Cloud Backup Schedule: error deleting MongoDB Cloud Backup Schedule (dmsc-theforce-sandbox): DELETE https://cloud.mongodb.com/api/atlas/v1.0/groups/619556868cad6a3ed2d10582/clusters/dmsc-theforce-sandbox/backup/schedule: 403 (request "RESOURCE_REQUIRES_ACCESS_LIST") This resource requires access through an access list of ip ranges.
  with mongodbatlas_cloud_backup_schedule.schedule,
  on main.tf line 89, in resource "mongodbatlas_cloud_backup_schedule" "schedule":
  89: resource "mongodbatlas_cloud_backup_schedule" "schedule" {
```

**Comment by themantissa** [comment]
@YusDyr this is not related to this issue.  Your issue is that you do not have an API key access list configured with the IP from where you are running Terraform.  Note the error "403 (request "RESOURCE_REQUIRES_ACCESS_LIST") This resource requires access through an access list of ip ranges.".  Add the IP and you should be fine.

**Comment by YusDyr** [comment]
@themantissa , I'm afraid it does related.
I first added `0.0.0/0` into _Project_ -> _Security_ -> _Network Access_ and it didn't help.
Also check the messages above, they have the same problem (ok, at least the same message) even after they made the same steps as I did.

**Comment by themantissa** [comment]
You are missing a 0, should be 0.0.0.0/0 and it would better - for your security - to do an IP or CIDR.  It is the IP address, not any of the issues we had as we've utterly redone cloud backup.

**Comment by YusDyr** [comment]
> You are missing a 0, should be 0.0.0.0/0 and it would better - for your security - to do an IP or CIDR

That's a mistype here, I typed it correctly in the form.
I rechecked it once more and got the same error.

> not any of the issues we had as we've utterly redone cloud backup.

You must be kidding. There is at least 4 messages over here with the same problem.

**Comment by themantissa** [comment]
@YusDyr ah, thought it might be but if not that would obviously have been it.  The error is due to the IP access list for your API key.  If you try putting the direct IP and it still doesn't work perhaps you can open an Atlas support ticket to get further help.  

The original issue here is around the cloud backup resource, it was re-architected to address the issues.  Somehow this also became an issue where some have reported running into IP access list issues with the API key access list. That is not related to this issue other than they are both about backup.  The access list is nothing within the realm of the provider itself.   And note, the IP access list for the API key is different than the Project IP access list.  Make sure you have access set up for the API key you are using.  Backup is one of the endpoints that requires the access list to exist.

**Comment by YusDyr** [comment]
@themantissa, I'll check it, but I do all other cluster(s) configuration with the same API key. It seems strange that I can't change with it a backup schedule only.

**Comment by themantissa** [comment]
Agree, it's a bit odd that one of the endpoints requiring an access list is the backup schedule. I've shared that feedback internally but will do so again.

**Comment by HarrisonKeeling** [comment]
> And note, the IP access list for the API key is different than the Project IP access list. Make sure you have access set up for the API key you are using. Backup is one of the endpoints that requires the access list to exist.

This was the key here for me... I didn't have an IP whitelist setup for the API key and needed to provide one

**Comment by leo-ferlin-sutton** [comment]
👋 Hi!

Encountered the same issue here.

Feels very weird an api can create projects/cluster/network-peering/database-users without IP whitelisting, but can't delete the default backup schedule (to replace it with a new one).

So +1 I guess :)

**Comment by davidsonsilvadev** [comment]
Hi!!
Today i had the same problem. So i created a new custom agent running in my AKS. I got the output CIDR block and put there.
It's fixed it.

Obs: some people confuse the correct place. We need to go in:
Access Manager -> APÌ Keys -> Private Key & Access List

![image](https://user-images.githubusercontent.com/26461881/209564805-b84901c1-af88-4837-a645-4369f051cd00.png)



Tks!
