### ISSUE TITLE
[Bug]: Documentation issue

### ISSUE THREAD

**Issue by AdamMAtWork** [mongodb/terraform-provider-mongodbatlas#2240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.16.0

### Terraform Version

n/a

### Terraform Edition

Terraform Enterprise

### Current Behavior

In the [reference documentation](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster#replication_specs), **num_shards** is labelled as (Required) but the description says to omit the value when cluster_type is REPLICASET.

When applying a cluster_type of REPLICASET, if num_shards is omitted, the following error is produced:

```
 Error: Provider produced invalid plan

 Provider "registry.terraform.io/mongodb/mongodbatlas" planned an invalid value for
 module.mongodb_contiguous_cluster.module.contiguous_cluster.mongodbatlas_advanced_cluster.replicaset.replication_specs[0].num_shards: planned value cty.NumberIntVal(1) for a non-computed attribute.

 This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

I'd like to create a non-sharded, REPLICASET cluster, but the documentation is misleading.

### Terraform configuration to reproduce the issue

```shell
TBD
```

### Steps To Reproduce

TBD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by marcosuma** [comment]
Thanks for opening this issue with us @AdamMAtWork , let me have a look at it and get back to you.

**Comment by marcosuma** [comment]
I've did a quick test and created

```
resource "mongodbatlas_advanced_cluster" "this" {
  project_id                     = var.project_id
  name                           = "advanced-cluster-0"
  mongo_db_major_version         = "6.0"
  termination_protection_enabled = false
  cluster_type                   = "REPLICASET"

  replication_specs {
    region_configs {
      electable_specs {
        instance_size = "M10"
        node_count    = 3
      }
      analytics_specs {
        instance_size = "M10"
        node_count    = 1
      }
      provider_name = "AWS"
      priority      = 7
      region_name   = "US_EAST_1"
    }
  }
}
```

and verified that num_shards is effectively not needed and that the creation succeeds.
I haven't investigated about your error, but I am assuming you tried to specify the num_shards field for a REPLICASET and you got that error.

You are correct the documentation should be updated and be more clear.
Let me take an action at it.
