### ISSUE TITLE
How to create a custom db role using built-in and connection action

### ISSUE THREAD

**Issue by vrathore18** [mongodb/terraform-provider-mongodbatlas#226]
I am facing an issue. Right now, in my atlas mongo cluster I need to set a user with permission 

readwrite@test-db.app
read@test-db.app-config
collmod@test-db.app

How can I combine above scenario in custom db role. Because one is build-role and second is collection action.

**Comment by themantissa** [comment]
@vrathore18 this issue section is for Terraform bug reporting.  If you have general Atlas or Terraform questions please reach out to Atlas support.
