### ISSUE TITLE
Can't create alerts with using many event_type 

### ISSUE THREAD

**Issue by rafafalves** [mongodb/terraform-provider-mongodbatlas#232]
Hi,
I'm trying create alerts from many different event_types using version 0.5.1, but just the type OUTSIDE_METRIC_THRESHOLD is working.
If I try any other type from Host, Replica Set or Billing groups, I received an error message like this:
REMOVED BY ADMIN

Creating any alert with OUTSIDE_METRIC_THRESHOLD parameter and trying change the configuration to met with desired other type, terraform return that changes was applied but looking in portal changes was not made.

Already tried configuration like this for all event_types that are returning error:

resource "mongodbatlas_alert_configuration" "test4" {
  project_id = var.id_project
  event_type = "UPGRADED"
  enabled    = true

  notification {
    type_name     = "SLACK"
    interval_min  = 5
    delay_min     = 0
    api_token     = var.slack_token
    channel_name  = var.slack_channel
  }
}

Also tried change the values that I'm passing from variable to "clear value" in code ans the error are the same

**Comment by rafafalves** [comment]
Another point that I forgot to comment in post. paramters from HOST group that appear in documentatino with HOST_, not work even trying make a change. If removed HOST_ and let just desired option like in the configuration example, I can make a change from OUTSIDE_METRIC_THRESHOLD type to new one. (UPGRADED, RESTARTED, NOW_SECONDARY and NOW_PRIMARY).
Anyway, the changes are not completed looking at the portal.

**Comment by themantissa** [comment]
@rafafalves  thank you for the information.  Issue #227  is similar and we are looking into the best course of action.   Will update as more info

**Comment by themantissa** [comment]
@rafafalves apologies for the length of time to resolution here but wanted to assure you and anyone else that we are working on this and will post updates as we have them.

**Comment by themantissa** [comment]
@rafafalves just an end of week update - we are updating the list of what is/isn't available as alerts in Atlas and then will update the provider that should correct the behavior you are seeing.   In the mean time let me know if you have any specific questions.

**Comment by PacoDw** [comment]
Hello @rafafalves, I created a PR implementing the threshold attribute if you want to check more details or play with the new feature see the PR #298.

Let me know if you have another comment or concern, thanks

**Comment by themantissa** [comment]
@rafafalves  we've released a preview version that should allow you to test if this fixes the issue.  If you can confirm we'd appreciate it.
https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/0.6.4

**Comment by languitar** [comment]
@rafafalves I hope you have changed the API token after this report ;-)

**Comment by themantissa** [comment]
@rafafalves please make sure you change your API token!  Thank you for noticing that @languitar - I'll remove the image from the post.

**Comment by rafafalves** [comment]
Hi,

Sorry for late response. I'm not working anymore with this part of project, but I noticed that the new responsible team was able to create the alerts now.
Also I sent the image that contains the API key and asked then to check and check the key if necessary, tks @languitar and @themantissa.
With this, I'm closing the ticket.
Thanks for the support
