### ISSUE TITLE
Cannot import mongodbatlas_database_user if username contains a hyphen

### ISSUE THREAD

**Issue by MontgomeryWatts** [mongodb/terraform-provider-mongodbatlas#234]
I was trying to import a mongodbatlas_database_user where the username is `lambda-producer`. I used a hyphen in the name to be in line with the [example usage](https://www.terraform.io/docs/providers/mongodbatlas/r/database_user.html#example-usages) but when running `terraform import mongodbatlas_database_user.producer_user <PROJECT-ID>-lambda-producer-admin` it's clear from the output that it is interpreted as the username being `lambda` and the auth_database_name being `producer-admin`. The [import section](https://www.terraform.io/docs/providers/mongodbatlas/r/database_user.html#import) shows an example with a username that contains an underscore. 

Since the documentation claims that syntax works but doesn't,  could the docs be changed to show usernames with underscores, or is this broken functionality?

**Comment by themantissa** [comment]
@MontgomeryWatts it's a known bug, reported and corrected and should be included in our next version release but already available in our master branch.   See https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/179 and https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/214

Thanks!
Melissa

**Comment by FirozAlam-az** [comment]
@themantissa - In which version this is included? I cannot find this in latest release - https://github.com/hashicorp/terraform/releases

**Comment by themantissa** [comment]
That is the main Terraform Changelog. Each provider has its own and the
Atlas one is here:
https://github.com/terraform-providers/terraform-provider-mongodbatlas/blob/master/CHANGELOG.md

**Comment by enm10k** [comment]
@themantissa 

Apparently I still have the same issue, although I'm using `v0.6.4`.

```
$ terraform init -v
Terraform v0.12.24
+ provider.mongodbatlas v0.6.4

Your version of Terraform is out of date! The latest version
is 0.13.2. You can update by downloading from https://www.terraform.io/downloads.html
```

> See https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/179 and https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/214

I want to check the issue and the PR but it's not reachable anymore.
Could you let me know where I can access the information?

**Comment by themantissa** [comment]
@enm10k apologies, as part of the Terraform .13 provider changes we had to move back to a MongoDB repo in Github.  The new links are:
See https://github.com/mongodb/terraform-provider-mongodbatlas/issues/179 and https://github.com/mongodb/terraform-provider-mongodbatlas/pull/214

**Comment by enm10k** [comment]
Thanks for you quick response!

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/database_user#import
> Import
> Database users can be imported using project ID and username, in the format project_id-username-auth_database_name, e.g.

After reviewing the information, I realized I misunderstood about `auth_database_name`.
I specified the actual database name with a hyphen and got an error like the following.

```
$ terraform import mongodbatlas_database_user.a_database_user <project_id>-user-name-database-name
mongodbatlas_database_user.a_database_user: Importing from ID "<project_id>-user-name-database-name"...

Error: import format error: to import a Database User, use the format {project_id}-{username}-{auth_database_name}
```

`terraform import mongodbatlas_database_user.a_database_user '<project_id>-user-name-$external'` worked for me.
Thanks again!

**Comment by themantissa** [comment]
@enm10k glad to hear you are good to go!   Let us know if anything else comes up.   Thanks!
