### ISSUE TITLE
Updating Snapshot Backup Policy: This resource requires access through a whitelist of ip ranges.

### ISSUE THREAD

**Issue by h3yduck** [mongodb/terraform-provider-mongodbatlas#235]
Hello,

I'm trying to update the cluster's backup policy via terraform.

I'm getting this error, even though access is allowed from anywhere (and whitelist shouldn't affect this API endpoint as far as I understand):
`
Error: error updating a Cloud Provider Snapshot Backup Policy: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/.../clusters/.../backup/schedule: 403 (request "Forbidden") This resource requires access through a whitelist of ip ranges.
`

It's working seamlessly on the Web UI. What do I miss?

Thanks in advance.

**Comment by themantissa** [comment]
@h3yduck that error is for when the API key requires a whitelist entry.  There are both project ip whitelists and API key whitelists.   If you edit the API key you are using you can add an appropriate IP or CIDR.

**Comment by h3yduck** [comment]
That was the problem, thank you!

The strange thing for me is that I could create a cluster and users for that cluster without explicitly whitelisting my IP address (there weren't any whitelist entries on the API key), but I couldn't update the whitelist schedule.

Is this the desired behavior?

**Comment by themantissa** [comment]
It is the current behavior but I think there's room for improvement in both what requires an IP Whitelist for the API key and where it's documented.  I'll follow up on that but thank you for confirming that was the issue @h3yduck !

**Comment by gvilarino** [comment]
Had the same issue and googled my way back here. @themantissa  I believe it's standard practice to set a warning in the resource docs section, [as the Azure AD provider does here](https://www.terraform.io/docs/providers/azuread/r/service_principal.html)

![image](https://user-images.githubusercontent.com/2538465/83688966-9e865c00-a5c4-11ea-95d1-6e812690549f.png)

That would probably help?

**Comment by themantissa** [comment]
@gvilarino agree, I think some assumptions were made that could be cleared up w/  information on the primary provider configuration page about Atlas' Programmatic API key roles/IP Whitelists.  I'll get something added and we'll improve it as we go.  Always appreciate the input!
