### ISSUE TITLE
Migration guide - `mongodbatlas_teams` to `mongodbatlas_team`

### ISSUE THREAD

**Issue by d-costa** [mongodb/terraform-provider-mongodbatlas#2393]
Is there any documentation regarding the migration of `mongodbatlas_teams` resources to `mongodbatlas_team`?
We have multiple such resources within modules and need a way to migrate without disrupting teams' access.

Does the `team_id` change?

**Comment by AgustinBettati** [comment]
Hi @d-costa.

You can reference to the [v1.16.0 migration guide](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/guides/1.16.0-upgrade-guide). Here you will find a section within deprecations which gives more details for transitioning to `mongodbatlas_team` resource.

Underlying implementations of the resources are the same, so `team_id` will remain the same.

Feel free to reopen if you have any remaining doubts to clarify.
