### ISSUE TITLE
[Bug]: Fields marked as sensitive unnecessarily?

### ISSUE THREAD

**Issue by throwaway58383958484** [mongodb/terraform-provider-mongodbatlas#2397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.17.3

### Terraform Version

v1.9.1

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

On the `mongodbatlas_x509_authentication_database_user` resource, the fields `current_certificate` and `customer_x509_cas` are marked as sensitive ([code](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/2288b94e681bca3ac03c546b6db9fa7dc372ccc0/internal/service/x509authenticationdatabaseuser/resource_x509_authentication_database_user.go#L57-L68)). From my understanding, these values are not actually sensitive/secret. Is there context here that I'm missing?

We have internal tooling that blocks committing secrets to Terraform state, and we currently make an exception for this resource, but if it's true that these don't need to be sensitive, and they were no longer marked as such, then we could remove the exception.

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_x509_authentication_database_user" "user" {
  project_id = "..."
  customer_x509_cas = "..."
}
```

### Steps To Reproduce

Run a plan: the `customer_x509_cas` attribute is considered sensitive and is redacted in the plan.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgustinBettati** [comment]
Hello @throwaway58383958484.

Some details regarding both attributes:
- `current_certificate`: As mentioned in the [terraform docs](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/x509_authentication_database_user#current_certificate) and [API docs](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/X.509-Authentication/operation/createDatabaseUserCertificate), this attribute stores a PEM file that contains the user's X.509 certificate and private key. Given the presence of the private key marking the attribute as sensitive would be accurate. 
- `customer_x509_cas`: For this case I will have to double check with the team and underlying API to verify if we can consider as non-sensitive.

Will let you know once we have updates.
