### ISSUE TITLE
Add MongoDB Collection Data Source

### ISSUE THREAD

**Issue by apolloclark** [mongodb/terraform-provider-mongodbatlas#250]
It would be helpful to enable HCL2 code to read from a MongoDB Collection during a Terraform Run.

**Comment by themantissa** [comment]
Hi @apolloclark, Thank you for the post.  We use the issues section for bug reports - feature requests can be made at our Feedback Portal: https://feedback.mongodb.com/forums/924145-atlas?category_id=370723.  If you can expand on your use case with the request there that helps a great deal.  Thank you!
