### ISSUE TITLE
[Bug]: EmptyStaticCreds error when using public_key and private_key as Static Credentials 

### ISSUE THREAD

**Issue by TeodorSst** [mongodb/terraform-provider-mongodbatlas#2560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.18.1

### Terraform Version

1.9.5

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Provider throws an error ```EmptyStaticCreds: static credentials are empty``` even though static credentials are provided - private_key and public_key. After hours of troubleshooting and reverse engineering in the provider's code I found out that if environment variable **ASSUME_ROLE_ARN** is set, the provider still assumes that should authenticate with the [AWS Secrets Manager](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs#aws-secrets-manager) method.

This is an issue in the documentation and the implementation as provider has assume_role block and if it is not set, it shouldn't use environment variables.

When **ASSUME_ROLE_ARN** is removed from the environment variables or set to empty it is working.

There is the providers implementation to read from environment variable - https://github.com/mongodb/terraform-provider-mongodbatlas/blob/v1.18.1/internal/provider/provider.go#L325

### Terraform configuration to reproduce the issue

```hcl
locals {
  mongoatlas_public_key  = jsondecode(data.aws_secretsmanager_secret_version.mongodb.secret_string)["public_key"]
  mongoatlas_private_key = jsondecode(data.aws_secretsmanager_secret_version.mongodb.secret_string)["private_key"]
}

provider "mongodbatlas" {
  public_key  = local.mongoatlas_public_key
  private_key = local.mongoatlas_private_key
}
```

### Steps To Reproduce

1. Set environment variable ASSUME_ROLE_ARN with some value.
2. configure mongodbatlas provider with static credentials (private_key and public_key)
3. Plan

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EspenAlbert** [comment]
Hi @TeodorSst . Sorry we didn't get back to you within two weeks.
~~It looks like what you are trying to do is not supported by any provider (using data sources to configure providers).
You need a step to download the variables from the AWS secret and then use those to configure the provider.
Alternatively, you can configure the provider directly. See [documentation here](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs#aws-secrets-manager)~~

*Update: I see now that you were asking more about the side effects of having an `ASSUME_ROLE_ARN` set. I think we will leave this as is as you were unfortunate to stumble into this edge case
