### ISSUE TITLE
[Bug]: 1.19.0 breaks compatibility with Mongo 5.x

### ISSUE THREAD

**Issue by KeithTreagueParaport** [mongodb/terraform-provider-mongodbatlas#2586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.19.0

### Terraform Version

v1.3.7

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

The latest point release of the mongo terraform provider "Supports change_stream_options_pre_and_post_images_expire_after_seconds attribute" however Mongo 5.x does not support that arg. This causes a failure when attempting to deploy. 
Since this breaks compatibility, this should be a major version release. Alternatively it should support mongo 5.x as it's still a supported atlas mongo version for a little bit yet. 

### Terraform configuration to reproduce the issue

```hcl
Attempt to deploy a mongo 5.x database
```

### Steps To Reproduce

Attempt to deploy a mongo 5.x database

### Logs

```txt
400 (request "PROCESS_ARG_NOT_SUPPORTED") Process arg not supported by version 5.0.28
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maastha** [comment]
Thanks @KeithTreagueParaport for bringing this to our attention. We have merged the fix for this issue and it will be available in our next release.

**Comment by jiggyjigsj** [comment]
Hi @maastha Is there is expected release date? We are in middle of an major version upgrade from `5.x` and its causing our terraform to fail.

We have been able to bypass the issue by configuring `ignore_changes` on `lifecycle` to ignore `advanced_configuration`, but its not the most elegant solution.

**Comment by maastha** [comment]
Hi @jiggyjigsj 

This is expected to release by end of week or early next week.

**Comment by lucasr-psq** [comment]
@maastha any updates on this?
