### ISSUE TITLE
[Bug]: customer_endpoint_dns_name is a required param for mongodbatlas_privatelink_endpoint_service_data_federation_online_archive

### ISSUE THREAD

**Issue by vkakde-discovery** [mongodb/terraform-provider-mongodbatlas#2587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.19.0

### Terraform Version

1.5.7

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Terraform doc lists "customer_endpoint_dns_name" attribute as optional, but seems it's required. 

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/privatelink_endpoint_service_data_federation_online_archive

Without this attribute, terraform plan succeeds but apply fails with below - 
Detail: Invalid attribute region specified. Reason: Bad Request. Params: [region]

### Terraform configuration to reproduce the issue

```hcl
-
```

### Steps To Reproduce

Apply resource without "customer_endpoint_dns_name" attribute

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EspenAlbert** [comment]
Hi @vkakde-discovery 
Can you double-check that it is not the `region` from which you were getting an error?

We are running tests in our CI nightly, and one of our [tests](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/26436b9c1f1bbd764383cba8e98883eb2fbbb325/internal/service/privatelinkendpointservicedatafederationonlinearchive/resource_privatelink_endpoint_service_data_federation_online_archive_test.go#L181-L182) doesn't use the `customer_endpoint_dns_name` attribute

**Comment by EspenAlbert** [comment]
Hi again @vkakde-discovery .
I'll close this issue; if you still have problems, please re-open it.
