### ISSUE TITLE
[Bug]: oplog_min_retention_hours doesn't accept decimal number like 2.5

### ISSUE THREAD

**Issue by SymbioticKilla** [mongodb/terraform-provider-mongodbatlas#2594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.19

### Terraform Version

1.9

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Hi,

oplog_min_retention_hours doesn't support decimal numbers.

Atlas UI supports them:
![image](https://github.com/user-attachments/assets/2888b7c8-5ec4-46b1-90d8-9c97ed633140)

Thank you!

### Terraform configuration to reproduce the issue

```hcl
oplog_min_retention_hours = 2.5
```

### Steps To Reproduce

oplog_min_retention_hours = 2.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EspenAlbert** [comment]
Hi @SymbioticKilla .
Thank you for the clear issue description.
This has been fixed in #2604 
We will hopefully release a new version this week so you can start using decimal values by the end of the week 😁

**Comment by EspenAlbert** [comment]
Hi again @SymbioticKilla 
This is now released in 1.20.0! Please test it out 😁
