### ISSUE TITLE
In recommendations, prevent export of keys appearing in OS history

### ISSUE THREAD

**Issue by pkdone** [mongodb/terraform-provider-mongodbatlas#261]
In [MongoDB Atlas Provider](https://www.terraform.io/docs/providers/mongodbatlas/index.html) landing page (also in README of this project)...

For section:

```
Usage:

$ export MONGODB_ATLAS_PUBLIC_KEY="xxxx"
$ export MONGODB_ATLAS_PRIVATE_KEY="xxxx"
$ terraform plan
```

Change to: 

```
Usage (prefix the export commands with a space to avoid the keys being recorded in OS history):

$  export MONGODB_ATLAS_PUBLIC_KEY="xxxx"
$  export MONGODB_ATLAS_PRIVATE_KEY="xxxx"
$ terraform plan
```

As a result, running `history` afterwards from a new terminal session will not show the values of the keys.

**Comment by themantissa** [comment]
@pkdone a good suggestion, I'll add this in a small PR and have you review.

**Comment by themantissa** [comment]
https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/263 < @pkdone take a look, pretty small so quick to add

**Comment by themantissa** [comment]
Completed.
