### ISSUE TITLE
[Bug]: error reading MongoDB EventTriggers

### ISSUE THREAD

**Issue by lacco** [mongodb/terraform-provider-mongodbatlas#2610]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.19.0

### Terraform Version

v1.6.6

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

From one day to another, `terraform apply` stopped working in multiple of our projects without making relevant changes to it.

We manage our app service triggers through terraform,
and now see the following error:

```
Error: error reading MongoDB EventTriggers (5e8740ef453beb52f8e7efd2)65940945fc50022fd5d2c55b: GET https://realm.mongodb.com/api/admin/v3.0/groups/5e8740ef453beb52f8e7efd2/apps/65940945fc50022fd5d2c55b/triggers/65941c750af8f6fd40d17770: 401 (request "") 
```

It looks like there are many deprecations right now related to MongoDB App Services,
[including a domain deprecation for `realm.mongodb.com`](https://www.mongodb.com/docs/atlas/app-services/domain-migration/).

### Terraform configuration to reproduce the issue

```hcl
data "mongodbatlas_project" "default" {
  name = var.mongodb_project_name
}

resource "mongodbatlas_event_trigger" "events" {
  app_id                      = var.mongodb_app_id
  config_collection           = var.mongodb_events_collection
  config_database             = var.mongodb_database
  config_full_document        = true
  config_full_document_before = true
  config_operation_types      = ["INSERT"]
  config_service_id           = var.mongodb_data_source_id
  disabled                    = false
  name                        = "Events"
  project_id                  = data.mongodbatlas_project.default.id
  type                        = "DATABASE"
  unordered                   = false

  event_processors {
    aws_eventbridge {
      config_account_id = var.aws_account_id
      config_region     = var.aws_region
    }
  }
}
```

### Steps To Reproduce

Run `terraform apply` using `mongodbatlas_event_trigger` resource.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amandugar** [comment]
Happening with us also

**Comment by chialunwu** [comment]
realm.mongodb.com is deprecated but it should continue to work (It's not working right now).
<img width="815" alt="Screenshot 2024-09-18 at 12 11 37" src="https://github.com/user-attachments/assets/b5e4aa38-8694-455c-b6c0-9dae579dc9e1">

**Comment by chialunwu** [comment]
@lacco Setting the following for the provider will fix the issue
```
      baseUrl: 'https://cloud.mongodb.com/',
      realmBaseUrl: 'https://services.cloud.mongodb.com/',
```

**Comment by The-Nutty** [comment]
@chialunwu's does not seem to work in terraform but those values can be overridden via environment variables, we have added the following bash before we call terraform plan/apply:
```
export MONGODB_ATLAS_BASE_URL='https://cloud.mongodb.com/'
export MONGODB_REALM_BASE_URL='https://services.cloud.mongodb.com/'
```

**Comment by EspenAlbert** [comment]
Hi @lacco 
It looks like this is due to an incident in the realm upstream dependency.
The workaround by @The-Nutty will work until the upstream resolves the issue. (Thank you 👏 @The-Nutty )

**Comment by piotrj** [comment]
It seems that it is possible to set it on provider level (and not via env variables) by using:
```
provider "mongodbatlas" {
  ...
  realm_base_url = "https://services.cloud.mongodb.com/"
  base_url       = "https://cloud.mongodb.com/"
}
```

**Comment by lacco** [comment]
The issue is resolved, it works for me again.

https://status.mongodb.com/incidents/1xm3z4xzcd4v

**Comment by EspenAlbert** [comment]
Thank you for re-testing. Closing this issue.
