### ISSUE TITLE
[Bug]: mongodbatlas_project_api_key inconsistent plan

### ISSUE THREAD

**Issue by megrehnsf** [mongodb/terraform-provider-mongodbatlas#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.20.0

### Terraform Version

v1.9.3

### Terraform Edition

Terraform Cloud

### Current Behavior

A `mongodbatlas_project_api_key` resource does not properly evaluate existing project_assignment in the plan.

The provider attempts to recreate existing project access and fails on the atlas api with: 
```
╷
│ Error: error assigning api_keys into the project(66f1): https://cloud.mongodb.com/api/atlas/v2/groups/*/apiKeys/* POST: HTTP 400 Bad Request (Error code: "API_KEY_ALREADY_IN_GROUP") Detail: API key is already in the group. Reason: Bad Request. Params: []
│ 
│   with mongodbatlas_project_api_key.project,
│   on main.tf line 116, in resource "mongodbatlas_project_api_key" "project":
│  116: resource "mongodbatlas_project_api_key" "project" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```

---
State show for resource
> terraform state show mongodbatlas_project_api_key.project
```
resource "mongodbatlas_project_api_key" "project" {
    api_key_id  = "*"
    description = "API Key for project-name"
    id          = "*"
    private_key = (sensitive value)
    public_key  = "*"

    project_assignment {
        project_id = "*"
        role_names = [
            "GROUP_OWNER",
        ]
    }
}
```

Plan result

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # mongodbatlas_project_api_key.project will be updated in-place
  ~ resource "mongodbatlas_project_api_key" "project" {
        id          = "*"
        # (4 unchanged attributes hidden)

      + project_assignment {
          + project_id = "*"
          + role_names = [
              + "GROUP_OWNER",
            ]
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

```
Terraform v1.9.3
on linux_amd64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.20.0
```

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_project" "atlas_project" {
  org_id           = <org id string>
  project_owner_id = <owner id string>
  name             = "project-name"

  is_collect_database_specifics_statistics_enabled = true
  is_data_explorer_enabled                         = true
  is_performance_advisor_enabled                   = true
  is_realtime_performance_panel_enabled            = true
  is_schema_advisor_enabled                        = true
  with_default_alerts_settings                     = false
}

resource "mongodbatlas_project_api_key" "project" {
  description = "API Key for project-name"

  project_assignment {
    project_id = mongodbatlas_project.atlas_project.id
    role_names = ["GROUP_OWNER"]
  }
}
```

### Steps To Reproduce

1.  Add `mongodbatlas_project` and `mongodbatlas_project_api_key` in the same terraform
2. Plan
3. Apply, resources created
4. Plan, project_access change proposed
5. Apply, Atlas api error returned: `API_KEY_ALREADY_IN_GROUP`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maastha** [comment]
Hi @megrehnsf 

Thank you for reaching out to us. I am not able to reproduce this issue. I tried with the configuration shared and below was the result of `terraform state show` (same as yours):

```
>terraform state show mongodbatlas_project_api_key.project

# mongodbatlas_project_api_key.project:
resource "mongodbatlas_project_api_key" "project" {
    api_key_id  = "xx"
    description = "API Key for project-name"
    id          = "YXBpX2tleV9pZA==:NjZmZTZmY2RmM2JlODE1MjlkZGVhZjE4"
    private_key = (sensitive value)
    public_key  = "xxxxxx"

    project_assignment {
        project_id = "xxxxxxxxxxxxxxxxxxxxxxx"
        role_names = [
            "GROUP_OWNER",
        ]
    }
}
```

After the resource was created, I ran `terraform plan` again and no drift was detected:

```
mongodbatlas_project_api_key.project: Refreshing state... [id=YXBpX2tleV9pZA==:NjZmZTZmY2RmM2JlODE1MjlkZGVhZjE4]

No changes. Your infrastructure matches the configuration.

```

**Comment by spencer-langley** [comment]
I'm encountering this issue as well. (Using provider version 1.20.0 with Terraform v1.9.5)

Plan shows the key will be updated in place with a new project_assignment, fails on apply because the assignment is already there.

**Comment by megrehnsf** [comment]
@maastha This does still happen to my plan consistently. I've decided to ignore changes on the assignment block for the interim. 
Are you able to provide the atlas api paths so that I can test outside of terraform and attempt to identify the condition on my project api keys which cause this?

**Comment by spencer-langley** [comment]
I also added ignore changes as a work around, but also had to add refresh=false to my plan and apply. However I now need to delete a resource and I'm encountering the error "Error: could not obtain a project id from state: could not obtain a project id as no assignments are defined".

Inspecting state, the underlying issue seems to be that the project_assignment block is not stored in state but is expected by the provider in subsequent operations on the resource.

**Comment by marcosuma** [comment]
Hi @spencer-langley @megrehnsf , I've also tried to reproduce your issue and I didn't manage.
Here's what I did:

```hcl
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "= 1.20.0"
    }
  }
  required_version = "= 1.9.3"
}


resource "mongodbatlas_project" "atlas_project" {
  org_id           = var.org_id
  project_owner_id = var.project_owner_id
  name             = "project-name"

  is_collect_database_specifics_statistics_enabled = true
  is_data_explorer_enabled                         = true
  is_performance_advisor_enabled                   = true
  is_realtime_performance_panel_enabled            = true
  is_schema_advisor_enabled                        = true
  with_default_alerts_settings                     = false
}

resource "mongodbatlas_project_api_key" "project" {
  description = "API Key for project-name"

  project_assignment {
    project_id = mongodbatlas_project.atlas_project.id
    role_names = ["GROUP_OWNER"]
  }
}
```

1. Run `terraform apply` 
2. After creation of 2 resources is confirmed, run `terraform plan`

Detected no changes: `No changes. Your infrastructure matches the configuration.`

Are you able to share with us the `debug.log` when this happens?

**Comment by AgustinBettati** [comment]
Hello @spencer-langley @megrehnsf. 

As part of version 1.21.4 we have introduced some improvements in the `mongodbatlas_project_api_key` resource, specifically avoiding `API_KEY_ALREADY_IN_GROUP` during update operation scenarios.

While I was not able to reproduce the issue mentioned, I would advise to try this new version. 

Lastly, are you aware of what organization permissions are defined in the API key configured in the provider? This will help us narrow down potentially causes. cc @lantoli
