### ISSUE TITLE
[Bug]: mongodbatlas_team membership changes delete all users from team

### ISSUE THREAD

**Issue by spencer-langley** [mongodb/terraform-provider-mongodbatlas#2680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.20.0

### Terraform Version

v1.8.2

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

Whenever the team members on a mongodbatlas_team resource are changed, the provider seems to remove the entire old set of members before adding the entire new set of members. This would be only a minor inconvenience of momentarily removing access from users before restoring, but the api does not support empty teams. As a result every time team membership is changed an apply ends trying to remove the last team member and cannot continue. The only workaround I've found is to manually match team membership to the Terraform templates before apply.

The provider should detect which specific users to add and remove, not modify the team membership of unchanged members, and add new members before removing old ones to avoid the server side error.

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_team" "devs" {

  org_id    = var.atlas_org_id
  name      = "devs"
  usernames = toset(["user1@email.com", "user2@email.com"])
}
```

### Steps To Reproduce

Add and new email address to the list of users and remove an existing one, leaving one unchanged.

Apply will fail attempting to remove the last user from the team.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgustinBettati** [comment]
Hello @spencer-langley, details of existing fix and additional considerations of this issue are captured in https://github.com/mongodb/terraform-provider-mongodbatlas/issues/2662. Feel free to leave a comment there if you have any follow up questions.
