### ISSUE TITLE
[Bug]: Terraform resource forDatabase Creation is not available under cluser collection

### ISSUE THREAD

**Issue by srikanth2302** [mongodb/terraform-provider-mongodbatlas#2681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

v1.21.1

### Terraform Version

v1.9.7

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

There is no resource available in the mongodb atlas provider to create a database in the given cluster and collection

### Terraform configuration to reproduce the issue

```hcl
NA
```

### Steps To Reproduce

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lantoli** [comment]
hi @srikanth2302 , thanks for your opening this issue.  Feel free to upvote this proposal or add a new one: https://feedback.mongodb.com/forums/924145-atlas/suggestions/40066732-create-databases-and-collections-via-api-thorough

thanks.
