### ISSUE TITLE
[Bug]: Error: mongodbatlas_cloud_backup_schedule.xxx[0].export: attribute representing nested block must not be unknown itself; 

### ISSUE THREAD

**Issue by ravi-prajapati** [mongodb/terraform-provider-mongodbatlas#2697]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Provider Version

v1.17.5

### Terraform Version

v1.0.11

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

After upgrading atlas provider version to v1.17.5, the `mongodbatlas_cloud_backup_schedule` resource is failing. Using this resource enable auto export snapshot on S3 bucket based on condition. 

>   auto_export_enabled = local.enable_export_s3_snapshot > 0 ? true : false
  dynamic "export" {
    for_each = local.enable_export_s3_snapshot > 0 ? [1] : []
    content {
      export_bucket_id = mongodbatlas_cloud_backup_snapshot_export_bucket.mongo-provider-export-bucket[count.index].export_bucket_id
      frequency_type   = var.MONGODBATLAS_EXPORT_S3_SNAPSHOT_FREQUENCY
    }
  }
  
  So when condition is `false` then failing with following error 
  

> ╷
│ Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/mongodb/mongodbatlas" planned an invalid
│ value for
│ module.mongodb.mongodbatlas_cloud_backup_schedule.mongodb_backup_schedule[0].export:
│ attribute representing nested block must not be unknown itself; set nested
│ attribute values to unknown instead.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵

Also remove complete block for `export` along with `auto_export_enabled` but still failing with this error.

> │ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.mongodb.mongodbatlas_cloud_backup_schedule.mongodb_backup_schedule[0], provider "module.mongodb.provider[\"registry.terraform.io/mongodb/mongodbatlas\"]"
│ produced an unexpected new value: .export: block count changed from 1 to 0.

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_cloud_backup_schedule" "mongodb_backup_schedule" {
  count        = local.enable_schedule_backup
  project_id   = local.MONGODB_PROJECT_ID
  cluster_name = mongodbatlas_cluster.mongodb_cluster[count.index].name

  dynamic "policy_item_hourly" {
    for_each = var.MONGODBATLAS_BACKUP_POLICY_ITEM_HOURLY_LIST
    content {
      frequency_interval = policy_item_hourly.value.frequency_interval
      retention_unit     = policy_item_hourly.value.retention_unit
      retention_value    = policy_item_hourly.value.retention_value
    }
  }

  dynamic "policy_item_daily" {
    for_each = var.MONGODBATLAS_BACKUP_POLICY_ITEM_DAILY_LIST
    content {
      frequency_interval = policy_item_daily.value.frequency_interval
      retention_unit     = policy_item_daily.value.retention_unit
      retention_value    = policy_item_daily.value.retention_value
    }
  }

  dynamic "policy_item_weekly" {
    for_each = var.MONGODBATLAS_BACKUP_POLICY_ITEM_WEEKLY_LIST
    content {
      frequency_interval = policy_item_weekly.value.frequency_interval
      retention_unit     = policy_item_weekly.value.retention_unit
      retention_value    = policy_item_weekly.value.retention_value
    }
  }

  dynamic "policy_item_monthly" {
    for_each = var.MONGODBATLAS_BACKUP_POLICY_ITEM_MONTHLY_LIST
    content {
      frequency_interval = policy_item_monthly.value.frequency_interval
      retention_unit     = policy_item_monthly.value.retention_unit
      retention_value    = policy_item_monthly.value.retention_value
    }
  }

  auto_export_enabled = local.enable_export_s3_snapshot > 0 ? true : false
  dynamic "export" {
    for_each = local.enable_export_s3_snapshot > 0 ? [1] : []
    content {
      export_bucket_id = mongodbatlas_cloud_backup_snapshot_export_bucket.mongo-provider-export-bucket[count.index].export_bucket_id
      frequency_type   = var.MONGODBATLAS_EXPORT_S3_SNAPSHOT_FREQUENCY
    }
  }

  dynamic "copy_settings" {
    for_each = local.enable_snapshot_distribution > 0 ? [1] : []
    content {
      cloud_provider      = "AWS"
      frequencies         = var.MONGODB_COPY_SNAPSHOT_FREQUENCIES
      region_name         = replace(upper(lookup(var.MONGODB_REPLICATION_ZONE, var.STACK_REGION)), "-", "_")
      replication_spec_id = mongodbatlas_cluster.mongodb_cluster[count.index].replication_specs.*.id[0]
      should_copy_oplogs  = var.MONGODB_COPY_OPLOGS
    }
  }
}
```

### Steps To Reproduce

1. The issue occurring with provider 1.17.5 but it' working with 1.11.1 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lantoli** [comment]
thanks @ravi-prajapati for opening the issue.  
Note that we only support Terraform versions supported by Hashicorp, right now it is 1.4.x and above: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs#hashicorp-terraform-versionhttpswwwterraformiodownloadshtml-compatibility-matrix.

Also we only fix the latest version of the Atlas MongoDB provider, the latest published released is currently 1.21.1.

Can you try to use Terraform 1.4.x or above and provider 1.21.1 and see if the error is still hapenning?

Thanks

**Comment by ravi-prajapati** [comment]
> provider 1.21.1 and see if the error is still hapenning?
> 
> Thanks

Thank you @lantoli for you response.

**Comment by amui12345** [comment]
The error is happening for me in mongo provider version 1.21.2 . I am receiving the below error -

 Error: Provider produced invalid plan
│ 
│ Provider "registry.terraform.io/mongodb/mongodbatlas" planned an invalid value for
│ module.mongo_atlas_regtech_cluster.mongodbatlas_cloud_backup_schedule.custom_backup_policy[0].export: attribute representing nested block must not be unknown
│ itself; set nested attribute values to unknown instead.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
