### ISSUE TITLE
Should not need Owner permissions on an API key to plan projects

### ISSUE THREAD

**Issue by evanrappe** [mongodb/terraform-provider-mongodbatlas#2726]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
Please ensure your issue is reproducible on a supported Terraform version. You may review our [Terraform version compatibility matrix](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/docs/index.md#hashicorp-terraform-version-compatibility-matrix) to know more.

```hcl
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.72.1
+ provider registry.terraform.io/hashicorp/random v3.6.3
+ provider registry.terraform.io/ibm-cloud/ibm v1.70.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.21.2
+ provider registry.terraform.io/strongdm/sdm v11.15.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "this" {
  name   = "project1"
  org_id = var.atlas_org_id

  teams {
    team_id    = data.mongodbatlas_team.editors.team_id
    role_names = ["GROUP_OWNER"]
  }

  teams {
    team_id    = data.mongodbatlas_team.viewers.team_id
    role_names = ["GROUP_READ_ONLY"]
  }
}

variable "atlas_org_id" {
  description = "The ID of the organization in Atlas you want to create the project within."
  type        = string
}
```

### Steps to Reproduce

Please be **as detailed as possible.**
* Plan a `mongodbatlas_project` resource using an API keypair with `Organization Read Only` access

### Expected Behavior
Before `is_slow_operation_thresholding_enabled` was added to `mongodbatlas_project` resources in v1.21.2 a read-only key was able to TFplan all Atlas projects and resources. Now it cannot plan any projects. 

### Actual Behavior
Before `is_slow_operation_thresholding_enabled` was added to `mongodbatlas_project` resources in v1.21.2 a read-only key was able to TFplan all Atlas projects and resources. Now it cannot plan any projects. Upgrading the api token to have Owner permissions appears to be the only workaround.

### Additional Context
```
 Error: error when getting project properties after create
│ 
│   with mongodbatlas_project.this,
│   on project.tf line 11, in resource "mongodbatlas_project" "this":
│   11: resource "mongodbatlas_project" "this" {
│ 
│ error getting project (xxxxxxx): error getting project's slow operation thresholding enabled (xxxxxxx): https://cloud.mongodb.com/api/atlas/v2/groups/xxxxxxx/managedSlowMs GET: HTTP 401
│ Unauthorized (Error code: "USER_UNAUTHORIZED") Detail: Current user is not authorized to perform this action. Reason: Unauthorized. Params: [], BadRequestDetail: 
```

### References
https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/v1.21.2
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CHANGELOG.md
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project#is_slow_operation_thresholding_enabled

**Comment by lantoli** [comment]
thanks @evanrappe for opening the issue. 

We've just released v1.21.3, the issue is fixed there. 

Sorry for the inconvenience, should you have any further question please let us know

**Comment by aprice-sss** [comment]
@lantoli we're seeing the same thing in v1.21.4, is it a regression? User with Project Cluster Manager role cannot execute a plan against a project even though it does not specify `is_slow_operation_thresholding_enabled`, getting error 401 Unauthorized. No issue with v1.18 we were using previously. Docs state "To use this attribute, the requesting API Key must have the Project Owner role, if not it will show a warning and will return false. If you are not using this field, you don't need to take any action." but this does not seem to be accurate.

**Comment by lantoli** [comment]
hi @aprice-sss , there shouldn't be a regression.  Can you send the Terraform version, MongoDB Atlas version (I understand you were using 1.18 and tried 1.21.4), the minimum Terraform file that causes the problem, and some logs with the error? Also can you try with v1.21.2?

thanks

**Comment by lra** [comment]
Hi,

Looks like you made the error a warning, and it's showing up in all our plan/apply logs:
```
│ Warning: user does not have permission to read is_slow_operation_thresholding_enabled. Please read our documentation for more information.
│ 
│   with module.stack.mongodbatlas_project.this,
│   on mongodb.tf line 51, in resource "mongodbatlas_project" "this":
│   51: resource "mongodbatlas_project" "this" {
│ 
│ error getting project (REDACTED):
│ https://cloud.mongodb.com/api/atlas/v2/groups/REDACTED/managedSlowMs
│ GET: HTTP 401 Unauthorized (Error code: "USER_UNAUTHORIZED") Detail:
│ Current user is not authorized to perform this action. Reason:
│ Unauthorized. Params: [], BadRequestDetail: 
```

If you deprecated the attribute, why keeping this warning?

For context:
```
Terraform v1.9.8
on darwin_arm64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.21.4
```

**Comment by lantoli** [comment]
Hi, Terraform only allows error and warning severities, there is not "info" or similar.  
We still wanted to tell the user that the value could be wrong if you don't have permissions, because you can try to read it (e.g. reference it in another result or output) even if you don't set it. 
Deprecated means that it will deleted at some point, but in the meantime it can be used.
Thanks
