### ISSUE TITLE
custom_db_roles cannot be created with only inherited roles

### ISSUE THREAD

**Issue by languitar** [mongodb/terraform-provider-mongodbatlas#279]
In the Atlas UI it is easily possible to create custom_db_roles which are comprised of only inherited roles. However, the resource definition currently requires one to always pass `actions`. Therefore, I don't see a chance to create roles which only use inherited roles such as this example:
![image](https://user-images.githubusercontent.com/1336287/89282658-24b63180-d64c-11ea-8c68-158e8940878f.png)

**Comment by themantissa** [comment]
@languitar thank you for the report - it seems that when custom roles was created the actions was defined as required, https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_custom_db_role.go#L50
but should be optional. Will file a ticket to get this addressed.   Thank you!

**Comment by themantissa** [comment]
See https://github.com/mongodb/terraform-provider-mongodbatlas/issues/280 as well for more around the impact of the behavior.

**Comment by languitar** [comment]
Another aspect of this thing could be the following:
```
      ~ inherited_roles {
          ~ database_name = "history" -> "userdata"
            role_name     = "readWrite"
        }
        inherited_roles {
            database_name = "catalog"
            role_name     = "readWrite"
        }
      ~ inherited_roles {
          ~ database_name = "userdata" -> "cache"
            role_name     = "readWrite"
        }
      ~ inherited_roles {
          ~ database_name = "cache" -> "history"
            role_name     = "readWrite"
        }
```
Seems the sorting wasn't correctly applied in the previous iteration and now this diff reappears everytime.

**Comment by PacoDw** [comment]
Hello, @languitar thank you so much for your review, I made changes resolving this issue could you test it to check if everything is okay? 
Also, let me know if you have another comment or concern, thanks.

**Comment by languitar** [comment]
Thanks for the fix. Are there any plans to generate a release including this fix?

**Comment by themantissa** [comment]
@languitar there are - we plan to cut 0.6.4, hopefully, in Aug (that is pretty soon). We are still finishing up some changes to be able to deploy releases ourselves (a new change for Terraform .13).

**Comment by ranjitrakwal** [comment]
mongodb+srv://cluster0-pl-0.55bl8u.mongodb.net/?authSource=$external&authMechanism=MONGODB-OIDC  link to connect to Mongodb  using individaul users
