### ISSUE TITLE
Set mongodb_major_version with tenant

### ISSUE THREAD

**Issue by MonicaMagoniCom** [mongodb/terraform-provider-mongodbatlas#2800]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.21.4

### Terraform Version

1.9.8

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

I'm trying to create a MongoDB Atlas cluster with GCP and with M5 instances and I would like to specify the mongoDB version. 
But from terraform apply I get:
mongoDBMajorVersion is read-only for tenant clusters

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_advanced_cluster" "test" {
  project_id   = mongodbatlas_project.mongodb-project.id
  name         = var.project
  cluster_type = "REPLICASET"
  replication_specs {
    region_configs {
      electable_specs {
        instance_size = "M5"
        node_count    = 3
      }
      provider_name = "TENANT"
      backing_provider_name = "GCP"
      priority      = 7
      region_name   = "WESTERN_EUROPE"
    }
  }
  mongo_db_major_version = "6"
  backup_enabled = false
}
```

### Steps To Reproduce

terraform apply

### Logs

```txt
error creating advanced cluster:  POST: HTTP 400 Bad Request (Error code: "TENANT_ATTRIBUTE_READ_ONLY") Detail: The attribute mongoDBMajorVersion is read-only for tenant clusters and cannot be changed by the user. Reason: Bad Request. Params: [mongoDBMajorVersion]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maastha** [comment]
Hi @MonicaMagoniCom 

Thank  you so much for reaching out! This is an expected error as users are not allowed to pick the MongoDB version used for TENANT.
Please refer to https://www.mongodb.com/docs/atlas/reference/free-shared-limitations/#configuration-limits for more details.

Closing this issue for now but please feel free to re-open in case of any questions.
