### ISSUE TITLE
Resource mongodbatlas_cloud_backup_snapshot_restore_job is not saved to state file

### ISSUE THREAD

**Issue by MonicaMagoniCom** [mongodb/terraform-provider-mongodbatlas#2804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.21.3

### Terraform Version

v1.9.8

### Terraform Edition

Terraform Open Source (OSS)

### Current Behavior

In my module I create this resource **mongodbatlas_cloud_backup_snapshot_restore_job**

The first time I do 'terraform apply', the resource is created and works correctly. If I do another terraform apply, it is recreated again from scratch. I don't want the restore job to be re-executed everytime I do terraform apply.

### Terraform configuration to reproduce the issue

```hcl
resource "mongodbatlas_cloud_backup_snapshot_restore_job" "mongo-restore-job" {
  project_id     = var.mongo_preprod_project_id
  cluster_name = var.mongo_preprod_cluster_name
  snapshot_id  = data.mongodbatlas_cloud_backup_snapshots.mongo-snapshot.results[0].id
  delivery_type_config {
    automated = true
    download = false
    oplog_inc = 0
    oplog_ts = 0
    point_in_time = false
    point_in_time_utc_seconds = 0
    target_cluster_name = var.project
    target_project_id     = mongodbatlas_project.mongodb-project.id
  }
  depends_on = [data.mongodbatlas_cloud_backup_snapshots.mongo-snapshot]
}
```

### Steps To Reproduce

Run terraform apply at least 2 times

### Logs

```txt
On the second apply the log is:
  # module.mongodb.mongodbatlas_cloud_backup_snapshot_restore_job.mongo-restore-job must be replaced
-/+ resource "mongodbatlas_cloud_backup_snapshot_restore_job" "mongo-restore-job" {
      ~ cancelled               = false -> (known after apply)
      ~ delivery_url            = [] -> (known after apply)
      ~ expired                 = false -> (known after apply)
      + expires_at              = (known after apply)
      ~ finished_at             = "2024-11-18T14:35:43Z" -> (known after apply)
      ~ id                      = "Y2x1c3Rlcl9uYW1l:Y2NzLXByZXByb2QtYmFja3Vw-cHJvamVjdF9pZA==:NjczNzA3ZDdlOTdmODUyYjBiNTk0N2U2-c25hcHNob3RfcmVzdG9yZV9qb2JfaWQ=:NjczYjRmYTJjYjBlNTc1MGQwYTVlMjky" -> (known after apply)
      ~ snapshot_id             = "673b4cdb02c12a42f963b02b" -> (known after apply) # **forces replacement**
      ~ snapshot_restore_job_id = "673b4fa2cb0e5750d0a5e292" -> (known after apply)
      ~ timestamp               = "2024-11-18T14:26:44Z" -> (known after apply)
        # (2 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maastha** [comment]
Hi @MonicaMagoniCom 

From your config, it looks like `snapshot_id  = data.mongodbatlas_cloud_backup_snapshots.mongo-snapshot.results[0].id` may be causing the snapshot_id to change dynamically.

Could you ensure this value doesn't change on subsequent runs?
The `mongodbatlas_cloud_backup_snapshots` data source doesn't guarantee order of snapshots return in case there may be multiple values.

Additionally, can you share the .tfstate content after the first apply?

**Comment by MonicaMagoniCom** [comment]
Is there a way I can get the latest snapshot on the first terraform apply, and then on subsequent run do not restore again even if there is a new snapshot?
