### ISSUE TITLE
[Bug]: DataSource to get all IP Access List added to the project

### ISSUE THREAD

**Issue by srikanth2302** [mongodb/terraform-provider-mongodbatlas#2828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Provider Version

1.21.4

### Terraform Version

v1.9.7

### Terraform Edition

Terraform Cloud

### Current Behavior

Currently we have a datasource that fetches only data when IP is given. I request to provide the datasource to fetch all the IP access list added to the project

MongoDB API: https://cloud.mongodb.com/api/atlas/v1.0/groups/<**PROJECTID**>/accessList

### Terraform configuration to reproduce the issue

```hcl
NA
```

### Steps To Reproduce

NA

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AgustinBettati** [comment]
Hello @srikanth2302. Thank you for raising this issue. 

I can confirm we current have a data source `mongodbatlas_project_ip_access_list` that uses [Return One Project IP Access List Entry](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Project-IP-Access-List/operation/getProjectIpList) returning a single entry, while we do not having any data source exposing [Return Project IP Access List](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Project-IP-Access-List/operation/listProjectIpAccessLists) for returning all entries of a project.

As per our guidance when creating GitHub issues, given that this is a feature request can you please file a request into our [feedback portal](https://feedback.mongodb.com/forums/924145-atlas?category_id=370723)? This will help us prioritise this work. Thank you!
