### ISSUE TITLE
mongo_db_major_version and provider_disk_iops don't stick

### ISSUE THREAD

**Issue by arthurio** [mongodb/terraform-provider-mongodbatlas#29]
Hi,

For some reason, every time I apply my terraform config, it detects a change for `mongo_db_major_version` and `provider_disk_iops` even though I set them explicitly in the configuration. Also, the values on the cluster are correct from the website UI.

```hcl
# main.tf
...
resource "mongodbatlas_cluster" "main" {
  name = "test"
  project_id = mongodbatlas_project.main.id
  mongo_db_major_version = "4.0"
  provider_name = "AWS"
  provider_region_name = upper(replace(var.region, "-", "_"))
  provider_instance_size_name = "M20"
  provider_disk_iops = 100
  backup_enabled = false
}
...
```

```shell
$ terraform apply
# module.sle_staging.mongodbatlas_cluster.main will be updated in-place
  ~ resource "mongodbatlas_cluster" "main" {
        auto_scaling_disk_gb_enabled = true
        backup_enabled               = false
        bi_connector                 = {
            "enabled"         = "false"
            "read_preference" = "secondary"
        }
        cluster_type                 = "REPLICASET"
        disk_size_gb                 = 10
        encryption_at_rest_provider  = "NONE"
        id                           = "[redacted]"
      ~ mongo_db_major_version       = "4.0.11" -> "4.0"
        mongo_db_version             = "4.0.11"
        mongo_uri                    = "[redacted]"
        mongo_uri_updated            = "2019-04-19T22:42:10Z"
        mongo_uri_with_options       = "[redacted]"
        name                         = "[redacted]"
        num_shards                   = 1
        paused                       = false
        project_id                   = "[redacted]"
        provider_backup_enabled      = false
      ~ provider_disk_iops           = 0 -> 100
        provider_encrypt_ebs_volume  = true
        provider_instance_size_name  = "M20"
        provider_name                = "AWS"
        provider_region_name         = "US_WEST_2"
        provider_volume_type         = "STANDARD"
        replication_factor           = 3
        ...
```

**Comment by themantissa** [comment]
@arthurio I think you've discovered two bugs.   @marinsalinas please address the following:

In the Provider for clusters: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/e0a8742a3067a0862d375147949ccb9fb67d3071/mongodbatlas/data_source_mongodbatlas_cluster.go#L228 should refer to cluster.MongoDBMajorVersion and cluster.DiskIOPS seems to be missing.

**Comment by marinsalinas** [comment]
@arthurio @themantissa, `mongo_db_major_version` was a mistake, I'll fix, but here we set `provider_disk_iops` here:

 https://github.com/mongodb/terraform-provider-mongodbatlas/blob/e0a8742a3067a0862d375147949ccb9fb67d3071/mongodbatlas/resource_mongodbatlas_cluster.go#L631

@arthurio, can you run the apply again like this `TF_LOG=DEBUG terraform apply` and post the output here?

**Comment by arthurio** [comment]
@marinsalinas I don't want to share the output publicly, can I share it with you in some other way? Or can you tell me what are you looking for? `provider_disk_iops` doesn't show up in the trace except when it shows the plan to apply.

**Comment by themantissa** [comment]
Ah, totally missed the Set @marinsalinas, thank you for the link.

One other thing to note is that for < M30 provider disk iops sets to the default and is not adjustable - https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ - see 
providerSettings.diskIOPS
An M20 is 100 so it doesn't need to be set and cannot be changed.  Above an M30 and it is dependent on both the cluster size and disk size.

**Comment by arthurio** [comment]
If I remove `provider_disk_iops` now it works but initially it was complaining that it couldn't  be "0" which is why I had to set it.

**Comment by marinsalinas** [comment]
> @marinsalinas I don't want to share the output publicly, can I share it with you in some other way? Or can you tell me what are you looking for? `provider_disk_iops` doesn't show up in the trace except when it shows the plan to apply.

I just want to see if the GET cluster request returns `providerSettings.diskIOPS` as zero, or it returns the proper value.

**Comment by andysnowden** [comment]
> > @marinsalinas I don't want to share the output publicly, can I share it with you in some other way? Or can you tell me what are you looking for? `provider_disk_iops` doesn't show up in the trace except when it shows the plan to apply.
> 
> I just want to see if the GET cluster request returns `providerSettings.diskIOPS` as zero, or it returns the proper value.

I don't mind sharing mine, it is indeed zero

`
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  "name": "pritunl-prod",
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  "numShards": 1,
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  "paused": false,
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  "pitEnabled": false,
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  "providerBackupEnabled": false,
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  "providerSettings": {
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:   "providerName": "AWS",
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:   "diskIOPS": 0,
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:   "encryptEBSVolume": true,
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:   "instanceSizeName": "M10",
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:   "regionName": "US_EAST_1",
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:   "volumeType": "STANDARD"
2019-08-05T17:04:05.878-0400 [DEBUG] plugin.terraform-provider-mongodbatlas:  },
`

**Comment by marinsalinas** [comment]
@themantissa, @andysnowden @arthurio, 

I have to add a validator that if the size is `<M30` then `provider_disk_iops` is non-settable to avoid this problem.

Let me figure out how to do this.

**Comment by arthurio** [comment]
Thanks everyone :)

**Comment by themantissa** [comment]
Thanks all!  I'm also checking internally.  Stay tuned as we purse all the paths, both temp and long term.
