### ISSUE TITLE
Can we create search index using terraform-provider-mongodbatlas?

### ISSUE THREAD

**Issue by vrathore18** [mongodb/terraform-provider-mongodbatlas#308]
I searched a lot but I guess there is no option for creating a search index using terraform-provider-mongodb-index. Could someone please confirm, if so then I will create a request for this feature.

https://docs.atlas.mongodb.com/reference/atlas-search/create-index/

**Comment by nikhil-mongo** [comment]
@vrathore18 This is still not available in Terraform and we will be happy to take the suggestion on our [feedback engine](https://feedback.mongodb.com). However in the meantime, please use the [Atlas API](https://docs.atlas.mongodb.com/reference/api/atlas-search/#atlas-search-api-ref) for creating the search index.

Thanks,
Nikhil

**Comment by MarcusSorealheis** [comment]
We have added Atlas Search support in Terraform: https://docs.atlas.mongodb.com/reference/api/atlas-search/

**Comment by MarcusSorealheis** [comment]
Oops: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs

**Comment by konaganesh555** [comment]
@MarcusSorealheis I would like to create index (Not search index) in MongoDB Atlas. Is there any resource available to create index in mongodb atlas?

**Comment by themantissa** [comment]
@konaganesh555 there is not at this time.   Feel free to suggest this or vote at feedback.mongodb.com.

**Comment by konaganesh555** [comment]
@themantissa Thanks for the confirmation.
I have post my suggestion here https://feedback.mongodb.com/forums/924145-atlas/suggestions/45754828-adding-indexes-not-search-index-using-terraform

**Comment by tyagian** [comment]
Hello, I have created a terraform provider to manage MongoDB indexes
Feel free to give it a try:
https://registry.terraform.io/providers/megum1n/mongodb/latest
