### ISSUE TITLE
Standardize Regions

### ISSUE THREAD

**Issue by nitrag** [mongodb/terraform-provider-mongodbatlas#31]
While in development. Can you please standardize the names for regions? Eg. Discrepency between `mongodbatlas_network_container` and `mongodbatlas_vpc_peering_connection`.

Instead of `US_EAST_1` use `us-east-1`.

**Comment by themantissa** [comment]
Team is working on a solution to make this a little easier.   Standby!

**Comment by marinsalinas** [comment]
@nitrag could you check #37 ?

**Comment by nitrag** [comment]
It works. Thank you.
