### ISSUE TITLE
"mongodbatlas_alert_configuration" prints Slack API token in plain text

### ISSUE THREAD

**Issue by Jeinhaus** [mongodb/terraform-provider-mongodbatlas#310]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform v0.12.27
+ provider.mongodbatlas v0.6.4
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_alert_configuration" "host_down" {
  event_type = "HOST_DOWN"
  project_id = mongodbatlas_cluster.this.project_id

  notification {
    type_name    = "SLACK"
    api_token    =  var.slack_api_token
    channel_name = var.slack_channel_name
    interval_min = 60
  }
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Expected Behavior

Sensitive values (in this case `api_token`) should not be printend when running `terraform plan` or `terraform apply`.

### Actual Behavior

The Slack API token is printed in plain text during when running `terraform plan`:

```hcl
  # mongodbatlas_alert_configuration.host_down will be created
  + resource "mongodbatlas_alert_configuration" "host_down" {
      + alert_configuration_id = (known after apply)
      + created                = (known after apply)
      + enabled                = (known after apply)
      + event_type             = "HOST_DOWN"
      + id                     = (known after apply)
      + project_id             = <redacted>
      + updated                = (known after apply)

      + notification {
          + api_token    =  <redacted>
          + channel_name =  <redacted>

          + interval_min = 60
          + type_name    = "SLACK"
        }
    }

```

**Comment by nikhil-mongo** [comment]
@Jeinhaus Thanks for raising this but currently there is no way to mark the variables as sensitive. This issue is open in the terraform issue list itself. You can check it [here](https://github.com/hashicorp/terraform/issues/16114). Thus, we will have to wait unless terraform provides the `sensitive=true` parameter to the input variables.
