### ISSUE TITLE
Container ID on the cluster data source is always empty

### ISSUE THREAD

**Issue by sdebruyn** [mongodb/terraform-provider-mongodbatlas#314]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
Terraform 0.13.2
mongodbatlas 0.6.4

```hcl
mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "0.6.4"
    }
```

### Terraform Configuration File 
```hcl
data "mongodbatlas_cluster" "admin" {
  name       = var.mongodb_admin_cluster_name
  project_id = var.projectid_admin
}

data "mongodbatlas_network_container" "admin" {
  project_id   = var.projectid_admin
  container_id = data.mongodbatlas_cluster.admin.container_id
}
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Expected Behavior
No errors

### Actual Behavior
Container ID is empty

```
Error: "container_id": required field is not set

  on mongodb_admin.tf line 6, in data "mongodbatlas_network_container" "admin":
   6: data "mongodbatlas_network_container" "admin" {
```

**Comment by nikhil-mongo** [comment]
@sdebruyn  The container-id is available only in two conditions:
- VPC peering is setup.
- A cluster exists in the project in that region.

If neither is the case, the `data` block wont be able to fetch the value and throw error as you are getting now. 

Also, you used `container_id = data.mongodbatlas_cluster.admin.container_id` which is not defined in the data block for the cluster. Therefore, it says it is empty and you can use the below configuration to achieve this.

```
resource "mongodbatlas_cluster" "cluster-test" {
  project_id = var.project_id
  name       = "cluster-test"
  num_shards = 1

  replication_factor           = 3
  provider_backup_enabled      = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.2"
  //Provider Settings "block"
  provider_name               = "AWS"
  disk_size_gb                = 10
  provider_disk_iops          = 100
  provider_volume_type        = "STANDARD"
  provider_encrypt_ebs_volume = true
  provider_instance_size_name = "M10"
  provider_region_name        = "EU_NORTH_1"
}
data "mongodbatlas_network_container" "test" {
  project_id   = mongodbatlas_cluster.cluster-test.project_id
  container_id = mongodbatlas_cluster.cluster-test.container_id
}
data "mongodbatlas_cluster" "cluster-test" {
  name       = mongodbatlas_cluster.cluster-test.name
  project_id = mongodbatlas_cluster.cluster-test.project_id
}
output "container" {
  value = data.mongodbatlas_network_container.test.container_id
}
```

This would give you all the details you need. Let us know if you still need any help.

**Comment by themantissa** [comment]
Hi  @sdebruyn - just checking in to see if the information from @nikhil-mongo solved your issue?  Thanks!

**Comment by themantissa** [comment]
Assuming issue solved, ping if not. Thanks.

**Comment by jpalmerpivotal** [comment]
Hi, following up on this issue as I have a similar issue to the original poster, but also not sure I fully understand the response.

Context: 
I have deployed a cluster through Atlas Web UI, not terraform. 
I have configured a VPC peering with terraform, I was able to get the `container_id` from curling the API.

When I try to retrieve the configuration of the pre-existing cluster, I do 
```
data "mongodbatlas_cluster" "test" {
    project_id = "project-id-string"
    name       = "cluster-name"
}
```

In the `.tfstate` I see all of the fields filled in, but `container_id` is null.

My understanding of your 2 conditions:
```
VPC peering is setup.
A cluster exists in the project in that region.
```
Makes me believe that container_id _should_ be populated.

So I guess my questions are:

1. Is this expected behavior?
2. Is there another way to use `terraform` to discover the `container_id` of an existing cluster?

Thanks

**Comment by themantissa** [comment]
@jpalmerpivotal this some context and steps missing that make this hard to potentially answer correct.  Container_id is a computed value by the terraform provider, not a returned value from the API (https://github.com/mongodb/terraform-provider-mongodbatlas/blob/221ee96e32e3f1c480adde0284386d026919082e/mongodbatlas/resource_mongodbatlas_cluster.go#L384).   We compute it for when someone has created a cluster before they setup peering.  In that case a container already exists so you use that already existing container to create the peering connection.   If your cluster has been properly imported and the data refreshed so the terraform provider knows to compute the value I would expect you to be able to see it (the issue being that the computed value may not happen when imported but I think it would after refresh - I'd have to test it to double check.).   

The two conditions listed are the basics of when a container id already exists, the complexity here is that one action happened in the UI and one via Terraform.  Ensuring all is imported to Terraform and refreshed makes it a different case.

**Comment by jpalmerpivotal** [comment]
Thanks @themantissa I am not importing the Mongo Cluster (yet) as we do not yet want it controlled by terraform, so I only was using the data source. For now my work around of hitting the Mongo api `groups/<GROUP-ID>/containers` and getting the right region will have to suffice until we move the cluster under full Terraform management.
A little disappointed that the `mongodbatlas_cluster` data_source doesn't seem to be able to populate it, but thanks for explaining the issue for me. 
EDIT: Actually I am now pursuing using the `mongodbatlas_network_containers` data_source and just finding the right one so I can handle it all in terraform.

**Comment by themantissa** [comment]
@jpalmerpivotal sounds good and sorry it wasn't quite what you'd hope for but sounds like, with the edit, you are on a good path.  Also fyi the ID in the UI is the peering ID, not the container ID. I think you've already likely figured that out from the edit to the original question but wanted to be sure to clear it up just in case.

**Comment by wkhatch** [comment]
> Thanks @themantissa I am not importing the Mongo Cluster (yet) as we do not yet want it controlled by terraform, so I only was using the data source. For now my work around of hitting the Mongo api `groups/<GROUP-ID>/containers` and getting the right region will have to suffice until we move the cluster under full Terraform management. A little disappointed that the `mongodbatlas_cluster` data_source doesn't seem to be able to populate it, but thanks for explaining the issue for me. EDIT: Actually I am now pursuing using the `mongodbatlas_network_containers` data_source and just finding the right one so I can handle it all in terraform.

How are you going about finding the right one? Were you able to figure this out?

 @themantissa perhaps document this, as I'd think it's a pretty common use case, no?

**Comment by themantissa** [comment]
I'm not sure I follow @wkhatch.  Can you explain what you mean specifically by "How are you going about finding the right one? Were you able to figure this out?"  do you mean container id via the API.

No, it's not a terrible common use case that we've seen thus far.  We solved a lot of the container_id pain by computing it in the cluster resource.  However, perhaps we can compute it with the data source as well - will find out.

**Comment by wkhatch** [comment]
@themantissa yes, I meant the container id. I was trying to automate the peering with a new eks vpc and cluster, with an existing atlas cluster, and not being able to easily get the container id was the pain point. The data source seemed like the perfect solution, but then nope, I needed the container for that, too lol. I ended up importing the resource, and getting the container id from the output, so problem solved. But in general, it seems like that attribute should be simpler to obtain. Why not expose it in the UI, or provide another data source to return it, or both? Thanks

**Comment by themantissa** [comment]
@wkhatch valid questions!  We don't expose it in the UI as, quite honestly, we obfuscate the whole notion of a container much better in the UI experience than API.  But you are right, we really do need to make it easier to find.   I've asked our engineers to look into this and see if we can actually get it to surface in the datasource and then we can add that as a helpful hit in the docs.  Thank you for the feedback on it.

**Comment by martinstibbe** [comment]
@wkhatch 
Validated by testing following scenario container_id populated in state after first apply ...

1) create cluster using curl command to simulate non terraform based cluster
curl --user "pub:priv" --digest \
--header "Content-Type: application/json" \
--include \
--request POST "https://cloud.mongodb.com/api/atlas/v1.0/groups/grpid/clusters?pretty=true" \
--data '
{
"name": "SingleRegionCluster",
"diskSizeGB": 100,
"numShards": 1,
"providerSettings":
{ "providerName": "AWS", "instanceSizeName": "M40", "regionName": "US_EAST_1" }

,
"clusterType" : "REPLICASET",
"replicationFactor": 3,
"replicationSpecs": [{
"numShards": 1,
"regionsConfig": {
"US_EAST_1":
{ "analyticsNodes": 0, "electableNodes": 3, "priority": 7, "readOnlyNodes": 0 }

},
"zoneName": "Zone 1"
}],
"backupEnabled": false,
"providerBackupEnabled" : true,
"autoScaling":
{ "diskGBEnabled": true }

}'

 

2) Apply this terraform to read information from datasources

 
data "mongodbatlas_cluster" "admin"
{ name = "SingleRegionCluster" project_id = local.mongodbatlas_project_id }

data "mongodbatlas_network_container" "admin"
{ project_id = local.mongodbatlas_project_id container_id = data.mongodbatlas_cluster.admin.container_id }

output "container"
{ value = data.mongodbatlas_network_container.admin.container_id }

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

container = "62ffe4ecb79e2e007c375935"

 

Using versions
darwin_amd64
provider registry.terraform.io/hashicorp/aws v4.26.0
provider registry.terraform.io/mongodb/mongodbatlas v1.4.3

**Comment by themantissa** [comment]
Thank you @martinstibbe for developing the above example.  All - we'll find a way to add this to the docs.

**Comment by wkhatch** [comment]
Thanks @martinstibbe! So to summarize, if you define a cluster resource using same name as existing cluster, and with same project id, it won't create another resource and you'll get the container id after apply. I think, anyway? Interesting approach, and I wouldn't have tried that. Thanks again.
