### ISSUE TITLE
Auto-calculate minimum IOPS

### ISSUE THREAD

**Issue by nitrag** [mongodb/terraform-provider-mongodbatlas#32]
I don't see why we have to specify `provider_disk_iops` if it is optional. Is the purpose to provision more IOPS than standard? How does this affect costs if chosen wrongly? Please provide safe way for the provider to automatically calculate for users who do not need/want to think about this.

```
Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/<>/clusters: 400 (request "Bad Request") 
The cluster's disk IOPS of 0 is invalid. For a disk of size 5 on instance size M10 with a volume type of (auto), the IOPS must be 100.0.
```

```
resource "mongodbatlas_cluster" "db" {
  project_id                   = mongodbatlas_project.db.id
  name                         = "${var.cluster_name}"
  backup_enabled               = true
  auto_scaling_disk_gb_enabled = true
  disk_size_gb                 = 5
  #provider_disk_iops           = 100
  provider_name                = "AWS"
  provider_instance_size_name  = var.cluster_tier
  provider_region_name         = "US_EAST_1"

  depends_on = ["mongodbatlas_network_container.container"]
}
```

**Comment by macintacos** [comment]
I'd also like to call out that, when you're using volumes where IOPS scales with the disk size (_not_ provisioned IOPS where they can be scaled independently), providing the IOPS value when you've already specified the disk size is redundant. M10 AWS instances on Atlas, for example, cannot separate IOPS from disk size, so providing it may actually things more confusing in those scenarios.

**Comment by themantissa** [comment]
This sounds similar to an issue that should be corrected (@marinsalinas?) that was reported via https://github.com/mongodb/terraform-provider-mongodbatlas/issues/29.   We had both a bug on the Atlas side and some clean up work on the Provider.    You should only have to provide if you want provisioned IOPS - otherwise it's optional as noted.

**Comment by PacoDw** [comment]
Hello,
We'll move this issue to github.com/terraform-providers/terraform-provoder-mongodbatlas
