### ISSUE TITLE
Unexpected behaviour from resource `mongodbatlas_teams` when adding username for user not yet part of/Pending to join Organisation

### ISSUE THREAD

**Issue by muscovitebob** [mongodb/terraform-provider-mongodbatlas#329]
# Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v0.12.20
Mongodbatlas v0.6.1
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "myproject" {
  name   = "myproject"
  org_id = "orgid"
  teams {
    team_id    = mongodbatlas_teams.myteam.team_id
    role_names = ["GROUP_OWNER"]
  }
}

resource "mongodbatlas_teams" "myteam" {
  org_id    = "orgid"
  name      = "My Team"
  usernames = ["user.that.exists.in.org@organization.com, user.that.does.not.exist.in.org@organization.com"]
}
```

### Steps to Reproduce

Have an organisation in which there is a `user.that.exists.in.org@organization.com`, whom have logged in at least once.
Invite a new user, `user.that.does.not.exist.in.org@organization.com`, to the organisation. They are listed as Pending in the organisation users overview.
Add the `user.that.does.not.exist.in.org@organization.com` to the usernames array in the `mongodbatlas_teams` resource.

### Expected Behavior

User is added to the team successfully, or a helpful error is produced if this is not possible. If this is not possible, the myteam team retains all of its members before we attempted adding a new member.

### Actual Behavior

Terraform plan reports user will be added to array. 

Terraform apply errors out:
```
Error: error getting Atlas User (user.that.does.not.exist.in.org@organization.com) information: GET https://cloud.mongodb.com/api/atlas/v1.0/users/byName/user.that.does.not.exist.in.org@organization.com: 401 (request "Unauthorized") The currently logged in user does not have the user administrator role for any group, team, or organization containing user user.that.does.not.exist.in.org@organization.com.

  on mongodb_extra.tf line 12, in resource "mongodbatlas_teams" "myteam":
  12: resource "mongodbatlas_teams" "myteam" {
```

Repeated terraform plan reports that the `myteam` team needs to have all of the usernames that were previously part of it added again. Navigating to the MongoDB Atlas project GUI confirms that the team has 0 members after this error.

### Additional Context

If this is indeed caused by the `user.that.does.not.exist.in.org@organization.com` being in status Pending for organisation member, the error message should probably be more helpful.

**Comment by muscovitebob** [comment]
Confirmed that `user.that.does.not.exist.in.org@organization.com` logging into the Organization and hence no longer being Pending resolves the error.

**Comment by themantissa** [comment]
@muscovitebob Thank you for the report.  It is documented that one cannot add an Atlas user to a team until the user has accepted the invite (see https://docs.atlas.mongodb.com/access/manage-teams-in-orgs/).  I also believe we have an internal request to improve the error message produced by Atlas (which is referenced above).

However it sounds like the core problem here is that when you added a user in a pending state it then removed all teams members from the team to which they were being added?  Is this a correct understanding?  If so @nikhil-mongo since I'll be OOO can you follow up with filing an internal ticket on this.  If not correct please assist in narrowing down on the specifics.  Thank you both!

**Comment by muscovitebob** [comment]
That is indeed the crux of the issue @themantissa, apologies that it is not as clear as it could have been.

**Comment by nikhil-mongo** [comment]
@muscovitebob Let me repro it and file an internal ticket to be worked on. And, I will update you here of any progress.

**Comment by nikhil-mongo** [comment]
I was able to repro this on provider version 0.6.0 but is working as expected when running through API directly. I am checking this internally.

**Comment by nikhil-mongo** [comment]
Internal ticket reference: HELP-19204

**Comment by themantissa** [comment]
Internal dev ticket: INTMDB-121

**Comment by themantissa** [comment]
@muscovitebob the fix for the core issue is completed and will be in the next version. Feel free to try in the mean time.  Thank you!
