### ISSUE TITLE
Problem encryption_at_rest

### ISSUE THREAD

**Issue by aliciaalcalde** [mongodb/terraform-provider-mongodbatlas#33]
Good morning,

I create an IAM service account, KMS keyring and key in my own GCP account.

```
#Service Account for KMS
resource "google_service_account" "encryption_at_rest" {
  count         = var.encryption_at_rest_provider == true ? 1 : 0
  project       = var.gcp_project_id
  account_id    = "atlas-encrypt-${var.cluster_name}"
  display_name  = "atlas-encrypt-${var.cluster_name}"
}

#IAM Policy for KMS
resource "google_project_iam_member" "encryption_at_rest" {
  count   = var.encryption_at_rest_provider == true ? 1 : 0
  project = var.gcp_project_id
  role    = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member  = "serviceAccount:atlas-encrypt-${var.cluster_name}@${var.gcp_project_id}.iam.gserviceaccount.com"
}

#Create service account key
resource "google_service_account_key" "encryption_at_rest" {
  count               = var.encryption_at_rest_provider == true ? 1 : 0
  service_account_id  = google_service_account.encryption_at_rest[count.index].name
  public_key_type     = "TYPE_X509_PEM_FILE"
}

#######################
#        KMS          #
#######################

# Create keyring for encryption_at_rest
resource "google_kms_key_ring" "encryption_at_rest" {
  count     = var.encryption_at_rest_provider == true ? 1 : 0
  project   = var.gcp_project_id
  name      = "atlas-${var.cluster_name}"
  location  = "global"
}
resource "google_kms_crypto_key" "crypto_key" {
  count     = var.encryption_at_rest_provider == true ? 1 : 0
  name      = "atlas-crypto-key"
  key_ring  = google_kms_key_ring.encryption_at_rest[count.index].id

  depends_on = [ "google_kms_key_ring.encryption_at_rest" ]
}

# Atlas encryption_at_rest
resource "mongodbatlas_encryption_at_rest" "kms" {
  count                     = var.encryption_at_rest_provider == true ? 1 : 0
  project_id                = mongodbatlas_project.project.id
  google_cloud_kms = {
    enabled                 = var.encryption_at_rest_provider
    service_account_key     = base64decode(google_service_account_key.encryption_at_rest[count.index].private_key)
    key_version_resource_id = "${google_kms_crypto_key.crypto_key[count.index].id}/cryptoKeyVersions/1"
  }

  depends_on = [ "mongodbatlas_project.project", "google_kms_crypto_key.crypto_key", "google_service_account_key.encryption_at_rest" ]
}
```
It returns the following error:
**Error: error creating Encryption at Rest: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxxxx/encryptionAtRest: 400 (request "Bad Request") Invalid Google Cloud credentials.**

If I only specified   encryption_at_rest_provider = true in mongodbatlas_cluster resource

```
resource "mongodbatlas_cluster" "cluster" {
  project_id                   = mongodbatlas_project.project.id
  name                         = var.cluster_name
  backup_enabled               = var.backup_enabled
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = var.mongodb_version
   encryption_at_rest_provider = true

  //Provider Settings "block"
  provider_name               = "GCP"
  disk_size_gb                = var.size_gb
  provider_instance_size_name = var.instance_type
  provider_region_name        = var.region

  //depends_on                  = ["mongodbatlas_project.project", "mongodbatlas_encryption_at_rest.kms"]
}
```
It returns the following error:
**Error: error updating MongoDB Cluster (mongodb-ag-dev): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxxxx/clusters/mongodb-ag-dev: 400 (request "Bad Request") An invalid enumeration value true was specified.**

Is my code right? Could you explain me how to implement encryption_at_rest in Atlas?

Thank you so much.

**Comment by themantissa** [comment]
@aliciaalcalde I'll try to assist here - we'll be posting soon that support for the provider will go through MongoDB Atlas support but in the mean time let's work together here.

For the cluster creation section:
encryption_at_rest_provider doesn't take a boolean but a string, in this case set it to GCP (and I'll make a todo to update the doc there to be more clear).  Make sure all the options match as well (they are documented in more depth here: https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ ) but for GCP they are: 
providerSettings .instanceSizeName | M10 or greater
backupEnabled | false or omitted

For setting up encryption at rest for the project before you create the cluster:
The resource looks correct (make sure the encryption at rest variable there is a boolean).   Could there be an issue with GCP in creating the the service acct?  The error seems to be the key isn't found as passed in.

**Comment by themantissa** [comment]
@aliciaalcalde since I've not heard back I'm going to close this.  Feel free to reach out if you have more issues.

**Comment by frankgu968** [comment]
Hi @themantissa , I am experiencing a similar issue as well. I have added the appropriate roles to allow for cryptoKeyEncryptDecrypt and get the service account key. However, I still see the "Invalid Google Credentials" error. After setting the permission on the service account to Owner (full permissions), the error goes away; suggesting that this is a permissions-related issue. 

It'd be helpful if the error message can show the specific Google IAM scopes missing.

**Comment by NurdaCodez** [comment]
> @aliciaalcalde I'll try to assist here - we'll be posting soon that support for the provider will go through MongoDB Atlas support but in the mean time let's work together here.
> 
> For the cluster creation section: encryption_at_rest_provider doesn't take a boolean but a string, in this case set it to GCP (and I'll make a todo to update the doc there to be more clear). 

Without "count" it works. #Service Account for KMS
resource "google_service_account" "encryption_at_rest" {
  project       = var.gcp_project
  account_id    = "atlas-encrypt-sar"
  display_name  = "atlas-encrypt-${var.cluster_name}"
}

resource "google_project_iam_member" "encryption_at_rest" {
  for_each  = toset([
    "roles/cloudkms.admin",
    "roles/cloudkms.cryptoKeyEncrypterDecrypter",  ])
  project   = var.gcp_project
  role      = each.value
  member    = "serviceAccount:atlas-encrypt-sar@${var.gcp_project}.iam.gserviceaccount.com"
}

#Create service account key
resource "google_service_account_key" "encryption_at_rest" {
  service_account_id = "atlas-encrypt-sar@${var.gcp_project}.iam.gserviceaccount.com"
  
  public_key_type     = "TYPE_X509_PEM_FILE"

}

#######################
#        KMS          #
#######################

# Create keyring for encryption_at_rest
resource "google_kms_key_ring" "encryption_at_rest" {
  project   = var.gcp_project
  name      = "atlas-keyring"
  location  = "global"
}

resource "google_kms_crypto_key" "crypto_key" {
  name      = "atlas-crypto-key"
  key_ring  = google_kms_key_ring.encryption_at_rest.id

  depends_on = [google_kms_key_ring.encryption_at_rest]
}

# Atlas encryption_at_rest
resource "mongodbatlas_encryption_at_rest" "kms" {
  project_id                = var.project_id_mongo
  google_cloud_kms_config {
    enabled                 = true
    service_account_key     = base64decode(google_service_account_key.encryption_at_rest.private_key)
    key_version_resource_id = "${google_kms_crypto_key.crypto_key.id}/cryptoKeyVersions/1"
  }

  depends_on = [google_kms_crypto_key.crypto_key, google_service_account_key.encryption_at_rest]
}

**Comment by NurdaCodez** [comment]
> @aliciaalcalde I'll try to assist here - we'll be posting soon that support for the provider will go through MongoDB Atlas support but in the mean time let's work together here.
> 
> For the cluster creation section: encryption_at_rest_provider doesn't take a boolean but a string, in this case set it to GCP (and I'll make a todo to update the doc there to be more clear). Make sure all the options match as well (they are documented in more depth here: https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ ) but for GCP they are: providerSettings .instanceSizeName | M10 or greater backupEnabled | false or omitted   Without "count" it works. ``` #Service Account for KMS
resource "google_service_account" "encryption_at_rest" {
  project       = var.gcp_project
  account_id    = "atlas-encrypt-sar"
  display_name  = "atlas-encrypt-${var.cluster_name}"
}

resource "google_project_iam_member" "encryption_at_rest" {
  for_each  = toset([
    "roles/cloudkms.admin",
    "roles/cloudkms.cryptoKeyEncrypterDecrypter",  ])
  project   = var.gcp_project
  role      = each.value
  member    = "serviceAccount:atlas-encrypt-sar@${var.gcp_project}.iam.gserviceaccount.com"
}

#Create service account key
resource "google_service_account_key" "encryption_at_rest" {
  service_account_id = "atlas-encrypt-sar@${var.gcp_project}.iam.gserviceaccount.com"
  
  public_key_type     = "TYPE_X509_PEM_FILE"

}

#######################
#        KMS          #
#######################

# Create keyring for encryption_at_rest
resource "google_kms_key_ring" "encryption_at_rest" {
  project   = var.gcp_project
  name      = "atlas-keyring"
  location  = "global"
}

resource "google_kms_crypto_key" "crypto_key" {
  name      = "atlas-crypto-key"
  key_ring  = google_kms_key_ring.encryption_at_rest.id

  depends_on = [google_kms_key_ring.encryption_at_rest]
}

# Atlas encryption_at_rest
resource "mongodbatlas_encryption_at_rest" "kms" {
  project_id                = var.project_id_mongo
  google_cloud_kms_config {
    enabled                 = true
    service_account_key     = base64decode(google_service_account_key.encryption_at_rest.private_key)
    key_version_resource_id = "${google_kms_crypto_key.crypto_key.id}/cryptoKeyVersions/1"
  }

  depends_on = [google_kms_crypto_key.crypto_key, google_service_account_key.encryption_at_rest]
} ```

**Comment by NurdaCodez** [comment]
> @aliciaalcalde I'll try to assist here - we'll be posting soon that support for the provider will go through MongoDB Atlas support but in the mean time let's work together here.
> 
> For the cluster creation section: encryption_at_rest_provider doesn't take a boolean but a string, in this case set it to GCP (and I'll make a todo to update the doc there to be more clear). Make sure all the options match as well (they are documented in more depth here: https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ ) but for GCP they are: providerSettings .instanceSizeName | M10 or greater backupEnabled | false or omitted


### Without "count" it works. 

``` hcl  #Service Account for KMS
resource "google_service_account" "encryption_at_rest" {
  project       = var.gcp_project
  account_id    = "atlas-encrypt-sar"
  display_name  = "atlas-encrypt-${var.cluster_name}"
}

resource "google_project_iam_member" "encryption_at_rest" {
  for_each  = toset([
    "roles/cloudkms.admin",
    "roles/cloudkms.cryptoKeyEncrypterDecrypter",  ])
  project   = var.gcp_project
  role      = each.value
  member    = "serviceAccount:atlas-encrypt-sar@${var.gcp_project}.iam.gserviceaccount.com"
}

#Create service account key
resource "google_service_account_key" "encryption_at_rest" {
  service_account_id = "atlas-encrypt-sar@${var.gcp_project}.iam.gserviceaccount.com"
  
  public_key_type     = "TYPE_X509_PEM_FILE"

}

#######################
#        KMS          #
#######################

# Create keyring for encryption_at_rest
resource "google_kms_key_ring" "encryption_at_rest" {
  project   = var.gcp_project
  name      = "atlas-keyring"
  location  = "global"
}

resource "google_kms_crypto_key" "crypto_key" {
  name      = "atlas-crypto-key"
  key_ring  = google_kms_key_ring.encryption_at_rest.id

  depends_on = [google_kms_key_ring.encryption_at_rest]
}

# Atlas encryption_at_rest
resource "mongodbatlas_encryption_at_rest" "kms" {
  project_id                = var.project_id_mongo
  google_cloud_kms_config {
    enabled                 = true
    service_account_key     = base64decode(google_service_account_key.encryption_at_rest.private_key)
    key_version_resource_id = "${google_kms_crypto_key.crypto_key.id}/cryptoKeyVersions/1"
  }

  depends_on = [google_kms_crypto_key.crypto_key, google_service_account_key.encryption_at_rest]
}

```
