### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by RavindraSinghKhichi** [mongodb/terraform-provider-mongodbatlas#335]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
# Copy-paste your version info here
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
```

### References

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/private_endpoint_interface_link

data source and resource names are wrong here.

**Comment by nikhil-mongo** [comment]
@RavindraSinghKhichi 

Can you please elaborate the typo error that you noticed here.

**Comment by RavindraSinghKhichi** [comment]
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/private_endpoint_interface_link

resource names should be as following:

mongodbatlas_private_endpoint_interface_link instead of mongodbatlas_private_endpoint_link. The provider report 404 on following the documentation.

Hope this helps !!

**Comment by nikhil-mongo** [comment]
Thanks for pointing it out @RavindraSinghKhichi. I will have it fixed soon.
