### ISSUE TITLE
Please add support for Azure Private Link as a private endpoint

### ISSUE THREAD

**Issue by kbetts-wwt** [mongodb/terraform-provider-mongodbatlas#346]
Currently "mongodbatlas_private_endpoint" only supports AWS. We are currently terraforming project and cluster creation. But we have to manually create the private endpoint for Azure. Much more convenient to TF the whole stack. Thank you.

**Comment by themantissa** [comment]
@kbetts-wwt this is actually already in our current work queue.  Support was just added for Azure and it also added a net new resource to support both Azure and AWS so we have to rework the provider.  I expect it to likely land in the next provider version.  Thank you!

Internal ticket: INTMDB-120

**Comment by kbetts-wwt** [comment]
Thank you!
