### ISSUE TITLE
Mongodbatlas documentation issue with Data Sources

### ISSUE THREAD

**Issue by igoratencompass** [mongodb/terraform-provider-mongodbatlas#347]
Hi,

Seems the whole section about Data Sources here https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/ is wrong and is just a copy of the Resources section for the same Provider.

**Comment by themantissa** [comment]
@igoratencompass can you be more specific?  Do note we include an example of using each resource and then an example of the data source after but looking at a few they are indeed datasources.

**Comment by igoratencompass** [comment]
@themantissa when you click on the Data Sources drop down for the provider and then on any of the data sources in that list like https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/cluster, you end up on a page describing the "resource" instead of the actual "data" source.

**Comment by igoratencompass** [comment]
Ah wait, yeah it is fine now not sure what happened I could sware the "data" source was not there before!? Yeah maybe I'm getting too old and my eayes are playing tricks on me :-/ Sorry for the noise.

**Comment by themantissa** [comment]
Glad to hear it worked out @igoratencompass .   No worries at all and let us know if anything does come up buggy!
