### ISSUE TITLE
r/mongodbatlas_third_party_integration fails on read after create

### ISSUE THREAD

**Issue by b-b3rn4rd** [mongodb/terraform-provider-mongodbatlas#354]
Hi Team,
I've been experiencing the following problem when trying to enable `third_party_integration` for WEBHOOK, as you can see from the logs it's been failing to perform GET immediately after the resource have been created. I can confirm that the integration was successfully created (via console), seems like an issue on API side...

```bash
module.atlas.mongodbatlas_third_party_integration.webhook[0]: Creating...
Error: error getting third party integration resource info WEBHOOK GET https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXXXXXXXXXXXXXXX/integrations/WEBHOOK: 404 (request "Not Found") The integration of type 'WEBHOOK' is not configured for this group.
```

**Comment by leofigy** [comment]
Hi @b-b3rn4rd , right the api accepts the  create request, but the get does not show the webhook. I thought it could a sync issue. But it seems it actually never returns it. Let us file an internal ticket to track the issue. Thank you !

**Comment by nikhil-mongo** [comment]
@leofigy This is reported internally in the JIRA as **HELP-20312**.

**Comment by nikhil-mongo** [comment]
Hi @b-b3rn4rd Could you please confirm which third-party webhook were you trying to use with Terraform?

**Comment by b-b3rn4rd** [comment]
H @nikhil-mongo not sure if I correctly understand the question, I'm trying to enable third-party integration to call my url (this is what WEBHOOK intergration type is )  via terraform. This is the code example:

```
  resource "mongodbatlas_third_party_integration" "webhook" {
    project_id = var.project_id
    type       = "WEBHOOK"
    url        = "${var.hook_url}?client_id=${var.hook_client_id}&client_secret=${var.hook_client_secret}"
  }
```
Let me know if you require any additional information

**Comment by nikhil-mongo** [comment]
@b-b3rn4rd This was fixed. Please check and let us know.

**Comment by themantissa** [comment]
Closing as issue was fixed, if still an issue let us know.
