### ISSUE TITLE
Quick start for provider is not quick and comes with side effect about `replication_factor` field

### ISSUE THREAD

**Issue by AlphaWong** [mongodb/terraform-provider-mongodbatlas#356]
# Workspace
Terraform v0.11.14

# issue
## step
1. Create a mongo cluster resource following https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#example-aws-cluster
```
resource "mongodbatlas_cluster" "cluster-test" {
  project_id   = "<YOUR-PROJECT-ID>"
  name         = "cluster-test"
  num_shards   = 1

  replication_factor           = 3
  provider_backup_enabled      = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.2"

  //Provider Settings "block"
  provider_name               = "AWS"
  disk_size_gb                = 100
  provider_disk_iops          = 300
  provider_volume_type        = "STANDARD"
  provider_encrypt_ebs_volume = true
  provider_instance_size_name = "M40"
  provider_region_name        = "US_EAST_1"
}
```
2. change the `replication_factor` from `3` to `5`
### expected
it should fire a request
```console
curl --request PATCH \
  --url https://cloud.mongodb.com/api/atlas/v1.0/groups/<PROJECT-ID>/clusters/cluster-test \
  --header 'Content-Type: application/json' \
  --data '{
	"replicationFactor": 3
}'
```
### actual
```json
{
    "autoScaling": {
        "compute": {}
    },
    "replicationFactor": 5,
    "replicationSpecs": [
        {
            "id": "<PROJECT-ID>",
            "numShards": 1,
            "zoneName": "Zone 1",
            "regionsConfig": {
                "US_EAST_1": {
                    "analyticsNodes": 0,
                    "electableNodes": 3,
                    "priority": 7,
                    "readOnlyNodes": 0
                }
            }
        }
    ]
}
```

# local state
```
"replication_factor": "5",
"replication_specs.#": "1",
"replication_specs.0.id": "<PROJECT-ID>",
"replication_specs.0.num_shards": "1",
"replication_specs.0.regions_config.#": "1",
"replication_specs.0.regions_config.4096232914.analytics_nodes": "0",
"replication_specs.0.regions_config.4096232914.electable_nodes": "5",
"replication_specs.0.regions_config.4096232914.priority": "7",
"replication_specs.0.regions_config.4096232914.read_only_nodes": "0",
"replication_specs.0.regions_config.4096232914.region_name": "US_EAST_1",
```

# reason
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/c82481ce1f55632e73894e01cc3bfeb434a9e553/mongodbatlas/resource_mongodbatlas_cluster.go#L512 will copy the `replication_factor` and create a `replicationSpecs` fields in state file.

In this case, the underlayer of the `main.tf` and tf state are not representing the same thing, which matches the statement `Atlas ignores this value if you pass the replicationSpec object.`  at https://docs.atlas.mongodb.com/reference/api/clusters-modify-one/ .

The json response will always come with an array `replicationSpecs` and the `replicationFactor` and the `replicationFactor` will never changed.

# resolution
I think it is better to change example and state the behaviour clearly about the underlayer of the `replicationFactor` stored at state file.

Or change this behaviour by removing the auto generate `replicationSpecs` side effect as it just a simple change for a field only.

**Comment by nikhil-mongo** [comment]
@AlphaWong Thanks for reporting this. The replication_factor has been deprecated as per the Atlas API [documentation](https://docs.atlas.mongodb.com/reference/api/clusters-modify-one/) and the documentation suggestions using the replication_specs for creating the cluster. I will update the documentation and the example.

**Comment by themantissa** [comment]
Since changes to address this have been made closing the issue.
