### ISSUE TITLE
plugin.terraform-provider-mongodbatlas_v0.2.0_x4: panic: runtime error: index out of range

### ISSUE THREAD

**Issue by acim** [mongodb/terraform-provider-mongodbatlas#36]
### Terraform Version

```
v0.11.14
```

### Terraform Configuration Files

```hcl
resource "mongodbatlas_cluster" "ff3_dev" {
  auto_scaling_disk_gb_enabled = false
  backing_provider_name        = "AWS"
  backup_enabled               = false
  mongo_db_major_version       = "4.0"
  name                         = "ff3_dev"
  project_id                   = "foobarbaz"
  provider_instance_size_name  = "M0"
  provider_name                = "TENANT"
  provider_region_name         = "${upper(replace(var.aws_region, "-", "_"))}"
}
```

### Crash Output

https://gist.github.com/acim/38b1f36ab10db14ba7460b7a7f130b07

### Expected Behavior

Plan should display what has to be modified.
### Actual Behavior

Crash.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan -target=mongodbatlas_cluster.ff3_dev`

### Additional Context

I previously used [3rd party mongodbatlas provider](https://github.com/akshaykarle/terraform-provider-mongodbatlas) when no other version was available. Now I switched to the official version but terraform crashes.

**Comment by PacoDw** [comment]
Thank you for your review, let us check the problem to resolve as soon as possible.

**Comment by marinsalinas** [comment]
Related to #26, 

@acim, could you please upgrade your terraform binary to 0.12+ and follow these steps?

https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/26#issuecomment-532481256,

**Comment by acim** [comment]
Same thing:

```
mongodbatlas_cluster.ff3_dev: Refreshing state... [id=5b9fc6a84e6581229d0e7095]

Error: rpc error: code = Unavailable desc = transport is closing


panic: runtime error: index out of range
2019-10-01T18:39:12.274+0200 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.2.0_x4: 
2019-10-01T18:39:12.274+0200 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.2.0_x4: goroutine 101 [running]:
2019-10-01T18:39:12.274+0200 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.2.0_x4: github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas.decodeStateID(0xc0001809a0, 0x18, 0x5d3d6855)
2019-10-01T18:39:12.274+0200 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.2.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-mongodbatlas/mongodbatlas/provider.go:97 +0x235
```

**Comment by acim** [comment]
Crashes stopped after I did "state rm" old resources created by akshaykarle/terraform-provider-mongodbatlas.

**Comment by themantissa** [comment]
We have someone working on a guide from moving from the community provider to the new one and if I get an ETA will share.    Ideally one should be able to import in the existing resources and then create the new configs (hopefully Terraform will someday have the tf file creation upon import) but it may take removing the state first (that sure is what it sounds like).

**Comment by themantissa** [comment]
closing as will be tracked in issue 26 - https://github.com/terraform-providers/terraform-provider-mongodbatlas/issues/26
