### ISSUE TITLE
Deleting a user from mongo atlas results in a 404 error, not that user getting re-created

### ISSUE THREAD

**Issue by sonic1981** [mongodb/terraform-provider-mongodbatlas#360]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v0.13.4
+ provider registry.terraform.io/terraform-providers/mongodbatlas v0.6.5
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_database_user" "dbuser" {
  username                      = "${var.prefix}${var.implementation_number}"
  project_id                    = data.mongodbatlas_project.proj.id
  auth_database_name            = "admin"
  password                      = var.mongoPassword

  roles {
    role_name                   = "readWriteAnyDatabase"
    database_name               = "admin"
  }

  scopes {
    name                        = mongodbatlas_cluster.clu.name
    type                        = "CLUSTER"
  }  
}
```

### Steps to Reproduce
1. Create a user using the above terraform config. 
2. Now manually delete that user using the shell
3. re-run terraform above

### Expected Behavior
Mongo database user should of been re-created

### Actual Behavior
> Error: error getting database user information: GET https://cloud.mongodb.com/api/atlas/v1.0/.....: 404 (request "Not Found") No user with username {{user}} exists.

### Additional Context
With other terraform providers we use, Azure and AWS deleting of resources results in the re-creation of these resources when the terraform scripts are re-ran.

**Comment by sonic1981** [comment]
I tried deleting the cluster, etc but in the end I had to actually remove the user from the state using:

```hcl
terraform state rm "module.mongo.mongodbatlas_database_user.dbuser"
```

**Comment by themantissa** [comment]
@sonic1981 thank you for the report. When you say re-run you are doing a refresh, plan, apply?   Any logs?  Want to ensure we repro what you are doing.  Also we'll repro with 0.7.0 as that's the latest. Thanks!

**Comment by sonic1981** [comment]
Hey @themantissa .

So a re-run is essentially an apply. (it's actually a plan - > output plan - > apply plan but this should be the same). I'll try and get logs for you when I'm back in the office on Monday

**Comment by themantissa** [comment]
@sonic1981 I follow but I'd like to repro exactly so steps/logs are helpful! Thank you and let me know on the logs.

**Comment by sonic1981** [comment]
Hi @themantissa 

Here is a GIST with the trace output of my re-creation 

https://gist.github.com/sonic1981/cc5957620c3ebfe6efbbaf0681aa5506

**Comment by themantissa** [comment]
@sonic1981  FYI I removed the link to the gist as there is some info you may not want to expose there and I would suggest redacting/removing it.  Feel free to reach out to me directly melissa.plunkett@mongodb.com

**Comment by themantissa** [comment]
@sonic1981 so I was able to repro and talk with our development team.  It seems early work in the provider is missing the functionality that will both catch the 404 and appropriately handle being able to simply apply the user again.  Some resources already have this.  I'll slot this improvement in our backlog, starting with the database users resource and we'll make our way through the existing till all have similar functionality in this regard.   In the mean time removing the item in state, as you found, unblocks recreating.

**Comment by themantissa** [comment]
Internal ticket INTMDB-141

**Comment by sonic1981** [comment]
Great thanks for your help @themantissa

**Comment by themantissa** [comment]
@sonic1981 we have a fix completed and merged and will be in the next version. Feel free to test in the mean time if you'd like.

**Comment by sonic1981** [comment]
any idea when this next version will be released @themantissa ?

**Comment by themantissa** [comment]
@sonic1981 we are estimating mid Jan right now.
