### ISSUE TITLE
Removal of user scopes is not detected by the provider

### ISSUE THREAD

**Issue by haidaraM** [mongodb/terraform-provider-mongodbatlas#363]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
# Copy-paste your version info here
Terraform v0.13.5
+ provider registry.terraform.io/mongodb/mongodbatlas v0.7.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_database_user" "user" {
  project_id         = data.mongodbatlas_project.this.id
  username           = "test-user-bug"
  password           = "password123!!-))"
  auth_database_name = "admin"

  roles {
    role_name = "read"
    database_name = "test"
  }

  scopes {
    name = "clu-dev-atlas-terraform"
    type = "CLUSTER"
  }

}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. Remove the `scopes {}` block from the configuration
4. `terraform apply`

### Expected Behavior
Terraform should remove the `scopes` from the user.

### Actual Behavior
Terraform doesn't detect this change. 

### Additional Context
Also, the provider doesn't detect when a scope is manually added in the Atlas console. This not the case for the roles which are correctly handled by the provider.

**Comment by themantissa** [comment]
Thank you for the report and details @haidaraM   @nikhil-mongo would you be able to repro to produce logs and open a PRODTRIAGE internally if confirmed?  Thank you!

**Comment by nikhil-mongo** [comment]
I could verify this and logged PRODTRIAGE-1237

**Comment by haidaraM** [comment]
Is this issue fixed by https://github.com/mongodb/terraform-provider-mongodbatlas/pull/368 ? If yes, when can we expect a new release of the provider ?

**Comment by themantissa** [comment]
@haidaraM yes, the PR did not get linked but we'll close this after the release.  We expect the release in the next week or so, will be in v0.8.0.  Thanks!

**Comment by haidaraM** [comment]
Perfect @themantissa. Thanks for your work :-)

**Comment by themantissa** [comment]
v0.8.0 is now released.   I'll close this issue.  TY
