### ISSUE TITLE
Bad Release Practice

### ISSUE THREAD

**Issue by stack72** [mongodb/terraform-provider-mongodbatlas#381]
Hi folks,

On Wednesday 13th January at approx 0130 UK Time, there was a tag cut v0.8.0 - it looks like that tag was overwritten by v0.8.0-pre.1

It would be really nice if this was communicated somewhere about why a 0.8.0 release was turned into a pre.1 release. We depend on the project and are now worried about using the 0.8.0 release

Thanks

Paul

**Comment by leofigy** [comment]
Hi @stack72 apologies for the inconvenience. the tag v0.8.0 was marked as a pre-release (in the github release page). but it ran into issues associated and caught during testing with https://github.com/mongodb/terraform-provider-mongodbatlas/pull/380, internally in the team we were talking about migration into better tagging. So I decided to remove the old tag to avoid confussions, and once we have an approved release, I'll tag it as v0.8.0 (without the pre-release checked in github).

**Comment by stack72** [comment]
Thanks @leofigy - understandable
