### ISSUE TITLE
failed to create policy items while using mongodbatlas_cloud_provider_snapshot_backup_policy

### ISSUE THREAD

**Issue by ahmad-shams** [mongodb/terraform-provider-mongodbatlas#386]
referring to example in documentation page:
policy_item {
      id                 = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.policy_item.1.id
      frequency_interval = 1
      frequency_type     = "daily"
      retention_unit     = "days"
      retention_value    = 2
    }

the index that should be created for each policy_item is failing, it seems problem with collection mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.policy_item

can I use random id ?

------------------- error returning after running terraform apply

Error: Invalid index

  on mongo_db.tf line 38, in resource "mongodbatlas_cloud_provider_snapshot_backup_policy" "keofit-backup-policy":
  38:       id                 = mongodbatlas_cluster.my_cluster.snapshot_backup_policy.0.policies.0.policy_item.1.id
    |----------------
    | mongodbatlas_cluster.my_cluster.snapshot_backup_policy[0].policies[0].policy_item is list of object with 1 element

The given key does not identify an element in this collection value.

**Comment by ahmad-shams** [comment]
after more research, I found that I can't use ... policy_item.1 or policy_item.2. until its created because by default I foudn that only index 0 is created by default

**Comment by themantissa** [comment]
@ahmad-shams correct, the policy is automatically created in Atlas so we imported it w/ the cluster resource. However as noted by a few issues reported in this repo there are problems with this approach.  I noted in https://github.com/mongodb/terraform-provider-mongodbatlas/issues/222 - we have reviewed the way this works and plan to make changes to improve this resource in a future version.
