### ISSUE TITLE
Error in Docs

### ISSUE THREAD

**Issue by adduty** [mongodb/terraform-provider-mongodbatlas#387]
In the docs for `mongodbatlas_privatelink_endpoint_service` (https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/privatelink_endpoint_service), the `mongodbatlas_privatelink_endpoint_service` resource in the example shows `project_id = "${mongodbatlas_privatelink_endpoint.test.project_id}"` when it should be `project_id = "${mongodbatlas_project.test.id}"`. Either that or the docs for `mongodbatlas_privatelink_endpoint` (https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/privatelink_endpoint#attributes-reference) need to be updated to show that project_id is an attribute for that resource if it really is.

Also, using the "${mongodbatlas_privatelink_endpoint.test.project_id}" notation is deprecated. I assume you are using it in the docs to support old versions of Terraform, but the docs for Hashicorp providers do not do this (e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecs_service).

**Comment by themantissa** [comment]
@adduty thank you for the report.  A few have commented that there are some issues with the new privatelink docs and we'll get those checked and addressed.

**Comment by themantissa** [comment]
@adduty this should be fixed with the release we just made, v0.8.1.  Thank you!
