### ISSUE TITLE
Can't add a team to a project

### ISSUE THREAD

**Issue by superduper** [mongodb/terraform-provider-mongodbatlas#389]
Hello!

Thank you for all the hard work on this terraform provider. I'm having an issue when trying to add a team to a project. Could you help me with it?

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v0.14.4
+ provider registry.terraform.io/mongodb/mongodbatlas v0.8.0
```

### Terraform Configuration File 

```hcl
terraform {
    required_providers {
        mongodbatlas = {
            source = "mongodb/mongodbatlas"
            version = "~> 0.8"
        }
    }
}


provider "mongodbatlas" {
  public_key   = "ZZZZZ"
  private_key  = "XXXXX"
}

resource "mongodbatlas_teams" "demo" {
    org_id    = "YYYYYYY"
    name      = "foo"
    usernames = ["mongo@example.com"]
}

resource "mongodbatlas_project" "demo" {
    name   = "proj_name"
    org_id = "YYYYYYY"
    teams {
          team_id = mongodbatlas_teams.demo.id
          role_names = [ "GROUP_DATA_ACCESS_READ_WRITE"]
    }
    depends_on = [
        mongodbatlas_teams.demo
    ]
}

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Expected Behavior
- A project and a team are created. 
- Team is added to a project

### Actual Behavior
Adding team into project fails with:
```
Error: error adding teams into the project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxxxx/teams: 400 (request "INVALID_JSON_ATTRIBUTE") Received JSON for the null attribute does not match expected format.
```

### Debug Output 
Link to debug output: https://gist.github.com/superduper/7f0fd2d5eabe0f4cc6e500be5e6a557f

### Crash Output
```
mongodbatlas_teams.demo: Creating...
mongodbatlas_teams.demo: Creation complete after 1s [id=xxxxx]
mongodbatlas_project.demo: Creating...

Error: error adding teams into the project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxx/teams: 400 (request "INVALID_JSON_ATTRIBUTE") Received JSON for the null attribute does not match expected format.

  on main.tf line 22, in resource "mongodbatlas_project" "demo":
  22: resource "mongodbatlas_project" "demo" {
```

**Comment by themantissa** [comment]
@superduper looks like you just need to change project to:

resource "mongodbatlas_project" "demo" {
    name   = "proj_name"
    org_id = "YYYYYYY"
    teams {
          team_id = **mongodbatlas_teams.demo.team_id**
          role_names = [ "GROUP_DATA_ACCESS_READ_WRITE"]
    }
    depends_on = [
        mongodbatlas_teams.demo
    ]
}

**Comment by superduper** [comment]
@themantissa Wow, this one was subtle. It worked! Thank you!
