### ISSUE TITLE
AWS clusters default provider_encrypt_ebs_volume to false

### ISSUE THREAD

**Issue by mattt416** [mongodb/terraform-provider-mongodbatlas#40]
Hey folks,

If I omit `provider_encrypt_ebs_volume` in my resource definition for an AWS cluster, this value defaults to `false`. However, the [Atlas API](https://docs.atlas.mongodb.com/reference/api/clusters-create-one/) defaults this to `true`.

I think it would also be beneficial to remove `provider_encrypt_ebs_volume: false` from the Example AWS cluster in the [**mongodbatlas_cluster** docs](https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html) as encrypting your volume is the preferred config.

Thanks!

**Comment by themantissa** [comment]
@mattt416 agreed.  @marinsalinas / @PacoDw can we get this corrected to the same default as the underlying system?

**Comment by PacoDw** [comment]
Hello, @mattt416 the fix is on the fix-#40 branch, could you plz check if this was resolved?

If you have another comment plz let us know, thanks!

**Comment by mattt416** [comment]
@PacoDw Apologies for delayed reply, was away on vacation when you posted your previous comment. I've since tested this (using 0.3.0 release) and all looks good. Thank you!

**Comment by PacoDw** [comment]
@mattt416 Don't worry about it :) I'm glad that everything is okay for you! 👍
