### ISSUE TITLE
SDK framework update v2.0.0+

### ISSUE THREAD

**Issue by leofigy** [mongodb/terraform-provider-mongodbatlas#408]
Currently the provider is using SDK github.com/hashicorp/terraform-plugin-sdk v1.14.0
that includes the support for terraform 0.11 . However the mongodb provider requires as minimum of tf 12. 
So it is candidate for upgrading. 

https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html

**Comment by themantissa** [comment]
Created INTMDB-183

**Comment by themantissa** [comment]
Upgraded to SDK v2 in 1.0.0, released today.
