### ISSUE TITLE
Outdated usage example about "mongodbatlas_encryption_at_rest"

### ISSUE THREAD

**Issue by eprokofev** [mongodb/terraform-provider-mongodbatlas#424]
Example usage from https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/encryption_at_rest

 ```
resource "mongodbatlas_encryption_at_rest" "test" {
  project_id = "<PROJECT-ID>"

  aws_kms = {
    enabled                = true
    access_key_id          = "AKIAIOSFODNN7EXAMPLE"
    secret_access_key      = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    customer_master_key_id = "030gce02-586d-48d2-a966-05ea954fde0g"
    region                 = "US_EAST_1"
  }
```

Actually this is not valid, because accessing AWS KMS with keys are deprecated. 

### Expected Behavior
Successful apply

### Actual Behavior
`Error: error creating Encryption At Rest: PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/xxxxxxxxxxxx/encryptionAtRest: 400 (request "AWS_KMS_CREDENTIALS_AUTH_DEPRECATED") Credentials based authentication is no longer supported for AWS KMS.`

**Comment by nikhil-mongo** [comment]
@bigvandi Thanks for pointing it out. We will update the documentation for this.

**Comment by themantissa** [comment]
@nikhil-mongo did you create a ticket for this?
