### ISSUE TITLE
Data resource for mongodbatlas_project reports null project_id due to changed interface but does not throw error.

### ISSUE THREAD

**Issue by monkeymantra** [mongodb/terraform-provider-mongodbatlas#429]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
# Copy-paste your version info here
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here

data mongodbatlas_project project {
  name = "my-project"
}

// used to work. Docs have been updated, but still returns a null instead of throwing exception. If provider is upgraded and user doesn't notice, this causes problems.

output project_id {
  value = data.mongodbatlas_project.project.project_id
}
```

### Expected Behavior
Now that project_id is no longer the exported attribute (it's `id` now) it should throw an error instead of returning null.

### Actual Behavior

Returns null

**Comment by themantissa** [comment]
Thank you @monkeymantra for the report.  @nikhil-mongo would you be able to do a quick repro and throw the log in a PRODTRIAGE ticket?  Thank you!

**Comment by nikhil-mongo** [comment]
@monkeymantra We have identified the difference and are going to work on it. PRODTRIAGE-1627 has been submitted internally for the doc update and recommendation when running **terraform apply**.

**Comment by nikhil-mongo** [comment]
INTMDB-128 has the fix released. terraform-provider-v1.0.0
