### ISSUE TITLE
Apple Silicon (darwin/arm64) support

### ISSUE THREAD

**Issue by tobernguyen** [mongodb/terraform-provider-mongodbatlas#430]
### Description
Please could you add support for Apple Silicon (aka release darwin/arm64 binaries) - this would require adopting Go 1.16

### References
Goes along with hashicorp/terraform#27257

**Comment by themantissa** [comment]
@tobernguyen thank you for the submission!  A solid feature request and one we can investigate.  I encourage you to post this in the Terraform category via https://feedback.mongodb.com/ as that allows other users to upvote the request.

**Comment by davl3232** [comment]
Hey, I just created one here if you're interested:
https://feedback.mongodb.com/forums/924145-atlas/suggestions/43110909-support-arm64-in-terraform-provider-mongodbatlas

**Comment by themantissa** [comment]
Thank you @davl3232 !  @tobernguyen please upvote that if you'd like to express this request in the best forum.   I'll close this issue for now as we track requests there.
