### ISSUE TITLE
TF support for creating api keys

### ISSUE THREAD

**Issue by JohnPolansky** [mongodb/terraform-provider-mongodbatlas#433]
I've been reviewing the [TF MongoDBAtlas 0.8.2](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest) page, and unless I'm missing it I don't see any resources for creating "API Keys" within Atlas. Is it supported?

I found the Atlas API clearly supports it: [Atlas API - Create Project APIKey](https://docs.atlas.mongodb.com/reference/api/projectApiKeys/create-one-apiKey-in-one-project/) and I tested with Postman and was able to create an API Key but I don't see how to do this with Terraform.

Use-Case: I realize that Terraform needs to have an API-Key in order to even work with Mongo Atlas, however in our case, we use a Terraform API key to build the clusters, and along with the cluster creation we want to create an API Key for that specific cluster. The reason for this is we use another tool that auto-provisions new customers and to do so that tool needs access to the API and this specific project. Since the tool is used on a per cluster basis, we wanted to limit security access by creating project base access keys, limits accidents, and improves security.

Can someone help let me know if I missed something? If it is missing can we do a feature request? As we plan to spin clusters up and down dynamically creating them by hand is not ideal.

Thanks,

John

**Comment by themantissa** [comment]
@JohnPolansky we have support for API key creation via the more secure method of using Vault:  https://www.vaultproject.io/docs/secrets/mongodbatlas   We wrote the Vault plugin and worked with HashiCorp to have included in order to ensure the most secure way to create and manage the keys.   If you'd still like the ability to create keys via Terraform itself (which will save that information in state) you can submit the feature request to https://feedback.mongodb.com   Thank you.

**Comment by jlamande** [comment]
Hi @themantissa,

_First, don't get me wrong, I am an happy customer using MongoDB Atlas on Cloud and I find this terraform provider really well engineered and useful._

I understand that using Hashicorp Vault may be a good practice to manage API Keys.

But here MongoDB deliberately chooses to obfuscate a feature that is available in the public API and enforces customers to use an external tool as Hashicorp Vault.

Vault is not used by every team on the planet and deploying it for managing MongoDB Project API Keys can have much more implications (other Vault solutions, ...).

I am not sure to get where MongoDB is trying to drive its customers by gently enforcing them to use Hashicorp Vault.

I am convinced that it should be a deliberate choice by customers to use or not a Vault for managing API Keys. Without this feature we have to manually create API Keys or automate their creation through another tool than terraform or using a 3rd party terraform provider :-/

**Comment by jlamande** [comment]
Added my comment to this feedback too : https://feedback.mongodb.com/forums/924145-atlas/suggestions/44775568-terraform-integration-to-manage-project-s-api-keys
