### ISSUE TITLE
mongodbatlas_private_endpoint and mongodbatlas_private_endpoint_interface_link gets re-created everytime

### ISSUE THREAD

**Issue by anshulpatel25** [mongodb/terraform-provider-mongodbatlas#464]
Hello,

https://github.com/mongodb/terraform-provider-mongodbatlas/issues/406 suggests that the issue is resolved with `0.8.2` but we are facing the same issue even with `0.8.2`

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```bash
$  terraform version
Terraform v0.12.13

$ terraform init
Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "mongodbatlas" (terraform-providers/mongodbatlas) 0.8.2...
- Downloading plugin for provider "aws" (hashicorp/aws) 3.37.0...
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_private_endpoint" "atlaspl" {
  project_id    = "${mongodbatlas_project.project.id}"
  provider_name = "AWS"
  region        = "${var.aws_region}"
}

resource "aws_vpc_endpoint" "ptfe_service" {
  vpc_id             = "${var.vpc_id}"
  service_name       = "${mongodbatlas_private_endpoint.atlaspl.endpoint_service_name}"
  vpc_endpoint_type  = "Interface"
  subnet_ids         = "${var.subnet_ids}"
  security_group_ids = [aws_security_group.atlas_sg.id]
}

resource "mongodbatlas_private_endpoint_interface_link" "atlaseplink" {
  project_id            = "${mongodbatlas_private_endpoint.atlaspl.project_id}"
  private_link_id       = "${mongodbatlas_private_endpoint.atlaspl.private_link_id}"
  interface_endpoint_id = "${aws_vpc_endpoint.ptfe_service.id}"
}
```
### Steps to Reproduce
1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. Change any other code apart from the above.
5. `terraform plan`
6. `terraform apply`

### Expected Behavior

- MongoDB provider should apply the other code changes and shouldn't re-create private links

### Actual Behavior

- On every `plan` and `apply` MonogDB provider is recreating the private link even though there is no code change in it.

```bash
  # mongodbatlas_private_endpoint.atlaspl must be replaced
-/+ resource "mongodbatlas_private_endpoint" "atlaspl" {
      ~ endpoint_service_name = "censored" -> (known after apply)
      + error_message         = (known after apply)
      ~ id                    = "censored" -> (known after apply)
      ~ interface_endpoints   = [
          - "censored",
        ] -> (known after apply)
      ~ private_link_id       = "censored" -> (known after apply)
        project_id            = "censored"
      + provider_name         = "AWS" # forces replacement
      + region                = "censored" # forces replacement
      ~ status                = "AVAILABLE" -> (known after apply)
    }

  # mongodbatlas_private_endpoint_interface_link.atlaseplink must be replaced
-/+ resource "mongodbatlas_private_endpoint_interface_link" "atlaseplink" {
      ~ connection_status     = "AVAILABLE" -> (known after apply)
      ~ delete_requested      = false -> (known after apply)
      + error_message         = (known after apply)
      ~ id                    = "censored" -> (known after apply)
      ~ interface_endpoint_id = "censored" -> (known after apply) # forces replacement
      ~ private_link_id       = "censored" -> (known after apply) # forces replacement
        project_id            = "censored"

```
### References

- https://github.com/mongodb/terraform-provider-mongodbatlas/issues/406

**Comment by themantissa** [comment]
@leofigy can you take a look at this please?

**Comment by leofigy** [comment]
Hello @anshulpatel25 in 0.8.2 we added the steps to upgrade from deprecated resources to the new resources. 
But we didn't document at the time, how to "upgrade" deprecated resources, there was a change in the state in order to support the upgrade. 

So, we document the steps in 0.9.1 however the same steps apply if you're using 0.8.2 
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/guides/0.9.1-upgrade-guide#upgrading-private-endpoint-and-private-endpoint-interface-link

But as the document says, please always backup :)

**Comment by anshulpatel25** [comment]
Thanks @leofigy, so If I understood correctly, If I need to avoid re-creation everytime I will require to move to `mongodbatlas_privatelink_endpoint` and `mongodbatlas_privatelink_endpoint_service`, right? Please do correct me if I misunderstood

**Comment by leofigy** [comment]
Hi @anshulpatel25. Let me explain myself. You have to options to avoid the recreation bug. 

- The First option is to re-import the deprecated resources using the 0.8.2/0.9.1 release this will fix the diff in the plan,  and you can follow the guide at https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/guides/0.9.1-upgrade-guide#upgrading-private-endpoint-and-private-endpoint-interface-link

- The second option is as you said migrate from the deprecated resources to the new ones using the guide https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/guides/0.9.1-upgrade-guide#upgrading-private-endpoint-and-private-endpoint-interface-link

:) both options are valid

**Comment by anshulpatel25** [comment]
Thanks a ton @leofigy, solution number one worked for us.
