### ISSUE TITLE
Documentation: Update contribution readme for developing the provider for terraform +14 newer

### ISSUE THREAD

**Issue by leofigy** [mongodb/terraform-provider-mongodbatlas#466]
As part of the terraform +14 , there is a new approach to tell terraform where to get the provider for development

https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers

**Comment by themantissa** [comment]
@leofigy  do we need an internal ticket for this?

**Comment by leofigy** [comment]
Hi @themantissa , I think we don't need the internal ticket, is just a quick readme update :) just for devs.

**Comment by themantissa** [comment]
@abner-dou did you get a chance to update the README for this so we can close this out?

**Comment by abner-dou** [comment]
@themantissa this change was already done some months ago in the README file :)
