### ISSUE TITLE
documentation: Azure private link example

### ISSUE THREAD

**Issue by jbrannst** [mongodb/terraform-provider-mongodbatlas#469]
Hi, this repo showcases linking on Azure
https://github.com/eugenebogaart/Atlas-Azure-Link

**Comment by themantissa** [comment]
@jbrannst yes, that seems to have been created by Eugene Bogaart, one of our MongoDB SAs.   I'm not sure what the purpose of this issue is though?

**Comment by jbrannst** [comment]
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs#examples-from-the-community

Den tors 3 juni 2021 23:02Melissa Plunkett ***@***.***> skrev:

**Comment by themantissa** [comment]
Ah, thank you - that helps. So you are suggesting we add this to the docs.  I"ll reach out to the creator and check if that's okay with them first.  If so we will add it.

**Comment by nikhil-mongo** [comment]
@jbrannst We have [Atlas Azure VNET peering](https://github.com/mongodb/terraform-provider-mongodbatlas/tree/master/examples/mongodbatlas-azure-vnet-peering) example in our repo. We can surely look to improve it if there is scope to do it and it benefits the users.
Please have a look and let  us know.

Thanks

**Comment by themantissa** [comment]
@nikhil-mongo  good point!   I'll add do a docs PR to add a link to our own examples in the repo.

**Comment by themantissa** [comment]
Added for next release.
