### ISSUE TITLE
Cluster region does not change after cluster creation

### ISSUE THREAD

**Issue by ddmedvedev** [mongodb/terraform-provider-mongodbatlas#478]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v0.15.4
mongodb/mongodbatlas v0.9.1
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_cluster" "this" {
  project_id                   = "my_project_id"
  provider_name                = "AWS"
  name                         = "test-cluster"
  provider_instance_size_name  = "M10"
  cluster_type                 = "REPLICASET"
  disk_size_gb                 = 10
  mongo_db_major_version       = "4.4"
  num_shards                   = 1
  provider_region_name         = "EU_CENTRAL_1"
  provider_volume_type         = "STANDARD"
}
```

### Steps to Reproduce
1. run `terraform init`
2. run `terraform apply`
3. change `provider_region_name` to something different, e.g. `EU_WEST_1`
4. run `terraform plan` (no errors will be shown, just `~ update in-place`)
5. run `terraform apply`(will shown `Modifications complete`)
6. login into https://cloud.mongodb.com and make sure that nothing changed
7. run `terraform plan` (no errors will be shown, just `~ update in-place`)
8. run `terraform apply`(will shown `Modifications complete`)
9. login into https://cloud.mongodb.com and make sure that nothing changed
etc.

### Expected Behavior
Change of cluster region from `eu-central-1` to `eu-west-1`

### Actual Behavior
Cluster region does not changed

**Comment by themantissa** [comment]
Thank you for the report @ddmedvedev.   Let us take a look and run a repo.

**Comment by nikhil-mongo** [comment]
@ddmedvedev I could repro the issue with the provided configuration. But please note, that we are no more using this older configuration for creating the cluster. 
Please see our documentation for the [resource cluster creation](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster).

You will need to provide the `replication_specs` explicitly in the configuration and everything will work as expected.

Thanks
