### ISSUE TITLE
Unsupported argument `bi_connector_config` 

### ISSUE THREAD

**Issue by mdiianni** [mongodb/terraform-provider-mongodbatlas#491]
# Problem
When replacing the deprecated parameter `bi_connector` with the `bi_connector_config` which seems to be now a list, Terraform plan fails with the following:
```
Error: Unsupported argument

  on .terraform/modules/mongodbatlas/main.tf line 136, in resource "mongodbatlas_cluster" "cluster":
 136:   bi_connector_config = {...}

An argument named "bi_connector_config" is not expected here. Did you mean to
define a block of type "bi_connector_config"?
```

# Current config
* Terraform version: `v0.13.3`
* Terraform aws provider: `~> 3.42`
* Terraform MongoDBAtlas provider: `0.9.1`
 
Trying to replace previous parameter settings with new `bi_connect_config` does not seem to work, could you provide an example on how those should be now?
```hcl
  bi_connector = {
    enabled         = var.bi_connector.enabled
    read_preference = var.bi_connector.read_preference
  }
```

Thanks in advance

**Comment by nikhil-mongo** [comment]
Hi @mdiianni 

Please use the below syntax for using the bi_connector_config

```
  bi_connector_config{
    enabled = true
    read_preference = "secondary"
  }
```

Thanks
