### ISSUE TITLE
Add resource for custom database roles

### ISSUE THREAD

**Issue by mpaluchowski** [mongodb/terraform-provider-mongodbatlas#50]
Could we have a resource for creating custom database roles? There is [the API for that](https://docs.atlas.mongodb.com/reference/api/custom-roles-create-a-role/) available.

**Comment by themantissa** [comment]
@mpaluchowski  we are taking feedback on what is needed for the next version of the provider at https://feedback.mongodb.com/forums/924145-atlas?category_id=370723 please add this suggestion there.  Thank you!

**Comment by themantissa** [comment]
Closing as suggestion was added to https://feedback.mongodb.com/forums/924145-atlas?category_id=370723, if others need please vote/comment there.
