### ISSUE TITLE
specify oplog size?

### ISSUE THREAD

**Issue by aeugenio** [mongodb/terraform-provider-mongodbatlas#52]
hello,

when will the `mongodbatlas_cluster` resource have support for setting the oplog size?  i dont see anything in the docs atm.

i also stood up a cluster via tf,  set the oplog size manually in the console, and then ran a `terraform plan` which results in `No changes. Infrastructure is up-to-date.` .  This would imply oplog size isn't supported at all yet.

thanks.

**Comment by themantissa** [comment]
Hi @aeugenio,  We will be including support for advanced config options soon.   Will keep you updated.  Thank you!

**Comment by PacoDw** [comment]
Hi! @aeugenio, thanks for your review, the advanced configuration options, were integrated into the cluster resource. You can check it on the `cluster_advanced_config` branch.

Let us know if you have another comment.
