### ISSUE TITLE
Add resource for maintenance window

### ISSUE THREAD

**Issue by carlos4ndre** [mongodb/terraform-provider-mongodbatlas#55]
Hi!

I would like to know if there is any plan of supporting a resource for provisioning [maintenance windows](https://docs.atlas.mongodb.com/reference/api/maintenance-windows-view-in-one-project/)?

This could be helpful to avoid setting this manually at the project level.

I'm new to Terraform but wouldn't mind to work on it, in case it makes sense.

Thanks

**Comment by themantissa** [comment]
Hi @carlos4ndre,  Per our README requests for new features for the provider can be made to https://feedback.mongodb.com/forums/924145-atlas?category_id=370723.   We do plan to continue to support more resources hence the submissions/votes there will help us rank user need.  We also welcome community submissions, see the README for more.  Thanks!

**Comment by PacoDw** [comment]
Thanks, @themantissa and @carlos4ndre  so much for your review, we will check what happens with it, @carlos4ndre can you help sharing us the Terraform configuration to recreate the issue?
