### ISSUE TITLE
mongodbatlas_auditing documentation mismatch

### ISSUE THREAD

**Issue by damien-vdb** [mongodb/terraform-provider-mongodbatlas#555]
```hcl
# 1.0.1
```

### Steps to Reproduce

Visit the current documentation for auditing: [https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/auditing](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/auditing)

---
![image](https://user-images.githubusercontent.com/11858675/132177223-40adeb5a-ddd3-4995-8305-1721454c28f4.png)
---
### Actual Behavior

`audit_filter` is documented as `audit_authorization_success` and vice-versa.

**Comment by gssbzn** [comment]
Hi @damienvdb06 thanks for reporting this, if you you want we'll be happy to accept a PR updating the docs, this is the file to update https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/website/docs/r/auditing.html.markdown

if not we'll review this as soon as possible

**Comment by nikhil-mongo** [comment]
@gssbzn @damienvdb06 I will take care of this shortly.

**Comment by themantissa** [comment]
Fix will go out to docs in next release.
