### ISSUE TITLE
Datalake configuration at creation time

### ISSUE THREAD

**Issue by luisllm** [mongodb/terraform-provider-mongodbatlas#561]
Hello,

First of all, I am not sure whether this a documentation bug or a feature request.

How are we supposed to create a functional mongodbatlas datalake without the config being part of the arguments?
In the documentation, the config is not part of the arguments, only part of the attributes you get once the datalake is created. Is it only possible to create like an empty datalake without any configuration, database, query, etc?
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/data_lake

Taking a look at the code, it seems like it should be possible to pass the config as the parameter, at the time you create the resource, by using "storage_stores", and "storage_databases":
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/data_source_mongodbatlas_data_lake.go

Thanks,
Luis

**Comment by themantissa** [comment]
@luisllm we added what was available to automated for Data Lake via the Atlas Administration API.  As you've noticed some configuration options are only exported (i.e. in the response) and not able to be configured via the API and so are not available in Terraform.  These must be configured via the UI.   The Product Manager, Ben Flast - benjamin.flast@mongodb.com, is aware of this and has informed me the team plans to add this ability.  When they do we will add the options to Terraform.  Feel free to reach out to him to provide more feedback.
