### ISSUE TITLE
gcp cluster doc issue

### ISSUE THREAD

**Issue by oreststetsiak** [mongodb/terraform-provider-mongodbatlas#568]
<!--
Hello!

there is a problem in official [doc for GCP](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#example-gcp-cluster)

according to a [doc](https://docs.atlas.mongodb.com/reference/google-gcp/#google-cloud-platform--gcp-) 
is should be **EASTERN_US** but not **US_EAST_1**
with  current config, terrafrom crash with meaningless error
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.mongodbatlas_instance.mongodbatlas_cluster.cluster: Creating...
╷
│ Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/$$$CHANGED$$$/clusters: 500 (request "UNEXPECTED_ERROR") Unexpected error.
│ 
│   with module.mongodbatlas_instance.mongodbatlas_cluster.cluster,
│   on ../../../modules/mongodbatlas/mongodbatlas_cluster/main.tf line 1, in resource "mongodbatlas_cluster" "cluster":
│    1: resource "mongodbatlas_cluster" "cluster" {
```

please fix that doc, or let me fix that
I just spent couple hours fixing it
regards!

**Comment by oreststetsiak** [comment]
omg, where is description lol
the issue is [here](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#example-gcp-cluster)

there is no **US_EAST_1**
[atlas doc](https://docs.atlas.mongodb.com/reference/google-gcp/#google-cloud-platform--gcp-) says it should be **EASTERN_US** for GCP

with **US_EAST_1** terraform fails like
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.mongodbatlas_instance.mongodbatlas_cluster.cluster: Creating...
╷
│ Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/$$$CHANGED$$$/clusters: 500 (request "UNEXPECTED_ERROR") Unexpected error.
│ 
│   with module.mongodbatlas_instance.mongodbatlas_cluster.cluster,
│   on ../../../modules/mongodbatlas/mongodbatlas_cluster/main.tf line 1, in resource "mongodbatlas_cluster" "cluster":
│    1: resource "mongodbatlas_cluster" "cluster" {
```
please fix that doc!

**Comment by nikhil-mongo** [comment]
@oreststetsiak Thank you for bringing to our attention. I will fix this shortly.

**Comment by oreststetsiak** [comment]
np
not sure, but other examples (aws azure etc) potentially might also be broken
just fyi
regards!

**Comment by themantissa** [comment]
Will go out to docs in next release.
