### ISSUE TITLE
Syntax are not mandatory and creates confusion

### ISSUE THREAD

**Issue by nikhil-mongo** [mongodb/terraform-provider-mongodbatlas#58]
To launch a cluster using terraform,
mongo_db_major_version       = “4.0” // this is in documentation and requires the version to be in string, but with version 4.2
mongo_db_major_version       = 4.2 // this will work without the “”. 

Please see if any changes need to be made to make this mandatory.

**Comment by PacoDw** [comment]
Hello @nikhil-mongo,
Thanks for your review, I made a few changes to allow string and float types to be able to set to the mongo_db_major_version attr, you can check the changes on the pr #63.

If you have another comment plz let us know.
