### ISSUE TITLE
INVALID_CLUSTER_CONFIGURATION when modifying a cluster to use replication_specs (eg for multi-region)

### ISSUE THREAD

**Issue by BlacCello** [mongodb/terraform-provider-mongodbatlas#588]
We have an issue when we want to modify a single-region cluster (which uses a in the meantime deprecated configuration) to use multi-region.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
```terraform
terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 1.0.2"
    }
  }
  required_version = ">= 1.0.9"
}
```

### Terraform Configuration File 

With the following snippets it is possible to reproduce the issue. Please note that because of history reasons, the there is no use of "replication_specs" yet.

An already existing cluster is configured with the following code:
```terraform
resource "mongodbatlas_cluster" "cluster" {
  project_id = "XXX"
  name       = "debug"

  replication_factor           = 3
  cloud_backup                 = false
  pit_enabled                  = false
  auto_scaling_disk_gb_enabled = false
  mongo_db_major_version       = "4.2"

  provider_name               = "AZURE"
  provider_instance_size_name = "M10"
  provider_region_name        = "EUROPE_WEST"
}
```
The creation of the cluster like this works without issues.
Then, we want to change it to multi-region with:
```terraform
resource "mongodbatlas_cluster" "cluster" {
  project_id = "XXX"
  name       = "debug"

  cloud_backup                 = false
  pit_enabled                  = false
  auto_scaling_disk_gb_enabled = false
  mongo_db_major_version       = "4.2"
  cluster_type                 = "REPLICASET"

  num_shards = 1

  // Provider Settings "block"
  provider_name               = "AZURE"
  provider_instance_size_name = "M10"

  replication_specs {
    num_shards = 1
    regions_config {
      region_name     = "EUROPE_WEST"
      electable_nodes = 1
      priority        = 7
      read_only_nodes = 0
    }
    regions_config {
      region_name     = "EUROPE_NORTH"
      electable_nodes = 1
      priority        = 6
      read_only_nodes = 0
    }
    regions_config {
      region_name     = "GERMANY_WEST_CENTRAL"
      electable_nodes = 1
      priority        = 5
      read_only_nodes = 0
    }
  }
}
```

The plan looks as follows:
```terraform
# mongodbatlas_cluster.cluster will be updated in-place
  ~ resource "mongodbatlas_cluster" "cluster" {
        id                                      = "XXXXXXXXXXXX"
        name                                    = "debug"
        # (29 unchanged attributes hidden)

      - replication_specs {
          - id         = "XXXXXXXXXXXXXX" -> null
          - num_shards = 1 -> null
          - zone_name  = "Zone 1" -> null

          - regions_config {
              - analytics_nodes = 0 -> null
              - electable_nodes = 3 -> null
              - priority        = 7 -> null
              - read_only_nodes = 0 -> null
              - region_name     = "EUROPE_WEST" -> null
            }
        }
      + replication_specs {
          + id         = (known after apply)
          + num_shards = 1
          + zone_name  = "ZoneName managed by Terraform"

          + regions_config {
              + analytics_nodes = 0
              + electable_nodes = 1
              + priority        = 5
              + read_only_nodes = 0
              + region_name     = "GERMANY_WEST_CENTRAL"
            }
          + regions_config {
              + analytics_nodes = 0
              + electable_nodes = 1
              + priority        = 6
              + read_only_nodes = 0
              + region_name     = "EUROPE_NORTH"
            }
          + regions_config {
              + analytics_nodes = 0
              + electable_nodes = 1
              + priority        = 7
              + read_only_nodes = 0
              + region_name     = "EUROPE_WEST"
            }
        }
        # (2 unchanged blocks hidden)
    }
```

### Steps to Reproduce

See configuration file section above. Steps: 
1. Create initial cluster (terraform apply) (code block with `replication_factor`)
2. Change terraform cluster configuration (code block with `replication_specs`)
3. terraform apply => fails

### Expected Behavior
Cluster should be changed without complaining about `INVALID_CLUSTER_CONFIGURATION`

### Actual Behavior
If we run `terraform apply` with the listed plan, we get the following error:
`Error: error updating MongoDB Cluster (debug): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXX/clusters/debug: 400 (request "INVALID_CLUSTER_CONFIGURATION") The specified cluster configuration is not valid.`

### Debug Output 
Both the initial cluster creation and the change to multi-region were logged with TF_LOG=trace.
See 
https://gist.github.com/BlacCello/9e36ee0d34fa981407e29564c9b9c7dd#file-initial_cluster_creation-log
https://gist.github.com/BlacCello/9e36ee0d34fa981407e29564c9b9c7dd#file-multi_region_change-log

### Additional Context

If we create the multi-region cluster from scratch, it works without issues, so the configuration in general has to be correct. We have already tested this migration with provider version 0.6 a few months ago and it worked, so this is a regression. 
The initial cluster was created with the deprecated version, because we have running production clusters with a similar configuration (same but different size + backend enabled) running, which have to be upgraded to multi-region.

> _Just a guess: It could relate to the replication_factor attribute that we still have applied to the "old clusters". Migrating to single region specified with replication_specs also does not work._
> That was going to be my question, if you tried updating your older format. So you did and this did not help?

I am not sure how to specify a multi-region cluster without the replication_specs attribute and by keeping the replication_factor attribute (I haven't found anything in the docs). Further, replication_factor is already deprecated, so it should be possible to replace it.

### References

Issue was initially mentioned in #550

**Comment by BlacCello** [comment]
For completeness, we also tried to change the config to use `replaction_specs` but without making it multi-region just to replace `replication_factor`.

It fails with the same issue, when we "migrate" from the "initial" cluster.
This is the single-region config which uses `replication_specs`:
```terraform
resource "mongodbatlas_cluster" "cluster" {
  project_id = "xxx"
  name       = "debug"

  cloud_backup                 = false
  pit_enabled                  = false
  auto_scaling_disk_gb_enabled = false
  mongo_db_major_version       = "4.2"
  cluster_type                 = "REPLICASET"

  // Provider Settings "block"
  provider_name               = "AZURE"
  provider_instance_size_name = "M10"

  replication_specs {
    num_shards = 1
    regions_config {
      region_name     = "EUROPE_WEST"
      electable_nodes = 3
      priority        = 7
      read_only_nodes = 0
    }
  }
}
```
Creating this cluster with this code from scratch as a new cluster succeeds.

**Comment by themantissa** [comment]
Thank you so much for getting this in and with such complete information @BlacCello.  I'll have the team take a look as soon as they can.

**Comment by themantissa** [comment]
Internal ticket INTMDB-273

**Comment by themantissa** [comment]
The fix for this issue will be in our next release, 1.1.0.  We expect that to come out very soon.  Thanks!

**Comment by 1uk4sh** [comment]
`v1.1.0` works, can be closed, thx!
