### ISSUE TITLE
PRIVATE_ENDPOINT_SERVICE_ALREADY_EXISTS_FOR_REGION

### ISSUE THREAD

**Issue by amontalban** [mongodb/terraform-provider-mongodbatlas#590]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.63.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.0.2

Your version of Terraform is out of date! The latest version
is 1.0.9. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_privatelink_endpoint" "mongodb" {
  project_id    = var.mongo_atlas_project_id
  provider_name = "AWS"
  region        = var.region
}

resource "aws_vpc_endpoint" "mongodb" {
  vpc_id            = module.vpc.vpc_id
  service_name      = mongodbatlas_privatelink_endpoint.mongodb.endpoint_service_name
  vpc_endpoint_type = "Interface"
  subnet_ids        = module.vpc.private_subnets

  security_group_ids = [module.mongodb_security_group.security_group_id]

  tags = merge({ Name = "mongo-atlas-vpc-endpoint" }, local.tags)
}

resource "mongodbatlas_privatelink_endpoint_service" "mongodb" {
  project_id          = mongodbatlas_privatelink_endpoint.mongodb.project_id
  private_link_id     = mongodbatlas_privatelink_endpoint.mongodb.private_link_id
  endpoint_service_id = aws_vpc_endpoint.mongodb.id
  provider_name       = "AWS"
}
```

### Steps to Reproduce
Create two VPCs in the same AWS account, and try to create two MongoDB Atlas Regional Cluster `mongodbatlas_cluster` each with a Private Endpoint in the same MongoDB Project.

### Expected Behavior
Have two VPCs, and two MongoDB Atlas Regional Clusters (Each one connected through a Private Endpoint to the VPCs).

According to the [documentation](https://docs.atlas.mongodb.com/security-private-endpoint/#limitations) I understand that I should be allowed to create more than one private endpoint in a single region:

```
You can do only one of the following:

- Create more than one private endpoint in a single region, or
- Create no more than one private endpoint per region, if nodes are deployed in more than one region.
```

### Actual Behavior

```
Error: error creating MongoDB Private Endpoints Connection: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/GROUP_ID/privateEndpoint/endpointService: 409 (request "PRIVATE_ENDPOINT_SERVICE_ALREADY_EXISTS_FOR_REGION") A private endpoint service already exists for AWS region US_EAST_1.
│ 
│   with mongodbatlas_privatelink_endpoint.mongodb,
│   on mongodb.tf line 29, in resource "mongodbatlas_privatelink_endpoint" "mongodb":
│   29: resource "mongodbatlas_privatelink_endpoint" "mongodb" {
```

**Comment by nikhil-mongo** [comment]
I was able to repro this using terraform, but succeeded in creating 2 private endpoints through UI.

>  Error: error creating MongoDB Private Endpoints Connection: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/608100122fe8ff3e1bf0c5c3/privateEndpoint/endpointService: 409 (request "PRIVATE_ENDPOINT_SERVICE_ALREADY_EXISTS_FOR_REGION") A private endpoint service already exists for AWS region EU_WEST_1.
│ 
│   with mongodbatlas_privatelink_endpoint.atlaspl,
│   on atlas-pl.tf line 1, in resource "mongodbatlas_privatelink_endpoint" "atlaspl":
│    1: resource "mongodbatlas_privatelink_endpoint" "atlaspl" {
│ 

But while working through the API requests to check how API requests behave I found out that the resource `"mongodbatlas_privatelink_endpoint" "mongodb"` needs to be created only once and should be referenced for the second private endpoint connection to be created.

Therefore you should follow something like the below example configuration.

```
//First Private Endpoint

resource "mongodbatlas_privatelink_endpoint" "atlaspl" {
  project_id    = var.atlasprojectid
  provider_name = "AWS"
  region        = var.aws_region
}

resource "aws_vpc_endpoint" "ptfe_service" {
  vpc_id             = aws_vpc.primary.id
  service_name       = mongodbatlas_privatelink_endpoint.atlaspl.endpoint_service_name
  vpc_endpoint_type  = "Interface"
  subnet_ids         = [aws_subnet.primary-az1.id, aws_subnet.primary-az2.id]
  security_group_ids = [aws_security_group.primary_default.id]
}

resource "mongodbatlas_privatelink_endpoint_service" "atlaseplink" {
  project_id          = mongodbatlas_privatelink_endpoint.atlaspl.project_id
  endpoint_service_id = aws_vpc_endpoint.ptfe_service.id
  private_link_id     = mongodbatlas_privatelink_endpoint.atlaspl.id
  provider_name       = "AWS"
}

//Second PrivateEndpoint

resource "aws_vpc_endpoint" "ptfe_service-1" {
  vpc_id             = aws_vpc.primary-1.id
  service_name       = mongodbatlas_privatelink_endpoint.atlaspl.endpoint_service_name
  vpc_endpoint_type  = "Interface"
  subnet_ids         = [aws_subnet.primary-az1-1.id, aws_subnet.primary-az2-1.id]
  security_group_ids = [aws_security_group.primary_default-1.id]
}

resource "mongodbatlas_privatelink_endpoint_service" "atlaseplink-1" {
  project_id          = mongodbatlas_privatelink_endpoint.atlaspl.project_id
  endpoint_service_id = aws_vpc_endpoint.ptfe_service-1.id
  private_link_id     = mongodbatlas_privatelink_endpoint.atlaspl.id
  provider_name       = "AWS"
}

```

**Comment by amontalban** [comment]
Hi @nikhil-mongo,

Thanks for that, I ended up creating a project for each cluster/endpoint.

In one of my runs I had this issue:

```
Failed to accept interface endpoint due to an unexpected error with code={InvalidParameter} and message={Cannot modify VPC Endpoint vpce-0dbb132faa5728740 at this time because there is an idempotent operation going on} from AWS API. Click 'Edit' to fix the problem.
```

But then I recreated everything and worked fine, so it must have been something sporadic.

In terms of the original issue, I think it would be good to document the limitation somewhere (Maybe in the Terraform provider docs?).

Thanks!

**Comment by ivankovnatsky** [comment]
@amontalban we're having the exact same issue as in your last comment.

It's also two different projects with separate private endpoints for different mongo db clusters. I'm inclined to think this is happening when we creating two environments concurrently. 

> But then I recreated everything and worked fine, so it must have been something sporadic.

I did not pay attention before, so was also just re-creating environments. It also went fine thereafter.

update:

To fix it without re-creating we could just edit the private endpoint:
![image](https://user-images.githubusercontent.com/75213/145201974-37c053cb-0cf0-4145-b61f-0c1f3c5c33d6.png)

changing to another vpc endpoint id and then back again to what we intend to use and it works fine, but having to deal with it manually is way too weird.

**Comment by nikhil-mongo** [comment]
@ivankovnatsky This is related to the functionality in Atlas and not Terraform related. So I will close this issue, as it is not related to Terraform. 
This is already being worked upon internally.

**Comment by pauldraper** [comment]
@nikhil-mongo any update on the internal work from 2021?

**Comment by Desislava-Petrova-IBM-1** [comment]
any update here?
