### ISSUE TITLE
update_snapshots is not getting set on Atlas while using "mongodbatlas_cloud_backup_schedule" tf resource 

### ISSUE THREAD

**Issue by prathish2503** [mongodb/terraform-provider-mongodbatlas#594]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
"Existing terraform version: Terraform v0.14.10"
"'mongodbatlas', 'version': '1.0.2'"
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
resource "mongodbatlas_cloud_backup_schedule" "backup_policies" {
  project_id   = mongodbatlas_cluster.atlas-cluster.project_id
  cluster_name = mongodbatlas_cluster.atlas-cluster.name

  reference_hour_of_day    = 1
  reference_minute_of_hour = 0
  restore_window_days      = 1
    update_snapshots         = true
    policy_item_hourly {
        frequency_interval = 6
        retention_unit     = "days"
        retention_value    = 1
    }
      policy_item_daily {
        frequency_interval = 1
        retention_unit     = "days"
        retention_value    = 7
    }
      policy_item_weekly {
        frequency_interval = 7
        retention_unit     = "weeks"
        retention_value    = 3
    }
}

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Expected Behavior
The backup policy on atlas gets updated with "Apply policy retention changes to existing snapshots" Enabled   (since update_snapshots : true  is set in tf configuration file)

### Actual Behavior
There are no errors while running terraform apply, But "Apply policy retention changes to existing snapshots" doesn't get enabled on Atlas side.

**Comment by themantissa** [comment]
@prathish2503 we really need all the information in the issue template to be able to help here.  Please add more information.

**Comment by themantissa** [comment]
Since no more information has been added closing this issue.  Feel free to reopen with additional data.
