### ISSUE TITLE
No way to modify advanced configuration options for a cluster

### ISSUE THREAD

**Issue by StephenBerezhnoy** [mongodb/terraform-provider-mongodbatlas#61]
https://docs.atlas.mongodb.com/reference/api/clusters-modify-advanced-configuration-options/

I'd like to be able to disable server-side javascript and specify the minimum enabled TLS protocol using terraform as can already be done through the mongoDB Atlas UI and API.

**Comment by PacoDw** [comment]
Hello @StephenBerezhnoy, 
Thanks for your review,  we have enabled the advanced configuration option in the pull request #60

If you have another comment just let us know.

**Comment by StephenBerezhnoy** [comment]
@PacoDw Wow! awesome, thank you. I was looking at the terraform docs for the mongoDB atlas here https://www.terraform.io/docs/providers/mongodbatlas/d/cluster.html and didn't see those options yet. I assume that's because those features were just added 3 hours ago.

So, I'm good to try them right now? or do I have to wait for a daily build or something like that?

**Comment by StephenBerezhnoy** [comment]
@PacoDw I see from trying a terraform init, and a terraform plan with the new configuration options, that it currently produces an error. When can I expect the terraform init to get the latest version with the advanced configuration options?

**Comment by PacoDw** [comment]
@StephenBerezhnoy These new changes are no deployed to Terraform yet if you want to use or test these new changes, you must use the master branch, just download this repo.

**Comment by StephenBerezhnoy** [comment]
@PacoDw  I'll just wait. Any idea when these changes will be deployed?

**Comment by PacoDw** [comment]
@StephenBerezhnoy I think the next week it's done, but if you need to work immediately with these new changes I recommend you to use the master branch because everything is ok there.

If you have another comment or question just let me know plz.
