### ISSUE TITLE
mongodb atlas network container atlas cidr block value and real  value is not mached

### ISSUE THREAD

**Issue by paikend** [mongodb/terraform-provider-mongodbatlas#617]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform v0.12.31
+ provider.mongodbatlas v1.0.2
```

### Terraform Configuration File 
```hcl
resource "mongodbatlas_network_container" "test" {
  project_id = mongodbatlas_project.test.id
  atlas_cidr_block = "10.255.0.0/16"
  provider_name = "AWS"
  region_name = "AP_NORTHEAST_2"
}
```

### Steps to Reproduce
1. terraform apply 
- applied planing infomations. But it is not reflected 

### Expected Behavior
terraform apply 'resource "mongodbatlas_network_container" ' resource. It is applied in main.state. 
It is same atlas cidr block in terraform remote state and real mongodb atlas cidr block.

### Actual Behavior
- terrafom remote state atlas cidr block value was "10.255.0.0/16". But real value was "192.~"

### Debug Output 
-

### Crash Output
-
### Additional Context
-

### References
-

**Comment by nikhil-mongo** [comment]
Hi @paikend Will it be possible for you to share the project ID over my email - nikhil.singh@mongodb.com

Also please note that if a cluster had existed in the region `AP_NORTHEAST_2` there is already a CIDR created by default and you will have to explicitly delete the Network container using Atlas API.
Having that said, I will be in better position to comment after verifying the project details.

Thanks

**Comment by nikhil-mongo** [comment]
@paikend Please confirm if this still persists, or are we good to close this.

**Comment by paikend** [comment]
sorry for late answer.
I understand the answer, but I'm looking forward to explaining it in more detail. So, I will send you the project ID by e-mail.
Thanks. :+1: 
happy new year

**Comment by themantissa** [comment]
@nikhil-mongo did you get the email?  Are we good to close this?

**Comment by nikhil-mongo** [comment]
@themantissa I am taking this forward over email. So, I will close it once we have the resolution.

**Comment by nikhil-mongo** [comment]
Hi @paikend I have asked for details over the email and due to no actions I am closing this issue. If you are still facing it, please reply on my email.
