### ISSUE TITLE
Cannot set multiple notifications for an alert

### ISSUE THREAD

**Issue by falcon-18-tech** [mongodb/terraform-provider-mongodbatlas#626]
Hello,

I wanted to set the multiple notifications for the same alert, but here in terraform resource of "mongodb_alert_configuration" we do not define notifications as an array, it poses a problem.
Whereas in MongoDB API we have the provision of setting up multiple alerts, therefore that must be somehow possible using terraform as well.
Here is the link of the MongoDB Atlas documentation for the creation of alerts using API, which has notification as an array in it's body.

https://docs.atlas.mongodb.com/reference/api/alert-configurations-create-config/#set-notifications

If that is already possible, do let me know.

**Comment by themantissa** [comment]
I don't believe it is currently possible with how the resource is setup but it should be.  Let me talk with the team on this item.

**Comment by themantissa** [comment]
Internal ticket INTMDB-282

**Comment by themantissa** [comment]
@falcon-18-tech so this seems to be a missing bit of documentation/examples on our part.   Looking at the code one or more notification block should work for the same alert, e.g.
notification { 
//set email
}
notification {
/set sms
}

That should work for you.   If so I'll ensure we get the documentation updated to make this clearer.

**Comment by falcon-18-tech** [comment]
Yes, it is working.
Thanks for the assistance.

It would be better to reflect this in the documentation as well.
