### ISSUE TITLE
Delete default alerts

### ISSUE THREAD

**Issue by falcon-18-tech** [mongodb/terraform-provider-mongodbatlas#628]
Hello,

Whenever we deploy any cluster using terraform or the web UI of the over Atlas, some of the alerts are autogenerated.
is there a way by which we can sanitize the alert section, as we don't require any alert by default since we want to use automation to configure all the alerts and to maintain similar alerts for all clusters?

Thank You.

**Comment by themantissa** [comment]
This just came out in the latest release @falcon-18-tech - see the project resource documentation for details.   It will allow you to create a project with no default alerts.

**Comment by asklokesh** [comment]
```
# Disable default alerts by setting alerts_config to an empty block
  alerts_config {
    project_alerts_enabled = false
  }
```
