### ISSUE TITLE
Not able to create M0 clusters

### ISSUE THREAD

**Issue by jackivanov** [mongodb/terraform-provider-mongodbatlas#64]
Hello,

For some reason I can't create M0 clusters via terraform. Meanwhile I can do it in the UI.

```
resource "mongodbatlas_cluster" "default" {
  name                        = "M0"
  project_id                  = mongodbatlas_project.backend.id
  provider_name               = "GCP"
  provider_region_name        = "WESTERN_EUROPE"
  provider_instance_size_name = "M0"
}
```
> Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/XXX/clusters: 400 (request "Bad Request") An invalid enumeration value M0 was specified.

```
resource "mongodbatlas_cluster" "default" {
  name                        = "M0"
  project_id                  = mongodbatlas_project.backend.id
  provider_name               = "TENANT"
  provider_region_name        = "WESTERN_EUROPE"
  provider_instance_size_name = "M0"
}
```
> Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/XXX/clusters: 400 (request "Bad Request") Invalid attribute instanceSizeName specified.

**Comment by jackivanov** [comment]
> API Access | You cannot modify or configure an M0 Free Tier cluster using the Clusters API endpoint. A subset of API endpoints support M2 and M5 shared clusters.

**Comment by ahanoff** [comment]
@jackivanov I'm getting same error for M2/M5 clusters with AWS. Based on docs it should be available https://docs.atlas.mongodb.com/reference/api/clusters-create-one/ 🤔  ?

**Comment by ahanoff** [comment]
All right, figure it out using correct **provider_name** and **backing_provider_name** for M2/M5:

> auto_scaling_disk_gb_enabled = false
>
>  //Provider Settings "block"
>  provider_name               = "TENANT"
>  backing_provider_name = "AWS"
>  disk_size_gb                = 2
>  provider_instance_size_name = "M2"
