### ISSUE TITLE
backup snapshot and restore not working automated 

### ISSUE THREAD

**Issue by ealbarqat** [mongodb/terraform-provider-mongodbatlas#642]
Hello, 

I am using mongodbatlas_cloud_backup_snapshot and mongodbatlas_cloud_backup_snapshot_restore_job in my templates to provision a cluster and then restore a snapshot from a specific project to it, I am using automated = true for the delivery type but the snapshot shows on Backup page as "on-demand" and provide me a link to download it, what I need is to automatically restore it. 

What happens is that main dbs and collections are created in my newly cluster but they are empty, I need to know what went wrong and how I can achieve my goal using terraform , Thanks

My config: 

resource "mongodbatlas_cluster" "config" {
  project_id = mongodbatlas_project.env-project.id
  name       = "${terraform.workspace}-config"
  num_shards = 1

  replication_factor                              = 3
  cloud_backup                         = true
  auto_scaling_disk_gb_enabled                    = true
  mongo_db_major_version                          = "4.2"
  auto_scaling_compute_enabled                    = true
  provider_auto_scaling_compute_max_instance_size = "M50"
  auto_scaling_compute_scale_down_enabled         = true
  provider_auto_scaling_compute_min_instance_size = "M10"

  //Provider Settings "block"
  provider_name               = "AWS"
  disk_size_gb                = 10
  provider_disk_iops          = 100
  provider_volume_type        = "STANDARD"
  provider_encrypt_ebs_volume = true
  provider_instance_size_name = "M10"
  provider_region_name        = "US_EAST_1"
}
// for Mongo Atlas Snapshots Migration
//-------------------------------------------
// this is for creating Snapshots
resource "mongodbatlas_cloud_backup_snapshot" "config-snapshot" {
  project_id        = "XXXXXXXXX"
  cluster_name      = "subConfig"
  description       = "Snapshot for Mongo Atlas DB"
  retention_in_days = 1
}

// this is for restoring Snapshots
resource "mongodbatlas_cloud_backup_snapshot_restore_job" "config-snapshot-restore" {
  project_id   = mongodbatlas_cloud_backup_snapshot.config-snapshot.project_id
  cluster_name = mongodbatlas_cloud_backup_snapshot.config-snapshot.cluster_name
  snapshot_id  = mongodbatlas_cloud_backup_snapshot.config-snapshot.snapshot_id
  delivery_type = {
    automated           = true
    target_cluster_name = "${mongodbatlas_cluster.config.name}"
    target_group_id   = "${mongodbatlas_cluster.config.project_id}"
  }
 
}

Versions: 
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.68.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.1.1

**Comment by nikhil-mongo** [comment]
@ealbarqat The below configuration works as required for your use case. Please ensure that the API key used here has access to both the projects as `Project Owner`.

```
resource "mongodbatlas_cluster" "config" {
  project_id = "<DestinationProjectID>"
  name       = "restore"
  num_shards = 1

  replication_factor                              = 3
  cloud_backup                                    = true
  auto_scaling_disk_gb_enabled                    = true
  mongo_db_major_version                          = "4.4"
  auto_scaling_compute_enabled                    = true
  provider_auto_scaling_compute_max_instance_size = "M50"
  auto_scaling_compute_scale_down_enabled         = true
  provider_auto_scaling_compute_min_instance_size = "M10"

  //Provider Settings "block"
  provider_name               = "AWS"
  disk_size_gb                = 80
//  provider_disk_iops          = 100
  provider_volume_type        = "STANDARD"
//  provider_encrypt_ebs_volume = true
  provider_instance_size_name = "M10"
  provider_region_name        = "US_EAST_1"
}
// for Mongo Atlas Snapshots Migration
//-------------------------------------------
// this is for creating Snapshots
resource "mongodbatlas_cloud_backup_snapshot" "config-snapshot" {
  project_id        = "<SourceProjectID>"
  cluster_name      = "Cluster0"
  description       = "Snapshot for Mongo Atlas DB"
  retention_in_days = 1
}

// this is for restoring Snapshots
resource "mongodbatlas_cloud_backup_snapshot_restore_job" "config-snapshot-restore" {
  project_id   = mongodbatlas_cloud_backup_snapshot.config-snapshot.project_id
  cluster_name = mongodbatlas_cloud_backup_snapshot.config-snapshot.cluster_name
  snapshot_id  = mongodbatlas_cloud_backup_snapshot.config-snapshot.snapshot_id
  delivery_type_config   {
    automated           = true
    target_cluster_name = mongodbatlas_cluster.config.name
    target_project_id     = mongodbatlas_cluster.config.project_id
  }

}

```

**Comment by ealbarqat** [comment]
Hello @nikhil-mongo 

I used the above as you mentioned and I made sure the api-key is a project owner for both of projects, its still the same result 
collections are created but empty all with zero size 

plus on the source project cluster under "snapshots" I can see on demand snapshot was created, but under "restore and downloads" I see this : 
![image](https://user-images.githubusercontent.com/23294621/147713226-fe4ac8a4-df0c-41b3-84bc-97242d3a1838.png)

its Manual download and I already used "automated" delivery type

also is the major engine version related ? my source cluster is 4.2 that's why am using it with my target cluster.
please advice
ThanQ

**Comment by nikhil-mongo** [comment]
Helllo @ealbarqat 

Can you share the project ID and other details on my [email](mailto:nikhil.singh@mongodb.com). This seems to be some issue local to your configuration and not with provider. If possible please raise a support case and mention this git issue link. 

Thanks

**Comment by ealbarqat** [comment]
I opened a support case and I mentioned this git issue
Thanks

**Comment by nikhil-mongo** [comment]
Thanks @ealbarqat We will look into it.

Closing this git issue and tracking internally.
