### ISSUE TITLE
mongodbatlas_teams provides a Team resource

### ISSUE THREAD

**Issue by wshao12** [mongodb/terraform-provider-mongodbatlas#649]
Is mongodbatlas_teams or mongodbatlas_team in your documentation?

**Comment by themantissa** [comment]
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/team

**Comment by themantissa** [comment]
You'll also need https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project to assign.
