### ISSUE TITLE
Error in documentation page : aws_kms -> aws_kms_config

### ISSUE THREAD

**Issue by dwgillies-bluescape** [mongodb/terraform-provider-mongodbatlas#666]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

documentation page:
https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/encryption_at_rest

"aws_kms - (Required) Specifies AWS KMS configuration details and whether Encryption at Rest is enabled for an Atlas project."

According to terraform and your documentation, the name "aws_kms" has been changed to "aws_kms_config".  Please make sure the whole web page is consistent in describing "aws_kms_config.

```hcl
n/a
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
```

**Comment by nikhil-mongo** [comment]
@dwgillies-bluescape This is already in process along with other doc changes and we will soon release it on the web

**Comment by nikhil-mongo** [comment]
@dwgillies-bluescape The changes have been submitted as PR #670. You will be seeing the changes with our next release and I will now close this case.
