### ISSUE TITLE
Support for AWS security groups in mongodbatlas_project_ip_whitelist

### ISSUE THREAD

**Issue by sjauld** [mongodb/terraform-provider-mongodbatlas#67]
The Atlas API supports adding security groups to a Project IP Whitelist, by specifying the security group ID in the `cidr_block` field.

However since we validate that `cidr_block` is a CIDR block, we can't input security groups here.

I'll throw together a quick PR.

**Comment by sjauld** [comment]
Actually, on further inspection, the Atlas API *returns* security group IDs in the cidr_block field, but doesn't *accept* them when you post it. I'll raise a ticket with them.

**Comment by sjauld** [comment]
No ticketing system exists for the API, but feel free to +1 this tweet if you want to support my request 👍  https://twitter.com/sjogrady/status/1194116135551029251

**Comment by themantissa** [comment]
Security group support was actually very recently added to the MongoDB Atlas IP Whitelist resource.  We have it on our roadmap to add support for it via the Provider as soon as we can schedule engineering resources to tackle it.   

For future reference,  per the README, feature requests can be made via https://feedback.mongodb.com for both MongoDB Atlas (and its API) as well as the Terraform provider.  

I'll leave this open until we add support and we'll post here when it's added.
