### ISSUE TITLE
Can't create M0 free tier on Azure

### ISSUE THREAD

**Issue by czmirek** [mongodb/terraform-provider-mongodbatlas#675]
I'm not really sure what I'm doing wrong, I'm following the documentation, according to [this](https://docs.atlas.mongodb.com/reference/api/clusters-create-one/) M0 on Azure should work... but I'm getting `INVALID_ENUM_VALUE` instead.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
```
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.8
+ provider registry.terraform.io/mongodb/mongodbatlas v1.2.0
```

### Terraform Configuration File 
```hcl
resource "mongodbatlas_project" "project" {
  name   = "MyProject"
  org_id = var.org_id
}

resource "mongodbatlas_cluster" "cluster" {
  project_id   = mongodbatlas_project.project.id
  name         = "mycluster"
  cluster_type = "REPLICASET"
  provider_name = "AZURE"
  provider_region_name = "EUROPE_WEST"
  provider_instance_size_name = "M0"
}
```

### Steps to Reproduce
`terraform apply`

### Expected Behavior
Free tier cluster is created

### Actual Behavior
```
│ Error: error creating MongoDB Cluster: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/***REDACTED***/clusters: 400 (request "INVALID_ENUM_VALUE") An invalid enumeration value M0 was specified.
│
│   with mongodbatlas_cluster.cluster,
│   on atlas.tf line 6, in resource "mongodbatlas_cluster" "cluster":
│    6: resource "mongodbatlas_cluster" "cluster" {
```

### References

**Comment by czmirek** [comment]
Okay I found out the right way

```hcl
resource "mongodbatlas_cluster" "cluster" {
  project_id   = mongodbatlas_project.project.id
  name         = "mycluster"
  cluster_type = "REPLICASET"
  provider_name = "TENANT"
  backing_provider_name = "AZURE"
  provider_region_name = "EUROPE_WEST"
  provider_instance_size_name = "M0"
}
```

**Comment by rlachic** [comment]
I am having the same issue that @czmirek reported. I am using the latest version, and I have to use parameters from mongodbatlas "v1.2.0" provider. I am using Terraform 1.26.0. Could you reopen the issue?

**Comment by thdk** [comment]
Note that you are only allowed one free cluster per project. If you run into this error it might be that you have already a sandbox (M0) cluster.

I verfied this by trying to add one extra M0 cluster from the web interface and got: "This project already has another free cluster:
