### ISSUE TITLE
Auto scaling of storage cannot be disabled for mongodbatlas_advanced_cluster via "disk_gb_enabled"

### ISSUE THREAD

**Issue by BlacCello** [mongodb/terraform-provider-mongodbatlas#677]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.1.5
on linux_amd64
...
+ provider registry.terraform.io/mongodb/mongodbatlas v1.2.0
...
```

### Steps to Reproduce
Create a cluster with the following settings
```terraform
resource "mongodbatlas_advanced_cluster" "cluster" {
  project_id = var.project_id
  name       = var.cluster_name
  cluster_type           = "REPLICASET"

  replication_specs {
    region_configs {
      electable_specs {
        instance_size = "M10"
        node_count    = 3
      }
      auto_scaling {
        disk_gb_enabled = false
      }
      provider_name = "AZURE"
      priority      = 7
      region_name   = "EUROPE_WEST"
    }
  }
}
```
The plan shows that the replication_specs object is recreated with `disk_gb_enabled = false`
Run `terraform apply`

### Expected Behavior

After the apply, storage auto scaling is disabled and subsequent plans don't show any changes 

### Actual Behavior

Storage auto scaling is enabled when looking at the UI (Cluster Configuration). Subsequent plan/apply runs still want to recreate replication_specs because of `storage_autoscaling_enabled -> false` but it stays enabled.
 
### Debug Output 
Not yet possible for me to create, since the migration to advanced cluster is currently on hold in our project. Nevertheless, I hope that this case is easy enough to reproduce very fast; otherwise I can try to do this the next days.

**Comment by nikhil-mongo** [comment]
@BlacCello As per the repro, this seems to be underlying API issue and not related to Terraform provider. I have filed an internal ticket to address this. It is better we can close this here as this will be handled for the API releases and not with Terraform provider.

Thanks

**Comment by nikhil-mongo** [comment]
HELP-31579 filed internally.

**Comment by themantissa** [comment]
Closing as not a Terraform issue.
