### ISSUE TITLE
Error: error creating MongoDB Network container, A container already exists for group

### ISSUE THREAD

**Issue by sumit-s-agrawal** [mongodb/terraform-provider-mongodbatlas#684]
Terraform Version
  required_version = ">= 1.0"

### Terraform Configuration File 

```hcl
data "aws_caller_identity" "account" {}

data "aws_vpc" "primary" {
  id = var.vpc.vpc_id
}

data "mongodbatlas_project" "aws_atlas" {
  project_id = var.atlas_project_id
}

resource "mongodbatlas_network_container" "atlas_container" {
  atlas_cidr_block = var.atlas_vpc_cidr
  project_id       = data.mongodbatlas_project.aws_atlas.id
  provider_name    = "AWS"
  region_name      = var.atlas_region
}

data "mongodbatlas_network_container" "atlas_container" {
  container_id = mongodbatlas_network_container.atlas_container.container_id
  project_id   = data.mongodbatlas_project.aws_atlas.id
}

resource "mongodbatlas_network_peering" "aws-atlas" {
  accepter_region_name   = var.aws_region
  project_id             = data.mongodbatlas_project.aws_atlas.id
  container_id           = mongodbatlas_network_container.atlas_container.container_id
  provider_name          = "AWS"
  route_table_cidr_block = data.aws_vpc.primary.cidr_block
  vpc_id                 = data.aws_vpc.primary.id
  aws_account_id         = data.aws_caller_identity.account.account_id
}

resource "aws_route" "peeraccess" {
  route_table_id            = data.aws_vpc.primary.main_route_table_id
  destination_cidr_block    = var.atlas_vpc_cidr
  vpc_peering_connection_id = mongodbatlas_network_peering.aws-atlas.connection_id
  depends_on                = [aws_vpc_peering_connection_accepter.peer]
}

resource "aws_vpc_peering_connection_accepter" "peer" {
  vpc_peering_connection_id = mongodbatlas_network_peering.aws-atlas.connection_id
  auto_accept               = true
}

```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

### Expected Behavior
Peer Atlas VPC with AWS VPC. 
### Actual Behavior
I tried to run the above module for multiple VPC peering connections, for first one it worked and for all others it failed with A container already exists for group error.

**Comment by themantissa** [comment]
@sumit-s-agrawal that's likely because you have already created the needed container.  Note the following in the container documentation: 
The following is the maximum number of Network Peering containers per cloud provider:
• GCP - One container per project.
• AWS and Azure - One container per cloud provider region.
You only need to create a container per AWS region.  This is not an issue so closing.

**Comment by sumit-s-agrawal** [comment]
How it should be done then in terraform script?

**Comment by themantissa** [comment]
@sumit-s-agrawal  you need to create a container like you've done in your example above for each AWS region you are setting up a peering connection to and then use that container id for the connection.  We have examples in the examples directory of this repo.  If you need more assistance I suggest utilizing Atlas support.

**Comment by fabriciocarboni** [comment]
I'd like to contribute to the discussion so if someone else face the same problem.

I had the same issue. As far as I could understand, atlas creates a container for the first time when you crate the project. If for some reason you delete your cluster and you get the CONTAINER_EXISTS error, it means that terraform could not delete the resource somehow.

To solve this, one could use curl to get the container id and then delete the "zombie" vpc resource (container in this case)

Get container id:
`curl --user "{PUBLIC-KEY}:{PRIVATE-KEY}" --digest \
  --header "Accept: application/json" \
  --request GET "https://cloud.mongodb.com/api/atlas/v1.0/groups/{YOUR-PROJECT-ID}/containers?providerName=AWS&pretty=true"`

Once you get the container_id you can delete it.

Delete resource:
`curl --user "{PUBLIC-KEY}:{PRIVATE-KEY}" --digest \
  --header "Accept: application/json" \
  --request DELETE "https://cloud.mongodb.com/api/atlas/v1.0/groups/{YOUR-PROJECT-ID}/containers/{CONTAINER-ID}?pretty=true"`
[Reference](https://docs.atlas.mongodb.com/reference/api/vpc-delete-one-container/)

However if you just want to create a peer connection on top of your existing container_id you need to retrieve the container_id and use this id in your peer network terraform resource.

[Example Usage - Peering Connection Only, Container Exists](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/network_peering#example-usage---peering-connection-only-container-exists)

**Comment by themantissa** [comment]
@fabriciocarboni just to clarify a bit - a container is just another name for a VPC or what ever the correct term is for that cloud provider.  It is not created when you first create a project but when you first do some action that needs a VPC, such as creating a cluster or a peering connection, but a container does not yet exist.  Hence if a project is not new there's a chance a container will exist.  We've tried to make this clear in the documentation but we may have some improvements to make here.  I hope this helps and appreciate the guidance for others who may stop by here.

**Comment by fabriciocarboni** [comment]
@themantissa thank you!

**Comment by ra4u12** [comment]
@themantissa  How can i fetch the atlas_cidr_block if the container was already created manually or already vpc peering exists in different project.
