### ISSUE TITLE
Role names are not validated for team configurations in project

### ISSUE THREAD

**Issue by steinwachs** [mongodb/terraform-provider-mongodbatlas#700]
### Summary
Running `terraform apply` to create a new `mongodbatlas_project` that contains a `teams` configuration with invalid `role_names`, invalid roles are ignored and the apply step is started. The project is created but not reflected in the (remote) state because of the issue with the invalid roles.

A subsequent run of `terraform apply` then fails because the project already exists in MongoDB Atlas, but not in the state:

```
│ Error: error creating Project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups: 409 (request "GROUP_ALREADY_EXISTS") A group with name "Issue Example" already exists.
│
│   with module.atlas-example-module.mongodbatlas_project.example,
│   on ../../../modules/atlas-example-module/main.tf line 41, in resource "mongodbatlas_project" "example":
│   41: resource "mongodbatlas_project" "example" {
```

I made a simplified example below to make reproducing the error easier.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
Tried both with:
```hcl
Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.3.0
```

and:

```hcl
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.19.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.3.0
```

#### Module main.tf
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.19.0"
    }
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 1.3.0"
    }
  }
}

provider "aws" {
  region = "ap-southeast-2"
}

locals {
  mongodbatlas_organisation_id = "..."
  mongodbatlas_apikey_id_one = "..."
  mongodbatlas_apikey_id_two = "..."
}

resource "mongodbatlas_teams" "issue" {
  org_id    = local.mongodbatlas_organisation_id
  name      = "Causes Issues"
  usernames = ["me@you.com", "you@me.com"]
}

resource "mongodbatlas_teams" "good" {
  org_id    = local.mongodbatlas_organisation_id
  name      = "No Issues"
  usernames = ["me@you.com"]
}

resource "mongodbatlas_project" "example" {
  name   = "Issue Example"
  org_id = local.mongodbatlas_organisation_id

  teams {
    team_id = mongodbatlas_teams.issue.team_id

    // The below configuration is wrong ("Role ORG_MEMBER is invalid for group ...")
    role_names = ["GROUP_OWNER", "ORG_MEMBER"]
  }

  teams {
    team_id    = mongodbatlas_teams.good.team_id
    role_names = ["GROUP_DATA_ACCESS_READ_WRITE", "GROUP_CLUSTER_MANAGER"]
  }

  api_keys {
    api_key_id = local.mongodbatlas_apikey_id_one
    role_names = ["GROUP_CLUSTER_MANAGER", "GROUP_DATA_ACCESS_ADMIN", "GROUP_DATA_ACCESS_READ_WRITE", "GROUP_READ_ONLY"]
  }

  api_keys {
    api_key_id = local.mongodbatlas_apikey_id_two
    role_names = ["GROUP_CLUSTER_MANAGER", "GROUP_DATA_ACCESS_ADMIN", "GROUP_DATA_ACCESS_READ_WRITE", "GROUP_READ_ONLY"]
  }
}
```
#### File using module (relevant parts only)
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.19.0"
    }
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 1.3.0"
    }
  }

  backend "s3" {
    bucket  = "my-terraform-state-storage"
    key     = "staging/data-storage/atlas-example"
    region  = "ap-southeast-2"
    encrypt = true
  }
}

module "atlas-example-module" {
  source = "../../../modules/atlas-example-module"
}
```

### Steps to Reproduce
1. Run `terraform apply`.
2. Terraform will stop with an error:
```
│ Error: error adding teams into the project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/<GROUP_ID_REMOVED>/teams: 400 (request "INVALID_ROLE_FOR_GROUP") Role ORG_MEMBER is invalid for group <GROUP_ID_REMOVED>.
│
│   with module.atlas-example-module.mongodbatlas_project.example,
│   on ../../../modules/atlas-example-module/main.tf line 41, in resource "mongodbatlas_project" "example":
│   41: resource "mongodbatlas_project" "example" {
```
3. Correct the roles (remove `ORG_MEMBER`)
4. Run `terraform apply` again.
5. Terraform will stop with an error:
```
│ Error: error creating Project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups: 409 (request "GROUP_ALREADY_EXISTS") A group with name "Issue Example" already exists.
│
│   with module.atlas-example-module.mongodbatlas_project.example,
│   on ../../../modules/atlas-example-module/main.tf line 41, in resource "mongodbatlas_project" "example":
│   41: resource "mongodbatlas_project" "example" {
```

### Expected Behavior
The `terraform apply` step should result in the MongoDB provider _validating_ the roles used in the project's team configurations. Valid roles are specified in the[ official docs](https://docs.atlas.mongodb.com/reference/api/project-add-team/#request-body-parameters). The plan should not be applied.

### Actual Behavior
* It ignores the invalid role and proceeds with the `apply` step.
* It creates the two teams successfully and adds them to the state.
* It creates the project in MongoDB Atlas but does _not_ add it to the remote state.
* Upon running `terraform apply` again, it determines that it needs to create the project (instead of modifying it) and aborts with an error:
```
Error: error creating Project: POST https://cloud.mongodb.com/api/atlas/v1.0/groups: 409 (request "GROUP_ALREADY_EXISTS") A group with name "Example" already exists.

  on ../../../modules/mongodbatlas/main.tf line 51, in resource "mongodbatlas_project" "example":
  51: resource "mongodbatlas_project" "example" {
```

#### State after terraform apply
```json
{
  "version": 4,
  "terraform_version": "1.1.7",
  "serial": 0,
  "lineage": "...",
  "outputs": {},
  "resources": [
    {
      "module": "module.atlas-example-module",
      "mode": "managed",
      "type": "mongodbatlas_teams",
      "name": "good",
      "provider": "provider[\"registry.terraform.io/mongodb/mongodbatlas\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "...",
            "name": "No Issues",
            "org_id": "...",
            "team_id": "...",
            "usernames": [
              "me@you.com"
            ]
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    },
    {
      "module": "module.atlas-example-module",
      "mode": "managed",
      "type": "mongodbatlas_teams",
      "name": "issue",
      "provider": "provider[\"registry.terraform.io/mongodb/mongodbatlas\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "...",
            "name": "Causes Issues",
            "org_id": "...",
            "team_id": "...",
            "usernames": [
              "me@you.com",
              "you@me.com"
            ]
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}
```

**Comment by themantissa** [comment]
@steinwachs we depend on the Atlas system to do the validations vs the provider. This reduces the complexity of the provider and ensures roles are always updated vs trying to keep the provider and system in sync.   Obviously in this case, when the request is invalid, it causes an issue.  Would rolling the apply back be acceptable?  e.g. if there's an invalid role remove the project and teams requested?

**Comment by steinwachs** [comment]
@themantissa I understand the desire to keep the complexity of the provider low, yet I believe that the set of roles would not be appended/modified all the time - or do they change frequently? I would assume those to be fairly static, so that validating prior to applying would make things straightforward.

However, if validation is not an option now, I see several options for handling the issue with the provider, two of which are: 

a) Update the state partially
The state would need to be updated partially to contain the created project without the failed team, so that its creation/modification is properly reflected in the state. Only the team assignment failed in my example, so the project should be part of the state, the team assignment would not. 

If I understand Terraform's [doc](https://www.terraform.io/plugin/framework/diagnostics#how-errors-affect-state) ("When returning error diagnostics, we recommend resetting the state in the response to the prior state available in the configuration.") correctly, this does not seem to be how things are intended. So I guess option b) would be the right way to go.

b) Roll back the apply as you suggested
All changes applied would be rolled back, including the project creation. I do think that this is acceptable in our case but may depend on the use case.

Validation prior to applying is still my clear favourite though.

**Comment by themantissa** [comment]
Created internal ticket INTMDB-433 for general improvement in this area. Going to close this issue as not directly 1:1 but will update once the areas is worked on. cc @Zuhairahmed
