### ISSUE TITLE
User Creation Guidance

### ISSUE THREAD

**Issue by vortexture** [mongodb/terraform-provider-mongodbatlas#703]
I'm looking for guidance on the user creation/invitation process.

Currently it seems like I have to invite users (via `mongodbatlas_org_invitation`) and then assign them to teams separately (using `mongodbatlas_teams`).

I am aware that you can invite someone with a specific team, but I also have to update the team (`mongodbatlas_teams`) to include that new user otherwise the next run of terraform will remove that user from the team.

I can't create an empty team, so I can't preemptively create the teams I need and then assign the users to the teams via invites.
```
resource "mongodbatlas_teams" "test_team" {
  org_id     = local.org_id
  name       = "test_team"
  usernames  = []
}

╷
│ Error: error creating Team information: POST https://cloud.mongodb.com/api/atlas/v1.0/orgs/x/teams: 400 (request "CANNOT_CREATE_EMPTY_TEAM") A team must contain at least one user. Add a user to your team to continue.
│ 
│   with mongodbatlas_teams.test_team,
│   on teams.tf line 38, in resource "mongodbatlas_teams" "test_team":
│   38: resource "mongodbatlas_teams" "test_team" {
│ 
╵
```

But I also can't change a user teams via their invites because the invite is not updatable anyway 
```
╷
│ Error: error updating Organization invitation for user blah@blah.com: for PATCH https://cloud.mongodb.com/api/atlas/v1.0/orgs/x/invites/x: 404 (request "INVALID_INVITATION_ID") An invalid invitation ID x was specified.
│ 
│   with mongodbatlas_org_invitation.bob,
│   on invites.tf line 1, in resource "mongodbatlas_org_invitation" "bob":
│    1: resource "mongodbatlas_org_invitation" "bob" {
│ 
```

I also can't add a pending user to a team so all of these constraints mean that inviting someone is a 2-step process in terraform, one `terraform apply` to create the invite and another `terraform apply` once the user has accepted the invite to add the user to some teams.

Is this intentional or am I missing something about how this works? (I couldn't see any examples of this in the examples directory)

**Comment by bart-rijnders** [comment]
Our users are provisioned through SAML, but the concept should be similar as they are also only provisioned after initial login. Perhaps you can use this as a jumping off point. We've wrapped this into a 'team' module to abstracts away the logic. It solves both the not-yet provisioned users and the empty team problem.

```terraform
data "external" "users" {
  for_each = toset([for user in var.usernames])

  program = [ "bash", "${path.module}/find-user.sh", var.public_key, var.private_key, each.value ]
}

locals {
  users = [ for user in data.external.users : user.result.id if user.result.id != "null" ]
}

resource "mongodbatlas_teams" "team" {
  count = length(local.users) > 0 ? 1 : 0 // MongoDB API fails at runtime if the team has no users.

  org_id     = var.org_id
  name       = var.team_name
  usernames  = [ for user in data.external.users : user.result.id if user.result.id != "null" ]
}
```
The find-user script curls the username from [Get an Atlas User by Name](https://www.mongodb.com/docs/atlas/reference/api/user-get-one-by-name/) and outputs the username field as id, which will be a string value of "null" if the user doesn't exist. You can script it however is convenient.

Then we just reference this as a module in a for_each with each team, and throw it in a cronjob that applies it every 30 mins. As users are accepting invites the teams, over time, will get filled in. So then you only need to solve your invite step and everything else is automated.

Edit: Another point that occurred to me, you can use the same external data source to manage whether you need to send an invite to a user or not.

**Comment by bart-rijnders** [comment]
Another point that occurred to me, you can use the same external data source to manage whether you need to send an invite to a user or not.

**Comment by vortexture** [comment]
Thanks for the clarification!
