### ISSUE TITLE
Documentation typo in  resources/cluster attributes reference

### ISSUE THREAD

**Issue by Marcus-James-Adams** [mongodb/terraform-provider-mongodbatlas#716]
Documentation error

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#attributes-reference

[connection_strings.private_endoint.#.endpoints.#.endpoint_id](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster#connection_strings.private_endoint.#.endpoints.#.endpoint_id) - Unique identifier of the private endpoint.

Shows private_endoint.

Should be private_endpoint

**Comment by themantissa** [comment]
@Marcus-James-Adams any chance you could submit via a PR and sign our CLA?

**Comment by Zuhairahmed** [comment]
Thanks @Marcus-James-Adams closing as PR has been merged: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/878
