### ISSUE TITLE
Creating M2 cluster without specifying disk_size_gb results in 400 Bad Request

### ISSUE THREAD

**Issue by Huggzorx** [mongodb/terraform-provider-mongodbatlas#72]
Excerpt from my main.tf file:

``` 
resource "mongodbatlas_cluster" "cluster-test" {
  project_id   = mongodbatlas_project.testing.id
  name         = "testing-cluster"

  backup_enabled               = false
  auto_scaling_disk_gb_enabled = false
  mongo_db_major_version       = "4.0"

  //Provider Settings "block"
  provider_name               = "TENANT"
  backing_provider_name       = "AWS"
  provider_instance_size_name = "M2"
  provider_region_name        = "eu-west-1"
}
```

According to the documentation, disk_size_gb is optional and should default to the minimum (2GB for an M2) but I get an error: `400 (request "Bad Request") The cluster's disk size of 0.0 GB is invalid"`.

If I specify `disk_size_gb = 2` it works as expected.

**Comment by themantissa** [comment]
@Huggzorx thank you!  I'll ask the team to address this.

**Comment by PacoDw** [comment]
Hi, @Huggzorx thanks for your review, I have made the change to avoid to specify the disk size attr, you can test it on the `cluster` branch and check the pr #77 for more information.

plz, let me know if you have another comment or concern.

**Comment by zomarg** [comment]
`disk_size_gb - (Optional - GCP/AWS Only) The size in gigabytes of the server’s root volume. You can add capacity by increasing this number, up to a maximum possible value of 4096 (i.e., 4 TB). This value must be a positive integer.`

When not setting up disk_size_gb using AZURE throws same error.

**Comment by PacoDw** [comment]
Hello @GramozKrasniqi, could you share with me your Terraform configuration omitting sensitive data? I tested with the following TF configuration, and I didn't have errors:

```hcl
resource "mongodbatlas_cluster" "test" {
  project_id = "Your-project-id"
  name       = "name"
  num_shards = 1

  replication_factor           = 3
  backup_enabled               = true
  auto_scaling_disk_gb_enabled = true
  mongo_db_major_version       = "4.0"

  //Provider Settings "block"
  provider_name               = "AZURE"
  provider_disk_type_name     = "P6"
  provider_instance_size_name = "M10" # I tested with the following tiers as well: M20, M30, M40, M50, M60, M80, M200
  provider_region_name        = "US_EAST_2"
}

```

**Comment by zomarg** [comment]
Yes sure:
```
resource "mongodbatlas_cluster" "mongo_cluster" {  
  project_id = var.project_id
  name = local.cluster_name  
  mongo_db_major_version = "4.0"

  //A multi-tenant deployment on one of the supported cloud service providers. Only valid when providerSettings.instanceSizeName is either M2 or M5.

  provider_name = "TENANT"  
  backing_provider_name = "AZURE"
  provider_instance_size_name  = "M2"
  provider_region_name = local.region_name
}
```

**Comment by PacoDw** [comment]
Thanks, @GramozKrasniqi, I tested your TF configuration and the auto_scaling_disk_gb_enabled is missing, so you need to set it to false when you want to use TENANT because if you don't, it sets to true by default and you will get an error. I made a few changes to avoid to set auto_scaling_disk_gb_enabled to false when you are using TENANT. It will set to false automatically.

So you must be able to use your above configuration without any problem on the cluster branch and check the pr #77 for more information. 

If you have another comment or concert plz let us know.

**Comment by zomarg** [comment]
Great @PacoDw thank you :)
