### ISSUE TITLE
Typos in documentation for resource/mongodbatlas_search_index

### ISSUE THREAD

**Issue by daniel-orlov** [mongodb/terraform-provider-mongodbatlas#723]
Where: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/search_index#example-usage
Or in the code: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/website/docs/r/search_index.html.markdown

What: both Basic and Advanced examples contain camelCase attribute names like **collectionName** and **searchAnalyzer** instead of expected snake_case ones.
Should be: collection_name, search_analyzer etc

Runs into `Error: Unsupported argument` if executed.

**Comment by themantissa** [comment]
@daniel-orlov  we welcome PRs to fix docs errors - please sign the CLA if you'd like to contribute.

**Comment by themantissa** [comment]
@daniel-orlov  we welcome PRs for docs fixes, just need to sign the CLA first.
