### ISSUE TITLE
Project deletion being attempted before cluster is destroyed 

### ISSUE THREAD

**Issue by dikirahman** [mongodb/terraform-provider-mongodbatlas#724]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
❯ terraform version
Terraform v1.1.9
on darwin_arm64
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_cluster" "cluster" {
  project_id                  = mongodbatlas_project.project.id
  name                        = var.cluster_name
  mongo_db_major_version      = var.mongodbversion
  cluster_type                = var.cluster_type
  provider_name               = var.provider_name
  backing_provider_name       = var.cloud_provider
  provider_region_name        = var.provider_region
  provider_instance_size_name = var.provider_instance_size_name
}


resource "mongodbatlas_database_user" "user" {
  username           = var.dbuser
  password           = var.dbuser_password
  project_id         = mongodbatlas_project.project.id
  auth_database_name = var.auth_database_name



  roles {
    role_name     = "readWrite"
    database_name = var.database_name
  }


  roles {
    role_name     = "atlasAdmin"
    database_name = var.roles_database_name
  }


  labels {
    key   = "Name"
    value = "DB User1"
  }
}

resource "mongodbatlas_project_ip_access_list" "ip" {
  project_id = mongodbatlas_project.project.id
  cidr_block = var.ip_address
  comment    = "IP Address for accessing the cluster"
}

resource "mongodbatlas_project" "project" {
  name   = var.project_name
  org_id = var.atlas_org_id
}
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform destroy`

### Expected Behavior

it should destroy projects, clusters and databases, but sometimes it successful to destroy and sometimes fails to destroy.
### Actual Behavior

<img width="1417" alt="mongodb" src="https://user-images.githubusercontent.com/47310183/166467560-dd07f5d9-5f13-4bd3-9b06-8ee30c7d8498.png">

**Comment by themantissa** [comment]
@dikirahman  what provider version are you using.  Also going to update the issue subject to better capture what you are reporting.

**Comment by dikirahman** [comment]
@themantissa I'm using version 1.3.0

**Comment by themantissa** [comment]
Internal ticket INTMDB-332

**Comment by martinstibbe** [comment]
@dikirahman This was fixed in v1.3.2 based on this enhancement to project resource
INTMDB-302: Ensure we handle new flow for project deletion well by @evertsd in https://github.com/mongodb/terraform-provider-mongodbatlas/pull/688 could you try a newer version of provider to validate

**Comment by dikirahman** [comment]
@martinstibbe Thanks for the update
however I get the following error when running `terraform init -upgrade`

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/47310183/185277497-86e2a5aa-60ec-4a2a-b484-70e8c1674d36.png">

**Comment by dikirahman** [comment]
We decided to use version v1.4.3 and it works
