### ISSUE TITLE
mongodbatlas_serverless_instance terraform import

### ISSUE THREAD

**Issue by garyhampson** [mongodb/terraform-provider-mongodbatlas#754]
The documentation for the terraform import says that the instance should be referenced using GroupID-InstanceID, but that is incorrect.

> Serverless Instance can be imported using the group ID and serverless instance id, in the format GROUP_ID-SERVERLESS_INSTANCE_ID, e.g.

`$ terraform import mongodbatlas_serverless_instance.my_serverless_instance 1112222b3bf99403840e8934-1112222b3bf99403840e8935`

Each time I tried that, it failed. When I tried GROUP_ID-SERVERLESS_INSTANCE_NAME, I was successful. The same goes for trying to curl the specific instance.
![atlas_serverless_curl](https://user-images.githubusercontent.com/29409339/173431864-7bed84ee-bc74-4d85-bf78-e8c1d3cdbdb2.png)

**Comment by themantissa** [comment]
Thank you @garyhampson - looks like a docs bug but but we'll take a look and make sure.

**Comment by themantissa** [comment]
Internal ticket INTMDB-330
