### ISSUE TITLE
Project settings in 1.4.0 incorrectly sets all options to false. 

### ISSUE THREAD

**Issue by wyardley** [mongodb/terraform-provider-mongodbatlas#772]
Hi - with 1.4 and a project created with default settings, is it expected that the provider will toggle the new settings introduced in #741 with values different from the default?

### Terraform CLI and Terraform MongoDB Atlas Provider Version
```bash
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/mongodb/mongodbatlas v1.4.0
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "foo" {
  name   = var.project
  org_id = var.org_id

  teams {
    \\ some basic team configuration here
  }
}
```

### Actual Behavior
```
  # mongodbatlas_project.foo will be updated in-place
  ~ resource "mongodbatlas_project" "foo" {
        id                                               = "xxxxxxxx"
      ~ is_collect_database_specifics_statistics_enabled = true -> false
      ~ is_data_explorer_enabled                         = true -> false
      ~ is_performance_advisor_enabled                   = true -> false
      ~ is_realtime_performance_panel_enabled            = true -> false
      ~ is_schema_advisor_enabled                        = true -> false
```

### Additional Context
I'm not sure if the goal of #741 was to keep settings aligned with API naming, but to me, something like
`data_explorer_enabled = true` would read better than `is_data_explorer_enabled`. `is_collect_database_specifics_statistics_enabled` in particular seems very awkward.

### References
#741

**Comment by themantissa** [comment]
@wyardley I'm surfacing this with the team now.  It should honor any defaults so we may have an issue here.  

Naming wise - it's traditional w/ Terraform providers to use the same name as the underlying API.   Understand these are not the most user friendly so we try to make that clear in the docs. Will take the feedback to the greater team!

**Comment by wyardley** [comment]
@themantissa thanks for the quick response!

Yeah, I wasn't sure if this was expected at all, or if it was for sure an issue, but wanted to surface it just in case.

I suppose it is possible that we'd set these manually away from defaults before using the tf provider, but I don't _think_ we'd have done it for all of these? I went back to check the plan to make sure it actually was trying to change them vs. just an "objects changed" notifications.

I've gone ahead and set all the parameters for now along with the provider update, but will follow this in case something changes / gets updated.

**Comment by themantissa** [comment]
Very much appreciate you surfacing this so quickly - you've likely helped many! 

Looking at the code these new parameters were incorrectly set with a default value of false. They are 1) true by default in Atlas but 2) the provider should not have a default so as to not interfere w/ what is already set.  It should allow users to set these via provider but not default them to anything.

**Comment by themantissa** [comment]
@wyardley we just released 1.4.1 with the fix. Can you give it a try and confirm?

**Comment by wyardley** [comment]
I saw that. Yeah, reverting my changes and about to apply, but looks good based on the plan.

**Comment by wyardley** [comment]
Seems to resolve the issue! thanks for the responsiveness and quick fix

**Comment by wyardley** [comment]
Hi @themantissa 
sorry to bug you again. After updating to 1.4.1, which should have had the right defaults, the plan showed up this way, which I assumed would make it a noop (since IIRC, the new defaults are `true`, and the plan showed up as setting things to `null` vs `false`:

```
  # mongodbatlas_project.xyz will be updated in-place
~ resource "mongodbatlas_project" "xyz" {
        id                                               = "xxxx"
      - is_collect_database_specifics_statistics_enabled = true -> null
      - is_data_explorer_enabled                         = true -> null
      - is_performance_advisor_enabled                   = true -> null
      - is_realtime_performance_panel_enabled            = true -> null
      - is_schema_advisor_enabled                        = true -> null
        name                                             = "xyz"
        # (4 unchanged attributes hidden)

        # (7 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

However, some of our users observed that "browse collections" is no longer available in the web interface. If I plan with `TF_LOG=debug`, I see the following output:

```
---[ REQUEST ]---------------------------------------
GET /api/atlas/v1.0/groups/xxx/settings HTTP/1.1
Host: cloud.mongodb.com
User-Agent: terraform-provider-mongodbatlas/1.4.1 go-mongodbatlas/0.16.0 (darwin;arm64)
Accept: application/json
Accept-Encoding: gzip
-----------------------------------------------------: timestamp=2022-07-07T11:02:34.873-0700
2022-07-07T11:02:35.127-0700 [INFO]  provider.terraform-provider-mongodbatlas_v1.4.1: 2022/07/07 11:02:35 [DEBUG] MongoDB Atlas API Response Details:
---[ RESPONSE ]--------------------------------------
HTTP/2.0 200 OK
Content-Type: application/json
Date: Thu, 07 Jul 2022 18:02:35 GMT
Location: https://cloud.mongodb.com//api/atlas/v1.0
Referrer-Policy: strict-origin-when-cross-origin
Server: envoy
Strict-Transport-Security: max-age=31536000; includeSubdomains;
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Envoy-Upstream-Service-Time: 72
X-Frame-Options: DENY
X-Mongodb-Service-Version: gitHash=895c685f36f43205d62753f540539c7e8748b9c6; versionString=v20220622
X-Permitted-Cross-Domain-Policies: none

{
 "isCollectDatabaseSpecificsStatisticsEnabled": false,
 "isDataExplorerEnabled": false,
 "isPerformanceAdvisorEnabled": false,
 "isRealtimePerformancePanelEnabled": false,
 "isSchemaAdvisorEnabled": false
}
[...]
2022-07-07T11:02:35.137-0700 [WARN]  Provider "registry.terraform.io/mongodb/mongodbatlas" produced an invalid plan for mongodbatlas_project.xyz, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .with_default_alerts_settings: planned value cty.True for a non-computed attribute
      - .is_data_explorer_enabled: planned value cty.False for a non-computed attribute
      - .is_realtime_performance_panel_enabled: planned value cty.False for a non-computed attribute
      - .is_schema_advisor_enabled: planned value cty.False for a non-computed attribute
      - .is_collect_database_specifics_statistics_enabled: planned value cty.False for a non-computed attribute
      - .is_performance_advisor_enabled: planned value cty.False for a non-computed attribute
```

Could this be related to our having had 1.4.0 with the values explicitly set and then taking them out? Is there a fix without having to set these all explicitly to true going forward?
Also, is there a way to view these values in the web UI, or just via the API (I don't see these in the project settings).

**Comment by wyardley** [comment]
Confirmed also that if I set them all to true explicly again (with 1.4.1), I'll see the following plan:
```
      ~ is_collect_database_specifics_statistics_enabled = false -> true
      ~ is_data_explorer_enabled                         = false -> true
      ~ is_performance_advisor_enabled                   = false -> true
      ~ is_realtime_performance_panel_enabled            = false -> true
      ~ is_schema_advisor_enabled                        = false -> true
```
and the setting is returned to `true`.

however, if I apply again without those parameters set, the plan shows it going from `true` => `null`

```
      - is_collect_database_specifics_statistics_enabled = true -> null
      - is_data_explorer_enabled                         = true -> null
      - is_performance_advisor_enabled                   = true -> null
      - is_realtime_performance_panel_enabled            = true -> null
      - is_schema_advisor_enabled                        = true -> null
```

rather than restoring to defaults (which, IIRC, should be `true` for all of these in `1.4.1`), this seems to have the effect of explicitly setting them to false (looking at the debug log, it doesn't look to me like it's just unsetting them at the API level, but explicitly setting them to `false`):
```
---[ REQUEST ]---------------------------------------
PATCH /api/atlas/v1.0/groups/xxxx/settings HTTP/1.1
Host: cloud.mongodb.com
User-Agent: terraform-provider-mongodbatlas/1.4.1 go-mongodbatlas/0.16.0 (darwin;arm64)
Content-Length: 193
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{
 "isCollectDatabaseSpecificsStatisticsEnabled": false,
 "isDataExplorerEnabled": false,
 "isPerformanceAdvisorEnabled": false,
 "isRealtimePerformancePanelEnabled": false,
 "isSchemaAdvisorEnabled": false
}
```

This warning then shows up:
```
2022-07-07T13:44:30.196-0700 [WARN]  Provider "provider[\"registry.terraform.io/mongodb/mongodbatlas\"]" produced an unexpected new value for mongodbatlas_project.xyz, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .is_schema_advisor_enabled: was null, but now cty.False
      - .is_data_explorer_enabled: was null, but now cty.False
      - .is_collect_database_specifics_statistics_enabled: was null, but now cty.False
      - .is_performance_advisor_enabled: was null, but now cty.False
      - .is_realtime_performance_panel_enabled: was null, but now cty.False
```

**Comment by wyardley** [comment]
Maybe because of:
```
				Optional: true,
```
in #773 

but no explicit default - the provider might need to explicitly remove them vs. patching with false when they've already been set to some value once? Is there an easy way with the CLI to unset these parameters, assuming that's the issue?

**Comment by themantissa** [comment]
@wyardley let me have the team take a look.  I think this might be because, as you noted, you already set it in 1.4.0 so there's an artifact in the state. But what concerns me is that when you set all to true and then just removed the parameters it set them to null.  Adding in new parameters is always complicated.  This one particularly so.  Let us get to the bottom of this.

**Comment by wyardley** [comment]
Thanks. I can make a new ticket if you think that's better vs. reusing this one - up to you.

**Comment by themantissa** [comment]
If you don't mind creating one with a more applicable to the problem title, that would be amazing @wyardley .  Just redirect here for all the great evidence you provided.   That way others looking for info can find it.

**Comment by wyardley** [comment]
Created #777, so closing this one again. Feel free to adjust description etc. as needed
