### ISSUE TITLE
Documentation: mongodbatlas_custom_db_role (collection_name vs. collection)

### ISSUE THREAD

**Issue by BryantD** [mongodb/terraform-provider-mongodbatlas#775]
Where: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/custom_db_role 
Code: https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/website/docs/r/custom_db_role.html.markdown

The Example Usage section correctly uses `actions.resources.#.collection_name` as an attribute name, but the Actions section of the Arguments reference refers to `resources.#.collection`. After testing, I believe the Example Usage section is correct.

Assuming this is a valid issue I'd be happy to sign the CLA and file a PR.

**Comment by themantissa** [comment]
@BryantD thank you for the issue.  You are correct, collection_name is the correct attribute name (https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/resource_mongodbatlas_custom_db_role.go#L66)  

We would very much appreciate a PR to correct this.  

fyi @Zuhairahmed

**Comment by Zuhairahmed** [comment]
Closing issue as PR has been merged and released as part of version 1.4.3
