### ISSUE TITLE
Provider defaults for parameters in provider version >= 1.4.1

### ISSUE THREAD

**Issue by wyardley** [mongodb/terraform-provider-mongodbatlas#777]
This is basically a continuation of #772 (issues with the changes in #741), but after the fix in #773, it seems as if the provider default is still forcing to false once the setting has been toggled at some point, even if it's currently set to `true`, for these newly added parameters. 

I haven't copied all the details / debugging info from #772, but I will close that again.

### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform v1.2.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/mongodb/mongodbatlas v1.4.1
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_project" "foo" {
  name   = var.project
  org_id = var.org_id

  teams {
    \\ some basic team configuration here
  }
}
```

**Comment by themantissa** [comment]
@wyardley we have a pre-release out with the fix: https://github.com/mongodb/terraform-provider-mongodbatlas/releases/tag/untagged-f6fcf34b988c94d3f95d would you be able to test it?  We did pretty extensive testing (automated and manual) but it would be good to get a check.

**Comment by themantissa** [comment]
We decided to get the fix out the door @wyardley so please let us know if 1.4.2 works well for you.   Closing this issue as complete.

**Comment by wyardley** [comment]
Thanks! And yes, after temporarily planning with all enabled again, we verified that the settings stay enabled. I didn’t check whether they’re set or unset under the hood, but seems to work now.

**Comment by themantissa** [comment]
@wyardley great news - thank you for sticking with us on this one.
