### ISSUE TITLE
Please elaborate how to acquire PROJECTID and PEERINGID and PROVIDERNAME for import of network peering

### ISSUE THREAD

**Issue by tback** [mongodb/terraform-provider-mongodbatlas#789]
Please elaborate how to acquire project and peering id and provider name for importing network peerings.

The reason I'm asking for this is that I failed to find the `PEERID`.

`PROJECTID` is easily acquired from Organization->Projects->Actions ... -> Copy Project ID.

`PROVIDERNAME` is `AWS` or `GCP` or something else.

`Clusters can be imported using project ID and network peering id, in the format PROJECTID-PEERID-PROVIDERNAME`
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/46dc303fb3378ae1d21a737bfef7be1787760a59/website/docs/r/network_peering.html.markdown?plain=1#L427

**Comment by themantissa** [comment]
@tback Peer id would match the id you can find via the API directly here: https://www.mongodb.com/docs/atlas/reference/api/vpc-get-connections-list/
