### ISSUE TITLE
documentation not correct for automation requirements for mongodbatlas_cloud_provider_snapshot_restore_job

### ISSUE THREAD

**Issue by atxplangl** [mongodb/terraform-provider-mongodbatlas#802]
target_group_id should be target_project_id according to source code and example.  

[target_group_id](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cloud_provider_snapshot_restore_job#target_group_id)

source code
[source-code](https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/data_source_mongodbatlas_cloud_provider_snapshot_restore_jobs.go#L78)

**Comment by evertsd** [comment]
Thanks for the heads up, looks like there are a few instances where documentation on `mongodbatlas_cloud_backup_snapshot_restore_job` refers to a `target_group_id` attribute which is in fact referring to the `target_project_id`.

Will address and keep the issue up to date.

**Comment by evertsd** [comment]
This documentation has been fixed
