### ISSUE TITLE
Documentation is wrong on encryption at rest alert configuration

### ISSUE THREAD

**Issue by jgrumboe** [mongodb/terraform-provider-mongodbatlas#805]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
1.2.2
```

### Terraform Configuration File 
```hcl
resource "mongodbatlas_encryption_at_rest" "test" {
  project_id = "<PROJECT-ID>"

  aws_kms_config {
    enabled                = true
    customer_master_key_id = "5ce83906-6563-46b7-8045-11c20e3a5766"
    region                 = "US_EAST_1"
    role_id                = "60815e2fe01a49138a928ebb"
  }
}
```

### Additional Context
The documentation states the following:
"Atlas automatically creates a 365-day key rotation alert when you configure Encryption at Rest using your Key Management in an Atlas project."

But in reality, the created alert is a 90-day key rotation alert. Together with AWS KMS and enabled rotation on the AWS side, which is 365-days and not adjustable,
the auto-created alert just creates false alarms and noise.

Secondly, is there a way to change the auto-created alert config to 365 days with Terraform? I haven't found anything helpful so far.

### References
Documentation link: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/encryption_at_rest

**Comment by iniinikoski** [comment]
Colleague of @jgrumboe here. We also know this exists when creating the projects: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project#with_default_alerts_settings - but this also does not feel the "way to go" - adjusting this.

Every Atlas AWS customer using KMS + the Terraform provider must have bumped into the same issue. @themantissa - huge apologies to ping you directly here - is there something you or some of your colleagues / team(s) could verify at some point...?

**Comment by themantissa** [comment]
@iniinikoski and @jgrumboe apologies for the delay, this was on my list to respond to so thank you for the ping.  The documentation was taken from our Atlas Admin API docs, which has since been updated so we need to update this as well: https://www.mongodb.com/docs/atlas/reference/api/enable-configure-encryptionatrest/  That states it is indeed 90 days.  I'll create a ticket for us to fix this in the Terraform doc.

You can change the day variable. You should be able to import in the alert (there is an alert config id you can pull via curl from the API directly - https://www.mongodb.com/docs/atlas/reference/api/alert-configurations-get-all-configs/) and then write a config block to match the alert with the variable changed for days.  This is exactly why we have a flag to create a project with no default alerts.  Many were not a fan of importing in the existing and the overall ask was to make it easy to just configure them from scratch to be the desired level.   I'm sure we can find a way to keep improving this in the future.

**Comment by iniinikoski** [comment]
No worries, huge thanks for the superquick reply @themantissa :) And for the workaround.

I had a small hunch about what you mentioned about the existence of the boolean :) We had a thought yes to use it - but then we were also looking what alerts are created by default - and actually, it's a very comprehensive list (and this is the only one - for us at least for now which would need adjustment).

Blondie question from a blondie: about the auto-created encryption key-alert - would it make sense to adjust this on your side to this... 365-ish days? I'm just thinking, is there something else to change than just the Terraform doc - on your side...?

**Comment by themantissa** [comment]
@iniinikoski happy to be able to help.  

On the blondie question :) The default alert is owned by the team that created/owns encryption at rest so I'd need to ask them why the move from 365 to 90.  Let me see if I can find out the backstory here.  I have a semi-educated guess on why but want to confirm before I answer.

**Comment by jgrumboe** [comment]
@themantissa Thanks for your support.
I just wanted to add that for AWS KMS 365 days of automatic rotation is the default and cannot be changed in some cases (https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#key-mgmt). So, for me a 90-days alert in combination with AWS KMS doesn't make sense.
I don't know how Azure or GCP have configured the automatic rotation interval on their side.

Maybe the alert settings can be adapted automatically for certain combinations.
Or the setting for disabling default alerts can be extended to selectively disbale key rotation alerts (or others) solely and keep the rest. That would really be helpful also. IMO it's easier to create an alert config feom scratch with TF (together with thr cluster and key settings) than importing an existing resource as there's always manual work involved. Additionally we would still benefit from other default alerts which would still be created.

**Comment by themantissa** [comment]
Internal ticket for docs fix INTMDB-383

**Comment by themantissa** [comment]
@jgrumboe   The 90 day window is based on how we are rotating the key based off the top level key so your feedback is quite valid in reference to AWS and the alert time.  I've surfaced this to the larger team with your comments.  I'll leave this issue open till we fix the docs on Terraform side and if there's any change on the alert days that I see I'll try to post here as well.

**Comment by martinstibbe** [comment]
@jgrumboe Will be fixed in v1.4.6 release

**Comment by jgrumboe** [comment]
@martinstibbe Thanks for fixing the docs, but honestly this doesn't help me technically.
Silently I was expecting that you'll fix the alert for AWS KMS to fire on 365 days as that's the automatic rotation done by AWS for CMK.

What's the workaround to get rid of this "false alert" when using AWS CMK? To be honest, manually importing the existing alert to the TF state and modifying it afterwards is not a good option when everything else around TF and MongoDB Atlas is automated.

**Comment by themantissa** [comment]
@jgrumboe this is what we can do for Terraform.  Alerts is within the Atlas system itself.  I've shared your feedback with the Product Manager of that system and will share your thoughts here as well.   We also have a feedback/idea portal where you can leave your suggestion (feedback.mongodb.com).  

Workaround wise importing and changing or creating projects without any alerts and starting fresh are the best I can think of but if I think of something better I will let you know.

**Comment by jgrumboe** [comment]
@themantissa Thank you for your response and for forwarding my thoughts to the PM!

**Comment by themantissa** [comment]
@jgrumboe you are most welcome.   Hopefully a better solution can be found!

**Comment by themantissa** [comment]
@jgrumboe closing this out on our side.  FYI I did talk w/ the team who is responsible for this area and I believe they are going to address it as it is confusing so you should see this alert corrected.

**Comment by jgrumboe** [comment]
@themantissa your support is highly appreciated! Thanks!
