### ISSUE TITLE
Cluster fails to build on 0.3.1 when mongo_db_major_version is not specified

### ISSUE THREAD

**Issue by mattt416** [mongodb/terraform-provider-mongodbatlas#81]
Hey folks,

Using version `0.3.1`, if you omit `mongo_db_major_version` on the `mongodbatlas_cluster` resource then you'll hit an API error as the provider is sending along the following:

```
2019-11-27T22:06:32.115-0500 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.3.1_x4:  "mongoDBMajorVersion": "0.0",
```

This doesn't seem to be an issue with `0.3.0`, so is likely something introduced in `0.3.1`.

The docs for the [**mongodbatlas_cluster** resource](https://www.terraform.io/docs/providers/mongodbatlas/r/cluster.html) indicate that this argument is optional, so this does appear to be a bug.

Thanks for having a look!

--Matt

**Comment by themantissa** [comment]
@mattt416 thank you!  We'll have the team take a look at this.   @PacoDw  or @marinsalinas possible bug.

**Comment by marinsalinas** [comment]
Hello @mattt416, I opened a PR #35 regarding this issue, could you please validate if it works with this fix.
