### ISSUE TITLE
feature request: mongodbatlas_function

### ISSUE THREAD

**Issue by ebouther** [mongodb/terraform-provider-mongodbatlas#828]
I can currently create [mongodbatlas_event_trigger](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/event_trigger) using terraform but I still have to manually create the function associated to it unfortunately.
I don't know if this is already part of the roadmap but I would love to be able to **manage mongodb atlas functions using terraform**.

**Comment by akierstein-insider** [comment]
+1

**Comment by themantissa** [comment]
@ebouther we've had submissions on this at feedback.mongodb.com (which is also where the issue template requests feature requests go to).   We will likely add it to the roadmap for next year but I encourage you to submit that idea there or vote on the existing one for this.
