### ISSUE TITLE
Inviting new users through mongodbatlas_org_invitation, forces the replacement of Private connection, clusters etc

### ISSUE THREAD

**Issue by ashutoshrathore** [mongodb/terraform-provider-mongodbatlas#856]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
Terraform v1.3.0
on windows_386
+ provider registry.terraform.io/hashicorp/azurerm v3.24.0  
+ provider registry.terraform.io/hashicorp/random v3.4.3    
+ provider registry.terraform.io/mongodb/mongodbatlas v1.4.5

### Terraform Configuration File 

```hcl
# resource "mongodbatlas_org_invitation" "portal_users_list" {
  for_each = var.environment == "test" ? var.portal_users_list : []
```

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `append new users in the variable of users list (var.portal_users_list)`
2. `terraform init`
3. `terraform plan`

### Expected Behavior
It should have only create invitation for the newly user added

### Actual Behavior
Whenever we are adding new users to the variable, its forcing replacement of clusters, private connection, vault etc

`
Note: Objects have changed outside of Terraform
.
.
Plan: 25 to add, 7 to change, 24 to destroy.
`

**Comment by ashutoshrathore** [comment]
cc: @themantissa @leo-ferlin-sutton @Zuhairahmed

**Comment by Zuhairahmed** [comment]
Thanks for raising this issue @ashutoshrathore. Can you share more of your Terraform Config file so we can attempt to reproduce on our side? cc @martinstibbe

**Comment by ashutoshrathore** [comment]
@tharinduug fyi

**Comment by Zuhairahmed** [comment]
hi @ashutoshrathore @tharinduug just following up on the above if you can share more details. happy to help, just need more details so we can fully reproduce on our side. if issue has been resolved already, feel free to close

**Comment by Zuhairahmed** [comment]
hi @ashutoshrathore @tharinduug closing this issue for now, but if you run into any issues feel free to re-open. thank you.
