### ISSUE TITLE
Schema error when creating event_trigger referring to Atlas App Services function 

### ISSUE THREAD

**Issue by willmorgan** [mongodb/terraform-provider-mongodbatlas#858]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
1.2.6
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_event_trigger" "ticket_claimed" {
  name                        = "${var.name}-trigger"
  type                        = "DATABASE"
  project_id                  = var.mongodbatlas_project_id
  app_id                      = "6xxxxxxxxxxxxxxxxxxxxxx0"
  function_id                 = "my_trigger"
  config_service_id           = mongodbatlas_advanced_cluster.atlas.cluster_id
  config_operation_types      = ["UPDATE"]
  config_database             = mongodbatlas_advanced_cluster.atlas.name
  config_collection           = "tickets"
  config_match                = "{\"updateDescription.updatedFields\":{\"some_field\":{\"$exists\":true}}}"
  config_full_document        = false
  config_full_document_before = false
  disabled                    = false
  unordered                   = false
}
```

### Steps to Reproduce
`tf apply`

### Expected Behavior
The trigger is created referring to the given function name.

### Actual Behavior
```
│ Error: error creating MongoDB EventTriggers (<groupId>): POST https://realm.mongodb.com/api/admin/v3.0/groups/<groupId>/apps/<appId>/triggers: 400 (request "") cannot unmarshal into an ObjectID, the length must be 24 but it is 9
```

Where 9 is the character length of "my_trigger" in the resource definition above.

### Debug Output 
```
---[ REQUEST ]---------------------------------------
POST /api/admin/v3.0/groups/<groupId>/apps/<appId>/triggers HTTP/1.1
Host: realm.mongodb.com
User-Agent: terraform-provider-mongodbatlas/1.4.6 go-realm
Content-Length: 293
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

{
 "name": "<name>",
 "type": "DATABASE",
 "function_id": "my_trigger",
 "config": {
  "operation_types": [
   "UPDATE"
  ],
  "database": "dev-stargate",
  "collection": "tickets",
  "service_id": "<clusterId>",
  "match": {
   "updateDescription.updatedFields": {
    "some_field": {
     "$exists": true
    }
   }
  }
 }
}

```

### Additional Context
It looks like the schema that the Terraform provider sends differs from the OpenAPI description of the endpoint here: https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#operation/adminListTriggers

As an aside, it took me a lot of time to narrow this down to a suspected provider issue because of the inconsistent naming of fields when finding all the data the resource has to ingest.

For example:
  * groupId/projectId are the same
  * ~~serviceId/clusterId appear to be the same~~ (no, you've got to link the cluster)
  * appId differs from the client app ID mentioned in the console
  * It isn't possible to map the client app ID into an app ObjectId, which is used by this endpoint
  * The function_id appears in the REST API docs to actually be a function name, not an ObjectID.

**Comment by martinstibbe** [comment]
@willmorgan I am have replicated your issue  v 1.2.6 I think 1.4.6 was version further down the details ...
Using latest version I get error as well `│ Error: error creating MongoDB EventTriggers (621952567c87684fd69b0101): POST https://realm.mongodb.com/api/admin/v3.0/groups/621952grpid9b0101/apps/633b89e4ecappid28af8f/triggers: 400 (request "") cannot unmarshal into an ObjectID, the length must be 24 but it is 6` Let me check with engineering on realm library API to see where this constraint comes from

**Comment by martinstibbe** [comment]
@willmorgan I used Function id from URL in the portal I get past that 24 digit ID requirement I still get an error ` Error: error creating MongoDB EventTriggers (621952567c8grpd69b0101): POST https://realm.mongodb.com/api/admin/v3.0/groups/621952567grpb0101/apps/633b89efuncid03be328af8f/triggers: 400 (request "") a database trigger requires an associated Atlas cluster service`

**Comment by Zuhairahmed** [comment]
moving ticket to internal team to review ([HELP-40295](https://jira.mongodb.org/browse/HELP-40295)) thank you @willmorgan. we will keep you updated as we dive deeper here

**Comment by Zuhairahmed** [comment]
@willmorgan thanks for patience here, few comments: 

- You can use cURL command (GET All Triggers) to pull `function_id`. For details see latest docs [here](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#tag/triggers/operation/adminListTriggers). Note `function_id` terraform input is neither the function_name, nor ObjectId parameter. It is a separate 24 character string, i.e. "6410b8ca7b9822764c3e8f54"
- Before you can use Atlas App Services API, you need to generate Bearer `access_token` and then pull your Application ID. For steps on how to do this see [here](https://www.mongodb.com/docs/atlas/app-services/admin/api/v3/#section/Project-and-Application-IDs)
- After you do this please attempt to replicate this issue with latest version of the Terraform Atlas Provider (v1.8.1). Based on these steps I was able to `terraform apply` your above HCL code without any errors

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else here

**Comment by willmorgan** [comment]
@Zuhairahmed Thanks for looking into this. I was on holiday as you replied and only got back now, and have changed my approach since raising this issue -- but if this comes up again I will let you know. Thanks again!

**Comment by Zuhairahmed** [comment]
sounds good, feel free to open a new issue if you need anything else and as always thank you for all the great feedback

**Comment by Jonovono** [comment]
@Zuhairahmed I seem to be getting this issue as well:

```
mongodbatlas_event_trigger.mongodbAtlasTrigger: Creating...
╷
│ Error: error creating MongoDB EventTriggers (23423424): POST https://realm.mongodb.com/api/admin/v3.0/groups/<>/apps/<>/triggers: 400 (request "") a database trigger requires an associated Atlas cluster service
│
│   with mongodbatlas_event_trigger.mongodbAtlasTrigger,
│   on main.tf line 88, in resource "mongodbatlas_event_trigger" "mongodbAtlasTrigger":
│   88: resource "mongodbatlas_event_trigger" "mongodbAtlasTrigger" {
│
```

I believe I have the values correct:


```
# Assuming MongoDB Atlas Provider is already set up
resource "mongodbatlas_event_trigger" "mongodbAtlasTrigger" {
  name       = "testMongoEventTrigger"
  project_id = "projectid"
  app_id     = "appid"

  type      = "DATABASE"
  disabled  = false
  unordered = true
  # operation_types = ["INSERT", "UPDATE"]

  config_operation_types = ["INSERT", "UPDATE", "REPLACE", "DELETE"]
  config_database        = "database name"
  config_collection      = "collection name"
  config_service_id    = <gotten from running atlas clusters list>
  config_full_document = true
  event_processors {
    aws_eventbridge {
      config_region     = "213123123"
      config_account_id = "us-east-1"
    }
  }
}

```

**Comment by Jonovono** [comment]
If anyone comes back to this with the same issue:

Found it - it was config_service_id. I was using the cluster_id output from cluster creation in Terraform - turns out it expects the id of the data link added to the application.



```
Certainly! The Data Link ID is often needed when configuring MongoDB Realm to connect to a MongoDB Atlas cluster. While the MongoDB Atlas and Realm UIs are frequently updated, as of my last update in September 2021, you could typically find this information in the MongoDB Atlas web dashboard.

Here are the general steps to find the Data Link ID in MongoDB Atlas:

Via MongoDB Atlas Web Dashboard:
Login: Sign in to your MongoDB Atlas account.
Select Project: Navigate to the project where your MongoDB Realm app and Atlas Cluster reside.
Realm: Click on the Realm tab, which might also be represented with an icon resembling a leaf or similar.
Your App: Choose the Realm app that you're interested in.
Linked Data Sources: Go to the Linked Data Sources or similar section. This section is where you define the link between your Realm app and your MongoDB Atlas cluster.
Data Link ID: Here, you should see a list of the data sources linked to your app. There should be an ID or similar identifier for each link. This is your Data Link ID that you can use in your Terraform configuration.
```

**Comment by etwillbefine** [comment]
I was running into the same issue (`cannot unmarshal into an ObjectID, the length must be 24 but it is 64`) - correcting the `config_service_id` was the solution too. The documentation around that could be improved - as its unclear which value is needed and where to get it. Also it would be really great seeing a terraform resource for the application and data-link too!
