### ISSUE TITLE
Cannot update GCP network peer

### ISSUE THREAD

**Issue by Uvedale** [mongodb/terraform-provider-mongodbatlas#86]
**What I did**: Import a mongodbatlas_network_peering resource and run terraform apply to apply the `route_table_cidr_block` change it thinks it needs to make (asserting the same value)

**What I expected**: The change to be successful

**What happened**: 
```Error: error updating MongoDB Network Peering Connection (our-group-id): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/our-group-id/peers/our-peer-id: 404 (request "Not Found") No peer with ID our-peer-id exists in project our-group-id```

Looking at the MongoDB API and the code, it looks like the default provider of AWS is being applied and thus the peering connection isn't found since we are using GCP.

Plugin version: 0.3.1
Terraform version: v0.12.17

**Comment by themantissa** [comment]
Thank you @Uvedale , we'll ensure the team addresses.

**Comment by marinsalinas** [comment]
Hello @Uvedale, could you please check on https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/92 if the issue is still happening?

**Comment by Uvedale** [comment]
Hi @marinsalinas. Unfortunately it is not simple for me to try again as this happened on our production cluster and changes to production require change management. Looking at the code in that PR, I don't think that will fix it as I was specifying provider_name correctly as GCP. 

When I said "it looks like the default provider of AWS is being applied", I meant on the API server side. The [API call ](https://docs.atlas.mongodb.com/reference/api/vpc-get-connections-list/) doesn't require the providerName to be specified and I think it is being omitted in the PATCH call. I've commented on the PR where I think the issue is.

**Comment by themantissa** [comment]
@Uvedale can you share more of your config (redacted of course) so we can ensure we are fixing this issue correctly?   The more information we have the better we can address this.

**Comment by Uvedale** [comment]
This is the resource config in question:

```
resource "mongodbatlas_network_peering" "mongo_network_peering" {
  depends_on             = [mongodbatlas_private_ip_mode.mongo_private_ip_mode]
  project_id             = mongodbatlas_project.project.id
  container_id           = mongodbatlas_network_container.mongo.container_id
  gcp_project_id         = var.google_project_id
  route_table_cidr_block = var.peering_network_cidr_block
  provider_name          = "GCP"
  network_name           = var.peering_network_name
}
```

**Comment by themantissa** [comment]
@Uvedale https://github.com/terraform-providers/terraform-provider-mongodbatlas/pull/92 should correct this now.  If you can confirm it corrects the issue we'll merge.  Thanks!

**Comment by Uvedale** [comment]
```Error: error updating MongoDB Network Peering Connection (our-peer-id): PATCH https://cloud.mongodb.com/api/atlas/v1.0/groups/our-group/peers/our-peer-id: 400 (request "Bad Request") Invalid attribute gcpProjectId specified```

**Comment by themantissa** [comment]
@Uvedale I'm assuming that errors is from using a build including the fix (It's not in a released version yet).   @marinsalinas  fyi^^

**Comment by marinsalinas** [comment]
Hello @Uvedale, are you running this based on the branch `network-peering-68`?
Can you run `terraform apply` with TF_LOG=DEBUG and send us the log skipping sensitive data?

**Comment by Uvedale** [comment]
@marinsalinas Yes, I compiled the plugin from the branch to test. 
We solved this issue by just removing route_table_cidr_block as it isn't a required parameter for GCP peering. 

To reproduce the issue:
* Create a peering connection with config like the one I posted above in GCP
* Remove it from terraform state
* Re-import it
* Terraform apply

**Comment by PacoDw** [comment]
Hello, @Uvedale I fixed the bug, now you can update your peering connection, but you need to consider something, the reciprocal peering connection needs to be done.

You can test it on the same PR #92, let us know if you have another concern or comment, thank you.
