### ISSUE TITLE
Pausing MongoDB Atlas Cluster with option of start/end time

### ISSUE THREAD

**Issue by Suresh-Sathish-Kumar** [mongodb/terraform-provider-mongodbatlas#861]
Hi,

There is a parameter available for cluster resource to pause the cluster. With this parameter, we have to flip the status from pause to unpause whenever needed.

I am looking for separate resource (like maintenance window) where one can configure to pause the cluster for specific window (start/end time)

Example: I want to pause all non-prod clusters by Friday evening 5 PM EST and resume the cluster 7 AM EST. With trigger it is possible, but we do have hundreds of deployments. It would be great if we have resource where customer can specify their own timing to pause and unpause. 

The intention to have this feature is to save cost.

Thanks,
Suresh Sathish Kumar

**Comment by Zuhairahmed** [comment]
Thanks @Suresh-Sathish-Kumar for the feedback. Can you post this feature request on https://feedback.mongodb.com/ as well as any future feedback you may have on the Terraform MongoDB Atlas Provider. Feel free to also simply upvote an existing feature request if similar one exists.

**Comment by Suresh-Sathish-Kumar** [comment]
Thanks @Zuhairahmed for the response, I have posted the feature request on feedback.mongodb.com. Please find the link below.
https://feedback.mongodb.com/forums/924145-atlas/suggestions/45769846-pausing-mongodb-atlas-cluster-with-option-of-start

**Comment by Zuhairahmed** [comment]
Thank you! Closing ticket in this case, if you need anything else on this one feel free to re-open.
