### ISSUE TITLE
Projects Data Source inaccurate documentation 

### ISSUE THREAD

**Issue by ashraidiam** [mongodb/terraform-provider-mongodbatlas#867]
Hello, this a documentation bug for the `mongodbatlas_projects` data source to return all projects. The resource is incorrectly documented. projects != project.

The correct documentation should be:

```hcl

data "mongodbatlas_projects" "active_projects" {
  page_num = 1
  items_per_page = 5

}

```

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
data "mongodbatlas_project" "active_projects" {
  page_num = 1
  items_per_page = 5

}
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
```

### Steps to Reproduce

Create the resource as described above. 

### Expected Behavior

Data to be returned. 

### Actual Behavior

```hcl
│ Error: Unsupported argument
│ 
│   on projects.tf line 18, in data "mongodbatlas_project" "active_projects":
│   18:   page_num = 1
│ 
│ An argument named "page_num" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on projects.tf line 19, in data "mongodbatlas_project" "active_projects":
│   19:   items_per_page = 5
│ 
│ An argument named "items_per_page" is not expected here.
```

### References

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/projects

**Comment by Zuhairahmed** [comment]
Great catch @ashraidiam. PR created and docs should be updated next week. https://github.com/mongodb/terraform-provider-mongodbatlas/pull/869

**Comment by Zuhairahmed** [comment]
Closing as PR has been merged https://github.com/mongodb/terraform-provider-mongodbatlas/pull/869
