### ISSUE TITLE
No "storedSource" parameter present in atlas provider for atlas search index

### ISSUE THREAD

**Issue by andriihrachov** [mongodb/terraform-provider-mongodbatlas#871]
**Provider version** : 1.4.6

**Expected:**

- Ability to configure "storedSource" parameter in atlas search index

**Actual:**

It's not possible with current provider version

**Comment by Zuhairahmed** [comment]
Hi @andriihrachov "storedSource" parameter is not available in the [Atlas Admin API ](https://www.mongodb.com/docs/atlas/reference/api/atlas-search/) so when we expose via the [MongoDB Atlas Terraform Provider](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/search_index) it won't be there either. If this is something that you think would be helpful feature to add please leave your feedback along with proposed use case at [feedback.mongodb.com](https://feedback.mongodb.com/) under Atlas Search section. 

In the interim, suggest explore if possible to perform these actions via the [Atlas UI ](https://www.mongodb.com/docs/atlas/atlas-search/return-stored-source/#std-label-fts-return-stored-source-option) instead.

**Comment by andriihrachov** [comment]
Thanks @Zuhairahmed ! I'll leave feedback there

**Comment by sqshq** [comment]
Hi @andriihrachov, @Zuhairahmed
Actually `storedSource` was always supported via the Admin API. The linked documentation page is deprecated and currently not supported, the [OpenAPI based docs](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Atlas-Search) will be updated soon, sorry for the confusion.

Here is an example request to create an Atlas Search index with stored source:

```
curl --user "{PUBLIC-KEY}:{PRIVATE-KEY}" --digest \
     --header "Content-Type: application/json" \
     --include \
     --request POST "https://cloud.mongodb.com/api/atlas/v1.0/groups/{GROUP-ID}/clusters/{CLUSTER-NAME}/fts/indexes?pretty=true" \
     --data '{
         "collectionName": "orders",
         "database": "test",
         "mappings": {
           "dynamic": true
         },
         "storedSource": {
           "include": [
             "location",
             "guests.personal.firstName",
             "guests.personal.lastName"
           ]
         },
         "name": "default"
       }'
```

Please let me know if you have any questions.

**Comment by andriihrachov** [comment]
sorry, just revisiting this - are we gonna have this in terraform provider as parameter?

**Comment by Zuhairahmed** [comment]
Hi @andriihrachov / @sqshq yes we will be adding to Terraform. Internal engineering ticket [INTMDB-443](https://jira.mongodb.org/browse/INTMDB-443). Likely still a few quarters away, will update this thread when it has been released. Hope this helps.

**Comment by andriihrachov** [comment]
Thanks a lot! @Zuhairahmed

**Comment by hazooma** [comment]
Any updates on this ? We also have the same issue. Thanks

**Comment by Zuhairahmed** [comment]
hi @hazooma, unfortunately no update at this time. I'm hoping to have another update out before end of the year, but still TBD

**Comment by sinafbd** [comment]
+1

**Comment by zghib** [comment]
Hey, any news on this?

**Comment by Zuhairahmed** [comment]
hi @sinafbd and @zghib if this is something that you think would be helpful feature to add please leave your feedback along with proposed use case at [feedback.mongodb.com](https://feedback.mongodb.com/) or +1 and existing comment. This will also help us prioritize this request faster. Thank you

**Comment by estebanbresba** [comment]
+1

**Comment by antoniolibrada** [comment]
+1

**Comment by gssbzn** [comment]
For those +1 on this issue please vote on the [feedback](https://feedback.mongodb.com/forums/924868-atlas-search/suggestions/45815407-add-storedsource-parameter-to-atlas-admin-api-sear) page

**Comment by Zuhairahmed** [comment]
Given this item is more a feature request best way to prioritize this item is to through UserVoice portal: https://feedback.mongodb.com/forums/924868-atlas-search/suggestions/45815407-add-storedsource-parameter-to-atlas-admin-api-sear 

Will be sharing updates on this item there. Hence resoling this issue. Feel free to create a new issue in case you need anything else. Thank you
