### ISSUE TITLE
Documentation Error for Teams Data Source

### ISSUE THREAD

**Issue by ashraidiam** [mongodb/terraform-provider-mongodbatlas#879]
Hello, this a documentation bug for the `mongodbatlas_teams` data source. The resource is incorrectly documented. teams != teams..

The correct documentation should be:

```hcl

data "mongodbatlas_team" "developers" {
  org_id = 123
  name   = mongodbatlas_team.developers.name
}

```

### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
```

### Steps to Reproduce

Create the resource as described above. 

### Expected Behavior

Data to be returned. 

### Actual Behavior

```hcl
 Error: Reference to undeclared resource
│ 
│   on  projects.tf line 17, in module "projects":
│   17:   team_id  = data.mongodbatlas_team.developers.team_id
│ 
│ A data resource "mongodbatlas_team" "developers" has not been declared in the root module.
```

### References

https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/data-sources/projects

**Comment by Zuhairahmed** [comment]
Thank you @ashraidiam for your eagle eyes! Do you mind creating a quick PR for this one? Also please be sure to sign the CLA if you haven't already. https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/CONTRIBUTING.md

**Comment by ashraidiam** [comment]
@Zuhairahmed I'm still rocking MK1 eyeballs 😂😂. Sure I will PR.

**Comment by Zuhairahmed** [comment]
Closing as PR was created here: https://github.com/mongodb/terraform-provider-mongodbatlas/pull/881
