### ISSUE TITLE
How to create a triggered a function 

### ISSUE THREAD

**Issue by greg-leocare** [mongodb/terraform-provider-mongodbatlas#889]
Hello, I try to add a Database trigger function, but in the mongodbatlas_event_trigger ressource I only found the field function_id to describe the action to do when the event is triggered.

I don't understand who to put my JS code that I want to exec when the event is triggered ? 
Which ressource must I use to define the function ?
Does anyone can help me ?

**Comment by Zuhairahmed** [comment]
hi @greg-leocare currently the MongoDB Atlas Terraform Provider does not yet support the ability to define [Atlas Functions](https://www.mongodb.com/docs/atlas/app-services/functions/) (this is where you would input the server-side JavaScript code). Atlas Functions are on our Terraform provider roadmap, but likely a few quarters out at this time. in the interim you can leverage the [App Services UI](https://www.mongodb.com/docs/atlas/app-services/functions/#create-a-new-function) or [App Services CLI](https://www.mongodb.com/docs/atlas/app-services/functions/#pull-your-app-s-latest-configuration-files) to first define your Atlas Function and then reference Function ID in your Terraform config files for resource [mongodbatlas_event_trigger](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/event_trigger). 

lastly, if you would like to raise this issue (or upvote an existing issue) at [feedback.mongodb.com](https://feedback.mongodb.com/forums/924145-atlas?category_id=370723), this helps us gauge customer need and adjust our roadmap accordingly if possible. we can also update you on timelines on submitted issues there. hope this helps. if you have no additional follow ups, feel free to close this issue. thank you.
