### ISSUE TITLE
Why is `org_id` a required argument?

### ISSUE THREAD

**Issue by azelezni** [mongodb/terraform-provider-mongodbatlas#892]
Just like the title says, why is `org_id` a required argument? Why is it even a configurable argument?
If the key is an organization API Key then why do I need to hardcode the org ID? (meaning a key can only be used within a single org, and not with multiple).
Also there is no data-source or anything to help find the org ID so the only way is to hardcode it somewhere.

In no other TF Provider have I encountered this, the org ID is something that should be handled by the provider.

Unless I'm missing something, is it even possible to use 1 API Key and work on multiple different organizations?

The only way around this I could find is to use an existing project to find out the org_id

```
provider "mongodbatlas" {
  public_key  = "foo"
  private_key = "bar"
}

data "mongodbatlas_project" "fake_proj_for_org_id" {
  name = "Fake Project For TF"
}

resource "mongodbatlas_project" "this" {
  name   = "ProjectTest"
  org_id = data.mongodbatlas_project.fake_proj_for_org_id.org_id
}
```

**Comment by Zuhairahmed** [comment]
@azelezni the resource [mongodbatlas_project](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project) in the Terraform provider simply exposes the [Create One Project](https://www.mongodb.com/docs/atlas/reference/api/project-create-one/) endpoint in the Atlas Admin API. Here both Name and Org_ID (as you correctly point out) are required parameters. If helpful, we are working to create a new endpoint to Programmatically Create Atlas Organizations which believe may help, but this is still 12 months+ away.    

If would like to raise your feature request at [feedback.mongodb.com](https://feedback.mongodb.com/forums/924145-atlas?category_id=370723), I'm happy to work with the team to try to expediate. If you have no other questions feel free to close this issue and can keep you updated over there. Thank you.
