### ISSUE TITLE
Add termination protection attribute to mongodbatlas_cluster resource

### ISSUE THREAD

**Issue by idriss-mezguich** [mongodb/terraform-provider-mongodbatlas#896]
A new `Termination protection`  attribute has been been added in the mongodb atlas UI, it would be really helpful if this can be set with Terraform as well. The `prevent_destroy` attribute in the lifecycle block does a similar thing but its value cannot be a variable so we cannot use at the moment if you have multiple environments and you want to set the `prevent_destroy` dynamically.

**Comment by Zuhairahmed** [comment]
Thanks @idriss-mezguich . We have added this feature to our roadmap and you can except to see updates here over the next few months. Appreciate your feedback. 

To stay update to date with feature feel free to upvote or comment on our feedback portal here: https://feedback.mongodb.com/forums/924145-atlas/suggestions/45892120-terraform-feature-request-cluster-termination-pro
