### ISSUE TITLE
Error importing ressource mongodbatlas_network_peering.mongo_peer

### ISSUE THREAD

**Issue by clement94310** [mongodb/terraform-provider-mongodbatlas#906]
Hello

i have an error on this command of import ressource mongodbatlas_network_peering.mongo_peer

 terraform  import mongodbatlas_network_peering.mongo_peer XXXXXXXXXXXXXX-XXXXXXX-AWS
mongodbatlas_network_peering.mongo_peer: Importing from ID "XXXXXXXXXXXXXX-XXXXXXX-AWS"...
╷
│ Error: couldn't import peer pcx in project XXXXXXX, error: GET https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXXXXXX/peers/pcx: 400 (request "PATH_PARAM_PARSE_ERROR") One or more path parameter in the request URI /api/atlas/v1.0/groups/XXXXXXXX/peers/pcx is malformed.

**Comment by evertsd** [comment]
Hi @clement94310 so you're aware, it looks like you omitted the parameters in demonstrating the import command, but included them in the error message.

Have you verified your peerID and projectID are correct?
The projectID looked correct to me, but the peerID perhaps looked like a name rather than an ID?

**Comment by clement94310** [comment]
I put the Atlas_project_ID-Peer_id-AWS.
the peer_id start with pcx- i tried with the pcx and without

without this is the result i put XXX in place of my privates IDs

Error: couldn't import peer XXXXX in project XXXXXXXX, error: GET https://cloud.mongodb.com/api/atlas/v1.0/groups/XXXXXX/peers/XXXXXX: 400 (request "PATH_PARAM_PARSE_ERROR") One or more path parameter in the request URI /api/atlas/v1.0/groups/XXXXXXX/peers/XXXXXXXX is malformed.

**Comment by evertsd** [comment]
I believe you may be using the peer connectionId, which is shown on the atlas ui. I'm unsure if the peerID is shown on that ui, however I was able to find the peerID using the following atlas-cli command
```
my-machine$ atlas networking peering list --projectId XXX
[
  {
    "awsAccountId": "XXX",
    "connectionId": "pcx-XXX",
    "containerId": "XXX",
    "id": "<USE THIS>",
    "routeTableCidrBlock": "XXX...XXX/XX",
    "statusName": "PENDING_ACCEPTANCE",
    "vpcId": "vpc-XXX"
  }
]
```

**Comment by clement94310** [comment]
it works thanks

**Comment by clement94310** [comment]
but when i import my "mongodbatlas_network_peering" it does not come in the states

import mongodbatlas_network_peering.mongo_peer XXXXXX-XXXXX-AWS       
data.mongodbatlas_project.mongo_project: Reading...
data.mongodbatlas_project.mongo_project: Read complete after 1s [id=XXXXX]
data.aws_route_tables.private: Reading...
data.aws_route_table.public: Reading...
data.aws_route_table.public: Read complete after 0s [id=rtb-XXXX]
data.aws_route_tables.private: Read complete after 0s [id=eu-west-3]

**Comment by evertsd** [comment]
I'm not exactly sure what you're asking @clement94310.

Are you saying the import runs successfully but that the state cannot be found in the resulting `terraform.tfstate`?

**Comment by clement94310** [comment]
@evertsd 
hello
yes it is in the state.
But when i run the plan it say it create a new one :

# mongodbatlas_network_peering.mongo_peer["vpc_peer_dev"] will be created
  + resource "mongodbatlas_network_peering" "mongo_peer" {
      + accepter_region_name   = "eu-west-3"
      + atlas_cidr_block       = (known after apply)
      + atlas_gcp_project_id   = (known after apply)
      + atlas_id               = (known after apply)
      + atlas_vpc_name         = (known after apply)
      + aws_account_id         = "XXX"
      + azure_directory_id     = (known after apply)
      + azure_subscription_id  = (known after apply)
      + connection_id          = (known after apply)
      + container_id           = "XXXX"
      + error_message          = (known after apply)
      + error_state            = (known after apply)
      + error_state_name       = (known after apply)
      + gcp_project_id         = (known after apply)
      + id                     = (known after apply)
      + network_name           = (known after apply)
      + peer_id                = (known after apply)
      + project_id             = "XXXXX"
      + provider_name          = "AWS"
      + resource_group_name    = (known after apply)
      + route_table_cidr_block = "XXXXX/16"
      + status                 = (known after apply)
      + status_name            = (known after apply)
      + vnet_name              = (known after apply)
      + vpc_id                 = "vpc-XXXXX"
    }

**Comment by clement94310** [comment]
sorry i was in a for each and i ahd to put tjis in my terraform import request :
tg  import 'mongodbatlas_network_peering.mongo_peer["element1"]' XXXXX-XXXX-AWS

it works fine
