### ISSUE TITLE
An argument named "webhook_url" is not expected here.

### ISSUE THREAD

**Issue by pragnesh-highlevel** [mongodb/terraform-provider-mongodbatlas#916]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
```hcl
Terraform v1.3.4
MongoDB Atlas Provider v1.3.1
```

### Terraform Configuration File 
```hcl
resource "mongodbatlas_alert_configuration" "cluster" {
  ....
  notification {
          delay_min     = 2
          interval_min  = 5
          roles         = []
          type_name     = "WEBHOOK"
          webhook_url   = "<url value>"
      }
    ....
}
```

### Steps to Reproduce
1. `Add alert configuration with webhook type of notification and add webhook_url parameter`
2. `terraform plan`

### Expected Behavior
It should accept webhook_url param and update it during terraform apply.

### Actual Behavior
Throws error "Unsupported argument -  An argument named "webhook_url" is not expected here."

### Debug Output 
NA

### Crash Output
NA

### Additional Context
NA

### References
NA

**Comment by Zuhairahmed** [comment]
hi @pragnesh-highlevel this feature is available in latest Terraform MongoDB Atlas Provider v1.5.0. Can you upgrade and let us know if this resolves your issue? https://registry.terraform.io/providers/mongodb/mongodbatlas/latest

**Comment by pragnesh-highlevel** [comment]
Thanks @Zuhairahmed . I upgraded to latest version and it's expecting webhook_url now. Thanks for quick resolution and reply.
