### ISSUE TITLE
GCP Network Peering remains pending when created via terraform

### ISSUE THREAD

**Issue by tback** [mongodb/terraform-provider-mongodbatlas#917]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.4
on darwin_arm64
+ provider registry.terraform.io/digitalocean/digitalocean v2.23.0
+ provider registry.terraform.io/hashicorp/google v4.43.0
+ provider registry.terraform.io/hashicorp/google-beta v4.43.0
+ provider registry.terraform.io/hashicorp/helm v2.7.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.15.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/mongodb/mongodbatlas v1.5.0
+ provider registry.terraform.io/vancluever/acme v2.11.1
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_network_container" "prod" {
  project_id       = mongodbatlas_project.prod.id
  atlas_cidr_block = "x.x.0.0/16"
  provider_name    = "GCP"
}
# Create the peering connection request
resource "mongodbatlas_network_peering" "prod" {
  project_id     = mongodbatlas_project.prod.id
  container_id   = mongodbatlas_network_container.prod.container_id
  provider_name  = "GCP"
  gcp_project_id = google_project.prod.project_id
  network_name   = "default"
}
resource "google_compute_network_peering" "mongodb_atlas" {
  name         = "peering-gcp-terraform-prod"
  network      = google_compute_network.vpc-02.self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${mongodbatlas_network_peering.prod.atlas_gcp_project_id}/global/networks/${mongodbatlas_network_peering.prod.atlas_vpc_name}"
}

```

### Steps to Reproduce
Apply terraform module. Create mongodbatlas project in same step.
```
terraform init
terraform apply
```

### Expected Behavior
Network peering to GCP should become available.

### Actual Behavior
State of peering remains "Pending"/"Inactive" as seen in screenshots.

### Debug Output 

Debug Output can be provided. It's full of sensitive data though. I prefer to share it confidentially.
<img width="575" alt="Screenshot 2022-11-12 at 12 13 48" src="https://user-images.githubusercontent.com/83432/201471796-6b3317a8-f5e0-4bbb-937e-ae8513b350a1.png">
<img width="349" alt="Screenshot 2022-11-12 at 12 13 19" src="https://user-images.githubusercontent.com/83432/201471799-4941a8d2-3937-4d25-82a8-9d0b34394351.png">

**Comment by Zuhairahmed** [comment]
hi @tback, for the atlas_cidr_block parameter in the mongodbatlas_network_container resource you can't use the Atlas user interface to specify an Atlas CIDR block smaller than /18 for GCP. for more information see our documentation: https://www.mongodb.com/docs/atlas/security-vpc-peering/ 

also if easier, we have created example templates for users to get started faster with VPC Peering on GCP in case you would like to leverage: https://github.com/mongodb/terraform-provider-mongodbatlas/tree/master/examples/MongoDB-Atlas-GCP-VPC-Peering

**Comment by kev-in047** [comment]
I'm also experiencing the same issue, with the following terraform config:

### Terraform config file

```
resource "mongodbatlas_network_container" "peering_container" {
  project_id       = local.project_id
  atlas_cidr_block = var.atlas_cidr_block
  provider_name    = "GCP"
}

resource "mongodbatlas_network_peering" "mongo_peering" {
  project_id     = local.project_id
  container_id   = mongodbatlas_network_container.peering_container.container_id
  provider_name  = "GCP"
  gcp_project_id = var.gcp_project
  network_name   = "mongo_net"
  depends_on = [
    mongodbatlas_network_container.peering_container
  ]
}

data "google_compute_network" "gcp_network" {
  name = var.gcp_network
}

resource "google_compute_network_peering" "peering" {
  name         = "mongo-peering"
  network      = data.google_compute_network.gcp_network.self_link
  peer_network = "https://www.googleapis.com/compute/v1/projects/${mongodbatlas_network_peering.mongo_peering.atlas_gcp_project_id}/global/networks/${mongodbatlas_network_peering.mongo_peering.atlas_vpc_name}"
  depends_on = [
    mongodbatlas_network_peering.mongo_peering
  ]
}

resource "mongodbatlas_project_ip_access_list" "my_ipaddress" {
  project_id = local.project_id
  cidr_block = var.cidr
  comment    = "CIDR block for GCP VPC Whitelist"
  depends_on = [
    google_compute_network_peering.peering
  ]
}
```


### Terraform and Provider versions

```
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/hashicorp/google v4.44.1
+ provider registry.terraform.io/hashicorp/google-beta v4.44.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.0
```


@tback did you find a solution/workaround?

**Comment by evertsd** [comment]
From my initial testing, it seems that there's an inferred connection between atlas and gcp, where the following have to have equality
```
mongodbatlas_network_peering.mongo_peering.network_name == google_compute_network.gcp_network.name
```

Further evidence on that equality being a requirement is the `mongodbatlas_network_peering` documentation here https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/network_peering#argument-reference

I can't tell from the examples either of you provided, @tback & @kev-in047, were those values the same in your configurations?

**Comment by kev-in047** [comment]
@evertsd the two values were not the same in my case. Changing them to the same value fixed the issue for me. Thanks

**Comment by Zuhairahmed** [comment]
just checking @tback are you still blocked here? if not, feel free to close this issue. thank you

**Comment by tback** [comment]
I don't know how this escaped my radar after asking for help on this. Yes matching the network names was the issue here @kev-in047 . Thanks a lot for your help.
