### ISSUE TITLE
Terraform apply failed with Error: Provider produced inconsistent final plan This is a bug in the provider, which should be reported in the provider's own issue tracker.

### ISSUE THREAD

**Issue by devopsvj** [mongodb/terraform-provider-mongodbatlas#926]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.3
on windows_amd64
```

### Terraform Configuration File 

```hcl
terraform {
  required_providers {
    mongodbatlas = {
      source = "mongodb/mongodbatlas"
      version = "1.5.0"
    }
  }
}

also tried with previous version of provider 1.4.6 same results 
```

### Actual Behavior

Error: Provider produced inconsistent final plan

When expanding the plan for
module.mongo_base.module.mongodbatlas.mongodbatlas_x509_authentication_database_user.my_user
to include new values learned so far during apply, provider
"registry.terraform.io/mongodb/mongodbatlas" produced an invalid new value
for .certificates[0].id: was cty.NumberIntVal(6.656703865428611756e+18), but
now cty.NumberIntVal(6.656703865428612e+18).

This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Additional Context

The above issue is not happening with terraform cli 1.0.5 with mongo provider version 1.5.0

**Comment by Zuhairahmed** [comment]
hi @devopsvj, can you share config and log files with us so we can try to reproduce the error from our end? 

also can you explain more what you mean by "The above issue is not happening with terraform cli 1.0.5 with mongo provider version 1.5.0"? The Terraform MongoDB Atlas Provider v1.5.0 is just the reference to the provider being used in the .tf files to create MongoDB Atlas resources.

**Comment by devopsvj** [comment]
@Zuhairahmed  I mean to say,  reported issue is not occurring when using terraform cli version 1.0.5 with mongo provider version 1.5.0.   

1.  Initial deployment using the terraform cli 1.3.3 successfully deployed resources.
2.  However the issue is occurred when we tried to apply second time with with change in audit attributes.  
3.  On the same scenario, if we use terraform cli 1.0.5, reported issue is not occurring.

**Comment by Zuhairahmed** [comment]
ok thanks for more context, can you share your terraform config files so we can re-create issue from our end?
