### ISSUE TITLE
Double checking Terraform Plan before I destroy Production

### ISSUE THREAD

**Issue by mentlak0** [mongodb/terraform-provider-mongodbatlas#938]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.0
```

### Terraform Configuration File 

```hcl
# Copy-paste your configuration info here
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
### Expected Behavior

Nice clean plan showing creates and changes. Not deleting.
### Actual Behavior

Showing replication specs being deleted and added on adv cluster.

![image](https://user-images.githubusercontent.com/93769720/204244892-600ac6d1-5df2-4004-aa22-c7215a925330.png)

### Additional Context

Something that not happened before. But this is infrastructure for production cluster and if I was to yolo it and it to go down I would be heartbroken.

Can someone confirm this is normal? I saw a closed issue from some time back and said that the changes are applied, not destroyed and applied. But I don't want to risk it so thought maybe a possible issue with the plugin.

**Comment by Zuhairahmed** [comment]
hi @mentlak0 there a number of resources that can get destroyed in Terraform when making changes. for example, changing the name of an existing Project in your Terraform configuration will result the destruction of that Project and related resources (including Clusters) and the re-creation of those resources. see here for more details on this one: https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/project

if you share your terraform config we can go into more detail. hope this helps.

**Comment by mentlak0** [comment]
@Zuhairahmed Good Evening, thank you very much for your reply. I can confirm that it was a 'me' problem. 

After further looking into it today there was a bit of config missing. Terraform didn't specifically shout about this. 

Thanks :)
