### ISSUE TITLE
Unable to add mongodbatlas provider to CDK

### ISSUE THREAD

**Issue by jose-jor** [mongodb/terraform-provider-mongodbatlas#952]
Getting the following error when trying to add mongodbatlas provider to CDK
### Error Screenshot
<img width="1349" alt="Screen Shot 2022-12-01 at 4 14 49 PM" src="https://user-images.githubusercontent.com/89214231/205369132-a110baf0-5d99-48c8-a86f-8222d3745107.png">

**Comment by Zuhairahmed** [comment]
Hi @jose-jor, believe there may be a syntax error. can you try `"version": "~>1.6.0"` instead and see if that unblocks you? more details here if helpful: https://developer.hashicorp.com/terraform/language/expressions/version-constraints#version-constraint-syntax

**Comment by jose-jor** [comment]
@Zuhairahmed so the command would be this "cdktf provider add mongoldb/mongodbatlas~>1.6.0"

**Comment by jose-jor** [comment]
@Zuhairahmed 
<img width="1254" alt="Screen Shot 2022-12-02 at 2 47 01 PM" src="https://user-images.githubusercontent.com/89214231/205374341-27d965ba-012a-4ac7-b72f-0ada36ec1b77.png">

**Comment by Zuhairahmed** [comment]
thanks @jose-jor, can you simply try the the `cdktf provider add mongodb/mongodbatlas` command in terminal? this should grab the latest Terraform MongoDB Atlas version from the Terraform Registry which is v1.6.0 and download locally into your environment. more details here: https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install
