### ISSUE TITLE
mongodbatlas_third_party_integration - api_token keeps updating on every apply

### ISSUE THREAD

**Issue by legal90** [mongodb/terraform-provider-mongodbatlas#963]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v1.3.6
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.1
```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_third_party_integration" "atlas_datadog" {
  project_id = mongodbatlas_project.atlas_project.id
  type = "DATADOG"
  api_key = var.datadog_api_key
  region = var.datadog_region
}
```

### Expected Behavior
No updates on subsequent `terraform apply`

### Actual Behavior
`terraform apply` always keeps offering to update the `api_key` attribute:
```terraform
  # mongodbatlas_third_party_integration.atlas_datadog will be updated in-place
  ~ resource "mongodbatlas_third_party_integration" "atlas_datadog" {
      ~ api_key                     = (sensitive value)
        id                          = "cHJvamVjdF9pZA==:NWY1OGFhMjczYzE1YzQ2NGNkNTdmYWVm-dHlwZQ==:REFUQURPRw=="
        # (9 unchanged attributes hidden)
    }
```

### Additional Context
The symptoms are exactly the same as was described in https://github.com/mongodb/terraform-provider-mongodbatlas/issues/863#issuecomment-1341034504. 
The value of `api_key` In the terraform state dumped by `terraform state pull` is masked and looks like `****************************a1b2c3`.
`terraform apply` doesn't fix it.

### References
This issue looks similar to https://github.com/mongodb/terraform-provider-mongodbatlas/issues/863

**Comment by martinstibbe** [comment]
@legal90 Will capture this fix in internal engineering ticket [INTMDB-519](https://jira.mongodb.org/browse/INTMDB-519)

**Comment by Zuhairahmed** [comment]
@legal90 as an update, this issue has been picked up in current sprint cycle and you can expect fix to be included as part of v1.8.0 release next week. will let you know when latest release has been published to the Terraform Registry.

**Comment by Zuhairahmed** [comment]
@legal90  we just released v1.8.0, feel free to give it try! issue should have been resolved.

**Comment by legal90** [comment]
@Zuhairahmed, thank you very much! I confirm that this issue is fixed in v1.8.0. 
There is no such diff in terraform plan or apply anymore 👍

**Comment by Zuhairahmed** [comment]
wonderful news thanks for the confirmation @legal90!

**Comment by AHovorukha** [comment]
I want to reopen this as I have the same issue with mongodbatlas v1.15.3.
