### ISSUE TITLE
Segmentation Fault in TerraForm Provider

### ISSUE THREAD

**Issue by fkieling** [mongodb/terraform-provider-mongodbatlas#969]
SegFault mit TF Provider 1.6.1 / TerraForm: 1.3.3

* Initial einen Atlas-Stack mit 2 Clustern durchgeführt - ohne Probleme
* Änderung an der Config frequency_interval von 1 auf 2 durchgeführt
* beim anschliessenden terraform apply tritt der nachstehend aufgeführte SegFault auf

module.mongodb_atlas.module.cloud-backup.mongodbatlas_cloud_backup_schedule.backup["atlas-test-cluster-1-r7ifcbw"]: Modifying... [id=Y2x1c3Rlcl9uYW1l:YXRsYXMtdGVzdC1jbHVzdGVyLTEtcjdpZmNidw==-cHJvamVjdF9pZA==:NjM5YzE3ZmFiODhmNTQ2YzFkMjNhMjcz]
╷
│ Error: Request cancelled
│
│   with module.mongodb_atlas.module.cloud-backup.mongodbatlas_cloud_backup_schedule.backup["atlas-test-cluster-1-r7ifcbw"],
│   on ../../cloud-backup/cloud-backup.tf line 13, in resource "mongodbatlas_cloud_backup_schedule" "backup":
│   13: resource "mongodbatlas_cloud_backup_schedule" "backup" {
│
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
 
Stack trace from the terraform-provider-mongodbatlas_v1.6.1 plugin:
 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x705328]
 
goroutine 38 [running]:
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.cloudBackupScheduleCreateOrUpdate({0xaa2b08, 0x400007b860}, 0x4000226c00, 0xc?, {0x4000176960, 0x18}, {0x400003b520, 0x1c})
    github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go:468 +0x788
github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas.resourceMongoDBAtlasCloudBackupScheduleUpdate({0xaa2b08, 0x400007b860}, 0x4000223400, {0x844520?, 0x400017f280?})
    github.com/mongodb/terraform-provider-mongodbatlas/mongodbatlas/resource_mongodbatlas_cloud_backup_schedule.go:348 +0x1b4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0x4000440000, {0xaa2b40, 0x40002cf4a0}, 0xd?, {0x844520, 0x400017f280})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0xec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x4000440000, {0xaa2b40, 0x40002cf4a0}, 0x40002156c0, 0x4000223280, {0x844520, 0x400017f280})
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x65c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x4000336450, {0xaa2b40?, 0x40002cf380?}, 0x4000591130)
    github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xbd0
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x4000318b40, {0xaa2b40?, 0x40002ceae0?}, 0x4000242000)
    github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x3c4
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x91c980?, 0x4000318b40}, {0xaa2b40, 0x40002ceae0}, 0x4000553f80, 0x0)
    github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x40001201e0, {0xaa5f60, 0x400020c9c0}, 0x40001347e0, 0x40004423f0, 0xfa10a0, 0x0)
    google.golang.org/grpc@v1.50.1/server.go:1340 +0xb7c
google.golang.org/grpc.(*Server).handleStream(0x40001201e0, {0xaa5f60, 0x400020c9c0}, 0x40001347e0, 0x0)
    google.golang.org/grpc@v1.50.1/server.go:1713 +0x854
google.golang.org/grpc.(*Server).serveStreams.func1.2()
    google.golang.org/grpc@v1.50.1/server.go:965 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
    google.golang.org/grpc@v1.50.1/server.go:963 +0x29c
 
Error: The terraform-provider-mongodbatlas_v1.6.1 plugin crashed!
 
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
 
ERRO[0022] Terraform invocation failed in /home/fkielin1/Projects/maps-bb-mongodb_atlas/mongodb_atlas/examples/complete
ERRO[0022] 1 error occurred:
    * exit status 1

**Comment by martinstibbe** [comment]
@fkieling I will attempt to replicate your issue by updating frequency_interval parameter from 1 to 2

**Comment by martinstibbe** [comment]
Replicated issue .. This is related to a possible bug internal ticket [INTMDB-427](https://jira.mongodb.org/browse/INTMDB-427) should fix this issue soon

**Comment by fkieling** [comment]
Yes. It's the same as [INTMDB-427](https://jira.mongodb.org/browse/INTMDB-427.)

**Comment by Zuhairahmed** [comment]
@fkieling as an update, this issue has been picked up in current sprint cycle and you can expect fix to be included as part of v1.8.0 release next week. will let you know when latest release has been published to the Terraform Registry.

**Comment by Zuhairahmed** [comment]
@fkieling we just released v1.8.0, feel free to give it try! issue should have been resolved.

**Comment by Zuhairahmed** [comment]
Closing this issue, but feel free to re-open if you need anything else here
