### ISSUE TITLE
num_shards value changed to 1

### ISSUE THREAD

**Issue by jmeagheriv** [mongodb/terraform-provider-mongodbatlas#970]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform v0.13.7
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.1

```

### Terraform Configuration File 

```hcl
resource "mongodbatlas_cluster" "cluster-test"
 project_id   = var.projid
 name         = "cluster-test"
 cluster_type = "SHARDED"
 replication_specs {
   num_shards = 3
   regions_config {
     region_name     = "US_EAST_1"
     electable_nodes = 3
     priority        = 7
     read_only_nodes = 0
   }
 }
 cloud_backup = true
 auto_scaling_disk_gb_enabled = true
 mongo_db_major_version       = "4.2"
 # Provider Settings "block"
 provider_name               = "AWS"
 disk_size_gb                = 100
 provider_instance_size_name = "M30"
}
```

### Expected Behavior
No changes

### Actual Behavior 
      ~ num_shards                              = 3 -> 1
 Number of shards reset to 1.

### Crash Output
No Crash output

### Additional Context
There are two different num_shards values in the plan output, one in replicationSpecs and one before that. If you have a sharded cluster and make any change except to num_shards it will revert the num_shards to 1. This issue could cause someone to remove shards erroneously.

### References
https://github.com/mongodb/terraform-provider-mongodbatlas/blob/master/mongodbatlas/data_source_mongodbatlas_cluster.go

**Comment by jmeagheriv** [comment]
Updated the references it seems in this resource there is num_shards inside the replication_specs and outside it. If you set them both the issue doesn't occur but your config looks weird with the same variable set multiple times

**Comment by martinstibbe** [comment]
@jmeagheriv Investigating the overlap of parameters with engineering to determine best course of action

**Comment by Zuhairahmed** [comment]
@jmeagheriv this issue has been resolved in [`advanced_cluster` ](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/advanced_cluster) resource with only 1 num_shards parameter within `replicationSpecs` block. For more details see here:  https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Multi-Cloud-Clusters/operation/listClusters

You are correct there are 2 num_shards parameters in [`cluster`](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest/docs/resources/cluster) resource and would recommend in this case to adopt advanced_cluster resource where possible going forward. Closing issue, but feel free to re-open if you need anything else here.
