### ISSUE TITLE
Type: TEAM alert notification not saved properly

### ISSUE THREAD

**Issue by pragnesh-highlevel** [mongodb/terraform-provider-mongodbatlas#971]
### Terraform CLI and Terraform MongoDB Atlas Provider Version

```hcl
Terraform - 1.3.6
mongodb/mongodbatlas - 1.5.0
```

### Terraform Configuration File 

```hcl
notification {
        delay_min     = 0
        email_enabled = true
        interval_min  = 60
        roles         = []
        sms_enabled   = true
        team_id       = mongodbatlas_teams.database-managers.team_id
        type_name     = "TEAM"
    }
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` and submit changes
3. `terraform apply`
4.  For this notification type it will prompt it has been changed even if nothing has been changed as shown below
```
~notification {
          ~ email_enabled = false -> true
          ~ sms_enabled   = false -> true
            # (5 unchanged attributes hidden)
        }
```
5. Open same alert configuration in Atlas console. 
6. Try to save it without changing anything 
7.  It shows below error 
<img width="1004" alt="Screenshot 2022-12-18 at 5 06 43 PM" src="https://user-images.githubusercontent.com/104757041/208296201-f3539b6b-e216-44e4-9a13-0a810e662436.png">

### Expected Behavior
- During second time when we apply changes via terraform it should not prompt for changes (if no changes are made)
- It should save alert configuration via terraform so that it should not throw error while saving in UI. 

### Actual Behavior
Please refer steps to reproduce

### Debug Output 
NA

### Crash Output
NA

### Additional Context
NA

### References
NA

**Comment by martinstibbe** [comment]
@pragnesh-highlevel We will attempt to replicate here as well

**Comment by martinstibbe** [comment]
Confirmed issue will resolved in internal engineering ticket [INTMDB-529 ](https://jira.mongodb.org/browse/INTMDB-529)

**Comment by Zuhairahmed** [comment]
@pragnesh-highlevel as an update, this issue has been picked up in the next sprint cycle and you can expect fix to be included as part of v1.8.1 release next month. will let you know when latest release has been published to the Terraform Registry.

**Comment by Zuhairahmed** [comment]
@pragnesh-highlevel  v1.8.1 has been published to the [Terraform Public Registry](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest)! take a spin and let us know if you need anything else.

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else here
