### ISSUE TITLE
mongodbatlas_alert_configuration not detecting drift

### ISSUE THREAD

**Issue by kkalmbach-rh** [mongodb/terraform-provider-mongodbatlas#999]
### Terraform CLI and Terraform MongoDB Atlas Provider Version
Terraform v1.3.3
on darwin_amd64
+ provider registry.terraform.io/mongodb/mongodbatlas v1.6.1

### Terraform Configuration File 

```
resource "mongodbatlas_alert_configuration" "cpu" {
  project_id = local.project_id
  event_type = "OUTSIDE_METRIC_THRESHOLD"
  enabled    = true

  notification {
       ....
  }

  metric_threshold_config {
    metric_name = "NORMALIZED_SYSTEM_CPU_USER"
    operator    = "GREATER_THAN"
    threshold   = 90.0
    units       = "RAW"
    mode        = "AVERAGE"
  }
}
```

### Steps to Reproduce
Please list the full steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change the values in atlas directly (outside of terraform)
3. `terraform apply`

### Expected Behavior
terraform replaces the drifted value with the correct value

### Actual Behavior
Terraform reports the configuration is up to date.

### Additional Context
If I create the alert as shown above (90% cpu), terraform creates the alert just fine.
I then go into the atlas UI directly, and change the threshold from 90 to 80. 
If I run terraform again, terraform does not recognize the drift and thinks the config is up to date.

I also added a "data.mongodbatlas_alert_configuration" section and added the output of the data.mongodbatlas_alert_configuration into an output variable.
Terraform updates the output value correctly, so terraform is reading in the new config in a data section.

**Comment by martinstibbe** [comment]
@kkalmbach-rh Confirmed this is a bug Internal ticket created to fix [INTMDB-542](https://jira.mongodb.org/browse/INTMDB-542)

**Comment by Zuhairahmed** [comment]
@kkalmbach-rh as an update, this issue has been picked up for the next sprint cycle and you can expect fix to be included as part of v1.8.1 release next month. will let you know when latest release has been published to the Terraform Registry.

**Comment by Zuhairahmed** [comment]
@kkalmbach-rh  v1.8.1 has been published to the [Terraform Public Registry](https://registry.terraform.io/providers/mongodb/mongodbatlas/latest)! take a spin and let us know if you need anything else.

**Comment by Zuhairahmed** [comment]
closing this issue, but feel free to re-open if you need anything else here
